//! GENERATED by tools/gen_data.py - DO NOT EDIT BY HAND.
//! Source of truth: Resources/Objects/pool_*.csv + Resources/Scenes/scenes_*.csv
//! Symbol values: Headers/Combo/{Scenes,NPC,Items,Objects}.h, Headers/Multi/Game.h
//! Scenes OoT=153 MM=154 | Objects OoT=3772 MM=3884

#![allow(dead_code, non_camel_case_types, non_upper_case_globals)]

mod consts;
pub use consts::*;
mod misc;
pub use misc::*;
mod prog;
pub use prog::*;
mod oot_items;
pub use oot_items::*;
mod oot_world;
pub use oot_world::*;
mod mm_items;
pub use mm_items::*;
mod mm_world;
pub use mm_world::*;


/// Scene identifier (matches the width of the C++ scene ids).
pub type SceneId = u16;


/// Mirror of ObjectType (Headers/Combo/Objects.h).
#[repr(u8)]
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub enum ObjectType {
    none,
    chest,
    collectible,
    npc,
    gs,
    sf,
    cow,
    shop,
    scrub,
    sr,
    fish,
    wonder,
    grass,
    crate_,
    pot,
    hive,
    butterfly,
    rupee,
    snowball,
    barrel,
    heart,
    fairy_spot,
    fairy,
    icicle,
    redboulder,
    redice,
    rock,
    soil,
    tree,
    bush,
    silverboulder,
    boulder,
    song,
    heart_piece,
    heart_container,
    small_key,
    boss_key,
    map,
    compass,
    sword,
    ocarina,
    merchant,
    mask,
    egg,
    owl,
}


/// Mirror of ObjectContext (Headers/Combo/Objects.h).
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub enum ObjectContext {
    All,
    Adult,
    Child,
    Winter,
    Spring,
}


/// Mirror of GameLayout (Headers/Multi/Game.h).
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub enum GameLayout {
    all,
    oot,
    oot_mq,
    mm,
    mm_jp,
}


/// Mirror of LocType (Headers/Combo/Scenes.h).
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub enum LocType {
    overworld,
    dungeon,
    minigame,
    broken,
}


/// Mirror of EntranceType (Headers/Combo/Entrances.h).
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub enum EntranceType {
    None,
    Normal,
    One_Way_In,
    One_Way_Out,
}


/// Mirror of ParamType (Headers/UI/Settings.h).
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub enum ParamType {
    game,
    mode,
    uint,
    boolean,
    shuffle,
}


/// Mirror of ParamCategory (Headers/UI/Settings.h).
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub enum ParamCategory {
    standard,
    souls,
    progressive,
    shared,
}


/// Mirror of ShuffleSetting (Headers/UI/Settings.h).
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub enum ShuffleSetting {
    vanilla,
    removed,
    starting,
    all,
    dungeons,
    overworld,
}


/// Scene id constants (mirror of the #defines in Scenes.h).
pub mod scenes {
    use super::SceneId;
    pub const MM_SOUTHERN_SWAMP_CLEAR: SceneId = 0x0;
    pub const OOT_DEKU_TREE: SceneId = 0x0;
    pub const MM_FAIRY_SNOWHEAD: SceneId = 0x1;
    pub const OOT_DODONGO_CAVERN: SceneId = 0x1;
    pub const MM_FAIRY_GREAT_BAY_COAST: SceneId = 0x2;
    pub const OOT_INSIDE_JABU_JABU: SceneId = 0x2;
    pub const MM_FAIRY_WOODFALL: SceneId = 0x3;
    pub const OOT_TEMPLE_FOREST: SceneId = 0x3;
    pub const MM_FAIRY_CLOCK_TOWN: SceneId = 0x4;
    pub const OOT_TEMPLE_FIRE: SceneId = 0x4;
    pub const MM_FAIRY_IKANA: SceneId = 0x5;
    pub const OOT_TEMPLE_WATER: SceneId = 0x5;
    pub const MM_PATH_SNOWHEAD_SPRING: SceneId = 0x6;
    pub const OOT_TEMPLE_SPIRIT: SceneId = 0x6;
    pub const MM_GROTTOS: SceneId = 0x7;
    pub const OOT_TEMPLE_SHADOW: SceneId = 0x7;
    pub const MM_CUTSCENE_MAP: SceneId = 0x8;
    pub const OOT_BOTTOM_OF_THE_WELL: SceneId = 0x8;
    pub const MM_PATH_MOUNTAIN_VILLAGE_SPRING: SceneId = 0x9;
    pub const OOT_ICE_CAVERN: SceneId = 0x9;
    pub const MM_POTION_SHOP: SceneId = 0xa;
    pub const OOT_GANON_TOWER: SceneId = 0xa;
    pub const MM_LAIR_MAJORA: SceneId = 0xb;
    pub const OOT_GERUDO_TRAINING_GROUND: SceneId = 0xb;
    pub const MM_BENEATH_THE_GRAVEYARD: SceneId = 0xc;
    pub const OOT_THIEVES_HIDEOUT: SceneId = 0xc;
    pub const MM_CURIOSITY_SHOP: SceneId = 0xd;
    pub const OOT_INSIDE_GANON_CASTLE: SceneId = 0xd;
    pub const MM_BENEATH_THE_GRAVEYARD_NIGHT1: SceneId = 0xe;
    pub const OOT_GANON_TOWER_COLLAPSING: SceneId = 0xe;
    pub const MM_BENEATH_THE_GRAVEYARD_NIGHT2: SceneId = 0xf;
    pub const OOT_INSIDE_GANON_CASTLE_COLLAPSING: SceneId = 0xf;
    pub const MM_RANCH_HOUSE_BARN: SceneId = 0x10;
    pub const OOT_TREASURE_SHOP: SceneId = 0x10;
    pub const MM_HONEY_DARLING: SceneId = 0x11;
    pub const OOT_LAIR_GOHMA: SceneId = 0x11;
    pub const MM_MAYOR_HOUSE: SceneId = 0x12;
    pub const OOT_LAIR_KING_DODONGO: SceneId = 0x12;
    pub const MM_IKANA_CANYON: SceneId = 0x13;
    pub const OOT_LAIR_BARINADE: SceneId = 0x13;
    pub const MM_PIRATE_FORTRESS_EXTERIOR: SceneId = 0x14;
    pub const OOT_LAIR_PHANTOM_GANON: SceneId = 0x14;
    pub const MM_MILK_BAR: SceneId = 0x15;
    pub const OOT_LAIR_VOLVAGIA: SceneId = 0x15;
    pub const MM_TEMPLE_STONE_TOWER: SceneId = 0x16;
    pub const OOT_LAIR_MORPHA: SceneId = 0x16;
    pub const MM_TREASURE_SHOP: SceneId = 0x17;
    pub const OOT_LAIR_TWINROVA: SceneId = 0x17;
    pub const MM_TEMPLE_STONE_TOWER_INVERTED: SceneId = 0x18;
    pub const OOT_LAIR_BONGO_BONGO: SceneId = 0x18;
    pub const MM_CLOCK_TOWER_ROOFTOP: SceneId = 0x19;
    pub const OOT_LAIR_GANONDORF: SceneId = 0x19;
    pub const MM_OPENING: SceneId = 0x1a;
    pub const OOT_TOWER_COLLAPSE_EXTERIOR: SceneId = 0x1a;
    pub const MM_TEMPLE_WOODFALL: SceneId = 0x1b;
    pub const OOT_MARKET_ENTRANCE_CHILD_DAY: SceneId = 0x1b;
    pub const MM_PATH_MOUNTAIN_VILLAGE: SceneId = 0x1c;
    pub const OOT_MARKET_ENTRANCE_CHILD_NIGHT: SceneId = 0x1c;
    pub const MM_CASTLE_IKANA: SceneId = 0x1d;
    pub const OOT_MARKET_ENTRANCE_ADULT: SceneId = 0x1d;
    pub const MM_DEKU_PLAYGROUND: SceneId = 0x1e;
    pub const OOT_BACK_ALLEY_DAY: SceneId = 0x1e;
    pub const MM_LAIR_ODOLWA: SceneId = 0x1f;
    pub const OOT_BACK_ALLEY_NIGHT: SceneId = 0x1f;
    pub const MM_SHOOTING_GALLERY: SceneId = 0x20;
    pub const OOT_MARKET_CHILD_DAY: SceneId = 0x20;
    pub const MM_TEMPLE_SNOWHEAD: SceneId = 0x21;
    pub const OOT_MARKET_CHILD_NIGHT: SceneId = 0x21;
    pub const MM_MILK_ROAD: SceneId = 0x22;
    pub const OOT_MARKET_ADULT: SceneId = 0x22;
    pub const MM_PIRATE_FORTRESS_INTERIOR: SceneId = 0x23;
    pub const OOT_TEMPLE_OF_TIME_EXTERIOR_CHILD_DAY: SceneId = 0x23;
    pub const MM_SHOOTING_GALLERY_SWAMP: SceneId = 0x24;
    pub const OOT_TEMPLE_OF_TIME_EXTERIOR_CHILD_NIGHT: SceneId = 0x24;
    pub const MM_PINNACLE_ROCK: SceneId = 0x25;
    pub const OOT_TEMPLE_OF_TIME_EXTERIOR_ADULT: SceneId = 0x25;
    pub const MM_FAIRY_FOUNTAIN: SceneId = 0x26;
    pub const OOT_KOKIRI_KNOW_IT_ALL: SceneId = 0x26;
    pub const MM_SPIDER_HOUSE_SWAMP: SceneId = 0x27;
    pub const OOT_KOKIRI_TWINS: SceneId = 0x27;
    pub const MM_SPIDER_HOUSE_OCEAN: SceneId = 0x28;
    pub const OOT_KOKIRI_MIDO: SceneId = 0x28;
    pub const MM_OBSERVATORY: SceneId = 0x29;
    pub const OOT_KOKIRI_SARIA: SceneId = 0x29;
    pub const MM_MOON_DEKU: SceneId = 0x2a;
    pub const OOT_CARPENTER_BOSS_HOUSE: SceneId = 0x2a;
    pub const MM_DEKU_PALACE: SceneId = 0x2b;
    pub const OOT_BACK_ALLEY_HOUSE: SceneId = 0x2b;
    pub const MM_BLACKSMITH: SceneId = 0x2c;
    pub const OOT_BAZAAR: SceneId = 0x2c;
    pub const MM_TERMINA_FIELD: SceneId = 0x2d;
    pub const OOT_KOKIRI_SHOP: SceneId = 0x2d;
    pub const MM_POST_OFFICE: SceneId = 0x2e;
    pub const OOT_GORON_SHOP: SceneId = 0x2e;
    pub const MM_LABORATORY: SceneId = 0x2f;
    pub const OOT_ZORA_SHOP: SceneId = 0x2f;
    pub const MM_DAMPE_HOUSE: SceneId = 0x30;
    pub const OOT_KAKARIKO_POTION_SHOP: SceneId = 0x30;
    pub const MM_INSIDE_CASTLE_IKANA: SceneId = 0x31;
    pub const OOT_MARKET_POTION_SHOP: SceneId = 0x31;
    pub const MM_GORON_SHRINE: SceneId = 0x32;
    pub const OOT_BOMBCHU_SHOP: SceneId = 0x32;
    pub const MM_ZORA_HALL: SceneId = 0x33;
    pub const OOT_HAPPY_MASK_SHOP: SceneId = 0x33;
    pub const MM_TRADING_POST: SceneId = 0x34;
    pub const OOT_LINK_HOUSE: SceneId = 0x34;
    pub const MM_ROMANI_RANCH: SceneId = 0x35;
    pub const OOT_BACK_ALLEY_HOUSE2: SceneId = 0x35;
    pub const MM_LAIR_TWINMOLD: SceneId = 0x36;
    pub const OOT_STABLE: SceneId = 0x36;
    pub const MM_GREAT_BAY_COAST: SceneId = 0x37;
    pub const OOT_IMPA_HOUSE: SceneId = 0x37;
    pub const MM_ZORA_CAPE: SceneId = 0x38;
    pub const OOT_LABORATORY: SceneId = 0x38;
    pub const MM_LOTTERY: SceneId = 0x39;
    pub const OOT_CARPENTER_TENT: SceneId = 0x39;
    pub const MM_SNOWHEAD_SPRING: SceneId = 0x3a;
    pub const OOT_GRAVEKEEPER_HUT: SceneId = 0x3a;
    pub const MM_PIRATE_FORTRESS_ENTRANCE: SceneId = 0x3b;
    pub const OOT_GREAT_FAIRY_FOUNTAIN_UPGRADES: SceneId = 0x3b;
    pub const MM_FISHERMAN_HUT: SceneId = 0x3c;
    pub const OOT_FAIRY_FOUNTAIN: SceneId = 0x3c;
    pub const MM_GORON_SHOP: SceneId = 0x3d;
    pub const OOT_GREAT_FAIRY_FOUNTAIN_SPELLS: SceneId = 0x3d;
    pub const MM_DEKU_KING_CHAMBER: SceneId = 0x3e;
    pub const OOT_GROTTOS: SceneId = 0x3e;
    pub const MM_MOON_GORON: SceneId = 0x3f;
    pub const OOT_TOMB_REDEAD: SceneId = 0x3f;
    pub const MM_ROAD_SOUTHERN_SWAMP: SceneId = 0x40;
    pub const OOT_TOMB_FAIRY: SceneId = 0x40;
    pub const MM_DOG_RACETRACK: SceneId = 0x41;
    pub const OOT_TOMB_ROYAL: SceneId = 0x41;
    pub const MM_CUCCO_SHACK: SceneId = 0x42;
    pub const OOT_SHOOTING_GALLERY: SceneId = 0x42;
    pub const MM_IKANA_GRAVEYARD: SceneId = 0x43;
    pub const OOT_TEMPLE_OF_TIME: SceneId = 0x43;
    pub const MM_LAIR_GOHT: SceneId = 0x44;
    pub const OOT_CHAMBER_OF_THE_SAGES: SceneId = 0x44;
    pub const MM_SOUTHERN_SWAMP: SceneId = 0x45;
    pub const OOT_CASTLE_MAZE_DAY: SceneId = 0x45;
    pub const MM_WOODFALL: SceneId = 0x46;
    pub const OOT_CASTLE_MAZE_NIGHT: SceneId = 0x46;
    pub const MM_MOON_ZORA: SceneId = 0x47;
    pub const OOT_CUTSCENE_MAP: SceneId = 0x47;
    pub const MM_GORON_VILLAGE_SPRING: SceneId = 0x48;
    pub const OOT_TOMB_DAMPE_WINDMILL: SceneId = 0x48;
    pub const MM_TEMPLE_GREAT_BAY: SceneId = 0x49;
    pub const OOT_FISHING_POND: SceneId = 0x49;
    pub const MM_WATERFALL_RAPIDS: SceneId = 0x4a;
    pub const OOT_CASTLE_COURTYARD: SceneId = 0x4a;
    pub const MM_BENEATH_THE_WELL: SceneId = 0x4b;
    pub const OOT_BOMBCHU_BOWLING_ALLEY: SceneId = 0x4b;
    pub const MM_ZORA_HALL_ROOMS: SceneId = 0x4c;
    pub const OOT_RANCH_HOUSE_SILO: SceneId = 0x4c;
    pub const MM_GORON_VILLAGE_WINTER: SceneId = 0x4d;
    pub const OOT_GUARD_HOUSE: SceneId = 0x4d;
    pub const MM_GORON_GRAVEYARD: SceneId = 0x4e;
    pub const OOT_GRANNY_POTION_SHOP: SceneId = 0x4e;
    pub const MM_SAKON_HIDEOUT: SceneId = 0x4f;
    pub const OOT_GANON_BATTLE_ARENA: SceneId = 0x4f;
    pub const MM_MOUNTAIN_VILLAGE_WINTER: SceneId = 0x50;
    pub const OOT_HOUSE_OF_SKULLTULA: SceneId = 0x50;
    pub const MM_GHOST_HUT: SceneId = 0x51;
    pub const OOT_HYRULE_FIELD: SceneId = 0x51;
    pub const MM_DEKU_SHRINE: SceneId = 0x52;
    pub const OOT_KAKARIKO_VILLAGE: SceneId = 0x52;
    pub const MM_ROAD_IKANA: SceneId = 0x53;
    pub const OOT_GRAVEYARD: SceneId = 0x53;
    pub const MM_SWORDSMAN_SCHOOL: SceneId = 0x54;
    pub const OOT_ZORA_RIVER: SceneId = 0x54;
    pub const MM_MUSIC_BOX_HOUSE: SceneId = 0x55;
    pub const OOT_KOKIRI_FOREST: SceneId = 0x55;
    pub const MM_LAIR_IKANA: SceneId = 0x56;
    pub const OOT_SACRED_FOREST_MEADOW: SceneId = 0x56;
    pub const MM_TOURIST_INFORMATION: SceneId = 0x57;
    pub const OOT_LAKE_HYLIA: SceneId = 0x57;
    pub const MM_STONE_TOWER: SceneId = 0x58;
    pub const OOT_ZORA_DOMAIN: SceneId = 0x58;
    pub const MM_STONE_TOWER_INVERTED: SceneId = 0x59;
    pub const OOT_ZORA_FOUNTAIN: SceneId = 0x59;
    pub const MM_MOUNTAIN_VILLAGE_SPRING: SceneId = 0x5a;
    pub const OOT_GERUDO_VALLEY: SceneId = 0x5a;
    pub const MM_PATH_SNOWHEAD: SceneId = 0x5b;
    pub const OOT_LOST_WOODS: SceneId = 0x5b;
    pub const MM_SNOWHEAD: SceneId = 0x5c;
    pub const OOT_DESERT_COLOSSUS: SceneId = 0x5c;
    pub const MM_TWIN_ISLANDS_WINTER: SceneId = 0x5d;
    pub const OOT_GERUDO_FORTRESS: SceneId = 0x5d;
    pub const MM_TWIN_ISLANDS_SPRING: SceneId = 0x5e;
    pub const OOT_HAUNTED_WASTELAND: SceneId = 0x5e;
    pub const MM_LAIR_GYORG: SceneId = 0x5f;
    pub const OOT_HYRULE_CASTLE: SceneId = 0x5f;
    pub const MM_SECRET_SHRINE: SceneId = 0x60;
    pub const OOT_DEATH_MOUNTAIN_TRAIL: SceneId = 0x60;
    pub const MM_STOCK_POT_INN: SceneId = 0x61;
    pub const OOT_DEATH_MOUNTAIN_CRATER: SceneId = 0x61;
    pub const MM_GREAT_BAY_CUTSCENE: SceneId = 0x62;
    pub const OOT_GORON_CITY: SceneId = 0x62;
    pub const MM_CLOCK_TOWER_INTERIOR: SceneId = 0x63;
    pub const OOT_LON_LON_RANCH: SceneId = 0x63;
    pub const MM_WOODS_MYSTERY: SceneId = 0x64;
    pub const OOT_GANON_CASTLE_EXTERIOR: SceneId = 0x64;
    pub const MM_LOST_WOODS: SceneId = 0x65;
    pub const OOT_GROTTO_KOKIRI_FOREST_STORMS: SceneId = 0x65;
    pub const MM_MOON_LINK: SceneId = 0x66;
    pub const OOT_GROTTO_LOST_WOODS_SCRUB_UPGRADE: SceneId = 0x66;
    pub const MM_MOON: SceneId = 0x67;
    pub const OOT_GROTTO_LOST_WOODS_GENERIC: SceneId = 0x67;
    pub const MM_BOMB_SHOP: SceneId = 0x68;
    pub const OOT_GROTTO_LOST_WOODS_THEATER: SceneId = 0x68;
    pub const MM_GIANT_CHAMBER: SceneId = 0x69;
    pub const OOT_GROTTO_SACRED_MEADOW_WOLFOS: SceneId = 0x69;
    pub const MM_GORMAN_TRACK: SceneId = 0x6a;
    pub const OOT_GROTTO_SACRED_MEADOW_STORMS: SceneId = 0x6a;
    pub const MM_GORON_RACETRACK: SceneId = 0x6b;
    pub const OOT_GROTTO_KAKARIKO_REDEAD: SceneId = 0x6b;
    pub const MM_CLOCK_TOWN_EAST: SceneId = 0x6c;
    pub const OOT_GROTTO_KAKARIKO_OPEN: SceneId = 0x6c;
    pub const MM_CLOCK_TOWN_WEST: SceneId = 0x6d;
    pub const OOT_GROTTO_DEATH_TRIAL_STORMS: SceneId = 0x6d;
    pub const MM_CLOCK_TOWN_NORTH: SceneId = 0x6e;
    pub const OOT_GROTTO_DEATH_TRIAL_COW: SceneId = 0x6e;
    pub const MM_CLOCK_TOWN_SOUTH: SceneId = 0x6f;
    pub const OOT_GROTTO_GORON_CITY_SCRUBS: SceneId = 0x6f;
    pub const MM_LAUNDRY_POOL: SceneId = 0x70;
    pub const OOT_GROTTO_DEATH_CRATER_GENERIC: SceneId = 0x70;
    pub const MM_EXTRA: SceneId = 0x71;
    pub const OOT_GROTTO_DEATH_CRATER_SCRUBS: SceneId = 0x71;
    pub const MM_LONE_PEAK: SceneId = 0x72;
    pub const OOT_GROTTO_ZORA_RIVER_STORMS: SceneId = 0x72;
    pub const MM_ZORA_SHOP: SceneId = 0x73;
    pub const OOT_GROTTO_ZORA_RIVER_GENERIC: SceneId = 0x73;
    pub const MM_ZORA_EVANS_ROOM: SceneId = 0x74;
    pub const OOT_GROTTO_LAKE_HYLIA_SCRUBS: SceneId = 0x74;
    pub const MM_ZORA_JAPAS_ROOM: SceneId = 0x75;
    pub const OOT_GROTTO_LON_LON_SCRUBS: SceneId = 0x75;
    pub const MM_ZORA_TIJO_ROOM: SceneId = 0x76;
    pub const OOT_GROTTO_HYRULE_SCRUBS: SceneId = 0x76;
    pub const MM_ZORA_LULU_ROOM: SceneId = 0x77;
    pub const OOT_GROTTO_HYRULE_SE: SceneId = 0x77;
    pub const MM_ROMANI_RANCH_BARN: SceneId = 0x78;
    pub const OOT_GROTTO_HYRULE_OPEN: SceneId = 0x78;
    pub const MM_PIRATE_SEWERS: SceneId = 0x79;
    pub const OOT_GROTTO_HYRULE_MARKET: SceneId = 0x79;
    pub const MM_OWLS: SceneId = 0x7a;
    pub const OOT_GROTTO_HYRULE_TEKTITE: SceneId = 0x7a;
    pub const MM_GROTTO_TERMINA_DODONGO: SceneId = 0x7b;
    pub const OOT_GROTTO_HYRULE_KAKARIKO: SceneId = 0x7b;
    pub const MM_GROTTO_TERMINA_OCEAN_GOSSIP: SceneId = 0x7c;
    pub const OOT_GROTTO_HYRULE_GERUDO: SceneId = 0x7c;
    pub const MM_GROTTO_TERMINA_CANYON_GOSSIP: SceneId = 0x7d;
    pub const OOT_GROTTO_CASTLE_STORMS: SceneId = 0x7d;
    pub const MM_GROTTO_TERMINA_SWAMP_GOSSIP: SceneId = 0x7e;
    pub const OOT_GROTTO_VALLEY_STORMS: SceneId = 0x7e;
    pub const MM_GROTTO_TERMINA_MOUNTAIN_GOSSIP: SceneId = 0x7f;
    pub const OOT_GROTTO_VALLEY_OCTOROK: SceneId = 0x7f;
    pub const MM_GROTTO_TERMINA_BIO_BABA: SceneId = 0x80;
    pub const OOT_GROTTO_DESERT_SCRUBS: SceneId = 0x80;
    pub const MM_GROTTO_TERMINA_PEAHAT: SceneId = 0x81;
    pub const OOT_FAIRY_SACRED_MEADOW: SceneId = 0x81;
    pub const MM_GROTTO_TERMINA_SCRUB: SceneId = 0x82;
    pub const OOT_FAIRY_ZORA_RIVER: SceneId = 0x82;
    pub const MM_GROTTO_TERMINA_TALL_GRASS: SceneId = 0x83;
    pub const OOT_FAIRY_ZORA_DOMAIN: SceneId = 0x83;
    pub const MM_GROTTO_TERMINA_COW: SceneId = 0x84;
    pub const OOT_FAIRY_HYRULE: SceneId = 0x84;
    pub const MM_GROTTO_TERMINA_PILLAR: SceneId = 0x85;
    pub const OOT_FAIRY_GERUDO_FORTRESS: SceneId = 0x85;
    pub const MM_GROTTO_GREAT_BAY_COAST_FISHERMAN: SceneId = 0x86;
    pub const OOT_GREAT_FAIRY_CASTLE: SceneId = 0x86;
    pub const MM_GROTTO_GREAT_BAY_COAST_COW: SceneId = 0x87;
    pub const OOT_GREAT_FAIRY_DEFENSE: SceneId = 0x87;
    pub const MM_GROTTO_ZORA_CAPE_GENERIC: SceneId = 0x88;
    pub const OOT_GREAT_FAIRY_FARORE: SceneId = 0x88;
    pub const MM_GROTTO_IKANA_GRAVEYARD_GENERIC: SceneId = 0x89;
    pub const OOT_GREAT_FAIRY_NAYRU: SceneId = 0x89;
    pub const MM_GROTTO_IKANA_VALLEY_OPEN: SceneId = 0x8a;
    pub const OOT_GREAT_FAIRY_MAGIC: SceneId = 0x8a;
    pub const MM_GROTTO_IKANA_ROAD_GENERIC: SceneId = 0x8b;
    pub const OOT_GREAT_FAIRY_MAGIC2: SceneId = 0x8b;
    pub const MM_GROTTO_TWIN_ISLANDS_FROZEN: SceneId = 0x8c;
    pub const OOT_GREAT_FAIRY: SceneId = 0x8c;
    pub const MM_GROTTO_TWIN_ISLANDS_RAMP: SceneId = 0x8d;
    pub const OOT_KAKARIKO_BAZAAR: SceneId = 0x8d;
    pub const MM_GROTTO_PATH_TO_SNOWHEAD_GENERIC: SceneId = 0x8e;
    pub const OOT_MARKET_BAZAAR: SceneId = 0x8e;
    pub const MM_GROTTO_MOUNTAIN_VILLAGE_GENERIC: SceneId = 0x8f;
    pub const OOT_KAKARIKO_SHOOTING: SceneId = 0x8f;
    pub const MM_GROTTO_SOUTHERN_SWAMP_ROAD_OPEN: SceneId = 0x90;
    pub const OOT_MARKET_SHOOTING: SceneId = 0x90;
    pub const MM_GROTTO_SOUTHERN_SWAMP_OPEN: SceneId = 0x91;
    pub const OOT_SILO: SceneId = 0x91;
    pub const MM_GROTTO_WOODS_OF_MYSTERY_OPEN: SceneId = 0x92;
    pub const OOT_WINDMILL: SceneId = 0x92;
    pub const MM_GROTTO_DEKU_PALACE_BEANS: SceneId = 0x93;
    pub const OOT_MARKET_ENTRANCE: SceneId = 0x93;
    pub const MM_GROTTO_DEKU_PALACE_GENERIC: SceneId = 0x94;
    pub const OOT_TEMPLE_OF_TIME_ENTRYWAY: SceneId = 0x94;
    pub const MM_GROTTO_DEKU_PALACE_CLIMB: SceneId = 0x95;
    pub const OOT_BACK_ALLEY: SceneId = 0x95;
    pub const MM_MOUNTAIN_VILLAGE: SceneId = 0x96;
    pub const OOT_SONGS: SceneId = 0x96;
    pub const MM_TWIN_ISLANDS: SceneId = 0x97;
    pub const OOT_INSIDE_EGGS: SceneId = 0x97;
    pub const MM_GORON_VILLAGE: SceneId = 0x98;
    pub const OOT_MARKET: SceneId = 0x98;
    pub const MM_SPRING_WATER_CAVE: SceneId = 0x99;
    pub const OOT_NUM_SCENES: SceneId = 0x99;
    pub const MM_NUM_SCENES: SceneId = 0x9a;
}


pub struct SceneDef {
    pub id: SceneId,
    pub name: &'static str,
    /// Artistic map (items). May be empty (dungeons use rooms/minimap).
    pub image_rel: &'static str,
    /// Minimap (entrances).
    pub minimap_rel: &'static str,
    pub region_id: u8,
    pub region_name: &'static str,
    pub has_context: bool,
    pub layout: GameLayout,
}


pub struct ObjectDef {
    pub object_id: u32,
    pub scene: SceneId,
    pub name: &'static str,
    pub location: &'static str,
    pub type_: ObjectType,
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub render_scene: SceneId,
    pub render_type: ObjectType,
    pub map_icon: &'static str,
    pub context: ObjectContext,
    pub room: u16,
    pub layout: GameLayout,
    pub loc_type: LocType,
}


pub struct RoomDef {
    pub id: u32,
    pub name: &'static str,
    pub image_rel: &'static str,
}


pub struct GrottoPos {
    pub id: u32,
    pub pos: [f32; 3],
}


pub struct EntranceDef {
    pub to_id: u32,
    pub from_id: u32,
    pub from_scene: SceneId,
    pub to_scene: SceneId,
    pub from_name: &'static str,
    pub to_name: &'static str,
    pub type_: EntranceType,
    pub anchor: [i32; 2],
    pub text: [i32; 2],
    pub icon: &'static str,
    pub layout: GameLayout,
}


/// A ROM build parameter (mirror of Settings.cpp Parameter, minus the
/// runtime shuffle value which lives in the Settings struct).
pub struct SettingMeta {
    pub key: &'static str,
    pub name: &'static str,
    pub type_: ParamType,
    pub cat: ParamCategory,
    pub default: ShuffleSetting,
    pub affected: &'static [u32],
}


/// A tracked item (mirror of Items.cpp ItemInfo, minus the render icon).
pub struct ItemDef {
    pub id: u32,
    pub name: &'static str,
    pub can_be_shared: bool,
}


/// One progression-dashboard entry (mirror of ProgressionEntry.h ProgEntry).
/// `icon` is the EGameIcon variant name (resolve the image via ICON_BY_NAME).
pub struct ProgEntry {
    pub icon: &'static str,
    pub name: &'static str,
    pub lookup_keys: &'static [u32],
    pub is_counter: bool,
    pub max_count: i32,
    pub max_from_spoiler: bool,
}


pub struct ProgSection {
    pub title: &'static str,
    pub entries: &'static [ProgEntry],
}


pub struct ProgPage {
    pub title: &'static str,
    pub sections: &'static [ProgSection],
}
