#include "Combo/Items.h"

#pragma region Items

#define NUM_ITEM 0x33E

const ItemInfo ItemList[NUM_ITEM] =
{
    { 0x01, "5 Bombs (OoT)" },
    { 0x02, "5 Deku Nuts (OoT)" },
    { 0x03, "10 Bombchu (OoT)" },
    { 0x04, "Fairy Bow (OoT)" },
    { 0x05, "Fairy Slingshot" },
    { 0x06, "Boomerang" },
    { 0x07, "Deku Stick (OoT)" },
    { 0x08, "Progressive Hookshot (OoT)" },
    { 0x09, "Longshot (OoT)" },
    { 0x0A, "Lens of Truth (OoT)" },
    { 0x0B, "Zelda's Letter" },
    { 0x0C, "Ocarina of Time (OoT)" },
    { 0x0D, "Megaton Hammer (OoT)" },
    { 0x0E, "Cojiro" },
    { 0x0F, "Empty Bottle (OoT)" },
    { 0x10, "Red Potion (OoT)" },
    { 0x11, "Green Potion (OoT)" },
    { 0x12, "Blue Potion (OoT)" },
    { 0x13, "Fairy (OoT)" },
    { 0x14, "Bottle of Milk (OoT)" },
    { 0x15, "Ruto's Letter" },
    { 0x16, "Magic Beans (OoT)" },
    { 0x17, "Skull Mask" },
    { 0x18, "Spooky Mask" },
    { 0x19, "Chicken" },
    { 0x1A, "Keaton Mask (OoT)" },
    { 0x1B, "Bunny Hood (OoT)" },
    { 0x1C, "Mask of Truth (OoT)" },
    { 0x1D, "Pocket Egg" },
    { 0x1E, "Pocket Cucco" },
    { 0x1F, "Odd Mushroom" },
    { 0x20, "Odd Potion" },
    { 0x21, "Poacher's Saw" },
    { 0x22, "Broken Goron's Sword" },
    { 0x23, "Prescription" },
    { 0x24, "Eyeball Frog" },
    { 0x25, "Eye Drops" },
    { 0x26, "Claim Check" },
    { 0x27, "Kokiri Sword (OoT)" },
    { 0x28, "Giant's Knife" },
    { 0x29, "Deku Shield (OoT)" },
    { 0x2A, "Hylian Shield" },
    { 0x2B, "Mirror Shield (OoT)" },
    { 0x2C, "Goron Tunic (OoT)" },
    { 0x2D, "Zora Tunic (OoT)" },
    { 0x2E, "Iron Boots (OoT)" },
    { 0x2F, "Hover Boots (OoT)" },
    { 0x30, "Big Quiver (OoT)" },
    { 0x31, "Biggest Quiver (OoT)" },
    { 0x32, "Bomb Bag (OoT)" },
    { 0x33, "Big Bomb Bag (OoT)" },
    { 0x34, "Biggest Bomb Bag (OoT)" },
    { 0x35, "Silver Gauntlets (OoT)" },
    { 0x36, "Golden Gauntlets (OoT)" },
    { 0x37, "Silver Scale (OoT)" },
    { 0x38, "Golden Scale (OoT)" },
    { 0x39, "Stone of Agony (OoT)" },
    { 0x3A, "Gerudo's Membership Card" },
    { 0x3B, "Fairy Ocarina (OoT)" },
    { 0x3C, "5 Deku Seeds (OoT)" },
    { 0x3D, "Heart Container (OoT)" },
    { 0x3E, "Piece of Heart (OoT)" },
    { 0x3F, "Boss Key (OoT)" },
    { 0x40, "Compass (OoT)" },
    { 0x41, "Map (OoT)" },
    { 0x42, "Small Key (OoT)" },
    { 0x43, "Small Magic Jar (OoT)" },
    { 0x44, "Large Magic Jar (OoT)" },
    { 0x45, "Adult's Wallet (OoT)" },
    { 0x46, "Giant's Wallet (OoT)" },
    { 0x47, "Weird Egg" },
    { 0x48, "Recovery Heart (OoT)" },
    { 0x49, "5 Arrows (OoT)" },
    { 0x4A, "10 Arrows (OoT)" },
    { 0x4B, "30 Arrows (OoT)" },
    { 0x4C, "Green Rupee (OoT)" },
    { 0x4D, "Blue Rupee (OoT)" },
    { 0x4E, "Red Rupee (OoT)" },
    { 0x4F, "Heart Container (OoT)" },
    { 0x50, "Lon Lon Milk (OoT)" },
    { 0x51, "Goron Mask (OoT)" },
    { 0x52, "Zora Mask (OoT)" },
    { 0x53, "Gerudo Mask" },
    { 0x54, "Goron's Bracelet (OoT)" },
    { 0x55, "Purple Rupee (OoT)" },
    { 0x56, "Gold Rupee (OoT)" },
    { 0x57, "Biggoron's Sword" },
    { 0x58, "Fire Arrows (OoT)" },
    { 0x59, "Ice Arrows (OoT)" },
    { 0x5A, "Light Arrows (OoT)" },
    { 0x5B, "Gold Skulltula Token" },
    { 0x5C, "Din's Fire (OoT)" },
    { 0x5D, "Farore's Wind (OoT)" },
    { 0x5E, "Nayru's Love (OoT)" },
    { 0x5F, "Bullet Bag" },
    { 0x60, "Large Bullet Bag" },
    { 0x61, "5 Deku Sticks (OoT)" },
    { 0x62, "10 Deku Sticks (OoT)" },
    { 0x63, "5 Deku Nuts (OoT)" },
    { 0x64, "10 Deku Nuts (OoT)" },
    { 0x65, "Bomb (OoT)" },
    { 0x66, "10 Bombs (OoT)" },
    { 0x67, "20 Bombs (OoT)" },
    { 0x68, "30 Bombs (OoT)" },
    { 0x69, "30 Deku Seeds" },
    { 0x6A, "5 Bombchu (OoT)" },
    { 0x6B, "20 Bombchu (OoT)" },
    { 0x6C, "Fish (OoT)" },
    { 0x6D, "Bugs (OoT)" },
    { 0x6E, "Blue Fire" },
    { 0x6F, "Poe (OoT)" },
    { 0x70, "Big Poe (OoT)" },
    { 0x71, "Small Key (OoT)" },
    { 0x72, "Green Rupee (OoT)" },
    { 0x73, "Blue Rupee (OoT)" },
    { 0x74, "Red Rupee (OoT)" },
    { 0x75, "Purple Rupee (OoT)" },
    { 0x76, "Piece of Heart (OoT)" },
    { 0x77, "Deku Stick Upgrade (OoT)" },
    { 0x78, "Second Deku Stick Upgrade (OoT)" },
    { 0x79, "Deku Nut Upgrade (OoT)" },
    { 0x7A, "Second Deku Nut Upgrade (OoT)" },
    { 0x7B, "Largest Bullet Bag" },
    { 0x7C, "IceTrap (OoT)" },
    { 0x7D, "Unknown" },
    { 0x7E, "Unknown" },
    { 0x7F, "Unknown" },
    { 0x80, "Rainbow Rupee (OoT)" },
    { 0x81, "Minuet of Forest" },
    { 0x82, "Bolero of Fire" },
    { 0x83, "Serenade of Water" },
    { 0x84, "Requiem of Spirit" },
    { 0x85, "Nocturne of Shadow" },
    { 0x86, "Prelude of Light" },
    { 0x87, "Zelda's Lullaby" },
    { 0x88, "Epona's Song (OoT)" },
    { 0x89, "Saria's Song" },
    { 0x8A, "Sun's Song (OoT)" },
    { 0x8B, "Song of Time (OoT)" },
    { 0x8C, "Song of Storms (OoT)" },
    { 0x8D, "Elegy of Emptiness (OoT)" },
    { 0x8E, "Note from Minuet of Forest (OoT)" },
    { 0x8F, "Note from Bolero of Fire (OoT)" },
    { 0x90, "Note from Serenade of Water (OoT)" },
    { 0x91, "Note from Requiem of Spirit (OoT)" },
    { 0x92, "Note from Nocturne of Shadow (OoT)" },
    { 0x93, "Note from Prelude of Light (OoT)" },
    { 0x94, "Note from Zelda's Lullaby (OoT)" },
    { 0x95, "Note from Epona's Song (OoT)" },
    { 0x96, "Note from Saria's Song (OoT)" },
    { 0x97, "Note from Sun's Song (OoT)" },
    { 0x98, "Note from Song of Time (OoT)" },
    { 0x99, "Note from Song of Storms (OoT)" },
    { 0x9A, "Note from Elegy of Emptiness (OoT)" },
    { 0x9B, "Master Sword" },
    { 0x9C, "Kokiri's Emerald" },
    { 0x9D, "Goron's Ruby" },
    { 0x9E, "Zora's Sapphire" },
    { 0x9F, "Forest Medallion" },
    { 0xA0, "Fire Medallion" },
    { 0xA1, "Water Medallion" },
    { 0xA2, "Spirit Medallion" },
    { 0xA3, "Shadow Medallion" },
    { 0xA4, "Light Medallion" },
    { 0xA5, "Magic Upgrade (OoT)" },
    { 0xA6, "Larger Magic Upgrade (OoT)" },
    { 0xA7, "Double Defense (OoT)" },
    { 0xA8, "Progressive Deku Shield (OoT)" },
    { 0xA9, "Progressive Hylian Shield" },
    { 0xAA, "Small Key (Forest Temple)" },
    { 0xAB, "Small Key (Fire Temple)" },
    { 0xAC, "Small Key (Water Temple)" },
    { 0xAD, "Small Key (Spirit Temple)" },
    { 0xAE, "Small Key (Shadow Temple)" },
    { 0xAF, "Small Key (Ganon's Castle)" },
    { 0xB0, "Small Key (Bottom of the Well)" },
    { 0xB1, "Small Key (Gerudo's Fortress)" },
    { 0xB2, "Small Key (Gerudo's Training Ground)" },
    { 0xB3, "Boss Key (Forest Temple)" },
    { 0xB4, "Boss Key (Fire Temple)" },
    { 0xB5, "Boss Key (Water Temple)" },
    { 0xB6, "Boss Key (Spirit Temple)" },
    { 0xB7, "Boss Key (Shadow Temple)" },
    { 0xB8, "Boss Key (Ganon's Castle)" },
    { 0xB9, "Map (Deku Tree)" },
    { 0xBA, "Map (Dodongo's Cavern)" },
    { 0xBB, "Map (Jabu-Jabu's Belly)" },
    { 0xBC, "Map (Forest Temple)" },
    { 0xBD, "Map (Fire Temple)" },
    { 0xBE, "Map (Water Temple)" },
    { 0xBF, "Map (Spirit Temple)" },
    { 0xC0, "Map (Shadow Temple)" },
    { 0xC1, "Map (Bottom of the Well)" },
    { 0xC2, "Map (Ice Cavern)" },
    { 0xC3, "Compass (Deku Tree)" },
    { 0xC4, "Compass (Dodongo's Cavern)" },
    { 0xC5, "Compass (Jabu-Jabu's Belly)" },
    { 0xC6, "Compass (Forest Temple)" },
    { 0xC7, "Compass (Fire Temple)" },
    { 0xC8, "Compass (Water Temple)" },
    { 0xC9, "Compass (Spirit Temple)" },
    { 0xCA, "Compass (Shadow Temple)" },
    { 0xCB, "Compass (Bottom of the Well)" },
    { 0xCC, "Compass (Ice Cavern)" },
    { 0xCD, "Child's Wallet (OoT)" },
    { 0xCE, "Colossal Wallet (OoT)" },
    { 0xCF, "Triforce Piece" },
    { 0xD0, "Bottomless Wallet (OoT)" },
    { 0xD1, "Silver Rupee (Dodongo's Cavern)" },
    { 0xD2, "Silver Rupee (Bottom of the Well)" },
    { 0xD3, "Silver Rupee (Spirit Temple - Child)" },
    { 0xD4, "Silver Rupee (Spirit Temple - Sun Block)" },
    { 0xD5, "Silver Rupee (Spirit Temple - Boulders)" },
    { 0xD6, "Silver Rupee (Spirit Temple - Lobby)" },
    { 0xD7, "Silver Rupee (Spirit Temple - Adult)" },
    { 0xD8, "Silver Rupee (Shadow Temple - Scythe)" },
    { 0xD9, "Silver Rupee (Shadow Temple - Large Pits)" },
    { 0xDA, "Silver Rupee (Shadow Temple - Spikes)" },
    { 0xDB, "Silver Rupee (Shadow Temple - Invisible Blades)" },
    { 0xDC, "Silver Rupee (Ice Cavern - Scythe)" },
    { 0xDD, "Silver Rupee (Ice Cavern - Block)" },
    { 0xDE, "Silver Rupee (Gerudo Training Ground - Slopes)" },
    { 0xDF, "Silver Rupee (Gerudo Training Ground - Lava)" },
    { 0xE0, "Silver Rupee (Gerudo Training Ground - Water)" },
    { 0xE1, "Silver Rupee (Ganon's Castle - Spirit Trial)" },
    { 0xE2, "Silver Rupee (Ganon's Castle - Light Trial)" },
    { 0xE3, "Silver Rupee (Ganon's Castle - Fire Trial)" },
    { 0xE4, "Silver Rupee (Ganon's Castle - Forest Trial)" },
    { 0xE5, "Silver Rupee (Ganon's Castle - Shadow Trial)" },
    { 0xE6, "Silver Rupee (Ganon's Castle - Water Trial)" },
    { 0xE7, "Soul of Stalfos (OoT)" },
    { 0xE8, "Soul of Octoroks (OoT)" },
    { 0xE9, "Soul of Wallmasters (OoT)" },
    { 0xEA, "Soul of Dodongos (OoT)" },
    { 0xEB, "Soul of Keese (OoT)" },
    { 0xEC, "Soul of Tektites (OoT)" },
    { 0xED, "Soul of Leevers (OoT)" },
    { 0xEE, "Soul of Peahats (OoT)" },
    { 0xEF, "Soul of Lizalfos/Dinolfos (OoT)" },
    { 0xF0, "Soul of Gohma Larvaes" },
    { 0xF1, "Soul of Shaboms" },
    { 0xF2, "Soul of Baby Dodongos" },
    { 0xF3, "Soul of Dark Link" },
    { 0xF4, "Soul of Biris/Baris" },
    { 0xF5, "Soul of Tailpasarans" },
    { 0xF6, "Soul of Jabu-Jabu's Parasites" },
    { 0xF7, "Soul of Skulltulas (OoT)" },
    { 0xF8, "Soul of Torch Slugs" },
    { 0xF9, "Soul of Moblins" },
    { 0xFA, "Soul of Armos (OoT)" },
    { 0xFB, "Soul of Deku Babas (OoT)" },
    { 0xFC, "Soul of Deku Scrubs (OoT)" },
    { 0xFD, "Soul of Bubbles (OoT)" },
    { 0xFE, "Soul of Beamos (OoT)" },
    { 0xFF, "Soul of Floormasters (OoT)" },
    { 0x100, "Soul of ReDeads/Gibdos (OoT)" },
    { 0x101, "Soul of Skullwalltulas (OoT)" },
    { 0x102, "Soul of Flare Dancers" },
    { 0x103, "Soul of Dead Hands" },
    { 0x104, "Soul of Shell Blades (OoT)" },
    { 0x105, "Soul of Like Likes (OoT)" },
    { 0x106, "Soul of Spikes" },
    { 0x107, "Soul of Anubis" },
    { 0x108, "Soul of Iron Knuckles (OoT)" },
    { 0x109, "Soul of Skull Kids (OoT)" },
    { 0x10A, "Soul of Flying Pots (OoT)" },
    { 0x10B, "Soul of Freezards (OoT)" },
    { 0x10C, "Soul of Stingers" },
    { 0x10D, "Soul of Wolfoses (OoT)" },
    { 0x10E, "Soul of Stalchildren (OoT)" },
    { 0x10F, "Soul of Guays (OoT)" },
    { 0x110, "Soul of the Fighting Gerudos" },
    { 0x111, "Soul of Poes (OoT)" },
    { 0x112, "Soul of Queen Gohma" },
    { 0x113, "Soul of King Dodongo" },
    { 0x114, "Soul of Barinade" },
    { 0x115, "Soul of Phantom Ganon" },
    { 0x116, "Soul of Volvagia" },
    { 0x117, "Soul of Morpha" },
    { 0x118, "Soul of Bongo Bongo" },
    { 0x119, "Soul of Twinrova" },
    { 0x11A, "Soul of Saria" },
    { 0x11B, "Soul of Darunia" },
    { 0x11C, "Soul of Ruto (OoT)" },
    { 0x11D, "Soul of King Zora" },
    { 0x11E, "Soul of Zelda" },
    { 0x11F, "Soul of Sheik" },
    { 0x120, "Soul of Cucco Lady (OoT)" },
    { 0x121, "Soul of Carpenters (OoT)" },
    { 0x122, "Soul of Guru-Guru (OoT)" },
    { 0x123, "Soul of Mido" },
    { 0x124, "Soul of Kokiri" },
    { 0x125, "Soul of Kokiri Shopkeeper" },
    { 0x126, "Soul of Hylian Guard" },
    { 0x127, "Soul of the Citizens (OoT)" },
    { 0x128, "Soul of Malon (OoT)" },
    { 0x129, "Soul of Talon (OoT)" },
    { 0x12A, "Soul of Fishing Pond Owner (OoT)" },
    { 0x12B, "Soul of Goron (OoT)" },
    { 0x12C, "Soul of Medigoron (OoT)" },
    { 0x12D, "Soul of Biggoron (OoT)" },
    { 0x12E, "Soul of Goron Child (OoT)" },
    { 0x12F, "Soul of Goron Shopkeeper (OoT)" },
    { 0x130, "Soul of Zora (OoT)" },
    { 0x131, "Soul of Zora Shopkeeper (OoT)" },
    { 0x132, "Soul of Bazaar Shopkeeper (OoT)" },
    { 0x133, "Soul of Bombchu Shopkeeper (OoT)" },
    { 0x134, "Soul of Potion Shopkeeper" },
    { 0x135, "Soul of Bombchu Bowling Lady (OoT)" },
    { 0x136, "Soul of Chest Game Owner (OoT)" },
    { 0x137, "Soul of Shooting Gallery Owner (OoT)" },
    { 0x138, "Soul of Dampe (OoT)" },
    { 0x139, "Soul of Graveyard Kid (OoT)" },
    { 0x13A, "Soul of Poe Collector (OoT)" },
    { 0x13B, "Soul of Composer Bros. (OoT)" },
    { 0x13C, "Soul of Honey & Darling (OoT)" },
    { 0x13D, "Soul of the Astronomer (OoT)" },
    { 0x13E, "Soul of the Rooftop Man (OoT)" },
    { 0x13F, "Soul of the Bean Salesman (OoT)" },
    { 0x140, "Soul of the Scientist (OoT)" },
    { 0x141, "Soul of Ingo (OoT)" },
    { 0x142, "Soul of the Punk Kid (OoT)" },
    { 0x143, "Soul of the Dog Lady (OoT)" },
    { 0x144, "Soul of the Carpet Man (OoT)" },
    { 0x145, "Soul of the Old Hag (OoT)" },
    { 0x146, "Soul of the Beggar (OoT)" },
    { 0x147, "Soul of the Patrolling Gerudos" },
    { 0x148, "Soul of Cuccos (OoT)" },
    { 0x149, "Soul of Cows (OoT)" },
    { 0x14A, "Soul of Dogs (OoT)" },
    { 0x14B, "Soul of Butterflies (OoT)" },
    { 0x14C, "Soul of Gold Skulltulas (OoT)" },
    { 0x14D, "Soul of Business Scrubs (OoT)" },
    { 0x14E, "Key Ring (OoT)" },
    { 0x14F, "Key Ring (Forest)" },
    { 0x150, "Key Ring (Fire)" },
    { 0x151, "Key Ring (Water)" },
    { 0x152, "Key Ring (Spirit)" },
    { 0x153, "Key Ring (Shadow)" },
    { 0x154, "Key Ring (Ganon)" },
    { 0x155, "Key Ring (Well)" },
    { 0x156, "Key Ring (Hideout)" },
    { 0x157, "Key Ring (GTG)" },
    { 0x158, "Skeleton Key (OoT)" },
    { 0x159, "Coin (Red)" },
    { 0x15A, "Coin (Green)" },
    { 0x15B, "Coin (Blue)" },
    { 0x15C, "Coin (Yellow)" },
    { 0x15D, "Triforce of Power" },
    { 0x15E, "Triforce of Courage" },
    { 0x15F, "Triforce of Wisdom" },
    { 0x160, "Silver Rupee Pouch (Dodongo's Cavern)" },
    { 0x161, "Silver Rupee Pouch (Bottom of the Well)" },
    { 0x162, "Silver Rupee Pouch (Spirit Temple - Child)" },
    { 0x163, "Silver Rupee Pouch (Spirit Temple - Sun Block)" },
    { 0x164, "Silver Rupee Pouch (Spirit Temple - Boulders)" },
    { 0x165, "Silver Rupee Pouch (Spirit Temple - Lobby)" },
    { 0x166, "Silver Rupee Pouch (Spirit Temple - Adult)" },
    { 0x167, "Silver Rupee Pouch (Shadow Temple - Scythe)" },
    { 0x168, "Silver Rupee Pouch (Shadow Temple - Large Pits)" },
    { 0x169, "Silver Rupee Pouch (Shadow Temple - Spikes)" },
    { 0x16A, "Silver Rupee Pouch (Shadow Temple - Invisible Blades)" },
    { 0x16B, "Silver Rupee Pouch (Ice Cavern - Scythe)" },
    { 0x16C, "Silver Rupee Pouch (Ice Cavern - Block)" },
    { 0x16D, "Silver Rupee Pouch (Gerudo Training Ground - Slopes)" },
    { 0x16E, "Silver Rupee Pouch (Gerudo Training Ground - Lava)" },
    { 0x16F, "Silver Rupee Pouch (Gerudo Training Ground - Water)" },
    { 0x170, "Silver Rupee Pouch (Ganon's Castle - Spirit Trial)" },
    { 0x171, "Silver Rupee Pouch (Ganon's Castle - Light Trial)" },
    { 0x172, "Silver Rupee Pouch (Ganon's Castle - Fire Trial)" },
    { 0x173, "Silver Rupee Pouch (Ganon's Castle - Forest Trial)" },
    { 0x174, "Silver Rupee Pouch (Ganon's Castle - Shadow Trial)" },
    { 0x175, "Silver Rupee Pouch (Ganon's Castle - Water Trial)" },
    { 0x176, "Magical Silver Rupee" },
    { 0x177, "A Button (OoT)" },
    { 0x178, "C-Right Button (OoT)" },
    { 0x179, "C-Left Button (OoT)" },
    { 0x17A, "C-Up Button (OoT)" },
    { 0x17B, "C-Down Button (OoT)" },
    { 0x17C, "Small Key (Chest Game)" },
    { 0x17D, "Key Ring (Chest Game)" },
    { 0x17E, "Bottle of Red Potion (OoT)" },
    { 0x17F, "Bottle of Green Potion (OoT)" },
    { 0x180, "Bottle of Blue Potion (OoT)" },
    { 0x181, "Bottled Fairy (OoT)" },
    { 0x182, "Bottled Poe (OoT)" },
    { 0x183, "Bottled Big Poe (OoT)" },
    { 0x184, "Bottle of Blue Fire" },
    { 0x185, "Child Fish (2 pounds)" },
    { 0x186, "Child Fish (3 pounds)" },
    { 0x187, "Child Fish (4 pounds)" },
    { 0x188, "Child Fish (5 pounds)" },
    { 0x189, "Child Fish (6 pounds)" },
    { 0x18A, "Child Fish (7 pounds)" },
    { 0x18B, "Child Fish (8 pounds)" },
    { 0x18C, "Child Fish (9 pounds)" },
    { 0x18D, "Child Fish (10 pounds)" },
    { 0x18E, "Child Fish (11 pounds)" },
    { 0x18F, "Child Fish (12 pounds)" },
    { 0x190, "Child Fish (13 pounds)" },
    { 0x191, "Child Fish (14 pounds)" },
    { 0x192, "Adult Fish (4 pounds)" },
    { 0x193, "Adult Fish (5 pounds)" },
    { 0x194, "Adult Fish (6 pounds)" },
    { 0x195, "Adult Fish (7 pounds)" },
    { 0x196, "Adult Fish (8 pounds)" },
    { 0x197, "Adult Fish (9 pounds)" },
    { 0x198, "Adult Fish (10 pounds)" },
    { 0x199, "Adult Fish (11 pounds)" },
    { 0x19A, "Adult Fish (12 pounds)" },
    { 0x19B, "Adult Fish (13 pounds)" },
    { 0x19C, "Adult Fish (14 pounds)" },
    { 0x19D, "Adult Fish (15 pounds)" },
    { 0x19E, "Adult Fish (16 pounds)" },
    { 0x19F, "Adult Fish (17 pounds)" },
    { 0x1A0, "Adult Fish (18 pounds)" },
    { 0x1A1, "Adult Fish (19 pounds)" },
    { 0x1A2, "Adult Fish (20 pounds)" },
    { 0x1A3, "Adult Fish (21 pounds)" },
    { 0x1A4, "Adult Fish (22 pounds)" },
    { 0x1A5, "Adult Fish (23 pounds)" },
    { 0x1A6, "Adult Fish (24 pounds)" },
    { 0x1A7, "Adult Fish (25 pounds)" },
    { 0x1A8, "Child Loach (14 pounds)" },
    { 0x1A9, "Child Loach (15 pounds)" },
    { 0x1AA, "Child Loach (16 pounds)" },
    { 0x1AB, "Child Loach (17 pounds)" },
    { 0x1AC, "Child Loach (18 pounds)" },
    { 0x1AD, "Child Loach (19 pounds)" },
    { 0x1AE, "Adult Loach (29 pounds)" },
    { 0x1AF, "Adult Loach (30 pounds)" },
    { 0x1B0, "Adult Loach (31 pounds)" },
    { 0x1B1, "Adult Loach (32 pounds)" },
    { 0x1B2, "Adult Loach (33 pounds)" },
    { 0x1B3, "Adult Loach (34 pounds)" },
    { 0x1B4, "Adult Loach (35 pounds)" },
    { 0x1B5, "Adult Loach (36 pounds)" },
    { 0x1B6, "Bombchu Bag (OoT)" },
    { 0x1B7, "Big Bombchu Bag (OoT)" },
    { 0x1B8, "Biggest Bombchu Bag (OoT)" },
    { 0x1B9, "Bombchu Bag (OoT)" },
    { 0x1BA, "Bombchu Bag (OoT)" },
    { 0x1BB, "Bombchu Bag (OoT)" },
    { 0x1BC, "Razor Sword (OoT)" },
    { 0x1BD, "Gilded Sword (OoT)" },
    { 0x1BE, "Spin Attack Upgrade (OoT)" },
    { 0x1BF, "Triforce (OoT)" },
    { 0x1C0, "Big Fairy (OoT)" },
    { 0x1C1, "Blast Mask (OoT)" },
    { 0x1C2, "Stone Mask (OoT)" },
    { 0x1C3, "Bronze Scale (OoT)" },
    { 0x1C4, "Magic Mushroom" },
    { 0x1C5, "Chateau Romani Refill" },
    { 0x1C6, "Chateau Romani" },
    { 0x1C7, "Seahorse" },
    { 0x1C8, "Bottle of Gold Dust" },
    { 0x1C9, "Bottle of Chateau Romani" },
    { 0x1CA, "Ice Trap" },
    { 0x1CB, "Fire Trap" },
    { 0x1CC, "Shock Trap" },
    { 0x1CD, "Drain Trap" },
    { 0x1CE, "Anti-Magic Trap" },
    { 0x1CF, "Knockback Trap" },
    { 0x1D0, "Rupoor" },
    { 0x1D1, "Platinum Token (OoT)" },
    { 0x1D2, "Green Rupee (MM)" },
    { 0x1D3, "Blue Rupee (MM)" },
    { 0x1D4, "Red Rupee (MM)" },
    { 0x1D5, "Red Rupee (MM)" },
    { 0x1D6, "Purple Rupee (MM)" },
    { 0x1D7, "Silver Rupee (MM)" },
    { 0x1D8, "Gold Rupee (MM)" },
    { 0x1D9, "Adult Wallet (MM)" },
    { 0x1DA, "Giant Wallet (MM)" },
    { 0x1DB, "Recovery Heart (MM)" },
    { 0x1DC, "Piece of Heart (MM)" },
    { 0x1DD, "Heart Container (MM)" },
    { 0x1DE, "Small Magic Jar (MM)" },
    { 0x1DF, "Large Magic Jar (MM)" },
    { 0x1E0, "Stray Fairy (MM)" },
    { 0x1E1, "Stray Fairy (Woodfall Temple)" },
    { 0x1E2, "Stray Fairy (Snowhead Temple)" },
    { 0x1E3, "Stray Fairy (Great Bay Temple)" },
    { 0x1E4, "Stray Fairy (Stone Tower Temple)" },
    { 0x1E5, "Stray Fairy (Clock Town)" },
    { 0x1E6, "Transcendent Fairy" },
    { 0x1E7, "Bomb (MM)" },
    { 0x1E8, "5 Bombs (MM)" },
    { 0x1E9, "10 Bombs (MM)" },
    { 0x1EA, "20 Bombs (MM)" },
    { 0x1EB, "30 Bombs (MM)" },
    { 0x1EC, "Deku Stick (MM)" },
    { 0x1ED, "10 Bombchu (MM)" },
    { 0x1EE, "Bomb Bag (MM)" },
    { 0x1EF, "Big Bomb Bag (MM)" },
    { 0x1F0, "Biggest Bomb Bag (MM)" },
    { 0x1F1, "10 Arrows (MM)" },
    { 0x1F2, "30 Arrows (MM)" },
    { 0x1F3, "40 Arrows (MM)" },
    { 0x1F4, "40 Arrows (MM)" },
    { 0x1F5, "Hero's Bow (MM)" },
    { 0x1F6, "Big Quiver (MM)" },
    { 0x1F7, "Biggest Quiver (MM)" },
    { 0x1F8, "Fire Arrows (MM)" },
    { 0x1F9, "Ice Arrows (MM)" },
    { 0x1FA, "Light Arrows (MM)" },
    { 0x1FB, "Nut (MM)" },
    { 0x1FC, "5 Deku Nuts (MM)" },
    { 0x1FD, "10 Deku Nuts (MM)" },
    { 0x1FE, "30 Deku Nuts (MM)" },
    { 0x1FF, "30 Deku Nuts (MM)" },
    { 0x200, "40 Deku Nuts (MM)" },
    { 0x201, "20 Bombchu (MM)" },
    { 0x202, "20 Deku Sticks (MM)" },
    { 0x203, "20 Deku Sticks (MM)" },
    { 0x204, "30 Deku Sticks (MM)" },
    { 0x205, "Deku Shield (MM)" },
    { 0x206, "Hero's Shield" },
    { 0x207, "Mirror Shield (MM)" },
    { 0x208, "Progressive Deku Shield (MM)" },
    { 0x209, "Progressive Hero's Shield" },
    { 0x20A, "Powder Keg" },
    { 0x20B, "Magic Bean (MM)" },
    { 0x20C, "1 Bombchu (MM)" },
    { 0x20D, "Kokiri Sword (MM)" },
    { 0x20E, "Razor Sword (MM)" },
    { 0x20F, "Gilded Sword (MM)" },
    { 0x210, "5 Bombchu (MM)" },
    { 0x211, "Great Fairy's Sword" },
    { 0x212, "Small Key (MM)" },
    { 0x213, "Boss Key (MM)" },
    { 0x214, "Map (MM)" },
    { 0x215, "Compass (MM)" },
    { 0x216, "Hookshot (MM)" },
    { 0x217, "Lens of Truth (MM)" },
    { 0x218, "Pictograph Box" },
    { 0x219, "Ocarina of Time (MM)" },
    { 0x21A, "Bombers' Notebook" },
    { 0x21B, "Bottle of Red Potion (MM)" },
    { 0x21C, "Empty Bottle (MM)" },
    { 0x21D, "Red Potion (MM)" },
    { 0x21E, "Green Potion (MM)" },
    { 0x21F, "Blue Potion (MM)" },
    { 0x220, "Fairy (MM)" },
    { 0x221, "Bottle of Milk (MM)" },
    { 0x222, "Fish (MM)" },
    { 0x223, "Bugs (MM)" },
    { 0x224, "Big Poe (MM)" },
    { 0x225, "Bottle of Gold Dust" },
    { 0x226, "Magic Mushroom" },
    { 0x227, "Bottle of Chateau Romani" },
    { 0x228, "Deku Mask" },
    { 0x229, "Goron Mask (MM)" },
    { 0x22A, "Zora Mask (MM)" },
    { 0x22B, "Fierce Deity's Mask" },
    { 0x22C, "Captain's Hat" },
    { 0x22D, "Giant's Mask" },
    { 0x22E, "All-Night Mask" },
    { 0x22F, "Bunny Hood (MM)" },
    { 0x230, "Keaton Mask" },
    { 0x231, "Garo's Mask" },
    { 0x232, "Romani's Mask" },
    { 0x233, "Circus Leader's Mask" },
    { 0x234, "Postman's Hat" },
    { 0x235, "Couple's Mask" },
    { 0x236, "Great Fairy's Mask" },
    { 0x237, "Gibdo Mask" },
    { 0x238, "Don Gero's Mask" },
    { 0x239, "Kamaro's Mask" },
    { 0x23A, "Mask of Truth (MM)" },
    { 0x23B, "Stone Mask (MM)" },
    { 0x23C, "Bremen Mask" },
    { 0x23D, "Blast Mask (MM)" },
    { 0x23E, "Mask of Scents" },
    { 0x23F, "Kafei's Mask" },
    { 0x240, "Chateau Romani Refill (MM)" },
    { 0x241, "Romani Milk" },
    { 0x242, "Gold Dust" },
    { 0x243, "Seahorse" },
    { 0x244, "Moon's Tear" },
    { 0x245, "Land Title Deed" },
    { 0x246, "Swamp Title Deed" },
    { 0x247, "Mountain Title Deed" },
    { 0x248, "Ocean Title Deed" },
    { 0x249, "Room Key" },
    { 0x24A, "Letter to Mama" },
    { 0x24B, "Letter to Kafei" },
    { 0x24C, "Pendant of Memories" },
    { 0x24D, "World Map of Clock Town" },
    { 0x24E, "World Map of Woodfall" },
    { 0x24F, "World Map of Snowhead" },
    { 0x250, "World Map of Ranch" },
    { 0x251, "World Map of Great Bay" },
    { 0x252, "World Map of Stone Tower" },
    { 0x253, "Magic Upgrade (MM)" },
    { 0x254, "Larger Magic Upgrade (MM)" },
    { 0x255, "Double Defense (MM)" },
    { 0x256, "Spin Attack Upgrade (MM)" },
    { 0x257, "Sonata of Awakening" },
    { 0x258, "Goron Lullaby" },
    { 0x259, "New Wave Bossa Nova" },
    { 0x25A, "Elegy of Emptiness (MM)" },
    { 0x25B, "Oath to Order" },
    { 0x25C, "Song of Time (MM)" },
    { 0x25D, "Song of Healing" },
    { 0x25E, "Epona's Song (MM)" },
    { 0x25F, "Song of Soaring" },
    { 0x260, "Song of Storms (MM)" },
    { 0x261, "Sun's Song (MM)" },
    { 0x262, "Progressive Goron Lullaby" },
    { 0x263, "Note from Sonata of Awakening (MM)" },
    { 0x264, "Note from Goron Lullaby (MM)" },
    { 0x265, "Note from New Wave Bossa Nova (MM)" },
    { 0x266, "Note from Elegy of Emptiness (MM)" },
    { 0x267, "Note from Oath to Order (MM)" },
    { 0x268, "Note from Song of Time (MM)" },
    { 0x269, "Note from Song of Healing (MM)" },
    { 0x26A, "Note from Epona's Song (MM)" },
    { 0x26B, "Note from Song of Soaring (MM)" },
    { 0x26C, "Note from Song of Storms (MM)" },
    { 0x26D, "Note from Sun's Song (MM)" },
    { 0x26E, "Odolwa's Remains" },
    { 0x26F, "Goht's Remains" },
    { 0x270, "Gyorg's Remains" },
    { 0x271, "Twinmold's Remains" },
    { 0x272, "Swamp Skulltula Token" },
    { 0x273, "Ocean Skulltula Token" },
    { 0x274, "Platinum Token (MM)" },
    { 0x275, "Small Key (Woodfall Temple)" },
    { 0x276, "Small Key (Snowhead Temple)" },
    { 0x277, "Small Key (Great Bay Temple)" },
    { 0x278, "Small Key (Stone Tower Temple)" },
    { 0x279, "Boss Key (Woodfall Temple)" },
    { 0x27A, "Boss Key (Snowhead Temple)" },
    { 0x27B, "Boss Key (Great Bay Temple)" },
    { 0x27C, "Boss Key (Stone Tower Temple)" },
    { 0x27D, "Map (Woodfall Temple)" },
    { 0x27E, "Map (Snowhead Temple)" },
    { 0x27F, "Map (Great Bay Temple)" },
    { 0x280, "Map (Stone Tower Temple)" },
    { 0x281, "Compass (Woodfall Temple)" },
    { 0x282, "Compass (Snowhead Temple)" },
    { 0x283, "Compass (Great Bay Temple)" },
    { 0x284, "Compass (Stone Tower Temple)" },
    { 0x285, "Fairy Ocarina (MM)" },
    { 0x286, "Short Hookshot (MM)" },
    { 0x287, "Child Wallet (MM)" },
    { 0x288, "Colossal Wallet (MM)" },
    { 0x289, "Owl Statue (Great Bay)" },
    { 0x28A, "Owl Statue (Zora Cape)" },
    { 0x28B, "Owl Statue (Snowhead)" },
    { 0x28C, "Owl Statue (Mountain Village)" },
    { 0x28D, "Owl Statue (Clock Town)" },
    { 0x28E, "Owl Statue (Milk Road)" },
    { 0x28F, "Owl Statue (Woodfall)" },
    { 0x290, "Owl Statue (Southern Swamp)" },
    { 0x291, "Owl Statue (Ikana Canyon)" },
    { 0x292, "Owl Statue (Stone Tower)" },
    { 0x293, "Owl Statue (Hidden)" },
    { 0x294, "Bottomless Wallet (MM)" },
    { 0x295, "Soul of Octoroks (MM)" },
    { 0x296, "Soul of Wallmasters (MM)" },
    { 0x297, "Soul of Dodongos (MM)" },
    { 0x298, "Soul of Keese (MM)" },
    { 0x299, "Soul of Tektites (MM)" },
    { 0x29A, "Soul of Peahats (MM)" },
    { 0x29B, "Soul of Lizalfos/Dinolfos (MM)" },
    { 0x29C, "Soul of Skulltulas (MM)" },
    { 0x29D, "Soul of Armos (MM)" },
    { 0x29E, "Soul of Deku Babas (MM)" },
    { 0x29F, "Soul of Deku Scrubs (MM)" },
    { 0x2A0, "Soul of Bubbles (MM)" },
    { 0x2A1, "Soul of Beamos (MM)" },
    { 0x2A2, "Soul of ReDeads/Gibdos (MM)" },
    { 0x2A3, "Soul of Skullwalltulas (MM)" },
    { 0x2A4, "Soul of Shell Blades (MM)" },
    { 0x2A5, "Soul of Like Likes (MM)" },
    { 0x2A6, "Soul of Iron Knuckles (MM)" },
    { 0x2A7, "Soul of Freezards (MM)" },
    { 0x2A8, "Soul of Wolfos (MM)" },
    { 0x2A9, "Soul of Guays (MM)" },
    { 0x2AA, "Soul of Flying Pots (MM)" },
    { 0x2AB, "Soul of Floormasters (MM)" },
    { 0x2AC, "Soul of Chuchus" },
    { 0x2AD, "Soul of Deep Pythons" },
    { 0x2AE, "Soul of Stalchildren (MM)" },
    { 0x2AF, "Soul of Leevers (MM)" },
    { 0x2B0, "Soul of Skullfish (MM)" },
    { 0x2B1, "Soul of Dexihands" },
    { 0x2B2, "Soul of Dragonflies" },
    { 0x2B3, "Soul of Eenoes" },
    { 0x2B4, "Soul of Eyegores" },
    { 0x2B5, "Soul of Hiploops" },
    { 0x2B6, "Soul of Real Bombchu" },
    { 0x2B7, "Soul of Takkuri" },
    { 0x2B8, "Soul of Boes" },
    { 0x2B9, "Soul of Nejirons" },
    { 0x2BA, "Soul of Bio Babas" },
    { 0x2BB, "Soul of Garo" },
    { 0x2BC, "Soul of Wizzrobes" },
    { 0x2BD, "Soul of Gomess" },
    { 0x2BE, "Soul of Gekkos" },
    { 0x2BF, "Soul of Bad Bats" },
    { 0x2C0, "Soul of Snappers" },
    { 0x2C1, "Soul of Warts" },
    { 0x2C2, "Soul of Captain Keeta" },
    { 0x2C3, "Soul of the Fighting Pirates" },
    { 0x2C4, "Soul of Poes (MM)" },
    { 0x2C5, "Soul of Odolwa" },
    { 0x2C6, "Soul of Goht" },
    { 0x2C7, "Soul of Gyorg" },
    { 0x2C8, "Soul of Twinmold" },
    { 0x2C9, "Soul of Igos" },
    { 0x2CA, "Soul of Madame Aroma (MM)" },
    { 0x2CB, "Soul of Town Archery Owner (MM)" },
    { 0x2CC, "Soul of Swamp Archery Owner (MM)" },
    { 0x2CD, "Soul of Gorons (MM)" },
    { 0x2CE, "Soul of the Goron Baby (MM)" },
    { 0x2CF, "Soul of the Bomb Shop Owner (MM)" },
    { 0x2D0, "Soul of Bombers (MM)" },
    { 0x2D1, "Soul of the Deku Butler" },
    { 0x2D2, "Soul of Citizens (MM)" },
    { 0x2D3, "Soul of Composer Bros. (MM)" },
    { 0x2D4, "Soul of Dampe (MM)" },
    { 0x2D5, "Soul of the Deku King" },
    { 0x2D6, "Soul of the Deku Princess" },
    { 0x2D7, "Soul of Playground Scrubs" },
    { 0x2D8, "Soul of the Goron Elder" },
    { 0x2D9, "Soul of the Fisherman (MM)" },
    { 0x2DA, "Soul of the Goron Shopkeeper (MM)" },
    { 0x2DB, "Soul of Honey & Darling (MM)" },
    { 0x2DC, "Soul of Toto(MM)" },
    { 0x2DD, "Soul of Lulu (MM)" },
    { 0x2DE, "Soul of the Zora Musicians" },
    { 0x2DF, "Soul of Kafei" },
    { 0x2E0, "Soul of Keaton" },
    { 0x2E1, "Soul of Koume and Kotake" },
    { 0x2E2, "Soul of Mayor Dotour" },
    { 0x2E3, "Soul of Keg Trial Goron (MM)" },
    { 0x2E4, "Soul of Biggoron (MM)" },
    { 0x2E5, "Soul of Mr. Barten (MM)" },
    { 0x2E6, "Soul of Astronomer (MM)" },
    { 0x2E7, "Soul of Ghost Hut Owner (MM)" },
    { 0x2E8, "Soul of Blacksmiths" },
    { 0x2E9, "Soul of Chest Game Lady (MM)" },
    { 0x2EA, "Soul of Tingle" },
    { 0x2EB, "Soul of Toilet Hand" },
    { 0x2EC, "Soul of Trading Post Owner (MM)" },
    { 0x2ED, "Soul of Part-Timer (MM)" },
    { 0x2EE, "Soul of Zoras (MM)" },
    { 0x2EF, "Soul of the Zora Shopkeeper (MM)" },
    { 0x2F0, "Soul of Romani/Cremia (MM)" },
    { 0x2F1, "Soul of the Beans Salesman (MM)" },
    { 0x2F2, "Soul of Carpenters (MM)" },
    { 0x2F3, "Soul of Anju (MM)" },
    { 0x2F4, "Soul of Guru-Guru (MM)" },
    { 0x2F5, "Soul of the Scientist (MM)" },
    { 0x2F6, "Soul of Gorman & Bros. (MM)" },
    { 0x2F7, "Soul of Grog (MM)" },
    { 0x2F8, "Soul of Dog Lady (MM)" },
    { 0x2F9, "Soul of Swordsman (MM)" },
    { 0x2FA, "Soul of Anju's Grandmother (MM)" },
    { 0x2FB, "Soul of Tourist Center Owner" },
    { 0x2FC, "Soul of the Banker (MM)" },
    { 0x2FD, "Soul of Moon Children" },
    { 0x2FE, "Soul of the Patrolling Pirates and their Chief" },
    { 0x2FF, "Soul of Cuccos (MM)" },
    { 0x300, "Soul of Cows (MM)" },
    { 0x301, "Sould of Dogs (MM)" },
    { 0x302, "Soul of Butterflies (MM)" },
    { 0x303, "Soul of Gold Skulltulas (MM)" },
    { 0x304, "Soul of Business Scrubs (MM)" },
    { 0x305, "Key Ring (MM)" },
    { 0x306, "Key Ring (Woodfall)" },
    { 0x307, "Key Ring (Snowhead)" },
    { 0x308, "Key Ring (Great Bay)" },
    { 0x309, "Key Ring (Stone Tower)" },
    { 0x30A, "Skeleton Key (MM)" },
    { 0x30B, "A Button (MM)" },
    { 0x30C, "C-Right Button (MM)" },
    { 0x30D, "C-Left Button (MM)" },
    { 0x30E, "C-Up Button (MM)" },
    { 0x30F, "C-Down Button (MM)" },
    { 0x310, "Bottle of Green Potion (MM)" },
    { 0x311, "Bottle of Blue Potion (MM)" },
    { 0x312, "Bottled Fairy (MM)" },
    { 0x313, "Poe (MM)" },
    { 0x314, "Bottled Poe (MM)" },
    { 0x315, "Bottled Big Poe (MM)" },
    { 0x316, "Bombchu Bag (MM)" },
    { 0x317, "Big Bombchu Bag (MM)" },
    { 0x318, "Biggest Bombchu Bag (MM)" },
    { 0x319, "Bombchu Bag (MM)" },
    { 0x31A, "Bombchu Bag (MM)" },
    { 0x31B, "Bombchu Bag (MM)" },
    { 0x31C, "Bombchu Bag (MM)" },
    { 0x31D, "Big Fairy (MM)" },
    { 0x31E, "Din's Fire (MM)" },
    { 0x31F, "Farore's Wind (MM)" },
    { 0x320, "Nayru's Love (MM)" },
    { 0x321, "Iron Boots (MM)" },
    { 0x322, "Hover Boots (MM)" },
    { 0x323, "Goron Tunic (MM)" },
    { 0x324, "Zora Tunic (MM)" },
    { 0x325, "Bronze Scale (MM)" },
    { 0x326, "Silver Scale (MM)" },
    { 0x327, "Golden Scale (MM)" },
    { 0x328, "Goron's Bracelet (MM)" },
    { 0x329, "Silver Gauntlets (MM)" },
    { 0x32A, "Golden Gauntlets (MM)" },
    { 0x32B, "Clock (Day 1)" },
    { 0x32C, "Clock (Night 1)" },
    { 0x32D, "Clock (Day 2)" },
    { 0x32E, "Clock (Night 2)" },
    { 0x32F, "Clock (Day 3)" },
    { 0x330, "Clock (Night 3)" },
    { 0x331, "Megaton Hammer (MM)" },
    { 0x332, "Deku Stick Upgrade (MM)" },
    { 0x333, "Second Deku Stick Upgrade (MM)" },
    { 0x334, "Deku Nut Upgrade (MM)" },
    { 0x335, "Second Deku Nut Upgrade (MM)" },
    { 0x336, "Stone of Agony (MM)" },
    { 0x337, "Ruto's Letter" },
    { 0x338, "Bottle of Blue Fire" },
    { 0x339, "Blue Fire" },
    { 0x33A, "Majora's Mask" },
    { 0x33B, "Sold Out" },
    { 0x33C, "Nothing" },
    { 0x33D, "MM Scoop" },
};

#pragma endregion 

void ParseKey(uint8_t Key[5], ComboItem* Item)
{
    uint8_t index = 0;

    Item->GameID = Key[index];
    Item->OvType = Key[++index];
    Item->SceneID = Key[++index];
    Item->RoomID = Key[++index];
    Item->ObjectID = Key[++index];
}

const ItemInfo * FindItem(uint32_t gi)
{
    const ItemInfo * currItem = nullptr;

    for (size_t i = 0; i < NUM_ITEM; i++)
    {
        currItem = &ItemList[i];

        if (currItem->ItemID == gi)
        {
            return currItem;
        }
    }

    return currItem;
}

const ItemInfo* FindItemByName(QString Name)
{
    Name = Name.replace("\n", "");
    size_t len = Name.length() + 1;
    char* tmpObjName = (char*)malloc(sizeof(char) * len);
    if (tmpObjName)
    {
        memcpy_s(tmpObjName, len, Name.toStdString().c_str(), len);
        tmpObjName[len - 1] = '\0';

        for (size_t i = 0; i < NUM_ITEM; i++)
        {
            if (strcmp(tmpObjName, ItemList[i].ItemName) == 0)
            {
                free(tmpObjName);
                return &ItemList[i];
            }
        }

        // No item found

        ItemInfo* item = new ItemInfo();
        item->ItemID = -1;
        item->ItemName = tmpObjName;

        return item;

    }
    return nullptr;
}