#include "Combo/Items.h"

#pragma region Items

#define NUM_ITEM 0x33D

const ItemInfo ItemList[NUM_ITEM] =
{
    { 0x1, "5 Bombs (OoT)" , ObjectIconMap::bomb },
{ 0x2, "5 Deku Nuts (OoT)" , ObjectIconMap::nut },
{ 0x3, "10 Bombchu (OoT)" , ObjectIconMap::bombchu },
{ 0x4, "Fairy Bow (OoT)" , ObjectIconMap::bow_oot },
{ 0x5, "Fairy Slingshot" , ObjectIconMap::slingshot },
{ 0x6, "Boomerang" , ObjectIconMap::boomrang },
{ 0x7, "Deku Stick (OoT)" , ObjectIconMap::stick },
{ 0x8, "Progressive Hookshot (OoT)" , ObjectIconMap::none },
{ 0x9, "Longshot (OoT)" , ObjectIconMap::longshot },
{ 0xA, "Lens of Truth (OoT)" , ObjectIconMap::lens },
{ 0xB, "Zelda's Letter" , ObjectIconMap::letter },
{ 0xC, "Ocarina of Time (OoT)" , ObjectIconMap::ocarina },
{ 0xD, "Megaton Hammer (OoT)" , ObjectIconMap::hammer },
{ 0xE, "Cojiro" , ObjectIconMap::cojiro },
{ 0xF, "Empty Bottle (OoT)" , ObjectIconMap::bottle },
{ 0x10, "Red Potion (OoT)" , ObjectIconMap::red_potion },
{ 0x11, "Green Potion (OoT)" , ObjectIconMap::green_potion },
{ 0x12, "Blue Potion (OoT)" , ObjectIconMap::blue_potion },
{ 0x13, "Fairy (OoT)" , ObjectIconMap::fairy },
{ 0x14, "Bottle of Milk (OoT)" , ObjectIconMap::milk },
{ 0x15, "Ruto's Letter" , ObjectIconMap::ruto },
{ 0x16, "Magic Beans (OoT)" , ObjectIconMap::bean },
{ 0x17, "Skull Mask" , ObjectIconMap::skull },
{ 0x18, "Spooky Mask" , ObjectIconMap::spooky },
{ 0x19, "Chicken" , ObjectIconMap::cucco },
{ 0x1A, "Keaton Mask (OoT)" , ObjectIconMap::keaton },
{ 0x1B, "Bunny Hood (OoT)" , ObjectIconMap::bunny },
{ 0x1C, "Mask of Truth (OoT)" , ObjectIconMap::truth },
{ 0x1D, "Pocket Egg" , ObjectIconMap::egg },
{ 0x1E, "Pocket Cucco" , ObjectIconMap::cucco },
{ 0x1F, "Odd Mushroom" , ObjectIconMap::mushroom },
{ 0x20, "Odd Potion" , ObjectIconMap::potion },
{ 0x21, "Poacher's Saw" , ObjectIconMap::saw },
{ 0x22, "Broken Goron's Sword" , ObjectIconMap::biggoron },
{ 0x23, "Prescription" , ObjectIconMap::prescription },
{ 0x24, "Eyeball Frog" , ObjectIconMap::frog },
{ 0x25, "Eye Drops" , ObjectIconMap::eye_drops },
{ 0x26, "Claim Check" , ObjectIconMap::claim },
{ 0x27, "Kokiri Sword (OoT)" , ObjectIconMap::kokiri },
{ 0x28, "Giant's Knife" , ObjectIconMap::biggoron },
{ 0x29, "Deku Shield (OoT)" , ObjectIconMap::deku_shield },
{ 0x2A, "Hylian Shield" , ObjectIconMap::hylian_shield },
{ 0x2B, "Mirror Shield (OoT)" , ObjectIconMap::mirror_oot },
{ 0x2C, "Goron Tunic (OoT)" , ObjectIconMap::goron_tunic },
{ 0x2D, "Zora Tunic (OoT)" , ObjectIconMap::zora_tunic },
{ 0x2E, "Iron Boots (OoT)" , ObjectIconMap::iron },
{ 0x2F, "Hover Boots (OoT)" , ObjectIconMap::hover },
{ 0x30, "Big Quiver (OoT)" , ObjectIconMap::big_quiver },
{ 0x31, "Biggest Quiver (OoT)" , ObjectIconMap::biggest_quiver },
{ 0x32, "Bomb Bag (OoT)" , ObjectIconMap::bomb_bag },
{ 0x33, "Big Bomb Bag (OoT)" , ObjectIconMap::big_bomb },
{ 0x34, "Biggest Bomb Bag (OoT)" , ObjectIconMap::biggest_bomb },
{ 0x35, "Silver Gauntlets (OoT)" , ObjectIconMap::silver_gauntlet },
{ 0x36, "Golden Gauntlets (OoT)" , ObjectIconMap::golden_gauntlet },
{ 0x37, "Silver Scale (OoT)" , ObjectIconMap::silver },
{ 0x38, "Golden Scale (OoT)" , ObjectIconMap::golden },
{ 0x39, "Stone of Agony (OoT)" , ObjectIconMap::agony },
{ 0x3A, "Gerudo's Membership Card" , ObjectIconMap::card },
{ 0x3B, "Fairy Ocarina (OoT)" , ObjectIconMap::fairy_ocarina },
{ 0x3C, "5 Deku Seeds (OoT)" , ObjectIconMap::seeds },
{ 0x3D, "Heart Container (OoT)" , ObjectIconMap::heart_container },
{ 0x3E, "Piece of Heart (OoT)" , ObjectIconMap::heart_piece },
{ 0x3F, "Boss Key (OoT)" , ObjectIconMap::boss_key },
{ 0x40, "Compass (OoT)" , ObjectIconMap::compass },
{ 0x41, "Map (OoT)" , ObjectIconMap::map },
{ 0x42, "Small Key (OoT)" , ObjectIconMap::small_key },
{ 0x43, "Small Magic Jar (OoT)" , ObjectIconMap::magic },
{ 0x44, "Large Magic Jar (OoT)" , ObjectIconMap::double_magic },
{ 0x45, "Adult's Wallet (OoT)" , ObjectIconMap::wallet },
{ 0x46, "Giant's Wallet (OoT)" , ObjectIconMap::big_wallet },
{ 0x47, "Weird Egg" , ObjectIconMap::egg },
{ 0x48, "Recovery Heart (OoT)" , ObjectIconMap::heart },
{ 0x49, "5 Arrows (OoT)" , ObjectIconMap::arrow },
{ 0x4A, "10 Arrows (OoT)" , ObjectIconMap::arrow },
{ 0x4B, "30 Arrows (OoT)" , ObjectIconMap::arrow },
{ 0x4C, "Green Rupee (OoT)" , ObjectIconMap::rupee },
{ 0x4D, "Blue Rupee (OoT)" , ObjectIconMap::blue_rupee },
{ 0x4E, "Red Rupee (OoT)" , ObjectIconMap::red_rupee },
{ 0x4F, "Heart Container (OoT)" , ObjectIconMap::heart_container },
{ 0x50, "Lon Lon Milk (OoT)" , ObjectIconMap::milk },
{ 0x51, "Goron Mask (OoT)" , ObjectIconMap::goron },
{ 0x52, "Zora Mask (OoT)" , ObjectIconMap::zora },
{ 0x53, "Gerudo Mask" , ObjectIconMap::gerudo },
{ 0x54, "Goron's Bracelet (OoT)" , ObjectIconMap::bracelet },
{ 0x55, "Purple Rupee (OoT)" , ObjectIconMap::purple_rupee },
{ 0x56, "Gold Rupee (OoT)" , ObjectIconMap::gold_rupee },
{ 0x57, "Biggoron's Sword" , ObjectIconMap::biggoron },
{ 0x58, "Fire Arrows (OoT)" , ObjectIconMap::fire_arrow },
{ 0x59, "Ice Arrows (OoT)" , ObjectIconMap::ice_arrow },
{ 0x5A, "Light Arrows (OoT)" , ObjectIconMap::light_arrow },
{ 0x5B, "Gold Skulltula Token" , ObjectIconMap::gs_token },
{ 0x5C, "Din's Fire (OoT)" , ObjectIconMap::din },
{ 0x5D, "Farore's Wind (OoT)" , ObjectIconMap::farore },
{ 0x5E, "Nayru's Love (OoT)" , ObjectIconMap::nayru },
{ 0x5F, "Bullet Bag" , ObjectIconMap::big_seed },
{ 0x60, "Large Bullet Bag" , ObjectIconMap::biggest_seed },
{ 0x61, "5 Deku Sticks (OoT)" , ObjectIconMap::stick },
{ 0x62, "10 Deku Sticks (OoT)" , ObjectIconMap::stick },
{ 0x63, "5 Deku Nuts (OoT)" , ObjectIconMap::nut },
{ 0x64, "10 Deku Nuts (OoT)" , ObjectIconMap::nut },
{ 0x65, "Bomb (OoT)" , ObjectIconMap::bomb },
{ 0x66, "10 Bombs (OoT)" , ObjectIconMap::bomb },
{ 0x67, "20 Bombs (OoT)" , ObjectIconMap::bomb },
{ 0x68, "30 Bombs (OoT)" , ObjectIconMap::bomb },
{ 0x69, "30 Deku Seeds" , ObjectIconMap::seeds },
{ 0x6A, "5 Bombchu (OoT)" , ObjectIconMap::bombchu },
{ 0x6B, "20 Bombchu (OoT)" , ObjectIconMap::bombchu },
{ 0x6C, "Fish (OoT)" , ObjectIconMap::bottled_fish },
{ 0x6D, "Bugs (OoT)" , ObjectIconMap::bottled_bugs },
{ 0x6E, "Blue Fire" , ObjectIconMap::blue_fire },
{ 0x6F, "Poe (OoT)" , ObjectIconMap::bottled_poe },
{ 0x70, "Big Poe (OoT)" , ObjectIconMap::bottled_big_poe },
{ 0x71, "Small Key (OoT)" , ObjectIconMap::small_key },
{ 0x72, "Green Rupee (OoT)" , ObjectIconMap::rupee },
{ 0x73, "Blue Rupee (OoT)" , ObjectIconMap::blue_rupee },
{ 0x74, "Red Rupee (OoT)" , ObjectIconMap::red_rupee },
{ 0x75, "Purple Rupee (OoT)" , ObjectIconMap::purple_rupee },
{ 0x76, "Piece of Heart (OoT)" , ObjectIconMap::heart_piece },
{ 0x77, "Deku Stick Upgrade (OoT)" , ObjectIconMap::stick_upgrade_1 },
{ 0x78, "Second Deku Stick Upgrade (OoT)" , ObjectIconMap::stick_upgrade_2 },
{ 0x79, "Deku Nut Upgrade (OoT)" , ObjectIconMap::nut_upgrade_1 },
{ 0x7A, "Second Deku Nut Upgrade (OoT)" , ObjectIconMap::nut_upgrade_2 },
{ 0x7B, "Largest Bullet Bag" , ObjectIconMap::biggest_seed },
{ 0x7C, "Ice Trap (OoT)" , ObjectIconMap::ice_trap },
{ 0x7D, "Unknown" , ObjectIconMap::none },
{ 0x7E, "Unknown" , ObjectIconMap::none },
{ 0x7F, "Unknown" , ObjectIconMap::none },
{ 0x80, "Rainbow Rupee (OoT)" , ObjectIconMap::rainbow_rupee },
{ 0x81, "Minuet of Forest" , ObjectIconMap::song_green },
{ 0x82, "Bolero of Fire" , ObjectIconMap::song_red },
{ 0x83, "Serenade of Water" , ObjectIconMap::song_blue },
{ 0x84, "Requiem of Spirit" , ObjectIconMap::song_orange },
{ 0x85, "Nocturne of Shadow" , ObjectIconMap::song_purple },
{ 0x86, "Prelude of Light" , ObjectIconMap::song_yellow },
{ 0x87, "Zelda's Lullaby" , ObjectIconMap::song },
{ 0x88, "Epona's Song (OoT)" , ObjectIconMap::song },
{ 0x89, "Saria's Song" , ObjectIconMap::song },
{ 0x8A, "Sun's Song (OoT)" , ObjectIconMap::song },
{ 0x8B, "Song of Time (OoT)" , ObjectIconMap::song },
{ 0x8C, "Song of Storms (OoT)" , ObjectIconMap::song },
{ 0x8D, "Elegy of Emptiness (OoT)" , ObjectIconMap::song_orange },
{ 0x8E, "Note from Minuet of Forest (OoT)" , ObjectIconMap::song_green },
{ 0x8F, "Note from Bolero of Fire (OoT)" , ObjectIconMap::song_red },
{ 0x90, "Note from Serenade of Water (OoT)" , ObjectIconMap::song_blue },
{ 0x91, "Note from Requiem of Spirit (OoT)" , ObjectIconMap::song_orange },
{ 0x92, "Note from Nocturne of Shadow (OoT)" , ObjectIconMap::song_purple },
{ 0x93, "Note from Prelude of Light (OoT)" , ObjectIconMap::song_yellow },
{ 0x94, "Note from Zelda's Lullaby (OoT)" , ObjectIconMap::song },
{ 0x95, "Note from Epona's Song (OoT)" , ObjectIconMap::song },
{ 0x96, "Note from Saria's Song (OoT)" , ObjectIconMap::song },
{ 0x97, "Note from Sun's Song (OoT)" , ObjectIconMap::song },
{ 0x98, "Note from Song of Time (OoT)" , ObjectIconMap::song },
{ 0x99, "Note from Song of Storms (OoT)" , ObjectIconMap::song },
{ 0x9A, "Note from Elegy of Emptiness (OoT)" , ObjectIconMap::song_orange },
{ 0x9B, "Master Sword" , ObjectIconMap::master },
{ 0x9C, "Kokiri's Emerald" , ObjectIconMap::emerald },
{ 0x9D, "Goron's Ruby" , ObjectIconMap::ruby },
{ 0x9E, "Zora's Sapphire" , ObjectIconMap::sapphire },
{ 0x9F, "Forest Medallion" , ObjectIconMap::forest },
{ 0xA0, "Fire Medallion" , ObjectIconMap::fire },
{ 0xA1, "Water Medallion" , ObjectIconMap::water },
{ 0xA2, "Spirit Medallion" , ObjectIconMap::spirit },
{ 0xA3, "Shadow Medallion" , ObjectIconMap::shadow },
{ 0xA4, "Light Medallion" , ObjectIconMap::light },
{ 0xA5, "Magic Upgrade (OoT)" , ObjectIconMap::magic_upgrade },
{ 0xA6, "Larger Magic Upgrade (OoT)" , ObjectIconMap::large_magic_upgrade },
{ 0xA7, "Double Defense (OoT)" , ObjectIconMap::defense },
{ 0xA8, "Progressive Deku Shield (OoT)" , ObjectIconMap::deku_shield },
{ 0xA9, "Progressive Hylian Shield" , ObjectIconMap::hylian_shield },
{ 0xAA, "Small Key (Forest Temple)" , ObjectIconMap::small_key },
{ 0xAB, "Small Key (Fire Temple)" , ObjectIconMap::small_key },
{ 0xAC, "Small Key (Water Temple)" , ObjectIconMap::small_key },
{ 0xAD, "Small Key (Spirit Temple)" , ObjectIconMap::small_key },
{ 0xAE, "Small Key (Shadow Temple)" , ObjectIconMap::small_key },
{ 0xAF, "Small Key (Ganon's Castle)" , ObjectIconMap::small_key },
{ 0xB0, "Small Key (Bottom of the Well)" , ObjectIconMap::small_key },
{ 0xB1, "Small Key (Gerudo's Fortress)" , ObjectIconMap::small_key },
{ 0xB2, "Small Key (Gerudo's Training Ground)" , ObjectIconMap::small_key },
{ 0xB3, "Boss Key (Forest Temple)" , ObjectIconMap::boss_key },
{ 0xB4, "Boss Key (Fire Temple)" , ObjectIconMap::boss_key },
{ 0xB5, "Boss Key (Water Temple)" , ObjectIconMap::boss_key },
{ 0xB6, "Boss Key (Spirit Temple)" , ObjectIconMap::boss_key },
{ 0xB7, "Boss Key (Shadow Temple)" , ObjectIconMap::boss_key },
{ 0xB8, "Boss Key (Ganon's Castle)" , ObjectIconMap::boss_key },
{ 0xB9, "Map (Deku Tree)" , ObjectIconMap::map },
{ 0xBA, "Map (Dodongo's Cavern)" , ObjectIconMap::map },
{ 0xBB, "Map (Jabu-Jabu's Belly)" , ObjectIconMap::map },
{ 0xBC, "Map (Forest Temple)" , ObjectIconMap::map },
{ 0xBD, "Map (Fire Temple)" , ObjectIconMap::map },
{ 0xBE, "Map (Water Temple)" , ObjectIconMap::map },
{ 0xBF, "Map (Spirit Temple)" , ObjectIconMap::map },
{ 0xC0, "Map (Shadow Temple)" , ObjectIconMap::map },
{ 0xC1, "Map (Bottom of the Well)" , ObjectIconMap::map },
{ 0xC2, "Map (Ice Cavern)" , ObjectIconMap::map },
{ 0xC3, "Compass (Deku Tree)" , ObjectIconMap::compass },
{ 0xC4, "Compass (Dodongo's Cavern)" , ObjectIconMap::compass },
{ 0xC5, "Compass (Jabu-Jabu's Belly)" , ObjectIconMap::compass },
{ 0xC6, "Compass (Forest Temple)" , ObjectIconMap::compass },
{ 0xC7, "Compass (Fire Temple)" , ObjectIconMap::compass },
{ 0xC8, "Compass (Water Temple)" , ObjectIconMap::compass },
{ 0xC9, "Compass (Spirit Temple)" , ObjectIconMap::compass },
{ 0xCA, "Compass (Shadow Temple)" , ObjectIconMap::compass },
{ 0xCB, "Compass (Bottom of the Well)" , ObjectIconMap::compass },
{ 0xCC, "Compass (Ice Cavern)" , ObjectIconMap::compass },
{ 0xCD, "Child's Wallet (OoT)" , ObjectIconMap::child_wallet },
{ 0xCE, "Colossal Wallet (OoT)" , ObjectIconMap::colossal_wallet },
{ 0xCF, "Triforce Piece" , ObjectIconMap::triforce_piece },
{ 0xD0, "Bottomless Wallet (OoT)" , ObjectIconMap::botomless_wallet },
{ 0xD1, "Silver Rupee (Dodongo's Cavern)" , ObjectIconMap::sr },
{ 0xD2, "Silver Rupee (Bottom of the Well)" , ObjectIconMap::sr },
{ 0xD3, "Silver Rupee (Spirit Temple - Child)" , ObjectIconMap::sr },
{ 0xD4, "Silver Rupee (Spirit Temple - Sun Block)" , ObjectIconMap::sr },
{ 0xD5, "Silver Rupee (Spirit Temple - Boulders)" , ObjectIconMap::sr },
{ 0xD6, "Silver Rupee (Spirit Temple - Lobby)" , ObjectIconMap::sr },
{ 0xD7, "Silver Rupee (Spirit Temple - Adult)" , ObjectIconMap::sr },
{ 0xD8, "Silver Rupee (Shadow Temple - Scythe)" , ObjectIconMap::sr },
{ 0xD9, "Silver Rupee (Shadow Temple - Large Pits)" , ObjectIconMap::sr },
{ 0xDA, "Silver Rupee (Shadow Temple - Spikes)" , ObjectIconMap::sr },
{ 0xDB, "Silver Rupee (Shadow Temple - Invisible Blades)" , ObjectIconMap::sr },
{ 0xDC, "Silver Rupee (Ice Cavern - Scythe)" , ObjectIconMap::sr },
{ 0xDD, "Silver Rupee (Ice Cavern - Block)" , ObjectIconMap::sr },
{ 0xDE, "Silver Rupee (Gerudo Training Ground - Slopes)" , ObjectIconMap::sr },
{ 0xDF, "Silver Rupee (Gerudo Training Ground - Lava)" , ObjectIconMap::sr },
{ 0xE0, "Silver Rupee (Gerudo Training Ground - Water)" , ObjectIconMap::sr },
{ 0xE1, "Silver Rupee (Ganon's Castle - Spirit Trial)" , ObjectIconMap::sr },
{ 0xE2, "Silver Rupee (Ganon's Castle - Light Trial)" , ObjectIconMap::sr },
{ 0xE3, "Silver Rupee (Ganon's Castle - Fire Trial)" , ObjectIconMap::sr },
{ 0xE4, "Silver Rupee (Ganon's Castle - Forest Trial)" , ObjectIconMap::sr },
{ 0xE5, "Silver Rupee (Ganon's Castle - Shadow Trial)" , ObjectIconMap::sr },
{ 0xE6, "Silver Rupee (Ganon's Castle - Water Trial)" , ObjectIconMap::sr },
{ 0xE7, "Soul of Stalfos (OoT)" , ObjectIconMap::soul_of_foe },
{ 0xE8, "Soul of Octoroks (OoT)" , ObjectIconMap::soul_of_foe },
{ 0xE9, "Soul of Wallmasters (OoT)" , ObjectIconMap::soul_of_foe },
{ 0xEA, "Soul of Dodongos (OoT)" , ObjectIconMap::soul_of_foe },
{ 0xEB, "Soul of Keese (OoT)" , ObjectIconMap::soul_of_foe },
{ 0xEC, "Soul of Tektites (OoT)" , ObjectIconMap::soul_of_foe },
{ 0xED, "Soul of Leevers (OoT)" , ObjectIconMap::soul_of_foe },
{ 0xEE, "Soul of Peahats (OoT)" , ObjectIconMap::soul_of_foe },
{ 0xEF, "Soul of Lizalfos/Dinolfos (OoT)" , ObjectIconMap::soul_of_foe },
{ 0xF0, "Soul of Gohma Larvaes" , ObjectIconMap::soul_of_foe },
{ 0xF1, "Soul of Shaboms" , ObjectIconMap::soul_of_foe },
{ 0xF2, "Soul of Baby Dodongos" , ObjectIconMap::soul_of_foe },
{ 0xF3, "Soul of Dark Link" , ObjectIconMap::soul_of_foe },
{ 0xF4, "Soul of Biris/Baris" , ObjectIconMap::soul_of_foe },
{ 0xF5, "Soul of Tailpasarans" , ObjectIconMap::soul_of_foe },
{ 0xF6, "Soul of Jabu-Jabu's Parasites" , ObjectIconMap::soul_of_foe },
{ 0xF7, "Soul of Skulltulas (OoT)" , ObjectIconMap::soul_of_foe },
{ 0xF8, "Soul of Torch Slugs" , ObjectIconMap::soul_of_foe },
{ 0xF9, "Soul of Moblins" , ObjectIconMap::soul_of_foe },
{ 0xFA, "Soul of Armos (OoT)" , ObjectIconMap::soul_of_foe },
{ 0xFB, "Soul of Deku Babas (OoT)" , ObjectIconMap::soul_of_foe },
{ 0xFC, "Soul of Deku Scrubs (OoT)" , ObjectIconMap::soul_of_foe },
{ 0xFD, "Soul of Bubbles (OoT)" , ObjectIconMap::soul_of_foe },
{ 0xFE, "Soul of Beamos (OoT)" , ObjectIconMap::soul_of_foe },
{ 0xFF, "Soul of Floormasters (OoT)" , ObjectIconMap::soul_of_foe },
{ 0x100, "Soul of ReDeads/Gibdos (OoT)" , ObjectIconMap::soul_of_foe },
{ 0x101, "Soul of Skullwalltulas (OoT)" , ObjectIconMap::soul_of_foe },
{ 0x102, "Soul of Flare Dancers" , ObjectIconMap::soul_of_foe },
{ 0x103, "Soul of Dead Hands" , ObjectIconMap::soul_of_foe },
{ 0x104, "Soul of Shell Blades (OoT)" , ObjectIconMap::soul_of_foe },
{ 0x105, "Soul of Like Likes (OoT)" , ObjectIconMap::soul_of_foe },
{ 0x106, "Soul of Spikes" , ObjectIconMap::soul_of_foe },
{ 0x107, "Soul of Anubis" , ObjectIconMap::soul_of_foe },
{ 0x108, "Soul of Iron Knuckles (OoT)" , ObjectIconMap::soul_of_foe },
{ 0x109, "Soul of Skull Kids (OoT)" , ObjectIconMap::soul_of_foe },
{ 0x10A, "Soul of Flying Pots (OoT)" , ObjectIconMap::soul_of_foe },
{ 0x10B, "Soul of Freezards (OoT)" , ObjectIconMap::soul_of_foe },
{ 0x10C, "Soul of Stingers" , ObjectIconMap::soul_of_foe },
{ 0x10D, "Soul of Wolfoses (OoT)" , ObjectIconMap::soul_of_foe },
{ 0x10E, "Soul of Stalchildren (OoT)" , ObjectIconMap::soul_of_foe },
{ 0x10F, "Soul of Guays (OoT)" , ObjectIconMap::soul_of_foe },
{ 0x110, "Soul of the Fighting Gerudos" , ObjectIconMap::soul_of_foe },
{ 0x111, "Soul of Poes (OoT)" , ObjectIconMap::soul_of_foe },
{ 0x112, "Soul of Queen Gohma" , ObjectIconMap::soul_of_boss },
{ 0x113, "Soul of King Dodongo" , ObjectIconMap::soul_of_boss },
{ 0x114, "Soul of Barinade" , ObjectIconMap::soul_of_boss },
{ 0x115, "Soul of Phantom Ganon" , ObjectIconMap::soul_of_boss },
{ 0x116, "Soul of Volvagia" , ObjectIconMap::soul_of_boss },
{ 0x117, "Soul of Morpha" , ObjectIconMap::soul_of_boss },
{ 0x118, "Soul of Bongo Bongo" , ObjectIconMap::soul_of_boss },
{ 0x119, "Soul of Twinrova" , ObjectIconMap::soul_of_boss },
{ 0x11A, "Soul of Saria" , ObjectIconMap::soul_of_npc },
{ 0x11B, "Soul of Darunia" , ObjectIconMap::soul_of_npc },
{ 0x11C, "Soul of Ruto (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x11D, "Soul of King Zora" , ObjectIconMap::soul_of_npc },
{ 0x11E, "Soul of Zelda" , ObjectIconMap::soul_of_npc },
{ 0x11F, "Soul of Sheik" , ObjectIconMap::soul_of_npc },
{ 0x120, "Soul of Cucco Lady (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x121, "Soul of Carpenters (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x122, "Soul of Guru-Guru (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x123, "Soul of Mido" , ObjectIconMap::soul_of_npc },
{ 0x124, "Soul of Kokiri" , ObjectIconMap::soul_of_npc },
{ 0x125, "Soul of Kokiri Shopkeeper" , ObjectIconMap::soul_of_npc },
{ 0x126, "Soul of Hylian Guard" , ObjectIconMap::soul_of_npc },
{ 0x127, "Soul of the Citizens (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x128, "Soul of Malon (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x129, "Soul of Talon (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x12A, "Soul of Fishing Pond Owner (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x12B, "Soul of Goron (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x12C, "Soul of Medigoron (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x12D, "Soul of Biggoron (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x12E, "Soul of Goron Child (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x12F, "Soul of Goron Shopkeeper (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x130, "Soul of Zora (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x131, "Soul of Zora Shopkeeper (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x132, "Soul of Bazaar Shopkeeper (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x133, "Soul of Bombchu Shopkeeper (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x134, "Soul of Potion Shopkeeper" , ObjectIconMap::soul_of_npc },
{ 0x135, "Soul of Bombchu Bowling Lady (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x136, "Soul of Chest Game Owner (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x137, "Soul of Shooting Gallery Owner (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x138, "Soul of Dampe (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x139, "Soul of Graveyard Kid (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x13A, "Soul of Poe Collector (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x13B, "Soul of Composer Bros. (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x13C, "Soul of Honey & Darling (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x13D, "Soul of the Astronomer (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x13E, "Soul of the Rooftop Man (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x13F, "Soul of the Bean Salesman (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x140, "Soul of the Scientist (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x141, "Soul of Ingo (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x142, "Soul of the Punk Kid (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x143, "Soul of the Dog Lady (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x144, "Soul of the Carpet Man (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x145, "Soul of the Old Hag (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x146, "Soul of the Beggar (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x147, "Soul of the Patrolling Gerudos" , ObjectIconMap::soul_of_npc },
{ 0x148, "Soul of Cuccos (OoT)" , ObjectIconMap::soul_of_animal },
{ 0x149, "Soul of Cows (OoT)" , ObjectIconMap::soul_of_animal },
{ 0x14A, "Soul of Dogs (OoT)" , ObjectIconMap::soul_of_animal },
{ 0x14B, "Soul of Butterflies (OoT)" , ObjectIconMap::soul_of_animal },
{ 0x14C, "Soul of Gold Skulltulas (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x14D, "Soul of Business Scrubs (OoT)" , ObjectIconMap::soul_of_npc },
{ 0x14E, "Key Ring (OoT)" , ObjectIconMap::key_ring },
{ 0x14F, "Key Ring (Forest)" , ObjectIconMap::key_ring },
{ 0x150, "Key Ring (Fire)" , ObjectIconMap::key_ring },
{ 0x151, "Key Ring (Water)" , ObjectIconMap::key_ring },
{ 0x152, "Key Ring (Spirit)" , ObjectIconMap::key_ring },
{ 0x153, "Key Ring (Shadow)" , ObjectIconMap::key_ring },
{ 0x154, "Key Ring (Ganon)" , ObjectIconMap::key_ring },
{ 0x155, "Key Ring (Well)" , ObjectIconMap::key_ring },
{ 0x156, "Key Ring (Hideout)" , ObjectIconMap::key_ring },
{ 0x157, "Key Ring (GTG)" , ObjectIconMap::key_ring },
{ 0x158, "Skeleton Key (OoT)" , ObjectIconMap::skeleton_key },
{ 0x159, "Coin (Red)" , ObjectIconMap::red_coin },
{ 0x15A, "Coin (Green)" , ObjectIconMap::green_coin },
{ 0x15B, "Coin (Blue)" , ObjectIconMap::blue_coin },
{ 0x15C, "Coin (Yellow)" , ObjectIconMap::yellow_coin },
{ 0x15D, "Triforce of Power" , ObjectIconMap::triforce_power },
{ 0x15E, "Triforce of Courage" , ObjectIconMap::triforce_courage },
{ 0x15F, "Triforce of Wisdom" , ObjectIconMap::triforce_wisdom },
{ 0x160, "Silver Rupee Pouch (Dodongo's Cavern)" , ObjectIconMap::silver_pouch },
{ 0x161, "Silver Rupee Pouch (Bottom of the Well)" , ObjectIconMap::silver_pouch },
{ 0x162, "Silver Rupee Pouch (Spirit Temple - Child)" , ObjectIconMap::silver_pouch },
{ 0x163, "Silver Rupee Pouch (Spirit Temple - Sun Block)" , ObjectIconMap::silver_pouch },
{ 0x164, "Silver Rupee Pouch (Spirit Temple - Boulders)" , ObjectIconMap::silver_pouch },
{ 0x165, "Silver Rupee Pouch (Spirit Temple - Lobby)" , ObjectIconMap::silver_pouch },
{ 0x166, "Silver Rupee Pouch (Spirit Temple - Adult)" , ObjectIconMap::silver_pouch },
{ 0x167, "Silver Rupee Pouch (Shadow Temple - Scythe)" , ObjectIconMap::silver_pouch },
{ 0x168, "Silver Rupee Pouch (Shadow Temple - Large Pits)" , ObjectIconMap::silver_pouch },
{ 0x169, "Silver Rupee Pouch (Shadow Temple - Spikes)" , ObjectIconMap::silver_pouch },
{ 0x16A, "Silver Rupee Pouch (Shadow Temple - Invisible Blades)" , ObjectIconMap::silver_pouch },
{ 0x16B, "Silver Rupee Pouch (Ice Cavern - Scythe)" , ObjectIconMap::silver_pouch },
{ 0x16C, "Silver Rupee Pouch (Ice Cavern - Block)" , ObjectIconMap::silver_pouch },
{ 0x16D, "Silver Rupee Pouch (Gerudo Training Ground - Slopes)" , ObjectIconMap::silver_pouch },
{ 0x16E, "Silver Rupee Pouch (Gerudo Training Ground - Lava)" , ObjectIconMap::silver_pouch },
{ 0x16F, "Silver Rupee Pouch (Gerudo Training Ground - Water)" , ObjectIconMap::silver_pouch },
{ 0x170, "Silver Rupee Pouch (Ganon's Castle - Spirit Trial)" , ObjectIconMap::silver_pouch },
{ 0x171, "Silver Rupee Pouch (Ganon's Castle - Light Trial)" , ObjectIconMap::silver_pouch },
{ 0x172, "Silver Rupee Pouch (Ganon's Castle - Fire Trial)" , ObjectIconMap::silver_pouch },
{ 0x173, "Silver Rupee Pouch (Ganon's Castle - Forest Trial)" , ObjectIconMap::silver_pouch },
{ 0x174, "Silver Rupee Pouch (Ganon's Castle - Shadow Trial)" , ObjectIconMap::silver_pouch },
{ 0x175, "Silver Rupee Pouch (Ganon's Castle - Water Trial)" , ObjectIconMap::silver_pouch },
{ 0x176, "Magical Silver Rupee" , ObjectIconMap::magical_rupee },
{ 0x177, "A Button (OoT)" , ObjectIconMap::a_button },
{ 0x178, "C-Right Button (OoT)" , ObjectIconMap::c_right },
{ 0x179, "C-Left Button (OoT)" , ObjectIconMap::c_left },
{ 0x17A, "C-Up Button (OoT)" , ObjectIconMap::c_up },
{ 0x17B, "C-Down Button (OoT)" , ObjectIconMap::c_down },
{ 0x17C, "Small Key (Chest Game)" , ObjectIconMap::small_key },
{ 0x17D, "Key Ring (Chest Game)" , ObjectIconMap::key_ring },
{ 0x17E, "Bottle of Red Potion (OoT)" , ObjectIconMap::red_potion },
{ 0x17F, "Bottle of Green Potion (OoT)" , ObjectIconMap::green_potion },
{ 0x180, "Bottle of Blue Potion (OoT)" , ObjectIconMap::blue_potion },
{ 0x181, "Bottled Fairy (OoT)" , ObjectIconMap::bottled_fairy },
{ 0x182, "Bottled Poe (OoT)" , ObjectIconMap::bottled_poe },
{ 0x183, "Bottled Big Poe (OoT)" , ObjectIconMap::bottled_big_poe },
{ 0x184, "Bottle of Blue Fire" , ObjectIconMap::blue_fire },
{ 0x185, "Child Fish (2 pounds)" , ObjectIconMap::carp_fish },
{ 0x186, "Child Fish (3 pounds)" , ObjectIconMap::carp_fish },
{ 0x187, "Child Fish (4 pounds)" , ObjectIconMap::carp_fish },
{ 0x188, "Child Fish (5 pounds)" , ObjectIconMap::carp_fish },
{ 0x189, "Child Fish (6 pounds)" , ObjectIconMap::carp_fish },
{ 0x18A, "Child Fish (7 pounds)" , ObjectIconMap::carp_fish },
{ 0x18B, "Child Fish (8 pounds)" , ObjectIconMap::carp_fish },
{ 0x18C, "Child Fish (9 pounds)" , ObjectIconMap::carp_fish },
{ 0x18D, "Child Fish (10 pounds)" , ObjectIconMap::carp_fish },
{ 0x18E, "Child Fish (11 pounds)" , ObjectIconMap::carp_fish },
{ 0x18F, "Child Fish (12 pounds)" , ObjectIconMap::carp_fish },
{ 0x190, "Child Fish (13 pounds)" , ObjectIconMap::carp_fish },
{ 0x191, "Child Fish (14 pounds)" , ObjectIconMap::carp_fish },
{ 0x192, "Adult Fish (4 pounds)" , ObjectIconMap::carp_fish },
{ 0x193, "Adult Fish (5 pounds)" , ObjectIconMap::carp_fish },
{ 0x194, "Adult Fish (6 pounds)" , ObjectIconMap::carp_fish },
{ 0x195, "Adult Fish (7 pounds)" , ObjectIconMap::carp_fish },
{ 0x196, "Adult Fish (8 pounds)" , ObjectIconMap::carp_fish },
{ 0x197, "Adult Fish (9 pounds)" , ObjectIconMap::carp_fish },
{ 0x198, "Adult Fish (10 pounds)" , ObjectIconMap::carp_fish },
{ 0x199, "Adult Fish (11 pounds)" , ObjectIconMap::carp_fish },
{ 0x19A, "Adult Fish (12 pounds)" , ObjectIconMap::carp_fish },
{ 0x19B, "Adult Fish (13 pounds)" , ObjectIconMap::carp_fish },
{ 0x19C, "Adult Fish (14 pounds)" , ObjectIconMap::carp_fish },
{ 0x19D, "Adult Fish (15 pounds)" , ObjectIconMap::carp_fish },
{ 0x19E, "Adult Fish (16 pounds)" , ObjectIconMap::carp_fish },
{ 0x19F, "Adult Fish (17 pounds)" , ObjectIconMap::carp_fish },
{ 0x1A0, "Adult Fish (18 pounds)" , ObjectIconMap::carp_fish },
{ 0x1A1, "Adult Fish (19 pounds)" , ObjectIconMap::carp_fish },
{ 0x1A2, "Adult Fish (20 pounds)" , ObjectIconMap::carp_fish },
{ 0x1A3, "Adult Fish (21 pounds)" , ObjectIconMap::carp_fish },
{ 0x1A4, "Adult Fish (22 pounds)" , ObjectIconMap::carp_fish },
{ 0x1A5, "Adult Fish (23 pounds)" , ObjectIconMap::carp_fish },
{ 0x1A6, "Adult Fish (24 pounds)" , ObjectIconMap::carp_fish },
{ 0x1A7, "Adult Fish (25 pounds)" , ObjectIconMap::carp_fish },
{ 0x1A8, "Child Loach (14 pounds)" , ObjectIconMap::carp_fish },
{ 0x1A9, "Child Loach (15 pounds)" , ObjectIconMap::carp_fish },
{ 0x1AA, "Child Loach (16 pounds)" , ObjectIconMap::carp_fish },
{ 0x1AB, "Child Loach (17 pounds)" , ObjectIconMap::carp_fish },
{ 0x1AC, "Child Loach (18 pounds)" , ObjectIconMap::carp_fish },
{ 0x1AD, "Child Loach (19 pounds)" , ObjectIconMap::carp_fish },
{ 0x1AE, "Adult Loach (29 pounds)" , ObjectIconMap::carp_fish },
{ 0x1AF, "Adult Loach (30 pounds)" , ObjectIconMap::carp_fish },
{ 0x1B0, "Adult Loach (31 pounds)" , ObjectIconMap::carp_fish },
{ 0x1B1, "Adult Loach (32 pounds)" , ObjectIconMap::carp_fish },
{ 0x1B2, "Adult Loach (33 pounds)" , ObjectIconMap::carp_fish },
{ 0x1B3, "Adult Loach (34 pounds)" , ObjectIconMap::carp_fish },
{ 0x1B4, "Adult Loach (35 pounds)" , ObjectIconMap::carp_fish },
{ 0x1B5, "Adult Loach (36 pounds)" , ObjectIconMap::carp_fish },
{ 0x1B6, "Bombchu Bag (OoT)" , ObjectIconMap::bombchu_bag },
{ 0x1B7, "Big Bombchu Bag (OoT)" , ObjectIconMap::bombchu_bag },
{ 0x1B8, "Biggest Bombchu Bag (OoT)" , ObjectIconMap::bombchu_bag },
{ 0x1B9, "Bombchu Bag (OoT)" , ObjectIconMap::bombchu_bag },
{ 0x1BA, "Bombchu Bag (OoT)" , ObjectIconMap::bombchu_bag },
{ 0x1BB, "Bombchu Bag (OoT)" , ObjectIconMap::bombchu_bag },
{ 0x1BC, "Razor Sword (OoT)" , ObjectIconMap::razor },
{ 0x1BD, "Gilded Sword (OoT)" , ObjectIconMap::gilded },
{ 0x1BE, "Spin Attack Upgrade (OoT)" , ObjectIconMap::spin },
{ 0x1BF, "Triforce (OoT)" , ObjectIconMap::triforce_piece },
{ 0x1C0, "Big Fairy (OoT)" , ObjectIconMap::fairy },
{ 0x1C1, "Blast Mask (OoT)" , ObjectIconMap::blast },
{ 0x1C2, "Stone Mask (OoT)" , ObjectIconMap::stone },
{ 0x1C3, "Bronze Scale (OoT)" , ObjectIconMap::bronze_scale },
{ 0x1C4, "Magic Mushroom" , ObjectIconMap::mushroom },
{ 0x1C5, "Chateau Romani Refill" , ObjectIconMap::chateau },
{ 0x1C6, "Chateau Romani" , ObjectIconMap::chateau },
{ 0x1C7, "Seahorse" , ObjectIconMap::seahorse },
{ 0x1C8, "Bottle of Gold Dust" , ObjectIconMap::dust },
{ 0x1C9, "Bottle of Chateau Romani" , ObjectIconMap::chateau },
{ 0x1CA, "Ice Trap" , ObjectIconMap::ice_trap },
{ 0x1CB, "Fire Trap" , ObjectIconMap::fire_trap },
{ 0x1CC, "Shock Trap" , ObjectIconMap::shock_trap },
{ 0x1CD, "Drain Trap" , ObjectIconMap::drain_trap },
{ 0x1CE, "Anti-Magic Trap" , ObjectIconMap::magic_trap },
{ 0x1CF, "Knockback Trap" , ObjectIconMap::knockback_trap },
{ 0x1D0, "Rupoor" , ObjectIconMap::rupoor },
{ 0x1D1, "Platinum Token (OoT)" , ObjectIconMap::gs_token },
{ 0x1D2, "Green Rupee (MM)" , ObjectIconMap::rupee },
{ 0x1D3, "Blue Rupee (MM)" , ObjectIconMap::blue_rupee },
{ 0x1D4, "Red Rupee (MM)" , ObjectIconMap::red_rupee },
{ 0x1D5, "Red Rupee (MM)" , ObjectIconMap::red_rupee },
{ 0x1D6, "Purple Rupee (MM)" , ObjectIconMap::purple_rupee },
{ 0x1D7, "Silver Rupee (MM)" , ObjectIconMap::sr },
{ 0x1D8, "Gold Rupee (MM)" , ObjectIconMap::gold_rupee },
{ 0x1D9, "Adult Wallet (MM)" , ObjectIconMap::wallet },
{ 0x1DA, "Giant Wallet (MM)" , ObjectIconMap::big_wallet },
{ 0x1DB, "Recovery Heart (MM)" , ObjectIconMap::heart },
{ 0x1DC, "Piece of Heart (MM)" , ObjectIconMap::heart_piece },
{ 0x1DD, "Heart Container (MM)" , ObjectIconMap::heart_container },
{ 0x1DE, "Small Magic Jar (MM)" , ObjectIconMap::magic },
{ 0x1DF, "Large Magic Jar (MM)" , ObjectIconMap::double_magic },
{ 0x1E0, "Stray Fairy (MM)" , ObjectIconMap::sf },
{ 0x1E1, "Stray Fairy (Woodfall Temple)" , ObjectIconMap::sf },
{ 0x1E2, "Stray Fairy (Snowhead Temple)" , ObjectIconMap::sf_green },
{ 0x1E3, "Stray Fairy (Great Bay Temple)" , ObjectIconMap::sf_blue },
{ 0x1E4, "Stray Fairy (Stone Tower Temple)" , ObjectIconMap::sf_yellow },
{ 0x1E5, "Stray Fairy (Clock Town)" , ObjectIconMap::sf_orange },
{ 0x1E6, "Transcendent Fairy" , ObjectIconMap::sf_transcendent },
{ 0x1E7, "Bomb (MM)" , ObjectIconMap::bomb },
{ 0x1E8, "5 Bombs (MM)" , ObjectIconMap::bomb },
{ 0x1E9, "10 Bombs (MM)" , ObjectIconMap::bomb },
{ 0x1EA, "20 Bombs (MM)" , ObjectIconMap::bomb },
{ 0x1EB, "30 Bombs (MM)" , ObjectIconMap::bomb },
{ 0x1EC, "Deku Stick (MM)" , ObjectIconMap::stick },
{ 0x1ED, "10 Bombchu (MM)" , ObjectIconMap::bombchu },
{ 0x1EE, "Bomb Bag (MM)" , ObjectIconMap::bomb_bag },
{ 0x1EF, "Big Bomb Bag (MM)" , ObjectIconMap::big_bomb_bag },
{ 0x1F0, "Biggest Bomb Bag (MM)" , ObjectIconMap::biggest_bomb_bag },
{ 0x1F1, "10 Arrows (MM)" , ObjectIconMap::arrow },
{ 0x1F2, "30 Arrows (MM)" , ObjectIconMap::arrow },
{ 0x1F3, "40 Arrows (MM)" , ObjectIconMap::arrow },
{ 0x1F4, "40 Arrows (MM)" , ObjectIconMap::arrow },
{ 0x1F5, "Hero's Bow (MM)" , ObjectIconMap::bow_mm },
{ 0x1F6, "Big Quiver (MM)" , ObjectIconMap::big_quiver },
{ 0x1F7, "Biggest Quiver (MM)" , ObjectIconMap::biggest_quiver },
{ 0x1F8, "Fire Arrows (MM)" , ObjectIconMap::fire_arrow },
{ 0x1F9, "Ice Arrows (MM)" , ObjectIconMap::ice_arrow },
{ 0x1FA, "Light Arrows (MM)" , ObjectIconMap::light_arrow },
{ 0x1FB, "Nut (MM)" , ObjectIconMap::nut },
{ 0x1FC, "5 Deku Nuts (MM)" , ObjectIconMap::nut },
{ 0x1FD, "10 Deku Nuts (MM)" , ObjectIconMap::nut },
{ 0x1FE, "30 Deku Nuts (MM)" , ObjectIconMap::nut },
{ 0x1FF, "30 Deku Nuts (MM)" , ObjectIconMap::nut },
{ 0x200, "40 Deku Nuts (MM)" , ObjectIconMap::nut },
{ 0x201, "20 Bombchu (MM)" , ObjectIconMap::bombchu },
{ 0x202, "20 Deku Sticks (MM)" , ObjectIconMap::stick },
{ 0x203, "20 Deku Sticks (MM)" , ObjectIconMap::stick },
{ 0x204, "30 Deku Sticks (MM)" , ObjectIconMap::stick },
{ 0x205, "Deku Shield (MM)" , ObjectIconMap::deku_shield },
{ 0x206, "Hero's Shield" , ObjectIconMap::hero_shield },
{ 0x207, "Mirror Shield (MM)" , ObjectIconMap::mirror_mm },
{ 0x208, "Progressive Deku Shield (MM)" , ObjectIconMap::deku_shield },
{ 0x209, "Progressive Hero's Shield" , ObjectIconMap::hero_shield },
{ 0x20A, "Powder Keg" , ObjectIconMap::powder },
{ 0x20B, "Magic Bean (MM)" , ObjectIconMap::bean },
{ 0x20C, "1 Bombchu (MM)" , ObjectIconMap::bombchu },
{ 0x20D, "Kokiri Sword (MM)" , ObjectIconMap::kokiri_mm },
{ 0x20E, "Razor Sword (MM)" , ObjectIconMap::razor },
{ 0x20F, "Gilded Sword (MM)" , ObjectIconMap::gilded },
{ 0x210, "5 Bombchu (MM)" , ObjectIconMap::bombchu },
{ 0x211, "Great Fairy's Sword" , ObjectIconMap::fairy_sword },
{ 0x212, "Small Key (MM)" , ObjectIconMap::small_key },
{ 0x213, "Boss Key (MM)" , ObjectIconMap::boss_key },
{ 0x214, "Map (MM)" , ObjectIconMap::map },
{ 0x215, "Compass (MM)" , ObjectIconMap::compass },
{ 0x216, "Hookshot (MM)" , ObjectIconMap::hookshot_mm },
{ 0x217, "Lens of Truth (MM)" , ObjectIconMap::lens },
{ 0x218, "Pictograph Box" , ObjectIconMap::picto },
{ 0x219, "Ocarina of Time (MM)" , ObjectIconMap::ocarina },
{ 0x21A, "Bombers' Notebook" , ObjectIconMap::bombers },
{ 0x21B, "Bottle of Red Potion (MM)" , ObjectIconMap::red_potion },
{ 0x21C, "Empty Bottle (MM)" , ObjectIconMap::bottle },
{ 0x21D, "Red Potion (MM)" , ObjectIconMap::red_potion },
{ 0x21E, "Green Potion (MM)" , ObjectIconMap::green_potion },
{ 0x21F, "Blue Potion (MM)" , ObjectIconMap::blue_potion },
{ 0x220, "Fairy (MM)" , ObjectIconMap::fairy },
{ 0x221, "Bottle of Milk (MM)" , ObjectIconMap::milk },
{ 0x222, "Fish (MM)" , ObjectIconMap::bottled_fish },
{ 0x223, "Bugs (MM)" , ObjectIconMap::bottled_bugs },
{ 0x224, "Big Poe (MM)" , ObjectIconMap::bottled_big_poe },
{ 0x225, "Bottle of Gold Dust" , ObjectIconMap::dust },
{ 0x226, "Magic Mushroom" , ObjectIconMap::mushroom },
{ 0x227, "Bottle of Chateau Romani" , ObjectIconMap::chateau },
{ 0x228, "Deku Mask" , ObjectIconMap::deku },
{ 0x229, "Goron Mask (MM)" , ObjectIconMap::goron },
{ 0x22A, "Zora Mask (MM)" , ObjectIconMap::zora },
{ 0x22B, "Fierce Deity's Mask" , ObjectIconMap::deity },
{ 0x22C, "Captain's Hat" , ObjectIconMap::capitain },
{ 0x22D, "Giant's Mask" , ObjectIconMap::giant },
{ 0x22E, "All-Night Mask" , ObjectIconMap::night },
{ 0x22F, "Bunny Hood (MM)" , ObjectIconMap::bunny },
{ 0x230, "Keaton Mask" , ObjectIconMap::keaton },
{ 0x231, "Garo's Mask" , ObjectIconMap::garo },
{ 0x232, "Romani's Mask" , ObjectIconMap::romani },
{ 0x233, "Circus Leader's Mask" , ObjectIconMap::troupe },
{ 0x234, "Postman's Hat" , ObjectIconMap::postman },
{ 0x235, "Couple's Mask" , ObjectIconMap::couple },
{ 0x236, "Great Fairy's Mask" , ObjectIconMap::fairy_mask },
{ 0x237, "Gibdo Mask" , ObjectIconMap::gibdo },
{ 0x238, "Don Gero's Mask" , ObjectIconMap::gero },
{ 0x239, "Kamaro's Mask" , ObjectIconMap::kamaro },
{ 0x23A, "Mask of Truth (MM)" , ObjectIconMap::truth },
{ 0x23B, "Stone Mask (MM)" , ObjectIconMap::stone },
{ 0x23C, "Bremen Mask" , ObjectIconMap::bremen },
{ 0x23D, "Blast Mask (MM)" , ObjectIconMap::blast },
{ 0x23E, "Mask of Scents" , ObjectIconMap::scents },
{ 0x23F, "Kafei's Mask" , ObjectIconMap::kafei },
{ 0x240, "Chateau Romani Refill (MM)" , ObjectIconMap::chateau },
{ 0x241, "Romani Milk" , ObjectIconMap::milk },
{ 0x242, "Gold Dust" , ObjectIconMap::dust },
{ 0x243, "Seahorse" , ObjectIconMap::seahorse },
{ 0x244, "Moon's Tear" , ObjectIconMap::moon },
{ 0x245, "Land Title Deed" , ObjectIconMap::land },
{ 0x246, "Swamp Title Deed" , ObjectIconMap::swamp },
{ 0x247, "Mountain Title Deed" , ObjectIconMap::mountain },
{ 0x248, "Ocean Title Deed" , ObjectIconMap::ocean },
{ 0x249, "Room Key" , ObjectIconMap::key },
{ 0x24A, "Letter to Mama" , ObjectIconMap::letter_mama },
{ 0x24B, "Letter to Kafei" , ObjectIconMap::letter_kafei },
{ 0x24C, "Pendant of Memories" , ObjectIconMap::pendant },
{ 0x24D, "World Map of Clock Town" , ObjectIconMap::map },
{ 0x24E, "World Map of Woodfall" , ObjectIconMap::map },
{ 0x24F, "World Map of Snowhead" , ObjectIconMap::map },
{ 0x250, "World Map of Ranch" , ObjectIconMap::map },
{ 0x251, "World Map of Great Bay" , ObjectIconMap::map },
{ 0x252, "World Map of Stone Tower" , ObjectIconMap::map },
{ 0x253, "Magic Upgrade (MM)" , ObjectIconMap::magic_upgrade },
{ 0x254, "Larger Magic Upgrade (MM)" , ObjectIconMap::large_magic_upgrade },
{ 0x255, "Double Defense (MM)" , ObjectIconMap::defense },
{ 0x256, "Spin Attack Upgrade (MM)" , ObjectIconMap::spin },
{ 0x257, "Sonata of Awakening" , ObjectIconMap::song_green },
{ 0x258, "Goron Lullaby" , ObjectIconMap::song_red },
{ 0x259, "New Wave Bossa Nova" , ObjectIconMap::song_blue },
{ 0x25A, "Elegy of Emptiness (MM)" , ObjectIconMap::song_orange },
{ 0x25B, "Oath to Order" , ObjectIconMap::song_purple },
{ 0x25C, "Song of Time (MM)" , ObjectIconMap::song },
{ 0x25D, "Song of Healing" , ObjectIconMap::song },
{ 0x25E, "Epona's Song (MM)" , ObjectIconMap::song },
{ 0x25F, "Song of Soaring" , ObjectIconMap::song },
{ 0x260, "Song of Storms (MM)" , ObjectIconMap::song },
{ 0x261, "Sun's Song (MM)" , ObjectIconMap::song },
{ 0x262, "Progressive Goron Lullaby" , ObjectIconMap::song_red },
{ 0x263, "Note from Sonata of Awakening (MM)" , ObjectIconMap::song_green },
{ 0x264, "Note from Goron Lullaby (MM)" , ObjectIconMap::song_red },
{ 0x265, "Note from New Wave Bossa Nova (MM)" , ObjectIconMap::song_blue },
{ 0x266, "Note from Elegy of Emptiness (MM)" , ObjectIconMap::song_orange },
{ 0x267, "Note from Oath to Order (MM)" , ObjectIconMap::song_purple },
{ 0x268, "Note from Song of Time (MM)" , ObjectIconMap::song },
{ 0x269, "Note from Song of Healing (MM)" , ObjectIconMap::song },
{ 0x26A, "Note from Epona's Song (MM)" , ObjectIconMap::song },
{ 0x26B, "Note from Song of Soaring (MM)" , ObjectIconMap::song },
{ 0x26C, "Note from Song of Storms (MM)" , ObjectIconMap::song },
{ 0x26D, "Note from Sun's Song (MM)" , ObjectIconMap::song },
{ 0x26E, "Odolwa's Remains" , ObjectIconMap::odolwa },
{ 0x26F, "Goht's Remains" , ObjectIconMap::goht },
{ 0x270, "Gyorg's Remains" , ObjectIconMap::hgyorg },
{ 0x271, "Twinmold's Remains" , ObjectIconMap::twinmold },
{ 0x272, "Swamp Skulltula Token" , ObjectIconMap::swamp_token },
{ 0x273, "Ocean Skulltula Token" , ObjectIconMap::ocean_token },
{ 0x274, "Platinum Token (MM)" , ObjectIconMap::gs_token },
{ 0x275, "Small Key (Woodfall Temple)" , ObjectIconMap::small_key },
{ 0x276, "Small Key (Snowhead Temple)" , ObjectIconMap::small_key },
{ 0x277, "Small Key (Great Bay Temple)" , ObjectIconMap::small_key },
{ 0x278, "Small Key (Stone Tower Temple)" , ObjectIconMap::small_key },
{ 0x279, "Boss Key (Woodfall Temple)" , ObjectIconMap::boss_key },
{ 0x27A, "Boss Key (Snowhead Temple)" , ObjectIconMap::boss_key },
{ 0x27B, "Boss Key (Great Bay Temple)" , ObjectIconMap::boss_key },
{ 0x27C, "Boss Key (Stone Tower Temple)" , ObjectIconMap::boss_key },
{ 0x27D, "Map (Woodfall Temple)" , ObjectIconMap::map },
{ 0x27E, "Map (Snowhead Temple)" , ObjectIconMap::map },
{ 0x27F, "Map (Great Bay Temple)" , ObjectIconMap::map },
{ 0x280, "Map (Stone Tower Temple)" , ObjectIconMap::map },
{ 0x281, "Compass (Woodfall Temple)" , ObjectIconMap::compass },
{ 0x282, "Compass (Snowhead Temple)" , ObjectIconMap::compass },
{ 0x283, "Compass (Great Bay Temple)" , ObjectIconMap::compass },
{ 0x284, "Compass (Stone Tower Temple)" , ObjectIconMap::compass },
{ 0x285, "Fairy Ocarina (MM)" , ObjectIconMap::fairy_ocarina },
{ 0x286, "Short Hookshot (MM)" , ObjectIconMap::hookshot_oot },
{ 0x287, "Child Wallet (MM)" , ObjectIconMap::child_wallet },
{ 0x288, "Colossal Wallet (MM)" , ObjectIconMap::colossal_wallet },
{ 0x289, "Owl Statue (Great Bay)" , ObjectIconMap::owl },
{ 0x28A, "Owl Statue (Zora Cape)" , ObjectIconMap::owl },
{ 0x28B, "Owl Statue (Snowhead)" , ObjectIconMap::owl },
{ 0x28C, "Owl Statue (Mountain Village)" , ObjectIconMap::owl },
{ 0x28D, "Owl Statue (Clock Town)" , ObjectIconMap::owl },
{ 0x28E, "Owl Statue (Milk Road)" , ObjectIconMap::owl },
{ 0x28F, "Owl Statue (Woodfall)" , ObjectIconMap::owl },
{ 0x290, "Owl Statue (Southern Swamp)" , ObjectIconMap::owl },
{ 0x291, "Owl Statue (Ikana Canyon)" , ObjectIconMap::owl },
{ 0x292, "Owl Statue (Stone Tower)" , ObjectIconMap::owl },
{ 0x293, "Owl Statue (Hidden)" , ObjectIconMap::none },
{ 0x294, "Bottomless Wallet (MM)" , ObjectIconMap::bottomless_wallet },
{ 0x295, "Soul of Octoroks (MM)" , ObjectIconMap::soul_of_foe },
{ 0x296, "Soul of Wallmasters (MM)" , ObjectIconMap::soul_of_foe },
{ 0x297, "Soul of Dodongos (MM)" , ObjectIconMap::soul_of_foe },
{ 0x298, "Soul of Keese (MM)" , ObjectIconMap::soul_of_foe },
{ 0x299, "Soul of Tektites (MM)" , ObjectIconMap::soul_of_foe },
{ 0x29A, "Soul of Peahats (MM)" , ObjectIconMap::soul_of_foe },
{ 0x29B, "Soul of Lizalfos/Dinolfos (MM)" , ObjectIconMap::soul_of_foe },
{ 0x29C, "Soul of Skulltulas (MM)" , ObjectIconMap::soul_of_foe },
{ 0x29D, "Soul of Armos (MM)" , ObjectIconMap::soul_of_foe },
{ 0x29E, "Soul of Deku Babas (MM)" , ObjectIconMap::soul_of_foe },
{ 0x29F, "Soul of Deku Scrubs (MM)" , ObjectIconMap::soul_of_foe },
{ 0x2A0, "Soul of Bubbles (MM)" , ObjectIconMap::soul_of_foe },
{ 0x2A1, "Soul of Beamos (MM)" , ObjectIconMap::soul_of_foe },
{ 0x2A2, "Soul of ReDeads/Gibdos (MM)" , ObjectIconMap::soul_of_foe },
{ 0x2A3, "Soul of Skullwalltulas (MM)" , ObjectIconMap::soul_of_foe },
{ 0x2A4, "Soul of Shell Blades (MM)" , ObjectIconMap::soul_of_foe },
{ 0x2A5, "Soul of Like Likes (MM)" , ObjectIconMap::soul_of_foe },
{ 0x2A6, "Soul of Iron Knuckles (MM)" , ObjectIconMap::soul_of_foe },
{ 0x2A7, "Soul of Freezards (MM)" , ObjectIconMap::soul_of_foe },
{ 0x2A8, "Soul of Wolfos (MM)" , ObjectIconMap::soul_of_foe },
{ 0x2A9, "Soul of Guays (MM)" , ObjectIconMap::soul_of_foe },
{ 0x2AA, "Soul of Flying Pots (MM)" , ObjectIconMap::soul_of_foe },
{ 0x2AB, "Soul of Floormasters (MM)" , ObjectIconMap::soul_of_foe },
{ 0x2AC, "Soul of Chuchus" , ObjectIconMap::soul_of_foe },
{ 0x2AD, "Soul of Deep Pythons" , ObjectIconMap::soul_of_foe },
{ 0x2AE, "Soul of Stalchildren (MM)" , ObjectIconMap::soul_of_foe },
{ 0x2AF, "Soul of Leevers (MM)" , ObjectIconMap::soul_of_foe },
{ 0x2B0, "Soul of Skullfish (MM)" , ObjectIconMap::soul_of_foe },
{ 0x2B1, "Soul of Dexihands" , ObjectIconMap::soul_of_foe },
{ 0x2B2, "Soul of Dragonflies" , ObjectIconMap::soul_of_foe },
{ 0x2B3, "Soul of Eenoes" , ObjectIconMap::soul_of_foe },
{ 0x2B4, "Soul of Eyegores" , ObjectIconMap::soul_of_foe },
{ 0x2B5, "Soul of Hiploops" , ObjectIconMap::soul_of_foe },
{ 0x2B6, "Soul of Real Bombchu" , ObjectIconMap::soul_of_foe },
{ 0x2B7, "Soul of Takkuri" , ObjectIconMap::soul_of_foe },
{ 0x2B8, "Soul of Boes" , ObjectIconMap::soul_of_foe },
{ 0x2B9, "Soul of Nejirons" , ObjectIconMap::soul_of_foe },
{ 0x2BA, "Soul of Bio Babas" , ObjectIconMap::soul_of_foe },
{ 0x2BB, "Soul of Garo" , ObjectIconMap::soul_of_foe },
{ 0x2BC, "Soul of Wizzrobes" , ObjectIconMap::soul_of_foe },
{ 0x2BD, "Soul of Gomess" , ObjectIconMap::soul_of_foe },
{ 0x2BE, "Soul of Gekkos" , ObjectIconMap::soul_of_foe },
{ 0x2BF, "Soul of Bad Bats" , ObjectIconMap::soul_of_foe },
{ 0x2C0, "Soul of Snappers" , ObjectIconMap::soul_of_foe },
{ 0x2C1, "Soul of Warts" , ObjectIconMap::soul_of_foe },
{ 0x2C2, "Soul of Captain Keeta" , ObjectIconMap::soul_of_foe },
{ 0x2C3, "Soul of the Fighting Pirates" , ObjectIconMap::soul_of_foe },
{ 0x2C4, "Soul of Poes (MM)" , ObjectIconMap::soul_of_foe },
{ 0x2C5, "Soul of Odolwa" , ObjectIconMap::soul_of_boss },
{ 0x2C6, "Soul of Goht" , ObjectIconMap::soul_of_boss },
{ 0x2C7, "Soul of Gyorg" , ObjectIconMap::soul_of_boss },
{ 0x2C8, "Soul of Twinmold" , ObjectIconMap::soul_of_boss },
{ 0x2C9, "Soul of Igos" , ObjectIconMap::soul_of_boss },
{ 0x2CA, "Soul of Madame Aroma (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2CB, "Soul of Town Archery Owner (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2CC, "Soul of Swamp Archery Owner (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2CD, "Soul of Gorons (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2CE, "Soul of the Goron Baby (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2CF, "Soul of the Bomb Shop Owner (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2D0, "Soul of Bombers (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2D1, "Soul of the Deku Butler" , ObjectIconMap::soul_of_npc },
{ 0x2D2, "Soul of Citizens (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2D3, "Soul of Composer Bros. (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2D4, "Soul of Dampe (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2D5, "Soul of the Deku King" , ObjectIconMap::soul_of_npc },
{ 0x2D6, "Soul of the Deku Princess" , ObjectIconMap::soul_of_npc },
{ 0x2D7, "Soul of Playground Scrubs" , ObjectIconMap::soul_of_npc },
{ 0x2D8, "Soul of the Goron Elder" , ObjectIconMap::soul_of_npc },
{ 0x2D9, "Soul of the Fisherman (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2DA, "Soul of the Goron Shopkeeper (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2DB, "Soul of Honey & Darling (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2DC, "Soul of Toto(MM)" , ObjectIconMap::soul_of_npc },
{ 0x2DD, "Soul of Lulu (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2DE, "Soul of the Zora Musicians" , ObjectIconMap::soul_of_npc },
{ 0x2DF, "Soul of Kafei" , ObjectIconMap::soul_of_npc },
{ 0x2E0, "Soul of Keaton" , ObjectIconMap::soul_of_npc },
{ 0x2E1, "Soul of Koume and Kotake" , ObjectIconMap::soul_of_npc },
{ 0x2E2, "Soul of Mayor Dotour" , ObjectIconMap::soul_of_npc },
{ 0x2E3, "Soul of Keg Trial Goron (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2E4, "Soul of Biggoron (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2E5, "Soul of Mr. Barten (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2E6, "Soul of Astronomer (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2E7, "Soul of Ghost Hut Owner (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2E8, "Soul of Blacksmiths" , ObjectIconMap::soul_of_npc },
{ 0x2E9, "Soul of Chest Game Lady (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2EA, "Soul of Tingle" , ObjectIconMap::soul_of_npc },
{ 0x2EB, "Soul of Toilet Hand" , ObjectIconMap::soul_of_npc },
{ 0x2EC, "Soul of Trading Post Owner (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2ED, "Soul of Part-Timer (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2EE, "Soul of Zoras (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2EF, "Soul of the Zora Shopkeeper (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2F0, "Soul of Romani/Cremia (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2F1, "Soul of the Beans Salesman (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2F2, "Soul of Carpenters (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2F3, "Soul of Anju (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2F4, "Soul of Guru-Guru (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2F5, "Soul of the Scientist (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2F6, "Soul of Gorman & Bros. (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2F7, "Soul of Grog (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2F8, "Soul of Dog Lady (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2F9, "Soul of Swordsman (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2FA, "Soul of Anju's Grandmother (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2FB, "Soul of Tourist Center Owner" , ObjectIconMap::soul_of_npc },
{ 0x2FC, "Soul of the Banker (MM)" , ObjectIconMap::soul_of_npc },
{ 0x2FD, "Soul of Moon Children" , ObjectIconMap::soul_of_npc },
{ 0x2FE, "Soul of the Patrolling Pirates and their Chief" , ObjectIconMap::soul_of_npc },
{ 0x2FF, "Soul of Cuccos (MM)" , ObjectIconMap::soul_of_animal },
{ 0x300, "Soul of Cows (MM)" , ObjectIconMap::soul_of_animal },
{ 0x301, "Sould of Dogs (MM)" , ObjectIconMap::soul_of_animal },
{ 0x302, "Soul of Butterflies (MM)" , ObjectIconMap::soul_of_animal },
{ 0x303, "Soul of Gold Skulltulas (MM)" , ObjectIconMap::soul_of_npc },
{ 0x304, "Soul of Business Scrubs (MM)" , ObjectIconMap::soul_of_npc },
{ 0x305, "Key Ring (MM)" , ObjectIconMap::key_ring },
{ 0x306, "Key Ring (Woodfall)" , ObjectIconMap::key_ring },
{ 0x307, "Key Ring (Snowhead)" , ObjectIconMap::key_ring },
{ 0x308, "Key Ring (Great Bay)" , ObjectIconMap::key_ring },
{ 0x309, "Key Ring (Stone Tower)" , ObjectIconMap::key_ring },
{ 0x30A, "Skeleton Key (MM)" , ObjectIconMap::skeleton_key },
{ 0x30B, "A Button (MM)" , ObjectIconMap::a_button },
{ 0x30C, "C-Right Button (MM)" , ObjectIconMap::c_right },
{ 0x30D, "C-Left Button (MM)" , ObjectIconMap::c_left },
{ 0x30E, "C-Up Button (MM)" , ObjectIconMap::c_up },
{ 0x30F, "C-Down Button (MM)" , ObjectIconMap::c_down },
{ 0x310, "Bottle of Green Potion (MM)" , ObjectIconMap::green_potion },
{ 0x311, "Bottle of Blue Potion (MM)" , ObjectIconMap::blue_potion },
{ 0x312, "Bottled Fairy (MM)" , ObjectIconMap::bottled_fairy },
{ 0x313, "Poe (MM)" , ObjectIconMap::bottled_poe },
{ 0x314, "Bottled Poe (MM)" , ObjectIconMap::bottled_poe },
{ 0x315, "Bottled Big Poe (MM)" , ObjectIconMap::bottled_big_poe },
{ 0x316, "Bombchu Bag (MM)" , ObjectIconMap::bombchu_bag },
{ 0x317, "Big Bombchu Bag (MM)" , ObjectIconMap::bombchu_bag },
{ 0x318, "Biggest Bombchu Bag (MM)" , ObjectIconMap::bombchu_bag },
{ 0x319, "Bombchu Bag (MM)" , ObjectIconMap::bombchu_bag },
{ 0x31A, "Bombchu Bag (MM)" , ObjectIconMap::bombchu_bag },
{ 0x31B, "Bombchu Bag (MM)" , ObjectIconMap::bombchu_bag },
{ 0x31C, "Bombchu Bag (MM)" , ObjectIconMap::bombchu_bag },
{ 0x31D, "Big Fairy (MM)" , ObjectIconMap::fairy },
{ 0x31E, "Din's Fire (MM)" , ObjectIconMap::din },
{ 0x31F, "Farore's Wind (MM)" , ObjectIconMap::farore },
{ 0x320, "Nayru's Love (MM)" , ObjectIconMap::nayru },
{ 0x321, "Iron Boots (MM)" , ObjectIconMap::iron },
{ 0x322, "Hover Boots (MM)" , ObjectIconMap::hover },
{ 0x323, "Goron Tunic (MM)" , ObjectIconMap::goron_tunic },
{ 0x324, "Zora Tunic (MM)" , ObjectIconMap::zora_tunic },
{ 0x325, "Bronze Scale (MM)" , ObjectIconMap::bronze_scale },
{ 0x326, "Silver Scale (MM)" , ObjectIconMap::silver },
{ 0x327, "Golden Scale (MM)" , ObjectIconMap::golden },
{ 0x328, "Goron's Bracelet (MM)" , ObjectIconMap::bracelet },
{ 0x329, "Silver Gauntlets (MM)" , ObjectIconMap::silver_gauntlet },
{ 0x32A, "Golden Gauntlets (MM)" , ObjectIconMap::golden_gauntlet },
{ 0x32B, "Clock (Day 1)" , ObjectIconMap::clock_d1 },
{ 0x32C, "Clock (Night 1)" , ObjectIconMap::clock_n1 },
{ 0x32D, "Clock (Day 2)" , ObjectIconMap::clock_d2 },
{ 0x32E, "Clock (Night 2)" , ObjectIconMap::clock_n2 },
{ 0x32F, "Clock (Day 3)" , ObjectIconMap::clock_d3 },
{ 0x330, "Clock (Night 3)" , ObjectIconMap::clock_n3 },
{ 0x331, "Megaton Hammer (MM)" , ObjectIconMap::hammer },
{ 0x332, "Deku Stick Upgrade (MM)" , ObjectIconMap::stick_upgrade_1 },
{ 0x333, "Second Deku Stick Upgrade (MM)" , ObjectIconMap::stick_upgrade_2 },
{ 0x334, "Deku Nut Upgrade (MM)" , ObjectIconMap::nut_upgrade_1 },
{ 0x335, "Second Deku Nut Upgrade (MM)" , ObjectIconMap::nut_upgrade_2 },
{ 0x336, "Stone of Agony (MM)" , ObjectIconMap::agony },
{ 0x337, "Ruto's Letter" , ObjectIconMap::ruto },
{ 0x338, "Bottle of Blue Fire" , ObjectIconMap::blue_fire },
{ 0x339, "Blue Fire" , ObjectIconMap::blue_fire },
{ 0x33A, "Majora's Mask" , ObjectIconMap::mask },
{ 0x33B, "Sold Out" , ObjectIconMap::none },
{ 0x33C, "Nothing" , ObjectIconMap::none },
{ 0x33D, "MM Scoop" , ObjectIconMap::none },

};

#pragma endregion 

void ParseKey(uint8_t Key[5], ComboItem* Item)
{
    uint8_t index = 0;

    Item->GameID = Key[index];
    Item->OvType = Key[++index];
    Item->SceneID = Key[++index];
    Item->RoomID = Key[++index];
    Item->ObjectID = Key[++index];
}

const ItemInfo * FindItem(uint32_t gi)
{
    const ItemInfo * currItem = nullptr;

    for (size_t i = 0; i < NUM_ITEM; i++)
    {
        currItem = &ItemList[i];

        if (currItem->ItemID == gi)
        {
            return currItem;
        }
    }

    return currItem;
}

const ItemInfo* FindItemByName(QString Name)
{
    Name = Name.replace("\n", "");
    size_t len = Name.length() + 1;
    char* tmpObjName = (char*)malloc(sizeof(char) * len);
    if (tmpObjName)
    {
        memcpy_s(tmpObjName, len, Name.toStdString().c_str(), len);
        tmpObjName[len - 1] = '\0';

        for (size_t i = 0; i < NUM_ITEM; i++)
        {
            if (strcmp(tmpObjName, ItemList[i].ItemName) == 0)
            {
                free(tmpObjName);
                return &ItemList[i];
            }
        }

        // No item found

        ItemInfo* item = new ItemInfo();
        item->ItemID = -1;
        item->ItemName = tmpObjName;

        return item;

    }
    return nullptr;
}
