#include "UI/SceneEntrance.h"
#include "Combo/Scenes.h"

std::map<uint32_t, SceneEntranceMetaInf>MMSceneEntranceMeta =
{
	{
		MM_LAIR_ODOLWA,
		{
			MM_LAIR_ODOLWA,
			{
				{ MM_BOSS_TEMPLE_WOODFALL_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_LAIR_GOHT,
		{
			MM_LAIR_GOHT,
			{
				{ MM_BOSS_TEMPLE_SNOWHEAD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_LAIR_GYORG,
		{
			MM_LAIR_GYORG,
			{
				{ MM_BOSS_TEMPLE_GREAT_BAY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_LAIR_TWINMOLD,
		{
			MM_LAIR_TWINMOLD,
			{
				{ MM_BOSS_TEMPLE_STONE_TOWER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_TEMPLE_WOODFALL,
		{
			MM_TEMPLE_WOODFALL,
			{
				{ MM_TEMPLE_WOODFALL_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_TEMPLE_SNOWHEAD,
		{
			MM_TEMPLE_SNOWHEAD,
			{
				{ MM_TEMPLE_SNOWHEAD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_TEMPLE_GREAT_BAY,
		{
			MM_TEMPLE_GREAT_BAY,
			{
				{ MM_TEMPLE_GREAT_BAY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_TEMPLE_STONE_TOWER_INVERTED,
		{
			MM_TEMPLE_STONE_TOWER_INVERTED,
			{
				{ MM_TEMPLE_STONE_TOWER_INVERTED_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_TEMPLE_STONE_TOWER,
		{
			MM_TEMPLE_STONE_TOWER,
			{
				{ MM_TEMPLE_STONE_TOWER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_SPIDER_HOUSE_SWAMP,
		{
			MM_SPIDER_HOUSE_SWAMP,
			{
				{ MM_SPIDER_HOUSE_SWAMP_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_SPIDER_HOUSE_OCEAN,
		{
			MM_SPIDER_HOUSE_OCEAN,
			{
				{ MM_SPIDER_HOUSE_OCEAN_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_BENEATH_THE_WELL,
		{
			MM_BENEATH_THE_WELL,
			{
				{ MM_BENEATH_THE_WELL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_BENEATH_THE_WELL_BACK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WALLMASTER_BTW_ENTRANCE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WALLMASTER_BTW_FOUNTAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WALLMASTER_BTW_EXIT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_INSIDE_CASTLE_IKANA,
		{
			MM_INSIDE_CASTLE_IKANA,
			{
				{ MM_IKANA_CASTLE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_CASTLE_INTERIOR_KEG_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_CASTLE_INTERIOR_BLOCK_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_SECRET_SHRINE,
		{
			MM_SECRET_SHRINE,
			{
				{ MM_SECRET_SHRINE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_CAVERN_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_PIRATE_FORTRESS_EXTERIOR,
		{
			MM_PIRATE_FORTRESS_EXTERIOR,
			{
				{ MM_PIRATE_FORTRESS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_EXTERIOR_GATE_FROM_SEWERS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_PIRATE_FORTRESS_EXTERIOR_FROM_INTERIOR_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_PIRATE_FORTRESS_EXTERIOR_LOOKOUT_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_EXTERIOR_DOOR_FROM_SEWERS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_CLOCK_TOWER_ROOFTOP,
		{
			MM_CLOCK_TOWER_ROOFTOP,
			{
				{ MM_CLOCK_TOWER_ROOF_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_WOODFALL,
		{
			MM_WOODFALL,
			{
				{ MM_WOODFALL_FROM_TEMPLE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WOODFALL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WOODFALL_FROM_FAIRY_FOUNTAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WARP_OWL_WOODFALL_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_SNOWHEAD,
		{
			MM_SNOWHEAD,
			{
				{ MM_SNOWHEAD_FROM_TEMPLE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_SNOWHEAD_FROM_SNOWHEAD_PATH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_SNOWHEAD_FROM_FAIRY_FOUNTAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WARP_OWL_SNOWHEAD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GREAT_BAY_COAST,
		{
			MM_GREAT_BAY_COAST,
			{
				{ MM_GREAT_BAY_FROM_TEMPLE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GREAT_BAY_FROM_SPIDER_HOUSE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GREAT_BAY_FROM_PIRATE_FORTRESS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GREAT_BAY_COAST_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GREAT_BAY_COAST_FROM_ZORA_CAPE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GREAT_BAY_FROM_PINNACLE_ROCK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GREAT_BAY_COAST_FROM_FISHER_HUT_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GREAT_BAY_COAST_FROM_LABORATORY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GREAT_BAY_FROM_FAIRY_FOUNTAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WARP_OWL_GREAT_BAY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_GREAT_BAY_COAST, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_COW_COAST, { UINT32_MAX, UINT32_MAX } },
				{ MM_VOID_GREAT_BAY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_VOID_GREAT_BAY_BY_PINNACLE_ROCK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_COAST_FROM_MIKAU_CS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_STONE_TOWER_INVERTED,
		{
			MM_STONE_TOWER_INVERTED,
			{
				{ MM_STONE_TOWER_INVERTED_FROM_TEMPLE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_STONE_TOWER,
		{
			MM_STONE_TOWER,
			{
				{ MM_STONE_TOWER_FROM_TEMPLE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_STONE_TOWER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WARP_OWL_STONE_TOWER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_SOUTHERN_SWAMP,
		{
			MM_SOUTHERN_SWAMP,
			{
				{ MM_SWAMP_FROM_SPIDER_HOUSE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_SWAMP_FROM_ROAD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_SWAMP_FROM_PALACE_MAIN_ENTRANCE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_SWAMP_FROM_PALACE_LEDGE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_SWAMP_FROM_WOODFALL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_SWAMP_FROM_MYSTERY_WOODS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_SWAMP_FROM_IKANA_CANYON_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_SWAMP_FROM_POTION_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_SWAMP_FROM_TOURIST_INFORMATION_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WARP_OWL_SOUTHERN_SWAMP_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_SWAMP, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_IKANA_CANYON,
		{
			MM_IKANA_CANYON,
			{
				{ MM_IKANA_CANYON_FROM_WELL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_VALLEY_FROM_SHRINE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_VALLEY_FROM_ROAD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_CASTLE_GARDENS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_CANYON_FROM_STONE_TOWER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_CANYON_FROM_GHOST_HUT_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_CANYON_FROM_MUSIC_BOX_HOUSE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_CANYON_FROM_FAIRY_FOUNTAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_CANYON_FROM_CAVERN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_CANYON_FROM_SAKON_HIDEOUT_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WARP_OWL_IKANA_CANYON_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_VALLEY, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_CASTLE_IKANA,
		{
			MM_CASTLE_IKANA,
			{
				{ MM_IKANA_CASTLE_EXTERIOR_FROM_WELL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_CASTLE_EXTERIOR_FROM_CASTLE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_CANYON_FROM_CASTLE_GARDENS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_CLOCK_TOWN_SOUTH,
		{
			MM_CLOCK_TOWN_SOUTH,
			{
				{ MM_CLOCK_TOWN_FROM_CLOCK_TOWER_ROOF_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_SOUTH_BOTTOM_FROM_WEST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_SOUTH_BOTTOM_FROM_EAST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_SOUTH_FROM_NORTH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_SOUTH_TOP_FROM_EAST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_SOUTH_TOP_FROM_WEST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_SOUTH_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_SOUTH_FROM_LAUNDRY_POOL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WARP_OWL_CLOCK_TOWN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_FROM_SONG_OF_TIME_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_FROM_CLOCK_TOWER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_MOUNTAIN_VILLAGE,
		{
			MM_MOUNTAIN_VILLAGE,
			{
				{ MM_MOUNTAIN_VILLAGE_FROM_PATH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_MOUNTAIN_VILLAGE_FROM_SNOWHEAD_PATH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_MOUNTAIN_VILLAGE_FROM_TWIN_ISLANDS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_MOUNTAIN_VILLAGE_FROM_GORON_GRAVEYARD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_MOUNTAIN_VILLAGE_FROM_BLACKSMITH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WARP_OWL_MOUNTAIN_VILLAGE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_MOUNTAIN_VILLAGE, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_MOUNTAIN_VILLAGE_WINTER, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_ROMANI_RANCH,
		{
			MM_ROMANI_RANCH,
			{
				{ MM_ROMANI_RANCH_FROM_MILK_ROAD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ROMANI_RANCH_FROM_CUCCO_SHACK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ROMANI_RANCH_FROM_DOGGY_RACETRACK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ROMANI_RANCH_FROM_STABLES_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ROMANI_RANCH_FROM_RANCH_HOUSE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_ROAD_SOUTHERN_SWAMP,
		{
			MM_ROAD_SOUTHERN_SWAMP,
			{
				{ MM_SWAMP_ROAD_FROM_SWAMP_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_SWAMP_ROAD_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_SWAMP_ROAD_FROM_ARCHERY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_PATH_SWAMP, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_PATH_MOUNTAIN_VILLAGE,
		{
			MM_PATH_MOUNTAIN_VILLAGE,
			{
				{ MM_PATH_FROM_MOUNTAIN_VILLAGE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_MOUNTAIN_VILLAGE_PATH_FROM_TERMINA_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_TERMINA_FIELD,
		{
			MM_TERMINA_FIELD,
			{
				{ MM_TERMINA_FIELD_FROM_GREAT_BAY_COAST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_TERMINA_FIELD_FROM_CLOCK_TOWN_WEST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_TERMINA_FIELD_FROM_CLOCK_TOWN_SOUTH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_TERMINA_FIELD_FROM_CLOCK_TOWN_EAST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_TERMINA_FIELD_FROM_CLOCK_TOWN_NORTH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_TERMINA_FIELD_FROM_ROAD_TO_IKANA_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_TERMINA_FIELD_FROM_PATH_TO_MOUNTAIN_VILLAGE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_TERMINA_FIELD_FROM_ROAD_TO_SWAMP_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_TERMINA_FIELD_FROM_MILK_ROAD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_FIELD_FROM_ASTRAL_OBSERVATORY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_FIELD_PILLAR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_GRASS, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_COW_FIELD, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GOSSIPS_MOUNTAIN, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GOSSIPS_CANYON, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GOSSIPS_OCEAN, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GOSSIPS_SWAMP, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_DODONGO, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_SCRUB, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_PEAHAT, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_BIO_BABA, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_ROAD_IKANA,
		{
			MM_ROAD_IKANA,
			{
				{ MM_IKANA_ROAD_FROM_VALLEY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_ROAD_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_ROAD_FROM_IKANA_GRAVEYARD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_PATH_IKANA, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_MILK_ROAD,
		{
			MM_MILK_ROAD,
			{
				{ MM_MILK_ROAD_FROM_ROMANI_RANCH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_MILK_ROAD_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_MILK_ROAD_FROM_GORMAN_TRACK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_MILK_ROAD_FROM_GORMAN_BACK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WARP_OWL_MILK_ROAD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_MILK_ROAD_FROM_RANCH2_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_MILK_ROAD_FROM_GORMAN_TRACK2_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_CLOCK_TOWN_WEST,
		{
			MM_CLOCK_TOWN_WEST,
			{
				{ MM_CLOCK_TOWN_WEST_FROM_SOUTH_BOTTOM_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_WEST_FROM_SOUTH_TOP_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_WEST_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_WEST_FROM_SWORDSMAN_SCHOOL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_WEST_FROM_CURIOSITY_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_WEST_FROM_TRADING_POST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_WEST_FROM_BOMB_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_WEST_FROM_POST_OFFICE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_WEST_FROM_LOTTERY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_CLOCK_TOWN_EAST,
		{
			MM_CLOCK_TOWN_EAST,
			{
				{ MM_CLOCK_TOWN_EAST_FROM_SOUTH_BOTTOM_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_EAST_FROM_NORTH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_EAST_FROM_SOUTH_TOP_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_EAST_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_EAST_FROM_CHEST_GAME_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_EAST_FROM_HONEY_AND_DARLING_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_EAST_FROM_MAYORS_OFFICE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_EAST_FROM_TOWN_ARCHERY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_EAST_FROM_STOCK_POT_INN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_EAST_FROM_STOCK_POT_INN_ROOF_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_EAST_FROM_MILK_BAR_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_EAST_FROM_ASTRAL_OBSERVATORY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_CLOCK_TOWN_NORTH,
		{
			MM_CLOCK_TOWN_NORTH,
			{
				{ MM_CLOCK_TOWN_NORTH_FROM_EAST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_NORTH_FROM_SOUTH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_NORTH_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_NORTH_FROM_FAIRY_FOUNTAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_DEKU_PLAYGROUND, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_LAUNDRY_POOL,
		{
			MM_LAUNDRY_POOL,
			{
				{ MM_LAUNDRY_POOL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_LAUNDRY_POOL_FROM_KAFEI_HIDEOUT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GORMAN_TRACK,
		{
			MM_GORMAN_TRACK,
			{
				{ MM_GORMAN_TRACK_FROM_MILK_ROAD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GORMAN_BACK_FROM_MILK_ROAD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GORMAN_TRACK_UNK2_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GORMAN_TRACK_UNK3_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GORMAN_TRACK_UNK5_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GORMAN_TRACK_UNK6_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_PATH_SNOWHEAD,
		{
			MM_PATH_SNOWHEAD,
			{
				{ MM_SNOWHEAD_PATH_FROM_MOUNTAIN_VILLAGE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_PATH_SNOWHEAD_FROM_SNOWHEAD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_PATH_SNOWHEAD, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_IKANA_GRAVEYARD,
		{
			MM_IKANA_GRAVEYARD,
			{
				{ MM_IKANA_GRAVEYARD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_GRAVEYARD, { UINT32_MAX, UINT32_MAX } },
				{ MM_GRAVE_EXIT_NIGHT1, { UINT32_MAX, UINT32_MAX } },
				{ MM_GRAVE_EXIT_NIGHT2, { UINT32_MAX, UINT32_MAX } },
				{ MM_GRAVE_EXIT_NIGHT3, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_GRAVEYARD_FROM_DAMPE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_ZORA_CAPE,
		{
			MM_ZORA_CAPE,
			{
				{ MM_ZORA_CAPE_FROM_GREAT_BAY_COAST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ZORA_CAPE_FROM_HALL_WATER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ZORA_CAPE_PENINSULA_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ZORA_CAPE_FROM_BEAVERS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WARP_OWL_ZORA_CAPE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_ZORA_CAPE, { UINT32_MAX, UINT32_MAX } },
				{ MM_VOID_ZORA_CAPE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_PINNACLE_ROCK,
		{
			MM_PINNACLE_ROCK,
			{
				{ MM_PINNACLE_ROCK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_VOID_PINNACLE_ROCK_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_ZORA_HALL,
		{
			MM_ZORA_HALL,
			{
				{ MM_ZORA_HALL_UNDERWATER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ZORA_HALL_LEDGE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ZORA_HALL_FROM_EVANS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ZORA_HALL_FROM_JAPAS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ZORA_HALL_FROM_TIJO_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ZORA_HALL_FROM_LULU_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ZORA_HALL_FROM_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_DEKU_PALACE,
		{
			MM_DEKU_PALACE,
			{
				{ MM_DEKU_PALACE_MAIN_ENTRANCE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_DEKU_PALACE_LEDGE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_DEKU_PALACE_EXTERIOR_FROM_SHRINE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_DEKU_PALACE_EXTERIOR_FROM_THRONE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_DEKU_PALACE_EXTERIOR_FROM_THRONE_CAGE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_BEAN, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_JP_CLIMB_LEFT, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_JP_CLIMB_RIGHT, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_JP_LINE_START, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_JP_LINE_END, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_LOST_WOODS,
		{
			MM_LOST_WOODS,
			{
				{ MM_MYSTERY_WOODS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_WOODS, { UINT32_MAX, UINT32_MAX } },
				{ MM_LOST_WOODS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_PIRATE_SEWERS,
		{
			MM_PIRATE_SEWERS,
			{
				{ MM_SEWERS_FROM_EXTERIOR_GATE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_SEWERS_FROM_EXTERIOR_DOOR_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_PIRATE_FORTRESS_INTERIOR,
		{
			MM_PIRATE_FORTRESS_INTERIOR,
			{
				{ MM_PIRATE_FORTRESS_INTERIOR_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_PIRATE_FORTRESS_INTERIOR_FROM_LOOKOUT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_TWIN_ISLANDS,
		{
			MM_TWIN_ISLANDS,
			{
				{ MM_TWIN_ISLANDS_FROM_MOUNTAIN_VILLAGE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_TWIN_ISLANDS_FROM_GORON_VILLAGE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_TWIN_ISLANDS_FROM_GORON_RACETRACK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_TWIN_ISLANDS, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_HOT_WATER, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GORON_VILLAGE_WINTER,
		{
			MM_GORON_VILLAGE_WINTER,
			{
				{ MM_GORON_VILLAGE_FROM_TWIN_ISLANDS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GORON_VILLAGE_FROM_GORON_SHRINE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GORON_VILLAGE_FROM_LONE_PEAK_SHRINE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_TREASURE_SHOP,
		{
			MM_TREASURE_SHOP,
			{
				{ MM_CHEST_GAME_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_HONEY_DARLING,
		{
			MM_HONEY_DARLING,
			{
				{ MM_HONEY_AND_DARLING_GAME_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_MAYOR_HOUSE,
		{
			MM_MAYOR_HOUSE,
			{
				{ MM_MAYORS_OFFICE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_SHOOTING_GALLERY,
		{
			MM_SHOOTING_GALLERY,
			{
				{ MM_TOWN_ARCHERY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_MILK_BAR,
		{
			MM_MILK_BAR,
			{
				{ MM_MILK_BAR_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_FAIRY_CLOCK_TOWN,
		{
			MM_FAIRY_CLOCK_TOWN,
			{
				{ MM_FAIRY_FOUNTAIN_TOWN_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_SWORDSMAN_SCHOOL,
		{
			MM_SWORDSMAN_SCHOOL,
			{
				{ MM_SWORDSMAN_SCHOOL_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_CURIOSITY_SHOP,
		{
			MM_CURIOSITY_SHOP,
			{
				{ MM_CURIOSITY_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_KAFEI_HIDEOUT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_TRADING_POST,
		{
			MM_TRADING_POST,
			{
				{ MM_TRADING_POST_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_BOMB_SHOP,
		{
			MM_BOMB_SHOP,
			{
				{ MM_BOMB_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_POST_OFFICE,
		{
			MM_POST_OFFICE,
			{
				{ MM_POST_OFFICE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_LOTTERY,
		{
			MM_LOTTERY,
			{
				{ MM_LOTTERY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_POTION_SHOP,
		{
			MM_POTION_SHOP,
			{
				{ MM_POTION_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_DEKU_SHRINE,
		{
			MM_DEKU_SHRINE,
			{
				{ MM_DEKU_SHRINE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GORON_SHOP,
		{
			MM_GORON_SHOP,
			{
				{ MM_GORON_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_FISHERMAN_HUT,
		{
			MM_FISHERMAN_HUT,
			{
				{ MM_FISHER_HUT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_LABORATORY,
		{
			MM_LABORATORY,
			{
				{ MM_LABORATORY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_ZORA_EVANS_ROOM,
		{
			MM_ZORA_EVANS_ROOM,
			{
				{ MM_ROOM_EVANS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_ZORA_JAPAS_ROOM,
		{
			MM_ZORA_JAPAS_ROOM,
			{
				{ MM_ROOM_JAPAS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_ZORA_TIJO_ROOM,
		{
			MM_ZORA_TIJO_ROOM,
			{
				{ MM_ROOM_TIJO_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_ZORA_LULU_ROOM,
		{
			MM_ZORA_LULU_ROOM,
			{
				{ MM_ROOM_LULU_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_ZORA_SHOP,
		{
			MM_ZORA_SHOP,
			{
				{ MM_ZORA_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GHOST_HUT,
		{
			MM_GHOST_HUT,
			{
				{ MM_GHOST_HUT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_MUSIC_BOX_HOUSE,
		{
			MM_MUSIC_BOX_HOUSE,
			{
				{ MM_MUSIC_BOX_HOUSE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_FAIRY_IKANA,
		{
			MM_FAIRY_IKANA,
			{
				{ MM_FAIRY_FOUNTAIN_IKANA_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_FAIRY_GREAT_BAY_COAST,
		{
			MM_FAIRY_GREAT_BAY_COAST,
			{
				{ MM_FAIRY_FOUNTAIN_GREAT_BAY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_FAIRY_SNOWHEAD,
		{
			MM_FAIRY_SNOWHEAD,
			{
				{ MM_FAIRY_FOUNTAIN_SNOWHEAD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_FAIRY_WOODFALL,
		{
			MM_FAIRY_WOODFALL,
			{
				{ MM_FAIRY_FOUNTAIN_WOODFALL_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GORON_GRAVEYARD,
		{
			MM_GORON_GRAVEYARD,
			{
				{ MM_GORON_GRAVEYARD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_BLACKSMITH,
		{
			MM_BLACKSMITH,
			{
				{ MM_BLACKSMITH_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_SHOOTING_GALLERY_SWAMP,
		{
			MM_SHOOTING_GALLERY_SWAMP,
			{
				{ MM_SWAMP_ARCHERY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GORON_RACETRACK,
		{
			MM_GORON_RACETRACK,
			{
				{ MM_GORON_RACETRACK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GORON_RACETRACK_ALT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_WATERFALL_RAPIDS,
		{
			MM_WATERFALL_RAPIDS,
			{
				{ MM_BEAVERS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_CUCCO_SHACK,
		{
			MM_CUCCO_SHACK,
			{
				{ MM_CUCCO_SHACK_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_DOG_RACETRACK,
		{
			MM_DOG_RACETRACK,
			{
				{ MM_DOGGY_RACETRACK_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_RANCH_HOUSE_BARN,
		{
			MM_RANCH_HOUSE_BARN,
			{
				{ MM_STABLES_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_ROMANI_RANCH_BARN,
		{
			MM_ROMANI_RANCH_BARN,
			{
				{ MM_RANCH_HOUSE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GORON_SHRINE,
		{
			MM_GORON_SHRINE,
			{
				{ MM_GORON_SHRINE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GORON_SHRINE_FROM_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_DEKU_KING_CHAMBER,
		{
			MM_DEKU_KING_CHAMBER,
			{
				{ MM_DEKU_PALACE_THRONE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_DEKU_PALACE_THRONE_CAGE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_LONE_PEAK,
		{
			MM_LONE_PEAK,
			{
				{ MM_LONE_PEAK_SHRINE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_STOCK_POT_INN,
		{
			MM_STOCK_POT_INN,
			{
				{ MM_STOCK_POT_INN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_STOCK_POT_INN_ROOF_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_TOURIST_INFORMATION,
		{
			MM_TOURIST_INFORMATION,
			{
				{ MM_TOURIST_INFORMATION_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_OBSERVATORY,
		{
			MM_OBSERVATORY,
			{
				{ MM_ASTRAL_OBSERVATORY_FROM_CLOCK_TOWN_EAST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ASTRAL_OBSERVATORY_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_SAKON_HIDEOUT,
		{
			MM_SAKON_HIDEOUT,
			{
				{ MM_SAKON_HIDEOUT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_DAMPE_HOUSE,
		{
			MM_DAMPE_HOUSE,
			{
				{ MM_WALLMASTER_DAMPE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GRAVE_NIGHT3_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_TERMINA_PILLAR,
		{
			MM_GROTTO_TERMINA_PILLAR,
			{
				{ MM_GROTTO_GENERIC_FIELD_PILLAR_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_TERMINA_TALL_GRASS,
		{
			MM_GROTTO_TERMINA_TALL_GRASS,
			{
				{ MM_GROTTO_GENERIC_GRASS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_SOUTHERN_SWAMP_ROAD_OPEN,
		{
			MM_GROTTO_SOUTHERN_SWAMP_ROAD_OPEN,
			{
				{ MM_GROTTO_GENERIC_PATH_SWAMP_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_WOODS_OF_MYSTERY_OPEN,
		{
			MM_GROTTO_WOODS_OF_MYSTERY_OPEN,
			{
				{ MM_GROTTO_GENERIC_WOODS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_SOUTHERN_SWAMP_OPEN,
		{
			MM_GROTTO_SOUTHERN_SWAMP_OPEN,
			{
				{ MM_GROTTO_GENERIC_SWAMP_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_MOUNTAIN_VILLAGE_GENERIC,
		{
			MM_GROTTO_MOUNTAIN_VILLAGE_GENERIC,
			{
				{ MM_GROTTO_GENERIC_MOUNTAIN_VILLAGE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_TWIN_ISLANDS_RAMP,
		{
			MM_GROTTO_TWIN_ISLANDS_RAMP,
			{
				{ MM_GROTTO_GENERIC_TWIN_ISLANDS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_PATH_TO_SNOWHEAD_GENERIC,
		{
			MM_GROTTO_PATH_TO_SNOWHEAD_GENERIC,
			{
				{ MM_GROTTO_GENERIC_PATH_SNOWHEAD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_GREAT_BAY_COAST_FISHERMAN,
		{
			MM_GROTTO_GREAT_BAY_COAST_FISHERMAN,
			{
				{ MM_GROTTO_GENERIC_GREAT_BAY_COAST_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_ZORA_CAPE_GENERIC,
		{
			MM_GROTTO_ZORA_CAPE_GENERIC,
			{
				{ MM_GROTTO_GENERIC_ZORA_CAPE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_IKANA_ROAD_GENERIC,
		{
			MM_GROTTO_IKANA_ROAD_GENERIC,
			{
				{ MM_GROTTO_GENERIC_PATH_IKANA_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_IKANA_GRAVEYARD_GENERIC,
		{
			MM_GROTTO_IKANA_GRAVEYARD_GENERIC,
			{
				{ MM_GROTTO_GENERIC_GRAVEYARD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_IKANA_VALLEY_OPEN,
		{
			MM_GROTTO_IKANA_VALLEY_OPEN,
			{
				{ MM_GROTTO_GENERIC_VALLEY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_TERMINA_COW,
		{
			MM_GROTTO_TERMINA_COW,
			{
				{ MM_GROTTO_COW_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_GREAT_BAY_COAST_COW,
		{
			MM_GROTTO_GREAT_BAY_COAST_COW,
			{
				{ MM_GROTTO_COW_COAST_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_TERMINA_MOUNTAIN_GOSSIP,
		{
			MM_GROTTO_TERMINA_MOUNTAIN_GOSSIP,
			{
				{ MM_GROTTO_GOSSIPS_MOUNTAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_TERMINA_CANYON_GOSSIP,
		{
			MM_GROTTO_TERMINA_CANYON_GOSSIP,
			{
				{ MM_GROTTO_GOSSIPS_CANYON_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_TERMINA_OCEAN_GOSSIP,
		{
			MM_GROTTO_TERMINA_OCEAN_GOSSIP,
			{
				{ MM_GROTTO_GOSSIPS_OCEAN_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_TERMINA_SWAMP_GOSSIP,
		{
			MM_GROTTO_TERMINA_SWAMP_GOSSIP,
			{
				{ MM_GROTTO_GOSSIPS_SWAMP_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_TERMINA_DODONGO,
		{
			MM_GROTTO_TERMINA_DODONGO,
			{
				{ MM_GROTTO_DODONGO_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_TERMINA_SCRUB,
		{
			MM_GROTTO_TERMINA_SCRUB,
			{
				{ MM_GROTTO_SCRUB_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_TERMINA_PEAHAT,
		{
			MM_GROTTO_TERMINA_PEAHAT,
			{
				{ MM_GROTTO_PEAHAT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_TERMINA_BIO_BABA,
		{
			MM_GROTTO_TERMINA_BIO_BABA,
			{
				{ MM_GROTTO_BIO_BABA_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_TWIN_ISLANDS_FROZEN,
		{
			MM_GROTTO_TWIN_ISLANDS_FROZEN,
			{
				{ MM_GROTTO_HOT_WATER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_DEKU_PALACE_BEANS,
		{
			MM_GROTTO_DEKU_PALACE_BEANS,
			{
				{ MM_GROTTO_BEAN_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_DEKU_PLAYGROUND,
		{
			MM_DEKU_PLAYGROUND,
			{
				{ MM_GROTTO_DEKU_PLAYGROUND_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_DEKU_PALACE_CLIMB,
		{
			MM_GROTTO_DEKU_PALACE_CLIMB,
			{
				{ MM_GROTTO_JP_CLIMB_LEFT_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_JP_CLIMB_RIGHT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_DEKU_PALACE_GENERIC,
		{
			MM_GROTTO_DEKU_PALACE_GENERIC,
			{
				{ MM_GROTTO_JP_LINE_START_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_JP_LINE_END_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_BENEATH_THE_GRAVEYARD_NIGHT1,
		{
			MM_BENEATH_THE_GRAVEYARD_NIGHT1,
			{
				{ MM_GRAVE_NIGHT1_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_BENEATH_THE_GRAVEYARD_NIGHT2,
		{
			MM_BENEATH_THE_GRAVEYARD_NIGHT2,
			{
				{ MM_GRAVE_NIGHT2_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_MOON,
		{
			MM_MOON,
			{
				{ MM_MOON_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_EXTRA,
		{
			MM_EXTRA,
			{
				{ MM_CLOCK_TOWER_MOON_CRASH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ SPAWN_LOADING, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_CLOCK_TOWER_INTERIOR,
		{
			MM_CLOCK_TOWER_INTERIOR,
			{
				{ MM_CLOCK_TOWER_FROM_CLOCK_TOWN_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTOS,
		{
			MM_GROTTOS,
			{
				{ MM_GROTTO_TYPE_GENERIC_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_TYPE_COW_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_INTERNAL_EXIT_GROTTO_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},

};
