#include "UI/SceneEntrance.h"
#include "Combo/Scenes.h"

std::map<uint32_t, SceneEntranceMetaInf>OoTSceneEntranceMeta =
{
	{
		OOT_BACK_ALLEY,
		{
			OOT_BACK_ALLEY, (uint8_t)OoTRegions::Market,
			{
				{ OOT_BACK_ALLEY_TREASURE_FROM_MARKET_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_BACK_ALLEY_FROM_HOUSE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_FROM_ALLEY_HOUSE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_BACK_ALLEY_SHOOTING_FROM_MARKET_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_FROM_BOMBCHU_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_BACK_ALLEY_HOUSE,
		{
			OOT_BACK_ALLEY_HOUSE, (uint8_t)OoTRegions::Market,
			{
				{ OOT_ALLEY_HOUSE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_BACK_ALLEY_HOUSE2,
		{
			OOT_BACK_ALLEY_HOUSE2, (uint8_t)OoTRegions::Market,
			{
				{ OOT_DOG_LADY_FROM_BACK_ALLEY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_KAKARIKO_BAZAAR,
		{
			OOT_KAKARIKO_BAZAAR, (uint8_t)OoTRegions::Kakariko,
			{
				{ OOT_KAKARIKO_BAZAAR_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_MARKET_BAZAAR,
		{
			OOT_MARKET_BAZAAR, (uint8_t)OoTRegions::Market,
			{
				{ OOT_MARKET_BAZAAR_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_BOMBCHU_BOWLING_ALLEY,
		{
			OOT_BOMBCHU_BOWLING_ALLEY, (uint8_t)OoTRegions::Market,
			{
				{ OOT_BOMBCHU_BOWLING_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_BOMBCHU_SHOP,
		{
			OOT_BOMBCHU_SHOP, (uint8_t)OoTRegions::Market,
			{
				{ OOT_BOMBCHU_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_BOTTOM_OF_THE_WELL,
		{
			OOT_BOTTOM_OF_THE_WELL, (uint8_t)OoTRegions::Kakariko,
			{
				{ OOT_BOTTOM_OF_THE_WELL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WALLMASTER_BOTW_MAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WALLMASTER_BOTW_BASEMENT_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WALLMASTER_BOTW_PIT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_CARPENTER_BOSS_HOUSE,
		{
			OOT_CARPENTER_BOSS_HOUSE, (uint8_t)OoTRegions::Kakariko,
			{
				{ OOT_HOUSE_CARPENTER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_CARPENTER_TENT,
		{
			OOT_CARPENTER_TENT, (uint8_t)OoTRegions::Kakariko,
			{
				{ OOT_VALLEY_TENT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_CASTLE_COURTYARD,
		{
			OOT_CASTLE_COURTYARD, (uint8_t)OoTRegions::Castle,
			{
				{ OOT_CASTLE_STEALTH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_CASTLE_COURTYARD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_CHAMBER_OF_THE_SAGES,
		{
			OOT_CHAMBER_OF_THE_SAGES, (uint8_t)OoTRegions::Castle,
			{
				{ OOT_END_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_SAGES_CHANBER_END_FROM_GANON2_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_CUTSCENE_MAP,
		{
			OOT_CUTSCENE_MAP, (uint8_t)OoTRegions::Castle,
			{
				{ OOT_HYRULE_END_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_END_FROM_SAGES_CHANBER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_DAMPE_HOUSE,
		{
			OOT_DAMPE_HOUSE, (uint8_t)OoTRegions::Graveyard,
			{
				{ OOT_HOUSE_DAMPE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_DEATH_MOUNTAIN_CRATER,
		{
			OOT_DEATH_MOUNTAIN_CRATER, (uint8_t)OoTRegions::Death_Mountain_Crater,
			{
				{ OOT_GROTTO_EXIT_GENERIC_DMC, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_SCRUBS3_DMC, { UINT32_MAX, UINT32_MAX } },
				{ OOT_DEATH_MOUNTAIN_CRATER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_CRATER_FROM_GORON_CITY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_DEATH_CRATER_FROM_TEMPLE_FIRE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_DEATH_CRATER_FROM_FAIRY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WARP_SONG_CRATER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_DEATH_MOUNTAIN_TRAIL,
		{
			OOT_DEATH_MOUNTAIN_TRAIL, (uint8_t)OoTRegions::Death_Mountain_Trail,
			{
				{ OOT_GROTTO_EXIT_GENERIC_DMT, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_TRAIL_COW, { UINT32_MAX, UINT32_MAX } },
				{ OOT_DEATH_MOUNTAIN_FROM_KAKARIKO_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_DEATH_MOUNTAIN_FROM_GORON_CITY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_TRAIL_SUMMIT_FROM_CRATER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MOUNTAIN_TRAIL_FROM_DODONGO_CAVERN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_DEATH_MOUNTAIN_FROM_FAIRY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_DMT_OWL_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_DEKU_TREE,
		{
			OOT_DEKU_TREE, (uint8_t)OoTRegions::Kokiri_Forest,
			{
				{ OOT_DEKU_TREE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_DEKU_TREE_TO_BOSS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_DESERT_COLOSSUS,
		{
			OOT_DESERT_COLOSSUS, (uint8_t)OoTRegions::Desert_Colossus,
			{
				{ OOT_GROTTO_EXIT_SCRUBS2_COLOSSUS, { UINT32_MAX, UINT32_MAX } },
				{ OOT_COLOSSUS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_DESERT_COLOSSUS_FROM_TEMPLE_SPIRIT_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WARP_SONG_DESERT_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_DESERT_COLOSSUS_FROM_FAIRY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_DESERT_FROM_MIROR_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_DESERT_FROM_GAUNTLET_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_DODONGO_CAVERN,
		{
			OOT_DODONGO_CAVERN, (uint8_t)OoTRegions::Death_Mountain_Trail,
			{
				{ OOT_DODONGO_CAVERN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_DODONGO_CAVERN_TO_BOSS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_FAIRY_GERUDO_FORTRESS,
		{
			OOT_FAIRY_GERUDO_FORTRESS, (uint8_t)OoTRegions::Gerudo_Fortress,
			{
				{ OOT_GROTTO_FAIRY_FORTRESS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_FAIRY_HYRULE,
		{
			OOT_FAIRY_HYRULE, (uint8_t)OoTRegions::Hyrule,
			{
				{ OOT_GROTTO_FAIRY_HF_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_FAIRY_SACRED_MEADOW,
		{
			OOT_FAIRY_SACRED_MEADOW, (uint8_t)OoTRegions::Sacred_Forest_Meadow,
			{
				{ OOT_GROTTO_FAIRY_SFM_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_FAIRY_ZORA_DOMAIN,
		{
			OOT_FAIRY_ZORA_DOMAIN, (uint8_t)OoTRegions::Zora_Domain,
			{
				{ OOT_GROTTO_FAIRY_DOMAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_FAIRY_ZORA_RIVER,
		{
			OOT_FAIRY_ZORA_RIVER, (uint8_t)OoTRegions::Zora_River,
			{
				{ OOT_GROTTO_FAIRY_RIVER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_FISHING_POND,
		{
			OOT_FISHING_POND, (uint8_t)OoTRegions::Lake_Hylia,
			{
				{ OOT_FISHING_POND_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GANON_BATTLE_ARENA,
		{
			OOT_GANON_BATTLE_ARENA, (uint8_t)OoTRegions::Castle,
			{
				{ OOT_SAGES_CHAMBER_END_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_BOSS_GANON2_FROM_GANONDORF_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GANON_CASTLE_EXTERIOR,
		{
			OOT_GANON_CASTLE_EXTERIOR, (uint8_t)OoTRegions::Castle,
			{
				{ OOT_GANON_CASTLE_EXTERIOR_FROM_CASTLE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_OUTSIDE_GANON_FROM_FAIRY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GANON_CASTLE_EXTERIOR_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GANON_TOWER,
		{
			OOT_GANON_TOWER, (uint8_t)OoTRegions::Castle,
			{
				{ OOT_GANON_TOWER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GANONDORF_CUTSCENE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GERUDO_FORTRESS,
		{
			OOT_GERUDO_FORTRESS, (uint8_t)OoTRegions::Gerudo_Fortress,
			{
				{ OOT_GROTTO_EXIT_FAIRY_FORTRESS, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GERUDO_FORTRESS_FROM_VALLEY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FORTRESS_FROM_HIDEOUT_LEFT_JAIL_1, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FORTRESS_FROM_HIDEOUT_RIGHT_JAIL_1, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FORTRESS_FROM_HIDEOUT_KITCHEN_BOTTOM, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FORTRESS_FROM_HIDEOUT_KITCHEN_BOTTOM_TO_TOP, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FORTRESS_FROM_HIDEOUT_JAIL_3_BOTTOM, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FORTRESS_FROM_HIDEOUT_JAIL_3_TOP, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FORTRESS_FROM_HIDEOUT_JAIL_2_BOTTOM, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FORTRESS_FROM_HIDEOUT_JAIL_2_TOP, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FORTRESS_FROM_HIDEOUT_KITCHEN_TOP_RIGHT, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FORTRESS_FROM_HIDEOUT_KITCHEN_TOP_LEFT, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FORTRESS_FROM_HIDEOUT_BREAKOUT, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FORTRESS_FROM_HIDEOUT_BREAKOUT_JAIL, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FORTRESS_FROM_HIDEOUT_JAIL_4, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GERUDO_FORTRESS_FROM_GERUDO_TRAINING_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FORTRESS_FROM_WASTELAND_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GERUDO_FORTRESS_CAUGHT_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GERUDO_FORTRESS_JAIL_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GERUDO_TRAINING_GROUND,
		{
			OOT_GERUDO_TRAINING_GROUND, (uint8_t)OoTRegions::Gerudo_Fortress,
			{
				{ OOT_GERUDO_TRAINING_GROUNDS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WALLMASTER_GTG_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GERUDO_VALLEY,
		{
			OOT_GERUDO_VALLEY, (uint8_t)OoTRegions::Gerudo_Valley,
			{
				{ OOT_GROTTO_EXIT_SCRUBS2_VALLEY, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_OCTOROK, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GERUDO_VALLEY_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GERUDO_FORTRESS_CAUGHT_NO_HOOK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GERUDO_VALLEY_CAUGHT_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_VALLEY_WATERFALLS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_VALLEY_FROM_GERUDO_FORTRESS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GERUDO_VALLEY_FROM_TENT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GORON_CITY,
		{
			OOT_GORON_CITY, (uint8_t)OoTRegions::Goron_City,
			{
				{ OOT_GROTTO_EXIT_SCRUBS3_GORON_CITY, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GORON_CITY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GORON_CITY_FROM_CRATER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GORON_CITY_FROM_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GORON_CITY_FROM_LOST_WOODS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GORON_SHOP,
		{
			OOT_GORON_SHOP, (uint8_t)OoTRegions::Goron_City,
			{
				{ OOT_SHOP_GORON_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GRANNY_POTION_SHOP,
		{
			OOT_GRANNY_POTION_SHOP, (uint8_t)OoTRegions::Kakariko,
			{
				{ OOT_SHOP_GRANNY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GRAVEYARD,
		{
			OOT_GRAVEYARD, (uint8_t)OoTRegions::Graveyard,
			{
				{ OOT_GRAVEYARD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GRAVEYARD_FROM_TEMPLE_SHADOW_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GRAVEYARD_FROM_DAMPE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GRAVE_EXIT_DAMPE, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GRAVE_EXIT_SHIELD, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GRAVE_EXIT_REDEAD, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GRAVE_EXIT_ROYAL, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WARP_SONG_GRAVE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GREAT_FAIRY_MAGIC,
		{
			OOT_GREAT_FAIRY_MAGIC, (uint8_t)OoTRegions::Death_Mountain_Trail,
			{
				{ OOT_FAIRY_MAGIC_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GREAT_FAIRY_FARORE,
		{
			OOT_GREAT_FAIRY_FARORE, (uint8_t)OoTRegions::Zora_Fountain,
			{
				{ OOT_FAIRY_FARORE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GREAT_FAIRY_MAGIC2,
		{
			OOT_GREAT_FAIRY_MAGIC2, (uint8_t)OoTRegions::Death_Mountain_Crater,
			{
				{ OOT_FAIRY_MAGIC2_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GREAT_FAIRY_DEFENSE,
		{
			OOT_GREAT_FAIRY_DEFENSE, (uint8_t)OoTRegions::Castle,
			{
				{ OOT_FAIRY_DEFENSE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GREAT_FAIRY_CASTLE,
		{
			OOT_GREAT_FAIRY_CASTLE, (uint8_t)OoTRegions::Castle,
			{
				{ OOT_FAIRY_DIN_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GREAT_FAIRY_NAYRU,
		{
			OOT_GREAT_FAIRY_NAYRU, (uint8_t)OoTRegions::Desert_Colossus,
			{
				{ OOT_FAIRY_NAYRU_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_CASTLE_STORMS,
		{
			OOT_GROTTO_CASTLE_STORMS, (uint8_t)OoTRegions::Castle,
			{
				{ OOT_GROTTO_CASTLE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_DEATH_CRATER_GENERIC,
		{
			OOT_GROTTO_DEATH_CRATER_GENERIC, (uint8_t)OoTRegions::Death_Mountain_Crater,
			{
				{ OOT_GROTTO_GENERIC_DMC_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_DEATH_CRATER_SCRUBS,
		{
			OOT_GROTTO_DEATH_CRATER_SCRUBS, (uint8_t)OoTRegions::Death_Mountain_Crater,
			{
				{ OOT_GROTTO_SCRUBS3_DMC_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_DEATH_TRIAL_COW,
		{
			OOT_GROTTO_DEATH_TRIAL_COW, (uint8_t)OoTRegions::Death_Mountain_Trail,
			{
				{ OOT_GROTTO_TRAIL_COW_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_DEATH_TRIAL_STORMS,
		{
			OOT_GROTTO_DEATH_TRIAL_STORMS, (uint8_t)OoTRegions::Death_Mountain_Trail,
			{
				{ OOT_GROTTO_GENERIC_DMT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_DESERT_SCRUBS,
		{
			OOT_GROTTO_DESERT_SCRUBS, (uint8_t)OoTRegions::Desert_Colossus,
			{
				{ OOT_GROTTO_SCRUBS2_COLOSSUS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_GORON_CITY_SCRUBS,
		{
			OOT_GROTTO_GORON_CITY_SCRUBS, (uint8_t)OoTRegions::Goron_City,
			{
				{ OOT_GROTTO_SCRUBS3_GORON_CITY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_HYRULE_GERUDO,
		{
			OOT_GROTTO_HYRULE_GERUDO, (uint8_t)OoTRegions::Hyrule,
			{
				{ OOT_GROTTO_FIELD_COW_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_HYRULE_KAKARIKO,
		{
			OOT_GROTTO_HYRULE_KAKARIKO, (uint8_t)OoTRegions::Hyrule,
			{
				{ OOT_GROTTO_FIELD_TREE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_HYRULE_MARKET,
		{
			OOT_GROTTO_HYRULE_MARKET, (uint8_t)OoTRegions::Hyrule,
			{
				{ OOT_GROTTO_GENERIC_HF_MARKET_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_HYRULE_OPEN,
		{
			OOT_GROTTO_HYRULE_OPEN, (uint8_t)OoTRegions::Hyrule,
			{
				{ OOT_GROTTO_GENERIC_HF_OPEN_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_HYRULE_SCRUBS,
		{
			OOT_GROTTO_HYRULE_SCRUBS, (uint8_t)OoTRegions::Hyrule,
			{
				{ OOT_GROTTO_SCRUB_HEART_PIECE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_HYRULE_SE,
		{
			OOT_GROTTO_HYRULE_SE, (uint8_t)OoTRegions::Hyrule,
			{
				{ OOT_GROTTO_GENERIC_HF_SOUTHEAST_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_HYRULE_TEKTITE,
		{
			OOT_GROTTO_HYRULE_TEKTITE, (uint8_t)OoTRegions::Hyrule,
			{
				{ OOT_GROTTO_TEKTITE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_KAKARIKO_OPEN,
		{
			OOT_GROTTO_KAKARIKO_OPEN, (uint8_t)OoTRegions::Kakariko,
			{
				{ OOT_GROTTO_GENERIC_KAKARIKO_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_KAKARIKO_REDEAD,
		{
			OOT_GROTTO_KAKARIKO_REDEAD, (uint8_t)OoTRegions::Kakariko,
			{
				{ OOT_GROTTO_REDEAD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_KOKIRI_FOREST_STORMS,
		{
			OOT_GROTTO_KOKIRI_FOREST_STORMS, (uint8_t)OoTRegions::Kokiri_Forest,
			{
				{ OOT_GROTTO_GENERIC_KOKIRI_FOREST_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_LAKE_HYLIA_SCRUBS,
		{
			OOT_GROTTO_LAKE_HYLIA_SCRUBS, (uint8_t)OoTRegions::Lake_Hylia,
			{
				{ OOT_GROTTO_SCRUBS3_LAKE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_LON_LON_SCRUBS,
		{
			OOT_GROTTO_LON_LON_SCRUBS, (uint8_t)OoTRegions::Lon_Lon_Ranch,
			{
				{ OOT_GROTTO_SCRUBS3_RANCH_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_LOST_WOODS_GENERIC,
		{
			OOT_GROTTO_LOST_WOODS_GENERIC, (uint8_t)OoTRegions::Lost_Woods,
			{
				{ OOT_GROTTO_GENERIC_LOST_WOODS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_LOST_WOODS_SCRUB_UPGRADE,
		{
			OOT_GROTTO_LOST_WOODS_SCRUB_UPGRADE, (uint8_t)OoTRegions::Lost_Woods,
			{
				{ OOT_GROTTO_SCRUB_UPGRADE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_LOST_WOODS_THEATER,
		{
			OOT_GROTTO_LOST_WOODS_THEATER, (uint8_t)OoTRegions::Lost_Woods,
			{
				{ OOT_GROTTO_DEKU_THEATER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_SACRED_MEADOW_STORMS,
		{
			OOT_GROTTO_SACRED_MEADOW_STORMS, (uint8_t)OoTRegions::Sacred_Forest_Meadow,
			{
				{ OOT_GROTTO_SCRUBS2_SFM_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_SACRED_MEADOW_WOLFOS,
		{
			OOT_GROTTO_SACRED_MEADOW_WOLFOS, (uint8_t)OoTRegions::Sacred_Forest_Meadow,
			{
				{ OOT_GROTTO_WOLFOS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_VALLEY_OCTOROK,
		{
			OOT_GROTTO_VALLEY_OCTOROK, (uint8_t)OoTRegions::Gerudo_Valley,
			{
				{ OOT_GROTTO_OCTOROK_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_VALLEY_STORMS,
		{
			OOT_GROTTO_VALLEY_STORMS, (uint8_t)OoTRegions::Gerudo_Valley,
			{
				{ OOT_GROTTO_SCRUBS2_VALLEY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_ZORA_RIVER_GENERIC,
		{
			OOT_GROTTO_ZORA_RIVER_GENERIC, (uint8_t)OoTRegions::Zora_River,
			{
				{ OOT_GROTTO_GENERIC_RIVER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_ZORA_RIVER_STORMS,
		{
			OOT_GROTTO_ZORA_RIVER_STORMS, (uint8_t)OoTRegions::Zora_River,
			{
				{ OOT_GROTTO_SCRUBS2_RIVER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTOS,
		{
			OOT_GROTTOS, (uint8_t)OoTRegions::None,
			{
				{ OOT_GROTTO_TYPE_GENERIC_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_TYPE_FAIRY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_TYPE_SCRUB3_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_TYPE_SCRUB2_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_INTERNAL_EXIT_GROTTO_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GUARD_HOUSE,
		{
			OOT_GUARD_HOUSE, (uint8_t)OoTRegions::Market,
			{
				{ OOT_HOUSE_POTS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_HAPPY_MASK_SHOP,
		{
			OOT_HAPPY_MASK_SHOP, (uint8_t)OoTRegions::Market,
			{
				{ OOT_SHOP_MASKS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_HAUNTED_WASTELAND,
		{
			OOT_HAUNTED_WASTELAND, (uint8_t)OoTRegions::Desert_Colossus,
			{
				{ OOT_WASTELAND_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WASTELAND_FROM_COLOSSUS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_HOUSE_OF_SKULLTULA,
		{
			OOT_HOUSE_OF_SKULLTULA, (uint8_t)OoTRegions::Kakariko,
			{
				{ OOT_HOUSE_SKULLTULA_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_HYRULE_CASTLE,
		{
			OOT_HYRULE_CASTLE, (uint8_t)OoTRegions::Castle,
			{
				{ OOT_GROTTO_EXIT_CASTLE, { UINT32_MAX, UINT32_MAX } },
				{ OOT_HYRULE_CASTLE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_CASTLE_STEALTH_FROM_COURTYARD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_HYRULE_CASTLE_FROM_FAIRY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_CASTLE_CAUGHT_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_CASTLE_GATE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_HYRULE_FIELD,
		{
			OOT_HYRULE_FIELD, (uint8_t)OoTRegions::Hyrule,
			{
				{ OOT_HYRULE_END_FROM_END_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_GENERIC_HF_SOUTHEAST, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_GENERIC_HF_OPEN, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_GENERIC_HF_MARKET, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_FAIRY_HF, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_SCRUB_HEART_PIECE, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_TEKTITE, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_FIELD_COW, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_FIELD_TREE, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FIELD_FROM_KAKARIKO_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FIELD_FROM_ZORA_RIVER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FIELD_FROM_LOST_WOODS_BRIDGE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FIELD_FROM_LAKE_HYLIA_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FIELD_FROM_GERUDO_VALLEY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FIELD_FROM_LON_LON_RANCH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FIELD_FROM_MARKET_ENTRANCE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FIELD_OWL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FIELD_FROM_LON_LON_EPONA_JUMP_MIDDLE, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FIELD_FROM_LON_LON_EPONA_JUMP_RIGHT, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FIELD_FROM_LON_LON_EPONA_JUMP_LEFT, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FIELD_FROM_ZORA_RIVER_WATER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_ICE_CAVERN,
		{
			OOT_ICE_CAVERN, (uint8_t)OoTRegions::Zora_Fountain,
			{
				{ OOT_ICE_CAVERN_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_IMPA_HOUSE,
		{
			OOT_IMPA_HOUSE, (uint8_t)OoTRegions::Kakariko,
			{
				{ OOT_HOUSE_IMPA_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_HOUSE_IMPA_BACK_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_INSIDE_GANON_CASTLE,
		{
			OOT_INSIDE_GANON_CASTLE, (uint8_t)OoTRegions::Castle,
			{
				{ OOT_GANON_CASTLE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GANON_CASTLE_FROM_TOWER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WALLMASTER_GANON_SPIRIT_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WALLMASTER_GANON_LIGHT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_INSIDE_JABU_JABU,
		{
			OOT_INSIDE_JABU_JABU, (uint8_t)OoTRegions::Zora_Fountain,
			{
				{ OOT_JABU_JABU_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_JABU_JABU_TO_BOSS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_KAKARIKO_POTION_SHOP,
		{
			OOT_KAKARIKO_POTION_SHOP, (uint8_t)OoTRegions::Kakariko,
			{
				{ OOT_SHOP_POTION_KAKARIKO_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_SHOP_POTION_KAKARIKO_BACK_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_KAKARIKO_VILLAGE,
		{
			OOT_KAKARIKO_VILLAGE, (uint8_t)OoTRegions::Kakariko,
			{
				{ OOT_KAKARIKO_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_GENERIC_KAKARIKO, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_REDEAD, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KAKARIKO_FROM_DEATH_MOUNTAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KAKARIKO_FROM_GRAVEYARD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KAKARIKO_FROM_BAZAAR_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KAKARIKO_FROM_BOTTOM_OF_THE_WELL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KAKARIKO_FROM_IMPA_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KAKARIKO_FROM_CARPENTER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KAKARIKO_FROM_GRANNY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KAKARIKO_FROM_WINDMILL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KAKARIKO_FROM_SHOP_POTION_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KAKARIKO_FROM_ARCHERY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KAKARIKO_FROM_SKULLTULA_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KAKARIKO_FROM_SHOP_POTION_BACK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_VILLAGE_OWL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KAKARIKO_FROM_IMPA_BACK_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_KOKIRI_FOREST,
		{
			OOT_KOKIRI_FOREST, (uint8_t)OoTRegions::Kokiri_Forest,
			{
				{ OOT_KOKIRI_END_FROM_ZORA_DOMAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_GENERIC_KOKIRI_FOREST, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KOKIRI_FOREST_FROM_DEKU_TREE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FOREST_FROM_LOST_WOODS_BRIDGE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KOKIRI_FOREST_FROM_LINK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KOKIRI_FOREST_FROM_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KOKIRI_FOREST_FROM_KNOW_IT_ALL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KOKIRI_FOREST_FROM_LOST_WOODS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KOKIRI_FOREST_FROM_TWINS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KOKIRI_FOREST_FROM_MIDO_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KOKIRI_FOREST_FROM_SARIA_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WARP_BOSS_DEKU_TREE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_KOKIRI_KNOW_IT_ALL,
		{
			OOT_KOKIRI_KNOW_IT_ALL, (uint8_t)OoTRegions::Kokiri_Forest,
			{
				{ OOT_HOUSE_KNOW_IT_ALL_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_KOKIRI_MIDO,
		{
			OOT_KOKIRI_MIDO, (uint8_t)OoTRegions::Kokiri_Forest,
			{
				{ OOT_HOUSE_MIDO_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_KOKIRI_SARIA,
		{
			OOT_KOKIRI_SARIA, (uint8_t)OoTRegions::Kokiri_Forest,
			{
				{ OOT_HOUSE_SARIA_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_KOKIRI_SHOP,
		{
			OOT_KOKIRI_SHOP, (uint8_t)OoTRegions::Kokiri_Forest,
			{
				{ OOT_KOKIRI_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_KOKIRI_TWINS,
		{
			OOT_KOKIRI_TWINS, (uint8_t)OoTRegions::Kokiri_Forest,
			{
				{ OOT_HOUSE_TWINS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_LABORATORY,
		{
			OOT_LABORATORY, (uint8_t)OoTRegions::Lake_Hylia,
			{
				{ OOT_LABORATORY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_LAIR_BARINADE,
		{
			OOT_LAIR_BARINADE, (uint8_t)OoTRegions::Zora_Fountain,
			{
				{ OOT_BOSS_JABU_JABU_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_BOSS_JABU_JABU_WARP_OUT, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_LAIR_BONGO_BONGO,
		{
			OOT_LAIR_BONGO_BONGO, (uint8_t)OoTRegions::Graveyard,
			{
				{ OOT_BOSS_TEMPLE_SHADOW_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_BOSS_SHADOW_TEMPLE_WARP_OUT, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_LAIR_GANONDORF,
		{
			OOT_LAIR_GANONDORF, (uint8_t)OoTRegions::Castle,
			{
				{ OOT_BOSS_GANONDORF_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GANONDORF_CUTSCENE_FROM_GANON_TOWER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_LAIR_GOHMA,
		{
			OOT_LAIR_GOHMA, (uint8_t)OoTRegions::Kokiri_Forest,
			{
				{ OOT_BOSS_DEKU_TREE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_BOSS_DEKU_TREE_WARP_OUT, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_LAIR_KING_DODONGO,
		{
			OOT_LAIR_KING_DODONGO, (uint8_t)OoTRegions::Death_Mountain_Trail,
			{
				{ OOT_BOSS_DODONGO_CAVERN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_BOSS_DODONGO_CAVERN_WARP_OUT, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_LAIR_MORPHA,
		{
			OOT_LAIR_MORPHA, (uint8_t)OoTRegions::Lake_Hylia,
			{
				{ OOT_BOSS_TEMPLE_WATER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_BOSS_WATER_TEMPLE_WARP_OUT, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_LAIR_PHANTOM_GANON,
		{
			OOT_LAIR_PHANTOM_GANON, (uint8_t)OoTRegions::Sacred_Forest_Meadow,
			{
				{ OOT_BOSS_TEMPLE_FOREST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_BOSS_FOREST_TEMPLE_WARP_OUT, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_LAIR_TWINROVA,
		{
			OOT_LAIR_TWINROVA, (uint8_t)OoTRegions::Desert_Colossus,
			{
				{ OOT_BOSS_TEMPLE_SPIRIT_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_BOSS_SPIRIT_TEMPLE_WARP_OUT, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_LAIR_VOLVAGIA,
		{
			OOT_LAIR_VOLVAGIA, (uint8_t)OoTRegions::Death_Mountain_Crater,
			{
				{ OOT_BOSS_TEMPLE_FIRE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_BOSS_FIRE_TEMPLE_WARP_OUT, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_LAKE_HYLIA,
		{
			OOT_LAKE_HYLIA, (uint8_t)OoTRegions::Lake_Hylia,
			{
				{ OOT_LAKE_HYLIA_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_SCRUBS3_LAKE, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LAKE_HYLIA_FROM_VALLEY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LAKE_HYLIA_FROM_TEMPLE_WATER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LAKE_OWL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LAKE_HYLIA_FROM_FISHING_POND_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LAKE_HYLIA_FROM_LABORATORY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LAKE_HYLIA_FROM_ZORA_DOMAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WARP_SONG_LAKE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_LINK_HOUSE,
		{
			OOT_LINK_HOUSE, (uint8_t)OoTRegions::Kokiri_Forest,
			{
				{ OOT_SPAWN_CHILD, { UINT32_MAX, UINT32_MAX } },
				{ OOT_HOUSE_LINK_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_LON_LON_RANCH,
		{
			OOT_LON_LON_RANCH, (uint8_t)OoTRegions::Lon_Lon_Ranch,
			{
				{ OOT_GROTTO_EXIT_SCRUBS3_RANCH, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LON_LON_RANCH_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LON_LON_EPONA_JUMP_MIDDLE, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LON_LON_EPONA_JUMP_RIGHT, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LON_LON_EPONA_JUMP_LEFT, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LON_LON_RANCH_FROM_HOUSE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LON_LON_RANCH_FROM_STABLES_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LON_LON_RANCH_FROM_SILO_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_LOST_WOODS,
		{
			OOT_LOST_WOODS, (uint8_t)OoTRegions::Lost_Woods,
			{
				{ OOT_GROTTO_EXIT_GENERIC_LOST_WOODS, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_SCRUB_UPGRADE, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_DEKU_THEATER, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LOST_WOODS_FROM_KOKIRI_FOREST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LOST_WOODS_FROM_MEADOW_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LOST_WOODS_FROM_LOST_WOODS_EAST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LOST_WOODS_FROM_LOST_WOODS_SOUTH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LOST_WOODS_FROM_LOST_WOODS_WEST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LOST_WOODS_FROM_GORON_CITY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LOST_WOODS_FROM_ZORA_RIVER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LOST_WOODS_BRIDGE_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LOST_WOODS_BRIDGE_FROM_FOREST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LOST_WOODS_FROM_LOST_WOODS_NORTH_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_MARKET,
		{
			OOT_MARKET, (uint8_t)OoTRegions::Market,
			{
				{ OOT_MARKET_FROM_BACK_ALLEY_SHOOTING_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_FROM_BACK_ALLEY_TREASURE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_FROM_MARKET_ENTRANCE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_FROM_ARCHERY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_FROM_MASK_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_FROM_TREASURE_GAME_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_FROM_CASTLE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_FROM_TEMPLE_OF_TIME_ENTRYWAY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_FROM_POTION_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_FROM_BAZAAR_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_FROM_BOWLING_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_ADULT_FROM_GANON_CASTLE_EXTERIOR_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_MARKET_ENTRANCE,
		{
			OOT_MARKET_ENTRANCE, (uint8_t)OoTRegions::Market,
			{
				{ OOT_MARKET_ENTRANCE_FROM_MARKET_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_ENTRANCE_FROM_POTS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_ENTRANCE_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_MARKET_POTION_SHOP,
		{
			OOT_MARKET_POTION_SHOP, (uint8_t)OoTRegions::Market,
			{
				{ OOT_MARKET_POTION_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_RANCH_HOUSE_SILO,
		{
			OOT_RANCH_HOUSE_SILO, (uint8_t)OoTRegions::Lon_Lon_Ranch,
			{
				{ OOT_HOUSE_LON_LON_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_SACRED_FOREST_MEADOW,
		{
			OOT_SACRED_FOREST_MEADOW, (uint8_t)OoTRegions::Sacred_Forest_Meadow,
			{
				{ OOT_SACRED_FOREST_MEADOW_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_FAIRY_SFM, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_SCRUBS2_SFM, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_WOLFOS, { UINT32_MAX, UINT32_MAX } },
				{ OOT_SACRED_MEADOW_FROM_TEMPLE_FOREST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WARP_SONG_MEADOW_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_KAKARIKO_SHOOTING,
		{
			OOT_KAKARIKO_SHOOTING, (uint8_t)OoTRegions::Kakariko,
			{
				{ OOT_ADULT_ARCHERY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_MARKET_SHOOTING,
		{
			OOT_MARKET_SHOOTING, (uint8_t)OoTRegions::Market,
			{
				{ OOT_CHILD_ARCHERY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_SILO,
		{
			OOT_SILO, (uint8_t)OoTRegions::Lon_Lon_Ranch,
			{
				{ OOT_SILO_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_SONGS,
		{
			OOT_SONGS, (uint8_t)OoTRegions::Songs,
			{
				{ OOT_MINUET_OF_FOREST_SONG, { UINT32_MAX, UINT32_MAX } },
				{ OOT_BOLERO_OF_FIRE_SONG, { UINT32_MAX, UINT32_MAX } },
				{ OOT_SERENADE_OF_WATER_SONG, { UINT32_MAX, UINT32_MAX } },
				{ OOT_REQUIEM_OF_SPIRIT_SONG, { UINT32_MAX, UINT32_MAX } },
				{ OOT_NOCTURNE_OF_SHADOW_SONG, { UINT32_MAX, UINT32_MAX } },
				{ OOT_PRELUDE_OF_LIGHT_SONG, { UINT32_MAX, UINT32_MAX } },
				{ WARP_LOADING, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_STABLE,
		{
			OOT_STABLE, (uint8_t)OoTRegions::Lon_Lon_Ranch,
			{
				{ OOT_STABLES_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_TEMPLE_FIRE,
		{
			OOT_TEMPLE_FIRE, (uint8_t)OoTRegions::Death_Mountain_Crater,
			{
				{ OOT_TEMPLE_FIRE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_TEMPLE_FIRE_TO_BOSS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_TEMPLE_FOREST,
		{
			OOT_TEMPLE_FOREST, (uint8_t)OoTRegions::Sacred_Forest_Meadow,
			{
				{ OOT_TEMPLE_FOREST_TO_BOSS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_TEMPLE_FOREST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WALLMASTER_FOREST_CORRIDOR_WEST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WALLMASTER_FOREST_CORRIDOR_EAST_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_TEMPLE_OF_TIME,
		{
			OOT_TEMPLE_OF_TIME, (uint8_t)OoTRegions::Market,
			{
				{ OOT_TEMPLE_OF_TIME_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_TEMPLE_OF_TIME_MASTER_SWORD_CS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WARP_SONG_TEMPLE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_SPAWN_ADULT, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_TEMPLE_OF_TIME_ENTRYWAY,
		{
			OOT_TEMPLE_OF_TIME_ENTRYWAY, (uint8_t)OoTRegions::Market,
			{
				{ OOT_TEMPLE_OF_TIME_ENTRYWAY_FROM_MARKET_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_TEMPLE_OF_TIME_ENTRYWAY_FROM_TEMPLE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_TEMPLE_SHADOW,
		{
			OOT_TEMPLE_SHADOW, (uint8_t)OoTRegions::Graveyard,
			{
				{ OOT_TEMPLE_SHADOW_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_SHADOW_TEMPLE_FROM_LAIR_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_TEMPLE_SHADOW_TO_BOSS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WALLMASTER_SHADOW_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_TEMPLE_SPIRIT,
		{
			OOT_TEMPLE_SPIRIT, (uint8_t)OoTRegions::Desert_Colossus,
			{
				{ OOT_TEMPLE_SPIRIT_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_TEMPLE_SPIRIT_TO_BOSS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WALLMASTER_SPIRIT_CHILD_RUPEES_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WALLMASTER_SPIRIT_ADULT_CLIMB_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WALLMASTER_SPIRIT_CHILD_SUN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WALLMASTER_SPIRIT_STATUE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_SPIRIT_TEMPLE_DESERT_MIROR_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_SPIRIT_TEMPLE_DESERT_GAUNTLET_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_TEMPLE_WATER,
		{
			OOT_TEMPLE_WATER, (uint8_t)OoTRegions::Lake_Hylia,
			{
				{ OOT_TEMPLE_WATER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_TEMPLE_WATER_TO_BOSS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_THIEVES_HIDEOUT,
		{
			OOT_THIEVES_HIDEOUT, (uint8_t)OoTRegions::Gerudo_Fortress,
			{
				{ OOT_HIDEOUT_LEFT_JAIL_1_FROM_FORTRESS, { UINT32_MAX, UINT32_MAX } },
				{ OOT_HIDEOUT_RIGHT_JAIL_1_FROM_FORTRESS, { UINT32_MAX, UINT32_MAX } },
				{ OOT_HIDEOUT_KITCHEN_BOTTOM_FROM_FORTRESS, { UINT32_MAX, UINT32_MAX } },
				{ OOT_HIDEOUT_KITCHEN_BOTTOM_TO_TOP_FROM_FORTRESS, { UINT32_MAX, UINT32_MAX } },
				{ OOT_HIDEOUT_JAIL_3_BOTTOM_FROM_FORTRESS, { UINT32_MAX, UINT32_MAX } },
				{ OOT_HIDEOUT_JAIL_3_TOP_FROM_FORTRESS, { UINT32_MAX, UINT32_MAX } },
				{ OOT_HIDEOUT_JAIL_2_BOTTOM_FROM_FORTRESS, { UINT32_MAX, UINT32_MAX } },
				{ OOT_HIDEOUT_JAIL_2_TOP_FROM_FORTRESS, { UINT32_MAX, UINT32_MAX } },
				{ OOT_HIDEOUT_KITCHEN_TOP_RIGHT_FROM_FORTRESS, { UINT32_MAX, UINT32_MAX } },
				{ OOT_HIDEOUT_KITCHEN_TOP_LEFT_FROM_FORTRESS, { UINT32_MAX, UINT32_MAX } },
				{ OOT_HIDEOUT_BREAKOUT_FROM_FORTRESS, { UINT32_MAX, UINT32_MAX } },
				{ OOT_HIDEOUT_BREAKOUT_FROM_FORTRESS_JAIL, { UINT32_MAX, UINT32_MAX } },
				{ OOT_HIDEOUT_JAIL_4_FROM_FORTRESS, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_TOMB_DAMPE_WINDMILL,
		{
			OOT_TOMB_DAMPE_WINDMILL, (uint8_t)OoTRegions::Graveyard,
			{
				{ OOT_GRAVE_DAMPE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_TOMB_FAIRY,
		{
			OOT_TOMB_FAIRY, (uint8_t)OoTRegions::Graveyard,
			{
				{ OOT_GRAVE_SHIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_TOMB_REDEAD,
		{
			OOT_TOMB_REDEAD, (uint8_t)OoTRegions::Graveyard,
			{
				{ OOT_GRAVE_REDEAD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_TOMB_ROYAL,
		{
			OOT_TOMB_ROYAL, (uint8_t)OoTRegions::Graveyard,
			{
				{ OOT_GRAVE_ROYAL_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_TREASURE_SHOP,
		{
			OOT_TREASURE_SHOP, (uint8_t)OoTRegions::Market,
			{
				{ OOT_TREASURE_GAME_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_WINDMILL,
		{
			OOT_WINDMILL, (uint8_t)OoTRegions::Kakariko,
			{
				{ OOT_WINDMILL_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_ZORA_DOMAIN,
		{
			OOT_ZORA_DOMAIN, (uint8_t)OoTRegions::Zora_Domain,
			{
				{ OOT_KOKIRI_END_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_ZORA_DOMAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_FAIRY_DOMAIN, { UINT32_MAX, UINT32_MAX } },
				{ OOT_DOMAIN_FROM_FOUNTAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_ZORA_DOMAIN_FROM_LAKE_HYLIA_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_ZORA_DOMAIN_FROM_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_ZORA_FOUNTAIN,
		{
			OOT_ZORA_FOUNTAIN, (uint8_t)OoTRegions::Zora_Fountain,
			{
				{ OOT_ZORA_FOUNTAIN_FROM_JABU_JABU_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FOUNTAIN_ZORA_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_ZORA_FOUNTAIN_FROM_FAIRY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_ZORA_FOUNTAIN_FROM_ICE_CAVERN_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_ZORA_RIVER,
		{
			OOT_ZORA_RIVER, (uint8_t)OoTRegions::Zora_River,
			{
				{ OOT_ZORA_RIVER_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_GENERIC_RIVER, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_FAIRY_RIVER, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_SCRUBS2_RIVER, { UINT32_MAX, UINT32_MAX } },
				{ OOT_RIVER_FROM_DOMAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_ZORA_RIVER_FROM_FIELD_WATER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_ZORA_RIVER_FROM_LOST_WOODS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_ZORA_SHOP,
		{
			OOT_ZORA_SHOP, (uint8_t)OoTRegions::Zora_Domain,
			{
				{ OOT_SHOP_ZORA_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},

};
