#include "UI/SceneEntrance.h"

#pragma region OoT Scene Meta Entrance

const std::map<uint32_t, SceneEntranceMetaInf> OoTSceneEntranceMeta =
{
	{
		OOT_LINK_HOUSE,
		{
			OOT_LINK_HOUSE,
			{
				{ OOT_SPAWN_CHILD, { UINT32_MAX, UINT32_MAX } },
				{ OOT_HOUSE_LINK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ SPAWN_LOADING, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_TEMPLE_OF_TIME,
		{
			OOT_TEMPLE_OF_TIME,
			{
				{ OOT_SPAWN_ADULT, { UINT32_MAX, UINT32_MAX } },
				{ OOT_TEMPLE_OF_TIME_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WARP_SONG_TEMPLE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_TEMPLE_OF_TIME_MASTER_SWORD_CS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_LAIR_GOHMA,
		{
			OOT_LAIR_GOHMA,
			{
				{ OOT_BOSS_DEKU_TREE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_LAIR_KING_DODONGO,
		{
			OOT_LAIR_KING_DODONGO,
			{
				{ OOT_BOSS_DODONGO_CAVERN_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_LAIR_BARINADE,
		{
			OOT_LAIR_BARINADE,
			{
				{ OOT_BOSS_JABU_JABU_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_LAIR_PHANTOM_GANON,
		{
			OOT_LAIR_PHANTOM_GANON,
			{
				{ OOT_BOSS_TEMPLE_FOREST_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_LAIR_VOLVAGIA,
		{
			OOT_LAIR_VOLVAGIA,
			{
				{ OOT_BOSS_TEMPLE_FIRE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_LAIR_MORPHA,
		{
			OOT_LAIR_MORPHA,
			{
				{ OOT_BOSS_TEMPLE_WATER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_LAIR_TWINROVA,
		{
			OOT_LAIR_TWINROVA,
			{
				{ OOT_BOSS_TEMPLE_SHADOW_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_LAIR_BONGO_BONGO,
		{
			OOT_LAIR_BONGO_BONGO,
			{
				{ OOT_BOSS_TEMPLE_SPIRIT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_DEKU_TREE,
		{
			OOT_DEKU_TREE,
			{
				{ OOT_DEKU_TREE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_DODONGO_CAVERN,
		{
			OOT_DODONGO_CAVERN,
			{
				{ OOT_DODONGO_CAVERN_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_INSIDE_JABU_JABU,
		{
			OOT_INSIDE_JABU_JABU,
			{
				{ OOT_JABU_JABU_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_TEMPLE_FOREST,
		{
			OOT_TEMPLE_FOREST,
			{
				{ OOT_TEMPLE_FOREST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WALLMASTER_FOREST_CORRIDOR_WEST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WALLMASTER_FOREST_CORRIDOR_EAST_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_TEMPLE_FIRE,
		{
			OOT_TEMPLE_FIRE,
			{
				{ OOT_TEMPLE_FIRE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_TEMPLE_WATER,
		{
			OOT_TEMPLE_WATER,
			{
				{ OOT_TEMPLE_WATER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_TEMPLE_SHADOW,
		{
			OOT_TEMPLE_SHADOW,
			{
				{ OOT_TEMPLE_SHADOW_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WALLMASTER_SHADOW_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_SHADOW_TEMPLE_FROM_LAIR_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_TEMPLE_SPIRIT,
		{
			OOT_TEMPLE_SPIRIT,
			{
				{ OOT_TEMPLE_SPIRIT_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WALLMASTER_SPIRIT_CHILD_RUPEES_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WALLMASTER_SPIRIT_ADULT_CLIMB_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WALLMASTER_SPIRIT_CHILD_SUN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WALLMASTER_SPIRIT_STATUE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_BOTTOM_OF_THE_WELL,
		{
			OOT_BOTTOM_OF_THE_WELL,
			{
				{ OOT_BOTTOM_OF_THE_WELL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WALLMASTER_BOTW_MAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WALLMASTER_BOTW_BASEMENT_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WALLMASTER_BOTW_PIT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_ICE_CAVERN,
		{
			OOT_ICE_CAVERN,
			{
				{ OOT_ICE_CAVERN_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GERUDO_TRAINING_GROUND,
		{
			OOT_GERUDO_TRAINING_GROUND,
			{
				{ OOT_GERUDO_TRAINING_GROUNDS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WALLMASTER_GTG_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_INSIDE_GANON_CASTLE,
		{
			OOT_INSIDE_GANON_CASTLE,
			{
				{ OOT_GANON_CASTLE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GANON_CASTLE_FROM_TOWER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WALLMASTER_GANON_SPIRIT_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WALLMASTER_GANON_LIGHT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GANON_TOWER,
		{
			OOT_GANON_TOWER,
			{
				{ OOT_GANON_TOWER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_KOKIRI_FOREST,
		{
			OOT_KOKIRI_FOREST,
			{
				{ OOT_KOKIRI_FOREST_FROM_DEKU_TREE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KOKIRI_FOREST_FROM_LOST_WOODS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FOREST_FROM_LOST_WOODS_BRIDGE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LOST_WOODS_FROM_LOST_WOODS_NORTH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LOST_WOODS_FROM_LOST_WOODS_EAST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LOST_WOODS_FROM_LOST_WOODS_SOUTH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LOST_WOODS_FROM_LOST_WOODS_WEST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KOKIRI_FOREST_FROM_MIDO_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KOKIRI_FOREST_FROM_SARIA_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KOKIRI_FOREST_FROM_TWINS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KOKIRI_FOREST_FROM_KNOW_IT_ALL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KOKIRI_FOREST_FROM_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KOKIRI_FOREST_FROM_LINK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_GENERIC_KOKIRI_FOREST, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_DEATH_MOUNTAIN_TRAIL,
		{
			OOT_DEATH_MOUNTAIN_TRAIL,
			{
				{ OOT_MOUNTAIN_TRAIL_FROM_DODONGO_CAVERN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_DEATH_MOUNTAIN_FROM_KAKARIKO_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_DEATH_MOUNTAIN_FROM_GORON_CITY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_TRAIL_SUMMIT_FROM_CRATER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_DEATH_MOUNTAIN_FROM_FAIRY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_GENERIC_DMT, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_TRAIL_COW, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_ZORA_FOUNTAIN,
		{
			OOT_ZORA_FOUNTAIN,
			{
				{ OOT_ZORA_FOUNTAIN_FROM_JABU_JABU_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_ZORA_FOUNTAIN_FROM_ICE_CAVERN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FOUNTAIN_ZORA_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_ZORA_FOUNTAIN_FROM_FAIRY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_SACRED_FOREST_MEADOW,
		{
			OOT_SACRED_FOREST_MEADOW,
			{
				{ OOT_SACRED_MEADOW_FROM_TEMPLE_FOREST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_SACRED_FOREST_MEADOW_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WARP_SONG_MEADOW_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_FAIRY_SFM, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_SCRUBS2_SFM, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_WOLFOS, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_DEATH_MOUNTAIN_CRATER,
		{
			OOT_DEATH_MOUNTAIN_CRATER,
			{
				{ OOT_DEATH_CRATER_FROM_TEMPLE_FIRE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_CRATER_FROM_GORON_CITY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_DEATH_MOUNTAIN_CRATER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_DEATH_CRATER_FROM_FAIRY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WARP_SONG_CRATER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_GENERIC_DMC, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_SCRUBS3_DMC, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_LAKE_HYLIA,
		{
			OOT_LAKE_HYLIA,
			{
				{ OOT_LAKE_HYLIA_FROM_TEMPLE_WATER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LAKE_HYLIA_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LAKE_HYLIA_FROM_ZORA_DOMAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LAKE_HYLIA_FROM_VALLEY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LAKE_HYLIA_FROM_LABORATORY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LAKE_HYLIA_FROM_FISHING_POND_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WARP_SONG_LAKE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_SCRUBS3_LAKE, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GRAVEYARD,
		{
			OOT_GRAVEYARD,
			{
				{ OOT_GRAVEYARD_FROM_TEMPLE_SHADOW_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GRAVEYARD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GRAVEYARD_FROM_DAMPE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WARP_SONG_GRAVE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GRAVE_EXIT_SHIELD, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GRAVE_EXIT_REDEAD, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GRAVE_EXIT_ROYAL, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GRAVE_EXIT_DAMPE, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_DESERT_COLOSSUS,
		{
			OOT_DESERT_COLOSSUS,
			{
				{ OOT_DESERT_COLOSSUS_FROM_TEMPLE_SPIRIT_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_COLOSSUS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_DESERT_COLOSSUS_FROM_FAIRY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WARP_SONG_DESERT_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_SCRUBS2_COLOSSUS, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_KAKARIKO_VILLAGE,
		{
			OOT_KAKARIKO_VILLAGE,
			{
				{ OOT_KAKARIKO_FROM_BOTTOM_OF_THE_WELL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KAKARIKO_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KAKARIKO_FROM_DEATH_MOUNTAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KAKARIKO_FROM_GRAVEYARD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KAKARIKO_FROM_CARPENTER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KAKARIKO_FROM_SKULLTULA_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KAKARIKO_FROM_IMPA_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KAKARIKO_FROM_IMPA_BACK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KAKARIKO_FROM_GRANNY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KAKARIKO_FROM_WINDMILL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KAKARIKO_FROM_SHOP_POTION_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KAKARIKO_FROM_SHOP_POTION_BACK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KAKARIKO_FROM_BAZAAR_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_KAKARIKO_FROM_ARCHERY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_VILLAGE_OWL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_GENERIC_KAKARIKO, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_REDEAD, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GERUDO_FORTRESS,
		{
			OOT_GERUDO_FORTRESS,
			{
				{ OOT_GERUDO_FORTRESS_FROM_GERUDO_TRAINING_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GERUDO_FORTRESS_FROM_VALLEY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FORTRESS_FROM_WASTELAND_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_FAIRY_FORTRESS, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GERUDO_FORTRESS_CAUGHT_NO_HOOK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GERUDO_FORTRESS_CAUGHT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GANON_CASTLE_EXTERIOR,
		{
			OOT_GANON_CASTLE_EXTERIOR,
			{
				{ OOT_GANON_CASTLE_EXTERIOR_FROM_CASTLE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_OUTSIDE_GANON_FROM_FAIRY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_LOST_WOODS,
		{
			OOT_LOST_WOODS,
			{
				{ OOT_LOST_WOODS_BRIDGE_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LOST_WOODS_FROM_ZORA_RIVER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LOST_WOODS_FROM_GORON_CITY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LOST_WOODS_FROM_MEADOW_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LOST_WOODS_FROM_KOKIRI_FOREST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LOST_WOODS_BRIDGE_FROM_FOREST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_GENERIC_LOST_WOODS, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_SCRUB_UPGRADE, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_DEKU_THEATER, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_ZORA_RIVER,
		{
			OOT_ZORA_RIVER,
			{
				{ OOT_ZORA_RIVER_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_ZORA_RIVER_FROM_LOST_WOODS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_RIVER_FROM_DOMAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_GENERIC_RIVER, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_FAIRY_RIVER, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_SCRUBS2_RIVER, { UINT32_MAX, UINT32_MAX } },
				{ OOT_ZORA_RIVER_FROM_FIELD_WATER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_LON_LON_RANCH,
		{
			OOT_LON_LON_RANCH,
			{
				{ OOT_LON_LON_RANCH_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LON_LON_RANCH_FROM_HOUSE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LON_LON_RANCH_FROM_STABLES_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_LON_LON_RANCH_FROM_SILO_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_SCRUBS3_RANCH, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GERUDO_VALLEY,
		{
			OOT_GERUDO_VALLEY,
			{
				{ OOT_GERUDO_VALLEY_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_VALLEY_FROM_GERUDO_FORTRESS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GERUDO_VALLEY_FROM_TENT_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_SCRUBS2_VALLEY, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_OCTOROK, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_MARKET,
		{
			OOT_MARKET,
			{
				{ OOT_MARKET_ENTRANCE_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_FROM_MARKET_ENTRANCE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_FROM_CASTLE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_FROM_TEMPLE_OF_TIME_ENTRYWAY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_FROM_BOWLING_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_FROM_TREASURE_GAME_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_FROM_BAZAAR_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_FROM_POTION_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_FROM_ARCHERY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_FROM_MASK_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_FROM_BACK_ALLEY_TREASURE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_FROM_BACK_ALLEY_SHOOTING_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GORON_CITY,
		{
			OOT_GORON_CITY,
			{
				{ OOT_GORON_CITY_FROM_LOST_WOODS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GORON_CITY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GORON_CITY_FROM_CRATER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GORON_CITY_FROM_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_SCRUBS3_GORON_CITY, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_HYRULE_FIELD,
		{
			OOT_HYRULE_FIELD,
			{
				{ OOT_FIELD_FROM_LOST_WOODS_BRIDGE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FIELD_FROM_ZORA_RIVER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FIELD_FROM_KAKARIKO_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FIELD_FROM_LON_LON_RANCH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FIELD_FROM_LAKE_HYLIA_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FIELD_FROM_GERUDO_VALLEY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FIELD_FROM_MARKET_ENTRANCE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FIELD_OWL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_GENERIC_HF_SOUTHEAST, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_GENERIC_HF_OPEN, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_GENERIC_HF_MARKET, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_FAIRY_HF, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_SCRUB_HEART_PIECE, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_TEKTITE, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_FIELD_COW, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_FIELD_TREE, { UINT32_MAX, UINT32_MAX } },
				{ OOT_FIELD_FROM_ZORA_RIVER_WATER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_ZORA_DOMAIN,
		{
			OOT_ZORA_DOMAIN,
			{
				{ OOT_ZORA_DOMAIN_FROM_LAKE_HYLIA_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_ZORA_DOMAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_DOMAIN_FROM_FOUNTAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_ZORA_DOMAIN_FROM_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_FAIRY_DOMAIN, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_HAUNTED_WASTELAND,
		{
			OOT_HAUNTED_WASTELAND,
			{
				{ OOT_WASTELAND_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_WASTELAND_FROM_COLOSSUS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_MARKET_ENTRANCE,
		{
			OOT_MARKET_ENTRANCE,
			{
				{ OOT_MARKET_ENTRANCE_FROM_MARKET_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_ENTRANCE_FROM_POTS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_HYRULE_CASTLE,
		{
			OOT_HYRULE_CASTLE,
			{
				{ OOT_HYRULE_CASTLE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_HYRULE_CASTLE_FROM_FAIRY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_EXIT_CASTLE, { UINT32_MAX, UINT32_MAX } },
				{ OOT_CASTLE_STEALTH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_CASTLE_STEALTH_FROM_COURTYARD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_CASTLE_CAUGHT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_TEMPLE_OF_TIME_ENTRYWAY,
		{
			OOT_TEMPLE_OF_TIME_ENTRYWAY,
			{
				{ OOT_TEMPLE_OF_TIME_ENTRYWAY_FROM_MARKET_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_TEMPLE_OF_TIME_ENTRYWAY_FROM_TEMPLE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_KOKIRI_MIDO,
		{
			OOT_KOKIRI_MIDO,
			{
				{ OOT_HOUSE_MIDO_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_KOKIRI_SARIA,
		{
			OOT_KOKIRI_SARIA,
			{
				{ OOT_HOUSE_SARIA_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_KOKIRI_TWINS,
		{
			OOT_KOKIRI_TWINS,
			{
				{ OOT_HOUSE_TWINS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_KOKIRI_KNOW_IT_ALL,
		{
			OOT_KOKIRI_KNOW_IT_ALL,
			{
				{ OOT_HOUSE_KNOW_IT_ALL_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_KOKIRI_SHOP,
		{
			OOT_KOKIRI_SHOP,
			{
				{ OOT_KOKIRI_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GUARD_HOUSE,
		{
			OOT_GUARD_HOUSE,
			{
				{ OOT_HOUSE_POTS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_LABORATORY,
		{
			OOT_LABORATORY,
			{
				{ OOT_LABORATORY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_FISHING_POND,
		{
			OOT_FISHING_POND,
			{
				{ OOT_FISHING_POND_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_CARPENTER_TENT,
		{
			OOT_CARPENTER_TENT,
			{
				{ OOT_VALLEY_TENT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_CARPENTER_BOSS_HOUSE,
		{
			OOT_CARPENTER_BOSS_HOUSE,
			{
				{ OOT_HOUSE_CARPENTER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_HOUSE_OF_SKULLTULA,
		{
			OOT_HOUSE_OF_SKULLTULA,
			{
				{ OOT_HOUSE_SKULLTULA_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_IMPA_HOUSE,
		{
			OOT_IMPA_HOUSE,
			{
				{ OOT_HOUSE_IMPA_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_HOUSE_IMPA_BACK_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GRANNY_POTION_SHOP,
		{
			OOT_GRANNY_POTION_SHOP,
			{
				{ OOT_SHOP_GRANNY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_DAMPE_HOUSE,
		{
			OOT_DAMPE_HOUSE,
			{
				{ OOT_HOUSE_DAMPE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GORON_SHOP,
		{
			OOT_GORON_SHOP,
			{
				{ OOT_SHOP_GORON_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_ZORA_SHOP,
		{
			OOT_ZORA_SHOP,
			{
				{ OOT_SHOP_ZORA_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_RANCH_HOUSE_SILO,
		{
			OOT_RANCH_HOUSE_SILO,
			{
				{ OOT_HOUSE_LON_LON_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_SILO,
		{
			OOT_SILO,
			{
				{ OOT_SILO_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_STABLE,
		{
			OOT_STABLE,
			{
				{ OOT_STABLES_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GREAT_FAIRY_MAGIC,
		{
			OOT_GREAT_FAIRY_MAGIC,
			{
				{ OOT_FAIRY_MAGIC_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GREAT_FAIRY_MAGIC2,
		{
			OOT_GREAT_FAIRY_MAGIC2,
			{
				{ OOT_FAIRY_MAGIC2_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GREAT_FAIRY_CASTLE,
		{
			OOT_GREAT_FAIRY_CASTLE,
			{
				{ OOT_FAIRY_DIN_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GREAT_FAIRY_FARORE,
		{
			OOT_GREAT_FAIRY_FARORE,
			{
				{ OOT_FAIRY_FARORE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GREAT_FAIRY_NAYRU,
		{
			OOT_GREAT_FAIRY_NAYRU,
			{
				{ OOT_FAIRY_NAYRU_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GREAT_FAIRY_DEFENSE,
		{
			OOT_GREAT_FAIRY_DEFENSE,
			{
				{ OOT_FAIRY_DEFENSE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_BOMBCHU_BOWLING_ALLEY,
		{
			OOT_BOMBCHU_BOWLING_ALLEY,
			{
				{ OOT_BOMBCHU_BOWLING_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_TREASURE_SHOP,
		{
			OOT_TREASURE_SHOP,
			{
				{ OOT_TREASURE_GAME_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_BOMBCHU_SHOP,
		{
			OOT_BOMBCHU_SHOP,
			{
				{ OOT_BOMBCHU_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_BACK_ALLEY_HOUSE2,
		{
			OOT_BACK_ALLEY_HOUSE2,
			{
				{ OOT_ALLEY_HOUSE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_MARKET_BAZAAR,
		{
			OOT_MARKET_BAZAAR,
			{
				{ OOT_MARKET_BAZAAR_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_MARKET_POTION_SHOP,
		{
			OOT_MARKET_POTION_SHOP,
			{
				{ OOT_MARKET_POTION_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_MARKET_SHOOTING,
		{
			OOT_MARKET_SHOOTING,
			{
				{ OOT_CHILD_ARCHERY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_KAKARIKO_BAZAAR,
		{
			OOT_KAKARIKO_BAZAAR,
			{
				{ OOT_KAKARIKO_BAZAAR_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_KAKARIKO_SHOOTING,
		{
			OOT_KAKARIKO_SHOOTING,
			{
				{ OOT_ADULT_ARCHERY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_WINDMILL,
		{
			OOT_WINDMILL,
			{
				{ OOT_WINDMILL_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_KAKARIKO_POTION_SHOP,
		{
			OOT_KAKARIKO_POTION_SHOP,
			{
				{ OOT_SHOP_POTION_KAKARIKO_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_SHOP_POTION_KAKARIKO_BACK_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_BACK_ALLEY,
		{
			OOT_BACK_ALLEY,
			{
				{ OOT_MARKET_FROM_BOMBCHU_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_MARKET_FROM_ALLEY_HOUSE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_BACK_ALLEY_TREASURE_FROM_MARKET_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_BACK_ALLEY_SHOOTING_FROM_MARKET_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_BACK_ALLEY_FROM_DOG_LADY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_KOKIRI_FOREST_STORMS,
		{
			OOT_GROTTO_KOKIRI_FOREST_STORMS,
			{
				{ OOT_GROTTO_GENERIC_KOKIRI_FOREST_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_LOST_WOODS_GENERIC,
		{
			OOT_GROTTO_LOST_WOODS_GENERIC,
			{
				{ OOT_GROTTO_GENERIC_LOST_WOODS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_KAKARIKO_OPEN,
		{
			OOT_GROTTO_KAKARIKO_OPEN,
			{
				{ OOT_GROTTO_GENERIC_KAKARIKO_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_DEATH_TRIAL_STORMS,
		{
			OOT_GROTTO_DEATH_TRIAL_STORMS,
			{
				{ OOT_GROTTO_GENERIC_DMT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_DEATH_CRATER_GENERIC,
		{
			OOT_GROTTO_DEATH_CRATER_GENERIC,
			{
				{ OOT_GROTTO_GENERIC_DMC_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_ZORA_RIVER_GENERIC,
		{
			OOT_GROTTO_ZORA_RIVER_GENERIC,
			{
				{ OOT_GROTTO_GENERIC_RIVER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_HYRULE_SE,
		{
			OOT_GROTTO_HYRULE_SE,
			{
				{ OOT_GROTTO_GENERIC_HF_SOUTHEAST_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_HYRULE_OPEN,
		{
			OOT_GROTTO_HYRULE_OPEN,
			{
				{ OOT_GROTTO_GENERIC_HF_OPEN_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_HYRULE_MARKET,
		{
			OOT_GROTTO_HYRULE_MARKET,
			{
				{ OOT_GROTTO_GENERIC_HF_MARKET_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_FAIRY_SACRED_MEADOW,
		{
			OOT_FAIRY_SACRED_MEADOW,
			{
				{ OOT_GROTTO_FAIRY_SFM_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_FAIRY_HYRULE,
		{
			OOT_FAIRY_HYRULE,
			{
				{ OOT_GROTTO_FAIRY_HF_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_FAIRY_ZORA_RIVER,
		{
			OOT_FAIRY_ZORA_RIVER,
			{
				{ OOT_GROTTO_FAIRY_RIVER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_FAIRY_ZORA_DOMAIN,
		{
			OOT_FAIRY_ZORA_DOMAIN,
			{
				{ OOT_GROTTO_FAIRY_DOMAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_FAIRY_GERUDO_FORTRESS,
		{
			OOT_FAIRY_GERUDO_FORTRESS,
			{
				{ OOT_GROTTO_FAIRY_FORTRESS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_SACRED_MEADOW_STORMS,
		{
			OOT_GROTTO_SACRED_MEADOW_STORMS,
			{
				{ OOT_GROTTO_SCRUBS2_SFM_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_ZORA_RIVER_STORMS,
		{
			OOT_GROTTO_ZORA_RIVER_STORMS,
			{
				{ OOT_GROTTO_SCRUBS2_RIVER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_VALLEY_STORMS,
		{
			OOT_GROTTO_VALLEY_STORMS,
			{
				{ OOT_GROTTO_SCRUBS2_VALLEY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_DESERT_SCRUBS,
		{
			OOT_GROTTO_DESERT_SCRUBS,
			{
				{ OOT_GROTTO_SCRUBS2_COLOSSUS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_LON_LON_SCRUBS,
		{
			OOT_GROTTO_LON_LON_SCRUBS,
			{
				{ OOT_GROTTO_SCRUBS3_RANCH_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_GORON_CITY_SCRUBS,
		{
			OOT_GROTTO_GORON_CITY_SCRUBS,
			{
				{ OOT_GROTTO_SCRUBS3_GORON_CITY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_DEATH_CRATER_SCRUBS,
		{
			OOT_GROTTO_DEATH_CRATER_SCRUBS,
			{
				{ OOT_GROTTO_SCRUBS3_DMC_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_LAKE_HYLIA_SCRUBS,
		{
			OOT_GROTTO_LAKE_HYLIA_SCRUBS,
			{
				{ OOT_GROTTO_SCRUBS3_LAKE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_LOST_WOODS_SCRUB_UPGRADE,
		{
			OOT_GROTTO_LOST_WOODS_SCRUB_UPGRADE,
			{
				{ OOT_GROTTO_SCRUB_UPGRADE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_HYRULE_SCRUBS,
		{
			OOT_GROTTO_HYRULE_SCRUBS,
			{
				{ OOT_GROTTO_SCRUB_HEART_PIECE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_LOST_WOODS_THEATER,
		{
			OOT_GROTTO_LOST_WOODS_THEATER,
			{
				{ OOT_GROTTO_DEKU_THEATER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_SACRED_MEADOW_WOLFOS,
		{
			OOT_GROTTO_SACRED_MEADOW_WOLFOS,
			{
				{ OOT_GROTTO_WOLFOS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_HYRULE_TEKTITE,
		{
			OOT_GROTTO_HYRULE_TEKTITE,
			{
				{ OOT_GROTTO_TEKTITE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_HYRULE_GERUDO,
		{
			OOT_GROTTO_HYRULE_GERUDO,
			{
				{ OOT_GROTTO_FIELD_COW_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_HYRULE_KAKARIKO,
		{
			OOT_GROTTO_HYRULE_KAKARIKO,
			{
				{ OOT_GROTTO_FIELD_TREE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_DEATH_TRIAL_COW,
		{
			OOT_GROTTO_DEATH_TRIAL_COW,
			{
				{ OOT_GROTTO_TRAIL_COW_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_CASTLE_STORMS,
		{
			OOT_GROTTO_CASTLE_STORMS,
			{
				{ OOT_GROTTO_CASTLE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_KAKARIKO_REDEAD,
		{
			OOT_GROTTO_KAKARIKO_REDEAD,
			{
				{ OOT_GROTTO_REDEAD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTO_VALLEY_OCTOROK,
		{
			OOT_GROTTO_VALLEY_OCTOROK,
			{
				{ OOT_GROTTO_OCTOROK_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_TOMB_REDEAD,
		{
			OOT_TOMB_REDEAD,
			{
				{ OOT_GRAVE_SHIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_TOMB_FAIRY,
		{
			OOT_TOMB_FAIRY,
			{
				{ OOT_GRAVE_REDEAD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_TOMB_ROYAL,
		{
			OOT_TOMB_ROYAL,
			{
				{ OOT_GRAVE_ROYAL_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_TOMB_DAMPE_WINDMILL,
		{
			OOT_TOMB_DAMPE_WINDMILL,
			{
				{ OOT_GRAVE_DAMPE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GANON_BATTLE_ARENA,
		{
			OOT_GANON_BATTLE_ARENA,
			{
				{ OOT_BOSS_GANON2_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_CASTLE_COURTYARD,
		{
			OOT_CASTLE_COURTYARD,
			{
				{ OOT_CASTLE_COURTYARD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_CLOCK_TOWN_SOUTH,
		{
			MM_CLOCK_TOWN_SOUTH,
			{
				{ OOT_SHOP_MASKS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_CHAMBER_OF_THE_SAGES,
		{
			OOT_CHAMBER_OF_THE_SAGES,
			{
				{ OOT_SAGES_CHAMBER_END_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_GROTTOS,
		{
			OOT_GROTTOS,
			{
				{ OOT_GROTTO_TYPE_GENERIC_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_TYPE_FAIRY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_TYPE_SCRUB2_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_GROTTO_TYPE_SCRUB3_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ OOT_INTERNAL_EXIT_GROTTO_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		OOT_BACK_ALLEY_HOUSE,
		{
			OOT_BACK_ALLEY_HOUSE,
			{
				{ OOT_DOG_LADY_FROM_BACK_ALLEY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	}
};

#pragma endregion

#pragma region MM Scene Meta Entrance

const std::map<uint32_t, SceneEntranceMetaInf> MMSceneEntranceMeta =
{
	{
		MM_LAIR_ODOLWA,
		{
			MM_LAIR_ODOLWA,
			{
				{ MM_BOSS_TEMPLE_WOODFALL_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_LAIR_GOHT,
		{
			MM_LAIR_GOHT,
			{
				{ MM_BOSS_TEMPLE_SNOWHEAD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_LAIR_GYORG,
		{
			MM_LAIR_GYORG,
			{
				{ MM_BOSS_TEMPLE_GREAT_BAY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_LAIR_TWINMOLD,
		{
			MM_LAIR_TWINMOLD,
			{
				{ MM_BOSS_TEMPLE_STONE_TOWER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_TEMPLE_WOODFALL,
		{
			MM_TEMPLE_WOODFALL,
			{
				{ MM_TEMPLE_WOODFALL_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_TEMPLE_SNOWHEAD,
		{
			MM_TEMPLE_SNOWHEAD,
			{
				{ MM_TEMPLE_SNOWHEAD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_TEMPLE_GREAT_BAY,
		{
			MM_TEMPLE_GREAT_BAY,
			{
				{ MM_TEMPLE_GREAT_BAY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_TEMPLE_STONE_TOWER_INVERTED,
		{
			MM_TEMPLE_STONE_TOWER_INVERTED,
			{
				{ MM_TEMPLE_STONE_TOWER_INVERTED_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_TEMPLE_STONE_TOWER,
		{
			MM_TEMPLE_STONE_TOWER,
			{
				{ MM_TEMPLE_STONE_TOWER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_SPIDER_HOUSE_SWAMP,
		{
			MM_SPIDER_HOUSE_SWAMP,
			{
				{ MM_SPIDER_HOUSE_SWAMP_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_SPIDER_HOUSE_OCEAN,
		{
			MM_SPIDER_HOUSE_OCEAN,
			{
				{ MM_SPIDER_HOUSE_OCEAN_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_BENEATH_THE_WELL,
		{
			MM_BENEATH_THE_WELL,
			{
				{ MM_BENEATH_THE_WELL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_BENEATH_THE_WELL_BACK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WALLMASTER_BTW_ENTRANCE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WALLMASTER_BTW_FOUNTAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WALLMASTER_BTW_EXIT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_INSIDE_CASTLE_IKANA,
		{
			MM_INSIDE_CASTLE_IKANA,
			{
				{ MM_IKANA_CASTLE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_CASTLE_INTERIOR_KEG_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_CASTLE_INTERIOR_BLOCK_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_SECRET_SHRINE,
		{
			MM_SECRET_SHRINE,
			{
				{ MM_SECRET_SHRINE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_CAVERN_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_PIRATE_FORTRESS_EXTERIOR,
		{
			MM_PIRATE_FORTRESS_EXTERIOR,
			{
				{ MM_PIRATE_FORTRESS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_EXTERIOR_GATE_FROM_SEWERS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_PIRATE_FORTRESS_EXTERIOR_FROM_INTERIOR_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_PIRATE_FORTRESS_EXTERIOR_LOOKOUT_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_EXTERIOR_DOOR_FROM_SEWERS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_CLOCK_TOWER_ROOFTOP,
		{
			MM_CLOCK_TOWER_ROOFTOP,
			{
				{ MM_CLOCK_TOWER_ROOF_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_WOODFALL,
		{
			MM_WOODFALL,
			{
				{ MM_WOODFALL_FROM_TEMPLE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WOODFALL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WOODFALL_FROM_FAIRY_FOUNTAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WARP_OWL_WOODFALL_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_SNOWHEAD,
		{
			MM_SNOWHEAD,
			{
				{ MM_SNOWHEAD_FROM_TEMPLE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_SNOWHEAD_FROM_SNOWHEAD_PATH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_SNOWHEAD_FROM_FAIRY_FOUNTAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WARP_OWL_SNOWHEAD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GREAT_BAY_COAST,
		{
			MM_GREAT_BAY_COAST,
			{
				{ MM_GREAT_BAY_FROM_TEMPLE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GREAT_BAY_FROM_SPIDER_HOUSE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GREAT_BAY_FROM_PIRATE_FORTRESS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GREAT_BAY_COAST_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GREAT_BAY_COAST_FROM_ZORA_CAPE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GREAT_BAY_FROM_PINNACLE_ROCK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GREAT_BAY_COAST_FROM_FISHER_HUT_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GREAT_BAY_COAST_FROM_LABORATORY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GREAT_BAY_FROM_FAIRY_FOUNTAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WARP_OWL_GREAT_BAY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_GREAT_BAY_COAST, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_COW_COAST, { UINT32_MAX, UINT32_MAX } },
				{ MM_VOID_GREAT_BAY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_VOID_GREAT_BAY_BY_PINNACLE_ROCK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_COAST_FROM_MIKAU_CS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_STONE_TOWER_INVERTED,
		{
			MM_STONE_TOWER_INVERTED,
			{
				{ MM_STONE_TOWER_INVERTED_FROM_TEMPLE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_STONE_TOWER,
		{
			MM_STONE_TOWER,
			{
				{ MM_STONE_TOWER_FROM_TEMPLE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_STONE_TOWER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WARP_OWL_STONE_TOWER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_SOUTHERN_SWAMP,
		{
			MM_SOUTHERN_SWAMP,
			{
				{ MM_SWAMP_FROM_SPIDER_HOUSE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_SWAMP_FROM_ROAD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_SWAMP_FROM_PALACE_MAIN_ENTRANCE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_SWAMP_FROM_PALACE_LEDGE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_SWAMP_FROM_WOODFALL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_SWAMP_FROM_MYSTERY_WOODS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_SWAMP_FROM_IKANA_CANYON_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_SWAMP_FROM_POTION_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_SWAMP_FROM_TOURIST_INFORMATION_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WARP_OWL_SOUTHERN_SWAMP_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_SWAMP, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_IKANA_CANYON,
		{
			MM_IKANA_CANYON,
			{
				{ MM_IKANA_CANYON_FROM_WELL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_VALLEY_FROM_SHRINE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_VALLEY_FROM_ROAD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_CASTLE_GARDENS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_CANYON_FROM_STONE_TOWER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_CANYON_FROM_GHOST_HUT_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_CANYON_FROM_MUSIC_BOX_HOUSE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_CANYON_FROM_FAIRY_FOUNTAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_CANYON_FROM_CAVERN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_CANYON_FROM_SAKON_HIDEOUT_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WARP_OWL_IKANA_CANYON_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_VALLEY, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_CASTLE_IKANA,
		{
			MM_CASTLE_IKANA,
			{
				{ MM_IKANA_CASTLE_EXTERIOR_FROM_WELL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_CASTLE_EXTERIOR_FROM_CASTLE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_CANYON_FROM_CASTLE_GARDENS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_CLOCK_TOWN_SOUTH,
		{
			MM_CLOCK_TOWN_SOUTH,
			{
				{ MM_CLOCK_TOWN_FROM_CLOCK_TOWER_ROOF_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_SOUTH_BOTTOM_FROM_WEST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_SOUTH_BOTTOM_FROM_EAST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_SOUTH_FROM_NORTH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_SOUTH_TOP_FROM_EAST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_SOUTH_TOP_FROM_WEST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_SOUTH_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_SOUTH_FROM_LAUNDRY_POOL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WARP_OWL_CLOCK_TOWN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_FROM_SONG_OF_TIME_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWER_FROM_CLOCK_TOWN_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_MOUNTAIN_VILLAGE,
		{
			MM_MOUNTAIN_VILLAGE,
			{
				{ MM_MOUNTAIN_VILLAGE_FROM_PATH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_MOUNTAIN_VILLAGE_FROM_SNOWHEAD_PATH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_MOUNTAIN_VILLAGE_FROM_TWIN_ISLANDS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_MOUNTAIN_VILLAGE_FROM_GORON_GRAVEYARD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_MOUNTAIN_VILLAGE_FROM_BLACKSMITH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WARP_OWL_MOUNTAIN_VILLAGE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_MOUNTAIN_VILLAGE, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_MOUNTAIN_VILLAGE_WINTER, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_ROMANI_RANCH,
		{
			MM_ROMANI_RANCH,
			{
				{ MM_ROMANI_RANCH_FROM_MILK_ROAD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ROMANI_RANCH_FROM_CUCCO_SHACK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ROMANI_RANCH_FROM_DOGGY_RACETRACK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ROMANI_RANCH_FROM_STABLES_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ROMANI_RANCH_FROM_RANCH_HOUSE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_ROAD_SOUTHERN_SWAMP,
		{
			MM_ROAD_SOUTHERN_SWAMP,
			{
				{ MM_SWAMP_ROAD_FROM_SWAMP_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_SWAMP_ROAD_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_SWAMP_ROAD_FROM_ARCHERY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_PATH_SWAMP, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_PATH_MOUNTAIN_VILLAGE,
		{
			MM_PATH_MOUNTAIN_VILLAGE,
			{
				{ MM_PATH_FROM_MOUNTAIN_VILLAGE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_MOUNTAIN_VILLAGE_PATH_FROM_TERMINA_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_TERMINA_FIELD,
		{
			MM_TERMINA_FIELD,
			{
				{ MM_TERMINA_FIELD_FROM_GREAT_BAY_COAST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_TERMINA_FIELD_FROM_CLOCK_TOWN_WEST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_TERMINA_FIELD_FROM_CLOCK_TOWN_SOUTH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_TERMINA_FIELD_FROM_CLOCK_TOWN_EAST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_TERMINA_FIELD_FROM_CLOCK_TOWN_NORTH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_TERMINA_FIELD_FROM_ROAD_TO_IKANA_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_TERMINA_FIELD_FROM_PATH_TO_MOUNTAIN_VILLAGE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_TERMINA_FIELD_FROM_ROAD_TO_SWAMP_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_TERMINA_FIELD_FROM_MILK_ROAD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_FIELD_FROM_ASTRAL_OBSERVATORY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_FIELD_PILLAR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_GRASS, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_COW_FIELD, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GOSSIPS_MOUNTAIN, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GOSSIPS_CANYON, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GOSSIPS_OCEAN, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GOSSIPS_SWAMP, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_DODONGO, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_SCRUB, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_PEAHAT, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_BIO_BABA, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_ROAD_IKANA,
		{
			MM_ROAD_IKANA,
			{
				{ MM_IKANA_ROAD_FROM_VALLEY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_ROAD_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_ROAD_FROM_IKANA_GRAVEYARD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_PATH_IKANA, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_MILK_ROAD,
		{
			MM_MILK_ROAD,
			{
				{ MM_MILK_ROAD_FROM_ROMANI_RANCH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_MILK_ROAD_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_MILK_ROAD_FROM_GORMAN_TRACK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_MILK_ROAD_FROM_GORMAN_BACK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WARP_OWL_MILK_ROAD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_MILK_ROAD_FROM_RANCH2_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_MILK_ROAD_FROM_GORMAN_TRACK2_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_CLOCK_TOWN_WEST,
		{
			MM_CLOCK_TOWN_WEST,
			{
				{ MM_CLOCK_TOWN_WEST_FROM_SOUTH_BOTTOM_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_WEST_FROM_SOUTH_TOP_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_WEST_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_WEST_FROM_SWORDSMAN_SCHOOL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_WEST_FROM_CURIOSITY_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_WEST_FROM_TRADING_POST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_WEST_FROM_BOMB_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_WEST_FROM_POST_OFFICE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_WEST_FROM_LOTTERY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_CLOCK_TOWN_EAST,
		{
			MM_CLOCK_TOWN_EAST,
			{
				{ MM_CLOCK_TOWN_EAST_FROM_SOUTH_BOTTOM_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_EAST_FROM_NORTH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_EAST_FROM_SOUTH_TOP_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_EAST_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_EAST_FROM_CHEST_GAME_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_EAST_FROM_HONEY_AND_DARLING_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_EAST_FROM_MAYORS_OFFICE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_EAST_FROM_TOWN_ARCHERY_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_EAST_FROM_STOCK_POT_INN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_EAST_FROM_STOCK_POT_INN_ROOF_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_EAST_FROM_MILK_BAR_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_EAST_FROM_ASTRAL_OBSERVATORY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_CLOCK_TOWN_NORTH,
		{
			MM_CLOCK_TOWN_NORTH,
			{
				{ MM_CLOCK_TOWN_NORTH_FROM_EAST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_NORTH_FROM_SOUTH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_NORTH_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_NORTH_FROM_FAIRY_FOUNTAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_DEKU_PLAYGROUND, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_LAUNDRY_POOL,
		{
			MM_LAUNDRY_POOL,
			{
				{ MM_LAUNDRY_POOL_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_LAUNDRY_POOL_FROM_KAFEI_HIDEOUT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GORMAN_TRACK,
		{
			MM_GORMAN_TRACK,
			{
				{ MM_GORMAN_TRACK_FROM_MILK_ROAD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GORMAN_BACK_FROM_MILK_ROAD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GORMAN_TRACK_UNK2_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GORMAN_TRACK_UNK3_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GORMAN_TRACK_UNK5_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GORMAN_TRACK_UNK6_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_PATH_SNOWHEAD,
		{
			MM_PATH_SNOWHEAD,
			{
				{ MM_SNOWHEAD_PATH_FROM_MOUNTAIN_VILLAGE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_PATH_SNOWHEAD_FROM_SNOWHEAD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_PATH_SNOWHEAD, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_IKANA_GRAVEYARD,
		{
			MM_IKANA_GRAVEYARD,
			{
				{ MM_IKANA_GRAVEYARD_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_GRAVEYARD, { UINT32_MAX, UINT32_MAX } },
				{ MM_GRAVE_EXIT_NIGHT1, { UINT32_MAX, UINT32_MAX } },
				{ MM_GRAVE_EXIT_NIGHT2, { UINT32_MAX, UINT32_MAX } },
				{ MM_GRAVE_EXIT_NIGHT3, { UINT32_MAX, UINT32_MAX } },
				{ MM_IKANA_GRAVEYARD_FROM_DAMPE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_ZORA_CAPE,
		{
			MM_ZORA_CAPE,
			{
				{ MM_ZORA_CAPE_FROM_GREAT_BAY_COAST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ZORA_CAPE_FROM_HALL_WATER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ZORA_CAPE_PENINSULA_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ZORA_CAPE_FROM_BEAVERS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_WARP_OWL_ZORA_CAPE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_ZORA_CAPE, { UINT32_MAX, UINT32_MAX } },
				{ MM_VOID_ZORA_CAPE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_PINNACLE_ROCK,
		{
			MM_PINNACLE_ROCK,
			{
				{ MM_PINNACLE_ROCK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_VOID_PINNACLE_ROCK_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_ZORA_HALL,
		{
			MM_ZORA_HALL,
			{
				{ MM_ZORA_HALL_UNDERWATER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ZORA_HALL_LEDGE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ZORA_HALL_FROM_EVANS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ZORA_HALL_FROM_JAPAS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ZORA_HALL_FROM_TIJO_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ZORA_HALL_FROM_LULU_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ZORA_HALL_FROM_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_DEKU_PALACE,
		{
			MM_DEKU_PALACE,
			{
				{ MM_DEKU_PALACE_MAIN_ENTRANCE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_DEKU_PALACE_LEDGE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_DEKU_PALACE_EXTERIOR_FROM_SHRINE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_DEKU_PALACE_EXTERIOR_FROM_THRONE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_DEKU_PALACE_EXTERIOR_FROM_THRONE_CAGE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_BEAN, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_JP_CLIMB_LEFT, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_JP_CLIMB_RIGHT, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_JP_LINE_START, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_JP_LINE_END, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_LOST_WOODS,
		{
			MM_LOST_WOODS,
			{
				{ MM_MYSTERY_WOODS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_WOODS, { UINT32_MAX, UINT32_MAX } },
				{ MM_LOST_WOODS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_PIRATE_SEWERS,
		{
			MM_PIRATE_SEWERS,
			{
				{ MM_SEWERS_FROM_EXTERIOR_GATE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_SEWERS_FROM_EXTERIOR_DOOR_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_PIRATE_FORTRESS_INTERIOR,
		{
			MM_PIRATE_FORTRESS_INTERIOR,
			{
				{ MM_PIRATE_FORTRESS_INTERIOR_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_PIRATE_FORTRESS_INTERIOR_FROM_LOOKOUT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_TWIN_ISLANDS,
		{
			MM_TWIN_ISLANDS,
			{
				{ MM_TWIN_ISLANDS_FROM_MOUNTAIN_VILLAGE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_TWIN_ISLANDS_FROM_GORON_VILLAGE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_TWIN_ISLANDS_FROM_GORON_RACETRACK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_GENERIC_TWIN_ISLANDS, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_EXIT_HOT_WATER, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GORON_VILLAGE_WINTER,
		{
			MM_GORON_VILLAGE_WINTER,
			{
				{ MM_GORON_VILLAGE_FROM_TWIN_ISLANDS_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GORON_VILLAGE_FROM_GORON_SHRINE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GORON_VILLAGE_FROM_LONE_PEAK_SHRINE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_TREASURE_SHOP,
		{
			MM_TREASURE_SHOP,
			{
				{ MM_CHEST_GAME_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_HONEY_DARLING,
		{
			MM_HONEY_DARLING,
			{
				{ MM_HONEY_AND_DARLING_GAME_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_MAYOR_HOUSE,
		{
			MM_MAYOR_HOUSE,
			{
				{ MM_MAYORS_OFFICE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_SHOOTING_GALLERY,
		{
			MM_SHOOTING_GALLERY,
			{
				{ MM_TOWN_ARCHERY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_MILK_BAR,
		{
			MM_MILK_BAR,
			{
				{ MM_MILK_BAR_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_FAIRY_CLOCK_TOWN,
		{
			MM_FAIRY_CLOCK_TOWN,
			{
				{ MM_FAIRY_FOUNTAIN_TOWN_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_SWORDSMAN_SCHOOL,
		{
			MM_SWORDSMAN_SCHOOL,
			{
				{ MM_SWORDSMAN_SCHOOL_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_CURIOSITY_SHOP,
		{
			MM_CURIOSITY_SHOP,
			{
				{ MM_CURIOSITY_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_KAFEI_HIDEOUT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_TRADING_POST,
		{
			MM_TRADING_POST,
			{
				{ MM_TRADING_POST_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_BOMB_SHOP,
		{
			MM_BOMB_SHOP,
			{
				{ MM_BOMB_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_POST_OFFICE,
		{
			MM_POST_OFFICE,
			{
				{ MM_POST_OFFICE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_LOTTERY,
		{
			MM_LOTTERY,
			{
				{ MM_LOTTERY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_POTION_SHOP,
		{
			MM_POTION_SHOP,
			{
				{ MM_POTION_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_DEKU_SHRINE,
		{
			MM_DEKU_SHRINE,
			{
				{ MM_DEKU_SHRINE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GORON_SHOP,
		{
			MM_GORON_SHOP,
			{
				{ MM_GORON_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_FISHERMAN_HUT,
		{
			MM_FISHERMAN_HUT,
			{
				{ MM_FISHER_HUT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_LABORATORY,
		{
			MM_LABORATORY,
			{
				{ MM_LABORATORY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_ZORA_EVANS_ROOM,
		{
			MM_ZORA_EVANS_ROOM,
			{
				{ MM_ROOM_EVANS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_ZORA_JAPAS_ROOM,
		{
			MM_ZORA_JAPAS_ROOM,
			{
				{ MM_ROOM_JAPAS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_ZORA_TIJO_ROOM,
		{
			MM_ZORA_TIJO_ROOM,
			{
				{ MM_ROOM_TIJO_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_ZORA_LULU_ROOM,
		{
			MM_ZORA_LULU_ROOM,
			{
				{ MM_ROOM_LULU_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_ZORA_SHOP,
		{
			MM_ZORA_SHOP,
			{
				{ MM_ZORA_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GHOST_HUT,
		{
			MM_GHOST_HUT,
			{
				{ MM_GHOST_HUT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_MUSIC_BOX_HOUSE,
		{
			MM_MUSIC_BOX_HOUSE,
			{
				{ MM_MUSIC_BOX_HOUSE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_FAIRY_IKANA,
		{
			MM_FAIRY_IKANA,
			{
				{ MM_FAIRY_FOUNTAIN_IKANA_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_FAIRY_GREAT_BAY_COAST,
		{
			MM_FAIRY_GREAT_BAY_COAST,
			{
				{ MM_FAIRY_FOUNTAIN_GREAT_BAY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_FAIRY_SNOWHEAD,
		{
			MM_FAIRY_SNOWHEAD,
			{
				{ MM_FAIRY_FOUNTAIN_SNOWHEAD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_FAIRY_WOODFALL,
		{
			MM_FAIRY_WOODFALL,
			{
				{ MM_FAIRY_FOUNTAIN_WOODFALL_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GORON_GRAVEYARD,
		{
			MM_GORON_GRAVEYARD,
			{
				{ MM_GORON_GRAVEYARD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_BLACKSMITH,
		{
			MM_BLACKSMITH,
			{
				{ MM_BLACKSMITH_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_SHOOTING_GALLERY_SWAMP,
		{
			MM_SHOOTING_GALLERY_SWAMP,
			{
				{ MM_SWAMP_ARCHERY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GORON_RACETRACK,
		{
			MM_GORON_RACETRACK,
			{
				{ MM_GORON_RACETRACK_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GORON_RACETRACK_ALT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_WATERFALL_RAPIDS,
		{
			MM_WATERFALL_RAPIDS,
			{
				{ MM_BEAVERS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_CUCCO_SHACK,
		{
			MM_CUCCO_SHACK,
			{
				{ MM_CUCCO_SHACK_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_DOG_RACETRACK,
		{
			MM_DOG_RACETRACK,
			{
				{ MM_DOGGY_RACETRACK_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_RANCH_HOUSE_BARN,
		{
			MM_RANCH_HOUSE_BARN,
			{
				{ MM_STABLES_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_ROMANI_RANCH_BARN,
		{
			MM_ROMANI_RANCH_BARN,
			{
				{ MM_RANCH_HOUSE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GORON_SHRINE,
		{
			MM_GORON_SHRINE,
			{
				{ MM_GORON_SHRINE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GORON_SHRINE_FROM_SHOP_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_DEKU_KING_CHAMBER,
		{
			MM_DEKU_KING_CHAMBER,
			{
				{ MM_DEKU_PALACE_THRONE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_DEKU_PALACE_THRONE_CAGE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_LONE_PEAK,
		{
			MM_LONE_PEAK,
			{
				{ MM_LONE_PEAK_SHRINE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_STOCK_POT_INN,
		{
			MM_STOCK_POT_INN,
			{
				{ MM_STOCK_POT_INN_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_STOCK_POT_INN_ROOF_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_TOURIST_INFORMATION,
		{
			MM_TOURIST_INFORMATION,
			{
				{ MM_TOURIST_INFORMATION_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_OBSERVATORY,
		{
			MM_OBSERVATORY,
			{
				{ MM_ASTRAL_OBSERVATORY_FROM_CLOCK_TOWN_EAST_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_ASTRAL_OBSERVATORY_FROM_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_SAKON_HIDEOUT,
		{
			MM_SAKON_HIDEOUT,
			{
				{ MM_SAKON_HIDEOUT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_DAMPE_HOUSE,
		{
			MM_DAMPE_HOUSE,
			{
				{ MM_WALLMASTER_DAMPE_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GRAVE_NIGHT3_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_TERMINA_PILLAR,
		{
			MM_GROTTO_TERMINA_PILLAR,
			{
				{ MM_GROTTO_GENERIC_FIELD_PILLAR_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_TERMINA_TALL_GRASS,
		{
			MM_GROTTO_TERMINA_TALL_GRASS,
			{
				{ MM_GROTTO_GENERIC_GRASS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_SOUTHERN_SWAMP_ROAD_OPEN,
		{
			MM_GROTTO_SOUTHERN_SWAMP_ROAD_OPEN,
			{
				{ MM_GROTTO_GENERIC_PATH_SWAMP_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_WOODS_OF_MYSTERY_OPEN,
		{
			MM_GROTTO_WOODS_OF_MYSTERY_OPEN,
			{
				{ MM_GROTTO_GENERIC_WOODS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_SOUTHERN_SWAMP_OPEN,
		{
			MM_GROTTO_SOUTHERN_SWAMP_OPEN,
			{
				{ MM_GROTTO_GENERIC_SWAMP_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_MOUNTAIN_VILLAGE_GENERIC,
		{
			MM_GROTTO_MOUNTAIN_VILLAGE_GENERIC,
			{
				{ MM_GROTTO_GENERIC_MOUNTAIN_VILLAGE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_TWIN_ISLANDS_RAMP,
		{
			MM_GROTTO_TWIN_ISLANDS_RAMP,
			{
				{ MM_GROTTO_GENERIC_TWIN_ISLANDS_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_PATH_TO_SNOWHEAD_GENERIC,
		{
			MM_GROTTO_PATH_TO_SNOWHEAD_GENERIC,
			{
				{ MM_GROTTO_GENERIC_PATH_SNOWHEAD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_GREAT_BAY_COAST_FISHERMAN,
		{
			MM_GROTTO_GREAT_BAY_COAST_FISHERMAN,
			{
				{ MM_GROTTO_GENERIC_GREAT_BAY_COAST_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_ZORA_CAPE_GENERIC,
		{
			MM_GROTTO_ZORA_CAPE_GENERIC,
			{
				{ MM_GROTTO_GENERIC_ZORA_CAPE_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_IKANA_ROAD_GENERIC,
		{
			MM_GROTTO_IKANA_ROAD_GENERIC,
			{
				{ MM_GROTTO_GENERIC_PATH_IKANA_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_IKANA_GRAVEYARD_GENERIC,
		{
			MM_GROTTO_IKANA_GRAVEYARD_GENERIC,
			{
				{ MM_GROTTO_GENERIC_GRAVEYARD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_IKANA_VALLEY_OPEN,
		{
			MM_GROTTO_IKANA_VALLEY_OPEN,
			{
				{ MM_GROTTO_GENERIC_VALLEY_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_TERMINA_COW,
		{
			MM_GROTTO_TERMINA_COW,
			{
				{ MM_GROTTO_COW_FIELD_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_GREAT_BAY_COAST_COW,
		{
			MM_GROTTO_GREAT_BAY_COAST_COW,
			{
				{ MM_GROTTO_COW_COAST_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_TERMINA_MOUNTAIN_GOSSIP,
		{
			MM_GROTTO_TERMINA_MOUNTAIN_GOSSIP,
			{
				{ MM_GROTTO_GOSSIPS_MOUNTAIN_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_TERMINA_CANYON_GOSSIP,
		{
			MM_GROTTO_TERMINA_CANYON_GOSSIP,
			{
				{ MM_GROTTO_GOSSIPS_CANYON_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_TERMINA_OCEAN_GOSSIP,
		{
			MM_GROTTO_TERMINA_OCEAN_GOSSIP,
			{
				{ MM_GROTTO_GOSSIPS_OCEAN_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_TERMINA_SWAMP_GOSSIP,
		{
			MM_GROTTO_TERMINA_SWAMP_GOSSIP,
			{
				{ MM_GROTTO_GOSSIPS_SWAMP_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_TERMINA_DODONGO,
		{
			MM_GROTTO_TERMINA_DODONGO,
			{
				{ MM_GROTTO_DODONGO_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_TERMINA_SCRUB,
		{
			MM_GROTTO_TERMINA_SCRUB,
			{
				{ MM_GROTTO_SCRUB_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_TERMINA_PEAHAT,
		{
			MM_GROTTO_TERMINA_PEAHAT,
			{
				{ MM_GROTTO_PEAHAT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_TERMINA_BIO_BABA,
		{
			MM_GROTTO_TERMINA_BIO_BABA,
			{
				{ MM_GROTTO_BIO_BABA_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_TWIN_ISLANDS_FROZEN,
		{
			MM_GROTTO_TWIN_ISLANDS_FROZEN,
			{
				{ MM_GROTTO_HOT_WATER_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_DEKU_PALACE_BEANS,
		{
			MM_GROTTO_DEKU_PALACE_BEANS,
			{
				{ MM_GROTTO_BEAN_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_DEKU_PLAYGROUND,
		{
			MM_DEKU_PLAYGROUND,
			{
				{ MM_GROTTO_DEKU_PLAYGROUND_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_DEKU_PALACE_CLIMB,
		{
			MM_GROTTO_DEKU_PALACE_CLIMB,
			{
				{ MM_GROTTO_JP_CLIMB_LEFT_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_JP_CLIMB_RIGHT_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTO_DEKU_PALACE_GENERIC,
		{
			MM_GROTTO_DEKU_PALACE_GENERIC,
			{
				{ MM_GROTTO_JP_LINE_START_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_JP_LINE_END_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_BENEATH_THE_GRAVEYARD_NIGHT1,
		{
			MM_BENEATH_THE_GRAVEYARD_NIGHT1,
			{
				{ MM_GRAVE_NIGHT1_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_BENEATH_THE_GRAVEYARD_NIGHT2,
		{
			MM_BENEATH_THE_GRAVEYARD_NIGHT2,
			{
				{ MM_GRAVE_NIGHT2_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_MOON,
		{
			MM_MOON,
			{
				{ MM_MOON_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_EXTRA,
		{
			MM_EXTRA,
			{
				{ MM_CLOCK_TOWER_MOON_CRASH_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_CLOCK_TOWN_FROM_CLOCK_TOWER_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ SPAWN_LOADING, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	},
	{
		MM_GROTTOS,
		{
			MM_GROTTOS,
			{
				{ MM_GROTTO_TYPE_GENERIC_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_GROTTO_TYPE_COW_ENTR, { UINT32_MAX, UINT32_MAX } },
				{ MM_INTERNAL_EXIT_GROTTO_ENTR, { UINT32_MAX, UINT32_MAX } },
			},
			NULL
		}
	}
};

#pragma endregion

const SceneEntranceMetaInf * GetSceneEntranceMetaInf(int Game, uint32_t SceneID)
{
	if (Game == OOT_GAME)
	{
		if (OoTSceneEntranceMeta.contains(SceneID))
		{
			return &OoTSceneEntranceMeta.at(SceneID);
		}
	}
	else if (Game == MM_GAME)
	{
		if (MMSceneEntranceMeta.contains(SceneID))
		{
			return &MMSceneEntranceMeta.at(SceneID);
		}
	}

	return NULL;
}


const std::map<uint32_t, SceneEntranceMetaInf>& GetSceneEntranceMetaInfForGame(int Game)
{
	if (Game == OOT_GAME)
	{
		return OoTSceneEntranceMeta;
	}
	else if (Game == MM_GAME)
	{
		return MMSceneEntranceMeta;
	}

	return std::map<uint32_t, SceneEntranceMetaInf>();
}