#pragma once

#include "Multi/API.h"
#include "Combo/Objects.h"
#include "UI/Icons.h"
#include <QString>

#pragma region Defines

#pragma region OoT

#define OOT_BOMBS_5					                0x001
#define OOT_NUTS_5					                0x002
#define OOT_BOMBCHU_10					            0x003
#define OOT_BOW					                    0x004
#define OOT_SLINGSHOT					            0x005
#define OOT_BOOMERANG					            0x006
#define OOT_STICK					                0x007
#define OOT_HOOKSHOT					            0x008
#define OOT_LONGSHOT					            0x009
#define OOT_LENS					                0x00A
#define OOT_ZELDA_LETTER					        0x00B
#define OOT_OCARINA_TIME					        0x00C
#define OOT_HAMMER					                0x00D
#define OOT_COJIRO					                0x00E
#define OOT_BOTTLE_EMPTY					        0x00F
#define OOT_POTION_RED					            0x010
#define OOT_POTION_GREEN					        0x011
#define OOT_POTION_BLUE					            0x012
#define OOT_FAIRY					                0x013
#define OOT_BOTTLE_MILK					            0x014
#define OOT_BOTTLE_RUTO_LETTER					    0x015
#define OOT_MAGIC_BEAN					            0x016
#define OOT_MASK_SKULL					            0x017
#define OOT_MASK_SPOOKY					            0x018
#define OOT_CHICKEN					                0x019
#define OOT_MASK_KEATON					            0x01A
#define OOT_MASK_BUNNY					            0x01B
#define OOT_MASK_TRUTH					            0x01C
#define OOT_POCKET_EGG					            0x01D
#define OOT_POCKET_CUCCO					        0x01E
#define OOT_ODD_MUSHROOM					        0x01F
#define OOT_ODD_POTION					            0x020
#define OOT_POACHER_SAW					            0x021
#define OOT_BROKEN_GORON_SWORD					    0x022
#define OOT_PRESCRIPTION					        0x023
#define OOT_EYEBALL_FROG					        0x024
#define OOT_EYE_DROPS					            0x025
#define OOT_CLAIM_CHECK					            0x026
#define OOT_SWORD_KOKIRI					        0x027
#define OOT_SWORD_KNIFE					            0x028
#define OOT_SHIELD_DEKU					            0x029
#define OOT_SHIELD_HYLIAN					        0x02A
#define OOT_SHIELD_MIRROR					        0x02B
#define OOT_TUNIC_GORON					            0x02C
#define OOT_TUNIC_ZORA					            0x02D
#define OOT_BOOTS_IRON					            0x02E
#define OOT_BOOTS_HOVER					            0x02F
#define OOT_QUIVER2					                0x030
#define OOT_QUIVER3					                0x031
#define OOT_BOMB_BAG					            0x032
#define OOT_BOMB_BAG2					            0x033
#define OOT_BOMB_BAG3					            0x034
#define OOT_SILVER_GAUNTLETS					    0x035
#define OOT_GOLDEN_GAUNTLETS					    0x036
#define OOT_SCALE_SILVER					        0x037
#define OOT_SCALE_GOLDEN					        0x038
#define OOT_STONE_OF_AGONY					        0x039
#define OOT_GERUDO_CARD					            0x03A
#define OOT_OCARINA_FAIRY					        0x03B
#define OOT_DEKU_SEEDS_5					        0x03C
#define OOT_HEART_CONTAINER					        0x03D
#define OOT_HEART_PIECE					            0x03E
#define OOT_BOSS_KEY					            0x03F
#define OOT_COMPASS					                0x040
#define OOT_MAP					                    0x041
#define OOT_SMALL_KEY					            0x042
#define OOT_MAGIC_JAR_SMALL					        0x043
#define OOT_MAGIC_JAR_LARGE					        0x044
#define OOT_WALLET2					                0x045
#define OOT_WALLET3					                0x046
#define OOT_WEIRD_EGG					            0x047
#define OOT_RECOVERY_HEART					        0x048
#define OOT_ARROWS_5					            0x049
#define OOT_ARROWS_10					            0x04A
#define OOT_ARROWS_30					            0x04B
#define OOT_RUPEE_GREEN					            0x04C
#define OOT_RUPEE_BLUE					            0x04D
#define OOT_RUPEE_RED					            0x04E
#define OOT_HEART_CONTAINER2					    0x04F
#define OOT_MILK					                0x050
#define OOT_MASK_GORON					            0x051
#define OOT_MASK_ZORA					            0x052
#define OOT_MASK_GERUDO					            0x053
#define OOT_GORON_BRACELET					        0x054
#define OOT_RUPEE_PURPLE					        0x055
#define OOT_RUPEE_HUGE					            0x056
#define OOT_SWORD_BIGGORON					        0x057
#define OOT_ARROW_FIRE					            0x058
#define OOT_ARROW_ICE					            0x059
#define OOT_ARROW_LIGHT					            0x05A
#define OOT_GS_TOKEN					            0x05B
#define OOT_SPELL_FIRE					            0x05C
#define OOT_SPELL_WIND					            0x05D
#define OOT_SPELL_LOVE					            0x05E
#define OOT_BULLET_BAG					            0x05F
#define OOT_BULLET_BAG2					            0x060
#define OOT_STICKS_5					            0x061
#define OOT_STICKS_10					            0x062
#define OOT_NUTS_5_ALT					            0x063
#define OOT_NUTS_10					                0x064
#define OOT_BOMB					                0x065
#define OOT_BOMBS_10					            0x066
#define OOT_BOMBS_20					            0x067
#define OOT_BOMBS_30					            0x068
#define OOT_DEKU_SEEDS_30					        0x069
#define OOT_BOMBCHU_5					            0x06A
#define OOT_BOMBCHU_20					            0x06B
#define OOT_FISH					                0x06C
#define OOT_BUGS					                0x06D
#define OOT_BLUE_FIRE					            0x06E
#define OOT_POE					                    0x06F
#define OOT_BIG_POE					                0x070
#define OOT_TC_SMALL_KEY					        0x071
#define OOT_TC_RUPEE_GREEN					        0x072
#define OOT_TC_RUPEE_BLUE					        0x073
#define OOT_TC_RUPEE_RED					        0x074
#define OOT_TC_RUPEE_PURPLE					        0x075
#define OOT_TC_HEART_PIECE					        0x076
#define OOT_STICK_UPGRADE					        0x077
#define OOT_STICK_UPGRADE2					        0x078
#define OOT_NUT_UPGRADE					            0x079
#define OOT_NUT_UPGRADE2					        0x07A
#define OOT_BULLET_BAG3					            0x07B
#define OOT_UNUSED_ICE_TRAP					        0x07C
#define OOT_UNK_7D					                0x07D
#define OOT_UNK_7E					                0x07E
#define OOT_UNK_7F					                0x07F
#define OOT_RUPEE_RAINBOW					        0x080
#define OOT_SONG_TP_FOREST					        0x081
#define OOT_SONG_TP_FIRE					        0x082
#define OOT_SONG_TP_WATER					        0x083
#define OOT_SONG_TP_SPIRIT					        0x084
#define OOT_SONG_TP_SHADOW					        0x085
#define OOT_SONG_TP_LIGHT					        0x086
#define OOT_SONG_ZELDA					            0x087
#define OOT_SONG_EPONA					            0x088
#define OOT_SONG_SARIA					            0x089
#define OOT_SONG_SUN					            0x08A
#define OOT_SONG_TIME					            0x08B
#define OOT_SONG_STORMS_ITEM					    0x08C
#define OOT_SONG_EMPTINESS					        0x08D
#define OOT_SONG_NOTE_TP_FOREST					    0x08E
#define OOT_SONG_NOTE_TP_FIRE					    0x08F
#define OOT_SONG_NOTE_TP_WATER					    0x090
#define OOT_SONG_NOTE_TP_SPIRIT					    0x091
#define OOT_SONG_NOTE_TP_SHADOW					    0x092
#define OOT_SONG_NOTE_TP_LIGHT					    0x093
#define OOT_SONG_NOTE_ZELDA					        0x094
#define OOT_SONG_NOTE_EPONA					        0x095
#define OOT_SONG_NOTE_SARIA					        0x096
#define OOT_SONG_NOTE_SUN					        0x097
#define OOT_SONG_NOTE_TIME					        0x098
#define OOT_SONG_NOTE_STORMS					    0x099
#define OOT_SONG_NOTE_EMPTINESS					    0x09A
#define OOT_SWORD_MASTER					        0x09B
#define OOT_STONE_EMERALD					        0x09C
#define OOT_STONE_RUBY					            0x09D
#define OOT_STONE_SAPPHIRE					        0x09E
#define OOT_MEDALLION_FOREST					    0x09F
#define OOT_MEDALLION_FIRE					        0x0A0
#define OOT_MEDALLION_WATER					        0x0A1
#define OOT_MEDALLION_SPIRIT					    0x0A2
#define OOT_MEDALLION_SHADOW					    0x0A3
#define OOT_MEDALLION_LIGHT					        0x0A4
#define OOT_MAGIC_UPGRADE					        0x0A5
#define OOT_MAGIC_UPGRADE2					        0x0A6
#define OOT_DEFENSE_UPGRADE					        0x0A7
#define OOT_PROGRESSIVE_SHIELD_DEKU					0x0A8
#define OOT_PROGRESSIVE_SHIELD_HYLIAN				0x0A9
#define OOT_SMALL_KEY_FOREST					    0x0AA
#define OOT_SMALL_KEY_FIRE					        0x0AB
#define OOT_SMALL_KEY_WATER					        0x0AC
#define OOT_SMALL_KEY_SPIRIT					    0x0AD
#define OOT_SMALL_KEY_SHADOW					    0x0AE
#define OOT_SMALL_KEY_GANON					        0x0AF
#define OOT_SMALL_KEY_BOTW					        0x0B0
#define OOT_SMALL_KEY_GF					        0x0B1
#define OOT_SMALL_KEY_GTG					        0x0B2
#define OOT_BOSS_KEY_FOREST					        0x0B3
#define OOT_BOSS_KEY_FIRE					        0x0B4
#define OOT_BOSS_KEY_WATER					        0x0B5
#define OOT_BOSS_KEY_SPIRIT					        0x0B6
#define OOT_BOSS_KEY_SHADOW					        0x0B7
#define OOT_BOSS_KEY_GANON					        0x0B8
#define OOT_MAP_DT					                0x0B9
#define OOT_MAP_DC					                0x0BA
#define OOT_MAP_JJ					                0x0BB
#define OOT_MAP_FOREST					            0x0BC
#define OOT_MAP_FIRE					            0x0BD
#define OOT_MAP_WATER					            0x0BE
#define OOT_MAP_SPIRIT					            0x0BF
#define OOT_MAP_SHADOW					            0x0C0
#define OOT_MAP_BOTW					            0x0C1
#define OOT_MAP_IC					                0x0C2
#define OOT_COMPASS_DT					            0x0C3
#define OOT_COMPASS_DC					            0x0C4
#define OOT_COMPASS_JJ					            0x0C5
#define OOT_COMPASS_FOREST					        0x0C6
#define OOT_COMPASS_FIRE					        0x0C7
#define OOT_COMPASS_WATER					        0x0C8
#define OOT_COMPASS_SPIRIT					        0x0C9
#define OOT_COMPASS_SHADOW					        0x0CA
#define OOT_COMPASS_BOTW					        0x0CB
#define OOT_COMPASS_IC					            0x0CC
#define OOT_WALLET					                0x0CD
#define OOT_WALLET4					                0x0CE
#define OOT_TRIFORCE					            0x0CF
#define OOT_WALLET5					                0x0D0
#define OOT_RUPEE_SILVER_DC					        0x0D1
#define OOT_RUPEE_SILVER_BOTW					    0x0D2
#define OOT_RUPEE_SILVER_SPIRIT_CHILD				0x0D3
#define OOT_RUPEE_SILVER_SPIRIT_SUN					0x0D4
#define OOT_RUPEE_SILVER_SPIRIT_BOULDERS			0x0D5
#define OOT_RUPEE_SILVER_SPIRIT_LOBBY				0x0D6
#define OOT_RUPEE_SILVER_SPIRIT_ADULT				0x0D7
#define OOT_RUPEE_SILVER_SHADOW_SCYTHE				0x0D8
#define OOT_RUPEE_SILVER_SHADOW_PIT					0x0D9
#define OOT_RUPEE_SILVER_SHADOW_SPIKES				0x0DA
#define OOT_RUPEE_SILVER_SHADOW_BLADES				0x0DB
#define OOT_RUPEE_SILVER_IC_SCYTHE					0x0DC
#define OOT_RUPEE_SILVER_IC_BLOCK					0x0DD
#define OOT_RUPEE_SILVER_GTG_SLOPES					0x0DE
#define OOT_RUPEE_SILVER_GTG_LAVA					0x0DF
#define OOT_RUPEE_SILVER_GTG_WATER					0x0E0
#define OOT_RUPEE_SILVER_GANON_SPIRIT				0x0E1
#define OOT_RUPEE_SILVER_GANON_LIGHT				0x0E2
#define OOT_RUPEE_SILVER_GANON_FIRE					0x0E3
#define OOT_RUPEE_SILVER_GANON_FOREST				0x0E4
#define OOT_RUPEE_SILVER_GANON_SHADOW				0x0E5
#define OOT_RUPEE_SILVER_GANON_WATER				0x0E6
#define OOT_SOUL_ENEMY_STALFOS					    0x0E7
#define OOT_SOUL_ENEMY_OCTOROK					    0x0E8
#define OOT_SOUL_ENEMY_WALLMASTER					0x0E9
#define OOT_SOUL_ENEMY_DODONGO					    0x0EA
#define OOT_SOUL_ENEMY_KEESE					    0x0EB
#define OOT_SOUL_ENEMY_TEKTITE					    0x0EC
#define OOT_SOUL_ENEMY_LEEVER					    0x0ED
#define OOT_SOUL_ENEMY_PEAHAT					    0x0EE
#define OOT_SOUL_ENEMY_LIZALFOS_DINOLFOS			0x0EF
#define OOT_SOUL_ENEMY_GOHMA_LARVA					0x0F0
#define OOT_SOUL_ENEMY_SHABOM					    0x0F1
#define OOT_SOUL_ENEMY_BABY_DODONGO					0x0F2
#define OOT_SOUL_ENEMY_DARK_LINK					0x0F3
#define OOT_SOUL_ENEMY_BIRI_BARI					0x0F4
#define OOT_SOUL_ENEMY_TAILPASARN					0x0F5
#define OOT_SOUL_ENEMY_PARASITE					    0x0F6
#define OOT_SOUL_ENEMY_SKULLTULA					0x0F7
#define OOT_SOUL_ENEMY_TORCH_SLUG					0x0F8
#define OOT_SOUL_ENEMY_MOBLIN					    0x0F9
#define OOT_SOUL_ENEMY_ARMOS					    0x0FA
#define OOT_SOUL_ENEMY_DEKU_BABA					0x0FB
#define OOT_SOUL_ENEMY_DEKU_SCRUB					0x0FC
#define OOT_SOUL_ENEMY_BUBBLE					    0x0FD
#define OOT_SOUL_ENEMY_BEAMOS					    0x0FE
#define OOT_SOUL_ENEMY_FLOORMASTER					0x0FF
#define OOT_SOUL_ENEMY_REDEAD_GIBDO					0x100
#define OOT_SOUL_ENEMY_SKULLWALLTULA				0x101
#define OOT_SOUL_ENEMY_FLARE_DANCER					0x102
#define OOT_SOUL_ENEMY_DEAD_HAND					0x103
#define OOT_SOUL_ENEMY_SHELL_BLADE					0x104
#define OOT_SOUL_ENEMY_LIKE_LIKE					0x105
#define OOT_SOUL_ENEMY_SPIKE					    0x106
#define OOT_SOUL_ENEMY_ANUBIS					    0x107
#define OOT_SOUL_ENEMY_IRON_KNUCKLE					0x108
#define OOT_SOUL_ENEMY_SKULL_KID					0x109
#define OOT_SOUL_ENEMY_FLYING_POT					0x10A
#define OOT_SOUL_ENEMY_FREEZARD					    0x10B
#define OOT_SOUL_ENEMY_STINGER					    0x10C
#define OOT_SOUL_ENEMY_WOLFOS					    0x10D
#define OOT_SOUL_ENEMY_STALCHILD					0x10E
#define OOT_SOUL_ENEMY_GUAY					        0x10F
#define OOT_SOUL_ENEMY_THIEVES					    0x110
#define OOT_SOUL_ENEMY_POE					        0x111
#define OOT_SOUL_BOSS_QUEEN_GOHMA					0x112
#define OOT_SOUL_BOSS_KING_DODONGO					0x113
#define OOT_SOUL_BOSS_BARINADE					    0x114
#define OOT_SOUL_BOSS_PHANTOM_GANON					0x115
#define OOT_SOUL_BOSS_VOLVAGIA					    0x116
#define OOT_SOUL_BOSS_MORPHA					    0x117
#define OOT_SOUL_BOSS_BONGO_BONGO					0x118
#define OOT_SOUL_BOSS_TWINROVA					    0x119
#define OOT_SOUL_NPC_SARIA					        0x11A
#define OOT_SOUL_NPC_DARUNIA					    0x11B
#define OOT_SOUL_NPC_RUTO					        0x11C
#define OOT_SOUL_NPC_KING_ZORA					    0x11D
#define OOT_SOUL_NPC_ZELDA					        0x11E
#define OOT_SOUL_NPC_SHEIK					        0x11F
#define OOT_SOUL_NPC_ANJU					        0x120
#define OOT_SOUL_NPC_CARPENTERS					    0x121
#define OOT_SOUL_NPC_GURU_GURU					    0x122
#define OOT_SOUL_NPC_MIDO					        0x123
#define OOT_SOUL_NPC_KOKIRI					        0x124
#define OOT_SOUL_NPC_KOKIRI_SHOPKEEPER				0x125
#define OOT_SOUL_NPC_HYLIAN_GUARD					0x126
#define OOT_SOUL_NPC_CITIZEN					    0x127
#define OOT_SOUL_NPC_MALON					        0x128
#define OOT_SOUL_NPC_TALON					        0x129
#define OOT_SOUL_NPC_FISHING_POND_OWNER				0x12A
#define OOT_SOUL_NPC_GORON					        0x12B
#define OOT_SOUL_NPC_MEDIGORON					    0x12C
#define OOT_SOUL_NPC_BIGGORON					    0x12D
#define OOT_SOUL_NPC_GORON_CHILD					0x12E
#define OOT_SOUL_NPC_GORON_SHOPKEEPER				0x12F
#define OOT_SOUL_NPC_ZORA					        0x130
#define OOT_SOUL_NPC_ZORA_SHOPKEEPER				0x131
#define OOT_SOUL_NPC_BAZAAR_SHOPKEEPER				0x132
#define OOT_SOUL_NPC_BOMBCHU_SHOPKEEPER				0x133
#define OOT_SOUL_NPC_POTION_SHOPKEEPER				0x134
#define OOT_SOUL_NPC_BOMBCHU_BOWLING_LADY			0x135
#define OOT_SOUL_NPC_CHEST_GAME_OWNER				0x136
#define OOT_SOUL_NPC_SHOOTING_GALLERY_OWNER			0x137
#define OOT_SOUL_NPC_DAMPE					        0x138
#define OOT_SOUL_NPC_BOMBERS					    0x139
#define OOT_SOUL_NPC_POE_COLLECTOR					0x13A
#define OOT_SOUL_NPC_COMPOSER_BROS					0x13B
#define OOT_SOUL_NPC_HONEY_DARLING					0x13C
#define OOT_SOUL_NPC_ASTRONOMER					    0x13D
#define OOT_SOUL_NPC_ROOFTOP_MAN					0x13E
#define OOT_SOUL_NPC_BEAN_SALESMAN					0x13F
#define OOT_SOUL_NPC_SCIENTIST					    0x140
#define OOT_SOUL_NPC_GORMAN					        0x141
#define OOT_SOUL_NPC_GROG					        0x142
#define OOT_SOUL_NPC_DOG_LADY					    0x143
#define OOT_SOUL_NPC_CARPET_MAN					    0x144
#define OOT_SOUL_NPC_OLD_HAG					    0x145
#define OOT_SOUL_NPC_BANKER					        0x146
#define OOT_SOUL_NPC_THIEVES					    0x147
#define OOT_SOUL_ANIMAL_CUCCO					    0x148
#define OOT_SOUL_ANIMAL_COW					        0x149
#define OOT_SOUL_ANIMAL_DOG					        0x14A
#define OOT_SOUL_ANIMAL_BUTTERFLY					0x14B
#define OOT_SOUL_MISC_GS					        0x14C
#define OOT_SOUL_MISC_BUSINESS_SCRUB				0x14D
#define OOT_KEY_RING					            0x14E
#define OOT_KEY_RING_FOREST					        0x14F
#define OOT_KEY_RING_FIRE					        0x150
#define OOT_KEY_RING_WATER					        0x151
#define OOT_KEY_RING_SPIRIT					        0x152
#define OOT_KEY_RING_SHADOW					        0x153
#define OOT_KEY_RING_GANON					        0x154
#define OOT_KEY_RING_BOTW					        0x155
#define OOT_KEY_RING_GF					            0x156
#define OOT_KEY_RING_GTG					        0x157
#define OOT_SKELETON_KEY					        0x158
#define OOT_COIN_RED					            0x159
#define OOT_COIN_GREEN					            0x15A
#define OOT_COIN_BLUE					            0x15B
#define OOT_COIN_YELLOW					            0x15C
#define OOT_TRIFORCE_POWER					        0x15D
#define OOT_TRIFORCE_COURAGE					    0x15E
#define OOT_TRIFORCE_WISDOM					        0x15F
#define OOT_POUCH_SILVER_DC					        0x160
#define OOT_POUCH_SILVER_BOTW					    0x161
#define OOT_POUCH_SILVER_SPIRIT_CHILD				0x162
#define OOT_POUCH_SILVER_SPIRIT_SUN					0x163
#define OOT_POUCH_SILVER_SPIRIT_BOULDERS			0x164
#define OOT_POUCH_SILVER_SPIRIT_LOBBY				0x165
#define OOT_POUCH_SILVER_SPIRIT_ADULT				0x166
#define OOT_POUCH_SILVER_SHADOW_SCYTHE				0x167
#define OOT_POUCH_SILVER_SHADOW_PIT					0x168
#define OOT_POUCH_SILVER_SHADOW_SPIKES				0x169
#define OOT_POUCH_SILVER_SHADOW_BLADES				0x16A
#define OOT_POUCH_SILVER_IC_SCYTHE					0x16B
#define OOT_POUCH_SILVER_IC_BLOCK					0x16C
#define OOT_POUCH_SILVER_GTG_SLOPES					0x16D
#define OOT_POUCH_SILVER_GTG_LAVA					0x16E
#define OOT_POUCH_SILVER_GTG_WATER					0x16F
#define OOT_POUCH_SILVER_GANON_SPIRIT				0x170
#define OOT_POUCH_SILVER_GANON_LIGHT				0x171
#define OOT_POUCH_SILVER_GANON_FIRE					0x172
#define OOT_POUCH_SILVER_GANON_FOREST				0x173
#define OOT_POUCH_SILVER_GANON_SHADOW				0x174
#define OOT_POUCH_SILVER_GANON_WATER				0x175
#define OOT_RUPEE_MAGICAL					        0x176
#define OOT_BUTTON_A					            0x177
#define OOT_BUTTON_C_RIGHT					        0x178
#define OOT_BUTTON_C_LEFT					        0x179
#define OOT_BUTTON_C_UP					            0x17A
#define OOT_BUTTON_C_DOWN					        0x17B
#define OOT_SMALL_KEY_TCG					        0x17C
#define OOT_KEY_RING_TCG					        0x17D
#define OOT_BOTTLE_POTION_RED					    0x17E
#define OOT_BOTTLE_POTION_GREEN					    0x17F
#define OOT_BOTTLE_POTION_BLUE					    0x180
#define OOT_BOTTLE_FAIRY					        0x181
#define OOT_BOTTLE_POE					            0x182
#define OOT_BOTTLE_BIG_POE					        0x183
#define OOT_BOTTLE_BLUE_FIRE					    0x184
#define OOT_FISHING_POND_CHILD_FISH_2LBS			0x185
#define OOT_FISHING_POND_CHILD_FISH_3LBS			0x186
#define OOT_FISHING_POND_CHILD_FISH_4LBS			0x187
#define OOT_FISHING_POND_CHILD_FISH_5LBS			0x188
#define OOT_FISHING_POND_CHILD_FISH_6LBS			0x189
#define OOT_FISHING_POND_CHILD_FISH_7LBS			0x18A
#define OOT_FISHING_POND_CHILD_FISH_8LBS			0x18B
#define OOT_FISHING_POND_CHILD_FISH_9LBS			0x18C
#define OOT_FISHING_POND_CHILD_FISH_10LBS			0x18D
#define OOT_FISHING_POND_CHILD_FISH_11LBS			0x18E
#define OOT_FISHING_POND_CHILD_FISH_12LBS			0x18F
#define OOT_FISHING_POND_CHILD_FISH_13LBS			0x190
#define OOT_FISHING_POND_CHILD_FISH_14LBS			0x191
#define OOT_FISHING_POND_ADULT_FISH_4LBS			0x192
#define OOT_FISHING_POND_ADULT_FISH_5LBS			0x193
#define OOT_FISHING_POND_ADULT_FISH_6LBS			0x194
#define OOT_FISHING_POND_ADULT_FISH_7LBS			0x195
#define OOT_FISHING_POND_ADULT_FISH_8LBS			0x196
#define OOT_FISHING_POND_ADULT_FISH_9LBS			0x197
#define OOT_FISHING_POND_ADULT_FISH_10LBS			0x198
#define OOT_FISHING_POND_ADULT_FISH_11LBS			0x199
#define OOT_FISHING_POND_ADULT_FISH_12LBS			0x19A
#define OOT_FISHING_POND_ADULT_FISH_13LBS			0x19B
#define OOT_FISHING_POND_ADULT_FISH_14LBS			0x19C
#define OOT_FISHING_POND_ADULT_FISH_15LBS			0x19D
#define OOT_FISHING_POND_ADULT_FISH_16LBS			0x19E
#define OOT_FISHING_POND_ADULT_FISH_17LBS			0x19F
#define OOT_FISHING_POND_ADULT_FISH_18LBS			0x1A0
#define OOT_FISHING_POND_ADULT_FISH_19LBS			0x1A1
#define OOT_FISHING_POND_ADULT_FISH_20LBS			0x1A2
#define OOT_FISHING_POND_ADULT_FISH_21LBS			0x1A3
#define OOT_FISHING_POND_ADULT_FISH_22LBS			0x1A4
#define OOT_FISHING_POND_ADULT_FISH_23LBS			0x1A5
#define OOT_FISHING_POND_ADULT_FISH_24LBS			0x1A6
#define OOT_FISHING_POND_ADULT_FISH_25LBS			0x1A7
#define OOT_FISHING_POND_CHILD_LOACH_14LBS			0x1A8
#define OOT_FISHING_POND_CHILD_LOACH_15LBS			0x1A9
#define OOT_FISHING_POND_CHILD_LOACH_16LBS			0x1AA
#define OOT_FISHING_POND_CHILD_LOACH_17LBS			0x1AB
#define OOT_FISHING_POND_CHILD_LOACH_18LBS			0x1AC
#define OOT_FISHING_POND_CHILD_LOACH_19LBS			0x1AD
#define OOT_FISHING_POND_ADULT_LOACH_29LBS			0x1AE
#define OOT_FISHING_POND_ADULT_LOACH_30LBS			0x1AF
#define OOT_FISHING_POND_ADULT_LOACH_31LBS			0x1B0
#define OOT_FISHING_POND_ADULT_LOACH_32LBS			0x1B1
#define OOT_FISHING_POND_ADULT_LOACH_33LBS			0x1B2
#define OOT_FISHING_POND_ADULT_LOACH_34LBS			0x1B3
#define OOT_FISHING_POND_ADULT_LOACH_35LBS			0x1B4
#define OOT_FISHING_POND_ADULT_LOACH_36LBS			0x1B5
#define OOT_BOMBCHU_BAG					            0x1B6
#define OOT_BOMBCHU_BAG2					        0x1B7
#define OOT_BOMBCHU_BAG3					        0x1B8
#define OOT_BOMBCHU_BAG_FIRST_5					    0x1B9
#define OOT_BOMBCHU_BAG_FIRST_10					0x1BA
#define OOT_BOMBCHU_BAG_FIRST_20					0x1BB
#define OOT_SWORD_RAZOR					            0x1BC
#define OOT_SWORD_GILDED					        0x1BD
#define OOT_SPIN_UPGRADE					        0x1BE
#define OOT_TRIFORCE_FULL					        0x1BF
#define OOT_FAIRY_BIG					            0x1C0
#define OOT_MASK_BLAST					            0x1C1
#define OOT_MASK_STONE					            0x1C2
#define OOT_SCALE_BRONZE					        0x1C3
#define OOT_WEIRD_MUSHROOM					        0x1C4
#define OOT_CHATEAU					                0x1C5
#define OOT_GOLD_DUST					            0x1C6
#define OOT_SEAHORSE2					            0x1C7
#define OOT_BOTTLED_GOLD_DUST					    0x1C8
#define OOT_BOTTLE_CHATEAU					        0x1C9
#define OOT_TRAP_ICE					            0x1CA
#define OOT_TRAP_FIRE					            0x1CB
#define OOT_TRAP_SHOCK					            0x1CC
#define OOT_TRAP_DRAIN					            0x1CD
#define OOT_TRAP_ANTI_MAGIC					        0x1CE
#define OOT_TRAP_KNOCKBACK					        0x1CF
#define OOT_TRAP_RUPOOR					            0x1D0
#define OOT_PLATINUM_TOKEN					        0x1D1

#pragma endregion OoT

#pragma region MM

#define MM_RUPEE_GREEN					            0x1D2
#define MM_RUPEE_BLUE					            0x1D3
#define MM_RUPEE_RED_10					            0x1D4
#define MM_RUPEE_RED					            0x1D5
#define MM_RUPEE_PURPLE					            0x1D6
#define MM_RUPEE_SILVER					            0x1D7
#define MM_RUPEE_GOLD					            0x1D8
#define MM_WALLET2					                0x1D9
#define MM_WALLET3					                0x1DA
#define MM_RECOVERY_HEART					        0x1DB
#define MM_HEART_PIECE					            0x1DC
#define MM_HEART_CONTAINER					        0x1DD
#define MM_MAGIC_JAR_SMALL					        0x1DE
#define MM_MAGIC_JAR_LARGE					        0x1DF
#define MM_STRAY_FAIRY					            0x1E0
#define MM_STRAY_FAIRY_WF					        0x1E1
#define MM_STRAY_FAIRY_SH					        0x1E2
#define MM_STRAY_FAIRY_GB					        0x1E3
#define MM_STRAY_FAIRY_ST					        0x1E4
#define MM_STRAY_FAIRY_TOWN					        0x1E5
#define MM_TRANSCENDENT_FAIRY					    0x1E6
#define MM_BOMB					                    0x1E7
#define MM_BOMBS_5					                0x1E8
#define MM_BOMBS_10					                0x1E9
#define MM_BOMBS_20					                0x1EA
#define MM_BOMBS_30					                0x1EB
#define MM_STICK					                0x1EC
#define MM_BOMBCHU_10					            0x1ED
#define MM_BOMB_BAG					                0x1EE
#define MM_BOMB_BAG2					            0x1EF
#define MM_BOMB_BAG3					            0x1F0
#define MM_ARROWS_10					            0x1F1
#define MM_ARROWS_30					            0x1F2
#define MM_ARROWS_40					            0x1F3
#define MM_UNK_21					                0x1F4
#define MM_BOW					                    0x1F5
#define MM_QUIVER2					                0x1F6
#define MM_QUIVER3					                0x1F7
#define MM_ARROW_FIRE					            0x1F8
#define MM_ARROW_ICE					            0x1F9
#define MM_ARROW_LIGHT					            0x1FA
#define MM_NUT					                    0x1FB
#define MM_NUTS_5					                0x1FC
#define MM_NUTS_10					                0x1FD
#define MM_UNK_2B					                0x1FE
#define MM_UNK_2C					                0x1FF
#define MM_UNK_2D					                0x200
#define MM_BOMBCHU_20					            0x201
#define MM_UNK_2F					                0x202
#define MM_UNK_30					                0x203
#define MM_UNK_31					                0x204
#define MM_SHIELD_DEKU					            0x205
#define MM_SHIELD_HERO					            0x206
#define MM_SHIELD_MIRROR					        0x207
#define MM_PROGRESSIVE_SHIELD_DEKU					0x208
#define MM_PROGRESSIVE_SHIELD_HERO					0x209
#define MM_POWDER_KEG					            0x20A
#define MM_MAGIC_BEAN					            0x20B
#define MM_BOMBCHU					                0x20C
#define MM_SWORD_KOKIRI					            0x20D
#define MM_SWORD_RAZOR					            0x20E
#define MM_SWORD_GILDED					            0x20F
#define MM_BOMBCHU_5					            0x210
#define MM_GREAT_FAIRY_SWORD					    0x211
#define MM_SMALL_KEY					            0x212
#define MM_BOSS_KEY					                0x213
#define MM_MAP					                    0x214
#define MM_COMPASS					                0x215
#define MM_HOOKSHOT					                0x216
#define MM_LENS					                    0x217
#define MM_PICTOGRAPH_BOX					        0x218
#define MM_OCARINA_OF_TIME					        0x219
#define MM_BOMBER_NOTEBOOK					        0x21A
#define MM_BOTTLE_POTION_RED					    0x21B
#define MM_BOTTLE_EMPTY					            0x21C
#define MM_POTION_RED					            0x21D
#define MM_POTION_GREEN					            0x21E
#define MM_POTION_BLUE					            0x21F
#define MM_FAIRY					                0x220
#define MM_BOTTLE_MILK					            0x221
#define MM_FISH					                    0x222
#define MM_BUGS					                    0x223
#define MM_BIG_POE					                0x224
#define MM_BOTTLED_GOLD_DUST					    0x225
#define MM_WEIRD_MUSHROOM					        0x226
#define MM_BOTTLE_CHATEAU					        0x227
#define MM_MASK_DEKU					            0x228
#define MM_MASK_GORON					            0x229
#define MM_MASK_ZORA					            0x22A
#define MM_MASK_FIERCE_DEITY					    0x22B
#define MM_MASK_CAPTAIN					            0x22C
#define MM_MASK_GIANT					            0x22D
#define MM_MASK_ALL_NIGHT					        0x22E
#define MM_MASK_BUNNY					            0x22F
#define MM_MASK_KEATON					            0x230
#define MM_MASK_GARO					            0x231
#define MM_MASK_ROMANI					            0x232
#define MM_MASK_TROUPE_LEADER					    0x233
#define MM_MASK_POSTMAN					            0x234
#define MM_MASK_COUPLE					            0x235
#define MM_MASK_GREAT_FAIRY					        0x236
#define MM_MASK_GIBDO					            0x237
#define MM_MASK_DON_GERO					        0x238
#define MM_MASK_KAMARO					            0x239
#define MM_MASK_TRUTH					            0x23A
#define MM_MASK_STONE					            0x23B
#define MM_MASK_BREMEN					            0x23C
#define MM_MASK_BLAST					            0x23D
#define MM_MASK_SCENTS					            0x23E
#define MM_MASK_KAFEI					            0x23F
#define MM_CHATEAU					                0x240
#define MM_MILK					                    0x241
#define MM_GOLD_DUST					            0x242
#define MM_SEAHORSE2					            0x243
#define MM_MOON_TEAR					            0x244
#define MM_DEED_LAND					            0x245
#define MM_DEED_SWAMP					            0x246
#define MM_DEED_MOUNTAIN					        0x247
#define MM_DEED_OCEAN					            0x248
#define MM_ROOM_KEY					                0x249
#define MM_LETTER_TO_MAMA					        0x24A
#define MM_LETTER_TO_KAFEI					        0x24B
#define MM_PENDANT_OF_MEMORIES					    0x24C
#define MM_WORLD_MAP_CLOCK_TOWN					    0x24D
#define MM_WORLD_MAP_WOODFALL					    0x24E
#define MM_WORLD_MAP_SNOWHEAD					    0x24F
#define MM_WORLD_MAP_ROMANI_RANCH					0x250
#define MM_WORLD_MAP_GREAT_BAY					    0x251
#define MM_WORLD_MAP_STONE_TOWER					0x252
#define MM_MAGIC_UPGRADE					        0x253
#define MM_MAGIC_UPGRADE2					        0x254
#define MM_DEFENSE_UPGRADE					        0x255
#define MM_SPIN_UPGRADE					            0x256
#define MM_SONG_AWAKENING					        0x257
#define MM_SONG_GORON					            0x258
#define MM_SONG_ZORA					            0x259
#define MM_SONG_EMPTINESS					        0x25A
#define MM_SONG_ORDER					            0x25B
#define MM_SONG_TIME					            0x25C
#define MM_SONG_HEALING					            0x25D
#define MM_SONG_EPONA					            0x25E
#define MM_SONG_SOARING					            0x25F
#define MM_SONG_STORMS_ITEM					        0x260
#define MM_SONG_SUN					                0x261
#define MM_SONG_GORON_HALF					        0x262
#define MM_SONG_NOTE_AWAKENING					    0x263
#define MM_SONG_NOTE_GORON					        0x264
#define MM_SONG_NOTE_ZORA					        0x265
#define MM_SONG_NOTE_EMPTINESS					    0x266
#define MM_SONG_NOTE_ORDER					        0x267
#define MM_SONG_NOTE_TIME					        0x268
#define MM_SONG_NOTE_HEALING					    0x269
#define MM_SONG_NOTE_EPONA					        0x26A
#define MM_SONG_NOTE_SOARING					    0x26B
#define MM_SONG_NOTE_STORMS					        0x26C
#define MM_SONG_NOTE_SUN					        0x26D
#define MM_REMAINS_ODOLWA					        0x26E
#define MM_REMAINS_GOHT					            0x26F
#define MM_REMAINS_GYORG					        0x270
#define MM_REMAINS_TWINMOLD					        0x271
#define MM_GS_TOKEN_SWAMP					        0x272
#define MM_GS_TOKEN_OCEAN					        0x273
#define MM_PLATINUM_TOKEN					        0x274
#define MM_SMALL_KEY_WF					            0x275
#define MM_SMALL_KEY_SH					            0x276
#define MM_SMALL_KEY_GB					            0x277
#define MM_SMALL_KEY_ST					            0x278
#define MM_BOSS_KEY_WF					            0x279
#define MM_BOSS_KEY_SH					            0x27A
#define MM_BOSS_KEY_GB					            0x27B
#define MM_BOSS_KEY_ST					            0x27C
#define MM_MAP_WF					                0x27D
#define MM_MAP_SH					                0x27E
#define MM_MAP_GB					                0x27F
#define MM_MAP_ST					                0x280
#define MM_COMPASS_WF					            0x281
#define MM_COMPASS_SH					            0x282
#define MM_COMPASS_GB					            0x283
#define MM_COMPASS_ST					            0x284
#define MM_OCARINA_FAIRY					        0x285
#define MM_HOOKSHOT_SHORT					        0x286
#define MM_WALLET					                0x287
#define MM_WALLET4					                0x288
#define MM_OWL_GREAT_BAY					        0x289
#define MM_OWL_ZORA_CAPE					        0x28A
#define MM_OWL_SNOWHEAD					            0x28B
#define MM_OWL_MOUNTAIN_VILLAGE					    0x28C
#define MM_OWL_CLOCK_TOWN					        0x28D
#define MM_OWL_MILK_ROAD					        0x28E
#define MM_OWL_WOODFALL					            0x28F
#define MM_OWL_SOUTHERN_SWAMP					    0x290
#define MM_OWL_IKANA_CANYON					        0x291
#define MM_OWL_STONE_TOWER					        0x292
#define MM_OWL_HIDDEN					            0x293
#define MM_WALLET5					                0x294
#define MM_SOUL_ENEMY_OCTOROK					    0x295
#define MM_SOUL_ENEMY_WALLMASTER					0x296
#define MM_SOUL_ENEMY_DODONGO					    0x297
#define MM_SOUL_ENEMY_KEESE					        0x298
#define MM_SOUL_ENEMY_TEKTITE					    0x299
#define MM_SOUL_ENEMY_PEAHAT					    0x29A
#define MM_SOUL_ENEMY_LIZALFOS_DINOLFOS				0x29B
#define MM_SOUL_ENEMY_SKULLTULA					    0x29C
#define MM_SOUL_ENEMY_ARMOS					        0x29D
#define MM_SOUL_ENEMY_DEKU_BABA					    0x29E
#define MM_SOUL_ENEMY_DEKU_SCRUB					0x29F
#define MM_SOUL_ENEMY_BUBBLE					    0x2A0
#define MM_SOUL_ENEMY_BEAMOS					    0x2A1
#define MM_SOUL_ENEMY_REDEAD_GIBDO					0x2A2
#define MM_SOUL_ENEMY_SKULLWALLTULA					0x2A3
#define MM_SOUL_ENEMY_SHELL_BLADE					0x2A4
#define MM_SOUL_ENEMY_LIKE_LIKE					    0x2A5
#define MM_SOUL_ENEMY_IRON_KNUCKLE					0x2A6
#define MM_SOUL_ENEMY_FREEZARD					    0x2A7
#define MM_SOUL_ENEMY_WOLFOS					    0x2A8
#define MM_SOUL_ENEMY_GUAY					        0x2A9
#define MM_SOUL_ENEMY_FLYING_POT					0x2AA
#define MM_SOUL_ENEMY_FLOORMASTER					0x2AB
#define MM_SOUL_ENEMY_CHUCHU					    0x2AC
#define MM_SOUL_ENEMY_DEEP_PYTHON					0x2AD
#define MM_SOUL_ENEMY_STALCHILD					    0x2AE
#define MM_SOUL_ENEMY_LEEVER					    0x2AF
#define MM_SOUL_ENEMY_SKULLFISH					    0x2B0
#define MM_SOUL_ENEMY_DEXIHAND					    0x2B1
#define MM_SOUL_ENEMY_DRAGONFLY					    0x2B2
#define MM_SOUL_ENEMY_EENO					        0x2B3
#define MM_SOUL_ENEMY_EYEGORE					    0x2B4
#define MM_SOUL_ENEMY_HIPLOOP					    0x2B5
#define MM_SOUL_ENEMY_REAL_BOMBCHU					0x2B6
#define MM_SOUL_ENEMY_TAKKURI					    0x2B7
#define MM_SOUL_ENEMY_BOE					        0x2B8
#define MM_SOUL_ENEMY_NEJIRON					    0x2B9
#define MM_SOUL_ENEMY_BIO_BABA					    0x2BA
#define MM_SOUL_ENEMY_GARO					        0x2BB
#define MM_SOUL_ENEMY_WIZZROBE					    0x2BC
#define MM_SOUL_ENEMY_GOMESS					    0x2BD
#define MM_SOUL_ENEMY_GEKKO					        0x2BE
#define MM_SOUL_ENEMY_BAD_BAT					    0x2BF
#define MM_SOUL_ENEMY_SNAPPER					    0x2C0
#define MM_SOUL_ENEMY_WART					        0x2C1
#define MM_SOUL_ENEMY_CAPTAIN_KEETA					0x2C2
#define MM_SOUL_ENEMY_THIEVES					    0x2C3
#define MM_SOUL_ENEMY_POE					        0x2C4
#define MM_SOUL_BOSS_ODOLWA					        0x2C5
#define MM_SOUL_BOSS_GOHT					        0x2C6
#define MM_SOUL_BOSS_GYORG					        0x2C7
#define MM_SOUL_BOSS_TWINMOLD					    0x2C8
#define MM_SOUL_BOSS_IGOS					        0x2C9
#define MM_SOUL_NPC_AROMA					        0x2CA
#define MM_SOUL_NPC_SHOOTING_GALLERY_OWNER			0x2CB
#define MM_SOUL_NPC_BAZAAR_SHOPKEEPER				0x2CC
#define MM_SOUL_NPC_GORON					        0x2CD
#define MM_SOUL_NPC_GORON_CHILD					    0x2CE
#define MM_SOUL_NPC_BOMBCHU_SHOPKEEPER				0x2CF
#define MM_SOUL_NPC_BOMBERS					        0x2D0
#define MM_SOUL_NPC_BUTLER_DEKU					    0x2D1
#define MM_SOUL_NPC_CITIZEN					        0x2D2
#define MM_SOUL_NPC_COMPOSER_BROS					0x2D3
#define MM_SOUL_NPC_DAMPE					        0x2D4
#define MM_SOUL_NPC_DEKU_KING					    0x2D5
#define MM_SOUL_NPC_DEKU_PRINCESS					0x2D6
#define MM_SOUL_NPC_PLAYGROUND_SCRUBS				0x2D7
#define MM_SOUL_NPC_GORON_ELDER					    0x2D8
#define MM_SOUL_NPC_CHEST_GAME_OWNER				0x2D9
#define MM_SOUL_NPC_GORON_SHOPKEEPER				0x2DA
#define MM_SOUL_NPC_HONEY_DARLING					0x2DB
#define MM_SOUL_NPC_TOTO					        0x2DC
#define MM_SOUL_NPC_RUTO					        0x2DD
#define MM_SOUL_NPC_ZORA_MUSICIANS					0x2DE
#define MM_SOUL_NPC_KAFEI					        0x2DF
#define MM_SOUL_NPC_KEATON					        0x2E0
#define MM_SOUL_NPC_KOUME_KOTAKE					0x2E1
#define MM_SOUL_NPC_MAYOR_DOTOUR					0x2E2
#define MM_SOUL_NPC_MEDIGORON					    0x2E3
#define MM_SOUL_NPC_BIGGORON					    0x2E4
#define MM_SOUL_NPC_TALON					        0x2E5
#define MM_SOUL_NPC_ASTRONOMER					    0x2E6
#define MM_SOUL_NPC_POE_COLLECTOR					0x2E7
#define MM_SOUL_NPC_BLACKSMITHS					    0x2E8
#define MM_SOUL_NPC_BOMBCHU_BOWLING_LADY			0x2E9
#define MM_SOUL_NPC_TINGLE					        0x2EA
#define MM_SOUL_NPC_TOILET_HAND					    0x2EB
#define MM_SOUL_NPC_FISHING_POND_OWNER				0x2EC
#define MM_SOUL_NPC_ROOFTOP_MAN					    0x2ED
#define MM_SOUL_NPC_ZORA					        0x2EE
#define MM_SOUL_NPC_ZORA_SHOPKEEPER					0x2EF
#define MM_SOUL_NPC_MALON					        0x2F0
#define MM_SOUL_NPC_BEAN_SALESMAN					0x2F1
#define MM_SOUL_NPC_CARPENTERS					    0x2F2
#define MM_SOUL_NPC_ANJU					        0x2F3
#define MM_SOUL_NPC_GURU_GURU					    0x2F4
#define MM_SOUL_NPC_SCIENTIST					    0x2F5
#define MM_SOUL_NPC_GORMAN					        0x2F6
#define MM_SOUL_NPC_GROG					        0x2F7
#define MM_SOUL_NPC_DOG_LADY					    0x2F8
#define MM_SOUL_NPC_CARPET_MAN					    0x2F9
#define MM_SOUL_NPC_OLD_HAG					        0x2FA
#define MM_SOUL_NPC_TOURIST_CENTER					0x2FB
#define MM_SOUL_NPC_BANKER					        0x2FC
#define MM_SOUL_NPC_MOON_CHILDREN					0x2FD
#define MM_SOUL_NPC_THIEVES					        0x2FE
#define MM_SOUL_ANIMAL_CUCCO					    0x2FF
#define MM_SOUL_ANIMAL_COW					        0x300
#define MM_SOUL_ANIMAL_DOG					        0x301
#define MM_SOUL_ANIMAL_BUTTERFLY					0x302
#define MM_SOUL_MISC_GS					            0x303
#define MM_SOUL_MISC_BUSINESS_SCRUB					0x304
#define MM_KEY_RING					                0x305
#define MM_KEY_RING_WF					            0x306
#define MM_KEY_RING_SH					            0x307
#define MM_KEY_RING_GB					            0x308
#define MM_KEY_RING_ST					            0x309
#define MM_SKELETON_KEY					            0x30A
#define MM_BUTTON_A					                0x30B
#define MM_BUTTON_C_RIGHT					        0x30C
#define MM_BUTTON_C_LEFT					        0x30D
#define MM_BUTTON_C_UP					            0x30E
#define MM_BUTTON_C_DOWN					        0x30F
#define MM_BOTTLE_POTION_GREEN					    0x310
#define MM_BOTTLE_POTION_BLUE					    0x311
#define MM_BOTTLE_FAIRY					            0x312
#define MM_POE					                    0x313
#define MM_BOTTLE_POE					            0x314
#define MM_BOTTLE_BIG_POE				            0x315
#define MM_BOMBCHU_BAG					            0x316
#define MM_BOMBCHU_BAG2					            0x317
#define MM_BOMBCHU_BAG3					            0x318
#define MM_BOMBCHU_BAG_FIRST_1					    0x319
#define MM_BOMBCHU_BAG_FIRST_5					    0x31A
#define MM_BOMBCHU_BAG_FIRST_10					    0x31B
#define MM_BOMBCHU_BAG_FIRST_20					    0x31C
#define MM_FAIRY_BIG					            0x31D
#define MM_SPELL_FIRE					            0x31E
#define MM_SPELL_WIND					            0x31F
#define MM_SPELL_LOVE					            0x320
#define MM_BOOTS_IRON					            0x321
#define MM_BOOTS_HOVER					            0x322
#define MM_TUNIC_GORON					            0x323
#define MM_TUNIC_ZORA					            0x324
#define MM_SCALE_BRONZE					            0x325
#define MM_SCALE_SILVER					            0x326
#define MM_SCALE_GOLDEN					            0x327
#define MM_GORON_BRACELET					        0x328
#define MM_SILVER_GAUNTLETS					        0x329
#define MM_GOLDEN_GAUNTLETS					        0x32A
#define MM_CLOCK1					                0x32B
#define MM_CLOCK2					                0x32C
#define MM_CLOCK3					                0x32D
#define MM_CLOCK4					                0x32E
#define MM_CLOCK5					                0x32F
#define MM_CLOCK6					                0x330
#define MM_HAMMER					                0x331
#define MM_STICK_UPGRADE					        0x332
#define MM_STICK_UPGRADE2					        0x333
#define MM_NUT_UPGRADE					            0x334
#define MM_NUT_UPGRADE2					            0x335
#define MM_STONE_OF_AGONY					        0x336
#define MM_BOTTLE_RUTO_LETTER					    0x337
#define MM_BOTTLE_BLUE_FIRE					        0x338
#define MM_BLUE_FIRE					            0x339
#define MM_MASK_MAJORA					            0x33A
#define MM_SOLD_OUT					                0x33B
#define NOTHING					                    0x33C
#define MM_SCOOP					                0x33D

#pragma endregion MM

#pragma endregion Degines

typedef struct ComboItem
{
	uint8_t GameID;
	uint8_t OvType;
	uint32_t SceneID;
	uint32_t RoomID;
	uint32_t ObjectID;
} ComboItem;


typedef struct ItemInfo
{
	uint32_t ItemID;
	const char* ItemName;
    EGameIcon RenderType;
} ItemInfo;



/*
*   Decode a raw 5 byte combo key into its matching ComboItem fields.
*
*   @param Key      The raw 5 byte key (Game, OvType, Scene, Room, Object).
*   @param Item     The combo item to populate with the decoded values.
*/
void ParseKey(uint8_t Key[5], ComboItem* Item);

/*
*   Find the item information matching the given item ID.
*
*   @param gi       The item ID to search for.
*
*   @return The item information matching the given ID, or a null pointer if none matched.
*/
const ItemInfo * FindItem(uint32_t gi);

/*
*   Find the item information matching the given item name.
*
*   @param Name     The item name to search for (newlines are stripped before matching).
*
*   @return The item information matching the given name, or a null pointer if none matched.
*/
const ItemInfo* FindItemByName(QString Name);
