#pragma once

#include "Multi/Multi.h"

typedef struct ComboItem
{
	uint8_t GameID;
	uint8_t OvType;
	uint32_t SceneID;
	uint32_t RoomID;
	uint32_t ObjectID;
} ComboItem;


typedef struct ItemInfo
{
	uint32_t ItemID;
	const char* ItemName;
} ItemInfo;


#pragma region Items

#define NUM_ITEM 767

const ItemInfo ItemList[NUM_ITEM] =
{
	{ 0x01, "5 Bombs (OoT)" },
	{ 0x02, "5 Deku Nuts (OoT)" },
	{ 0x03, "10 Bombchu (OoT)" },
	{ 0x04, "Fairy Bow (OoT)" },
	{ 0x05, "Fairy Slingshot" },
	{ 0x06, "Boomerang" },
	{ 0x07, "Deku Stick (OoT)" },
	{ 0x08, "Hookshot" },
	{ 0x09, "Longshot" },
	{ 0x0A, "Lens of Truth (OoT)" },
	{ 0x0B, "Zelda's Letter" },
	{ 0x0C, "Ocarina of Time (OoT)" },
	{ 0x0D, "Megaton Hammer (OoT)" },
	{ 0x0E, "Cojiro" },
	{ 0x0F, "Unknown" },
	{ 0x10, "Red Potion (OoT)" },
	{ 0x11, "Green Potion (OoT)" },
	{ 0x12, "Blue Potion (OoT)" },
	{ 0x13, "Fairy (OoT)" },
	{ 0x14, "Lon Lon Milk (OoT)" },
	{ 0x15, "Ruto's Letter" },
	{ 0x16, "Magic Bean (OoT)" },
	{ 0x17, "Skull Mask" },
	{ 0x18, "Spooky Mask" },
	{ 0x19, "Chicken" },
	{ 0x1A, "Keaton Mask (OoT)" },
	{ 0x1B, "Bunny Hood (OoT)" },
	{ 0x1C, "Mask of Truth (OoT)" },
	{ 0x1D, "Pocket Egg" },
	{ 0x1E, "Pocket Cucco" },
	{ 0x1F, "Odd Mushroom" },
	{ 0x20, "Odd Potion" },
	{ 0x21, "Poacher's Saw" },
	{ 0x22, "Unknown" },
	{ 0x23, "Prescription" },
	{ 0x24, "Eyeball Frog" },
	{ 0x25, "Eye Drops" },
	{ 0x26, "Claim Check" },
	{ 0x27, "Kokiri's Sword (OoT)" },
	{ 0x28, "Giant's Knife" },
	{ 0x29, "Deku Shield" },
	{ 0x2A, "Hylian Shield" },
	{ 0x2B, "Mirror Shield (OoT)" },
	{ 0x2C, "Goron Tunic (OoT)" },
	{ 0x2D, "Zora Tunic (OoT)" },
	{ 0x2E, "Iron Boots (OoT)" },
	{ 0x2F, "Hover Boots (OoT)" },
	{ 0x30, "Unknown" },
	{ 0x31, "Unknown" },
	{ 0x32, "Bomb Bag (OoT)" },
	{ 0x33, "Big Bomb Bag (OoT)" },
	{ 0x34, "Biggest Bomb Bag (OoT)" },
	{ 0x35, "Silver Gauntlets (OoT)" },
	{ 0x36, "Golden Gauntlets (OoT)" },
	{ 0x37, "Silver Scale (OoT)" },
	{ 0x38, "Golden Scale (OoT)" },
	{ 0x39, "Stone of Agony (OoT)" },
	{ 0x3A, "Gerudo's Card" },
	{ 0x3B, "Fairy Ocarina" },
	{ 0x3C, "5 Deku Seeds (OoT)" },
	{ 0x3D, "Heart Container (OoT)" },
	{ 0x3E, "Piece of Heart (OoT)" },
	{ 0x3F, "Unknown" },
	{ 0x40, "Unknown" },
	{ 0x41, "Unknown" },
	{ 0x42, "Unknown" },
	{ 0x43, "Small Magic Jar (OoT)" },
	{ 0x44, "Large Magic Jar (OoT)" },
	{ 0x45, "Adult's Wallet" },
	{ 0x46, "Giant's Wallet" },
	{ 0x47, "Weird Egg" },
	{ 0x48, "Recovery Heart (OoT)" },
	{ 0x49, "5 Arrows (OoT)" },
	{ 0x4A, "10 Arrows (OoT)" },
	{ 0x4B, "30 Arrows (OoT)" },
	{ 0x4C, "Green Rupee (OoT)" },
	{ 0x4D, "Blue Rupee (OoT)" },
	{ 0x4E, "Red Rupee (OoT)" },
	{ 0x4F, "Unknown" },
	{ 0x50, "Lon Lon Milk (OoT)" },
	{ 0x51, "Goron Mask (OoT)" },
	{ 0x52, "Zora Mask (OoT)" },
	{ 0x53, "Gerudo Mask" },
	{ 0x54, "Goron's Bracelet" },
	{ 0x55, "Purple Rupee (OoT)" },
	{ 0x56, "Gold Rupee (OoT)" },
	{ 0x57, "Biggoron’s Sword" },
	{ 0x58, "Fire Arrow (OoT)" },
	{ 0x59, "Ice Arrow (OoT)" },
	{ 0x5A, "Light Arrow (OoT)" },
	{ 0x5B, "Gold Skulltula Token" },
	{ 0x5C, "Din's Fire (OoT)" },
	{ 0x5D, "Farore's Fire (OoT)" },
	{ 0x5E, "Nayru's Love (OoT)" },
	{ 0x5F, "Deku Seeds Bullet Bag (40)" },
	{ 0x60, "Deku Seeds Bullet Bag (40)" },
	{ 0x61, "5 Deku Sticks (OoT)" },
	{ 0x62, "10 Deku Sticks (OoT)" },
	{ 0x63, "5 Deku Nuts (OoT)" },
	{ 0x64, "10 Deku Nuts (OoT)" },
	{ 0x65, "1 Bomb (OoT)" },
	{ 0x66, "10 Bomb (OoT)" },
	{ 0x67, "20 Bombs (OoT)" },
	{ 0x68, "30 Bombs (OoT)" },
	{ 0x69, "30 Deku Seeds (OoT)" },
	{ 0x6A, "5 Bombchu (OoT)" },
	{ 0x6B, "20 Bombchu (OoT)" },
	{ 0x6C, "Fish (OoT)" },
	{ 0x6D, "Bugs (OoT)" },
	{ 0x6E, "Blue Fire" },
	{ 0x6F, "Bottled Poe" },
	{ 0x70, "Bottled Big Poe" },
	{ 0x71, "Door Key (OoT Treasure Box Shop)" },
	{ 0x72, "Loser Green Rupee (OoT Treasure Box Shop)" },
	{ 0x73, "Loser Blue Rupee (OoT Treasure Box Shop)" },
	{ 0x74, "Loser Red Rupee (OoT Treasure Box Shop)" },
	{ 0x75, "Winner Purple Rupee (OoT Treasure Box Shop)" },
	{ 0x76, "Winner Piece of Heart (OoT Treasure Box Shop)" },
	{ 0x77, "First Deku Stick Upgrade (OoT)" },
	{ 0x78, "Second Deku Stick Upgrade (OoT)" },
	{ 0x79, "First Deku Nut Upgrade (OoT)" },
	{ 0x7A, "Second Deku Nut Upgrade (OoT)" },
	{ 0x7B, "Deku Seeds Bullet Bag (50)" },
	{ 0x7C, "Ice Trap (OoT)" },
	{ 0x7D, "Unknown" },
	{ 0x7E, "Unknown" },
	{ 0x7F, "Unknown" },
	{ 0x80, "Unknown" },
	{ 0x81, "Minuet of Forest" },
	{ 0x82, "Bolero of Fire" },
	{ 0x83, "Serenade of Water" },
	{ 0x84, "Requiem of Spirit" },
	{ 0x85, "Nocturne of Shadow" },
	{ 0x86, "Prelude of Light" },
	{ 0x87, "Zelda's Song" },
	{ 0x88, "Unknown" },
	{ 0x89, "Unknown" },
	{ 0x8A, "Sun's Song" },
	{ 0x8B, "Song of Time" },
	{ 0x8C, "Unknown" },
	{ 0x8D, "Master Sword (OoT)" },
	{ 0x8E, "Kokiri's Emerald" },
	{ 0x8F, "Goron's Ruby" },
	{ 0x90, "Zora's Sapphire" },
	{ 0x91, "Forest Medallion" },
	{ 0x92, "Fire Medallion" },
	{ 0x93, "Water Medallion" },
	{ 0x94, "Spirit Medallion" },
	{ 0x95, "Shadow Medallion" },
	{ 0x96, "Light Medallion" },
	{ 0x97, "Unknown" },
	{ 0x98, "Unknown" },
	{ 0x99, "Unknown" },
	{ 0x9A, "Progressive Deku Shield (OoT)" },
	{ 0x9B, "Progressive Hylian Shield (OoT)" },
	{ 0x9C, "Small Key (Forest Temple)" },
	{ 0x9D, "Small Key (Fire Temple)" },
	{ 0x9E, "Small Key (Water Temple)" },
	{ 0x9F, "Small Key (Spirit Temple)" },
	{ 0xA0, "Small Key (Shadow Temple)" },
	{ 0xA1, "Small Key (Ganon's Castle)" },
	{ 0xA2, "Small Key (Bottom of the Well)" },
	{ 0xA3, "Small Key (Gerudo's Fortress)" },
	{ 0xA4, "Small Key (Gerudo's Training Ground)" },
	{ 0xA5, "Boss Key (Forest Temple)" },
	{ 0xA6, "Boss Key (Fire Temple)" },
	{ 0xA7, "Boss Key (Water Temple)" },
	{ 0xA8, "Boss Key (Spirit Temple)" },
	{ 0xA9, "Boss Key (Shadow Temple)" },
	{ 0xAA, "Boss Key (Ganon's Castle)" },
	{ 0xAB, "Map (Deku Tree)" },
	{ 0xAC, "Map (Dodongo's Cavern)" },
	{ 0xAD, "Map (Jabu-Jabu's Belly)" },
	{ 0xAE, "Map (Forest Temple)" },
	{ 0xAF, "Map (Fire Temple)" },
	{ 0xB0, "Map (Water Temple)" },
	{ 0xB1, "Map (Spirit Temple)" },
	{ 0xB2, "Map (Shadow Temple)" },
	{ 0xB3, "Map (Bottom of the Well)" },
	{ 0xB4, "Map (Ice Cavern)" },
	{ 0xB5, "Compass (Deku Tree)" },
	{ 0xB6, "Compass (Dodongo's Cavern)" },
	{ 0xB7, "Compass (Jabu-Jabu's Belly)" },
	{ 0xB8, "Compass (Forest Temple)" },
	{ 0xB9, "Compass (Fire Temple)" },
	{ 0xBA, "Compass (Water Temple)" },
	{ 0xBB, "Compass (Spirit Temple)" },
	{ 0xBC, "Compass (Shadow Temple)" },
	{ 0xBD, "Compass (Bottom of the Well)" },
	{ 0xBE, "Compass (Ice Cavern)" },
	{ 0xBF, "Child's Wallet" },
	{ 0xC0, "Unknown" },
	{ 0xC1, "Unknown" },
	{ 0xC2, "Unknown" },
	{ 0xC3, "Unknown" },
	{ 0xC4, "Unknown" },
	{ 0xC5, "Unknown" },
	{ 0xC6, "Unknown" },
	{ 0xC7, "Unknown" },
	{ 0xC8, "Unknown" },
	{ 0xC9, "Unknown" },
	{ 0xCA, "Unknown" },
	{ 0xCB, "Unknown" },
	{ 0xCC, "Unknown" },
	{ 0xCD, "Unknown" },
	{ 0xCE, "Unknown" },
	{ 0xCF, "Unknown" },
	{ 0xD0, "Unknown" },
	{ 0xD1, "Unknown" },
	{ 0xD2, "Unknown" },
	{ 0xD3, "Unknown" },
	{ 0xD4, "Unknown" },
	{ 0xD5, "Unknown" },
	{ 0xD6, "Unknown" },
	{ 0xD7, "Unknown" },
	{ 0xD8, "Unknown" },
	{ 0xD9, "Soul of Stalfos (OoT)" },
	{ 0xDA, "Unknown" },
	{ 0xDB, "Unknown" },
	{ 0xDC, "Soul of Dodongos (OoT)" },
	{ 0xDD, "Soul of Keeses (OoT)" },
	{ 0xDE, "Soul of Tektites (OoT)" },
	{ 0xDF, "Unknown" },
	{ 0xE0, "Unknown" },
	{ 0xE1, "Soul of Lizalfos/Dinolfos (OoT)" },
	{ 0xE2, "Unknown" },
	{ 0xE3, "Soul of Shaboms" },
	{ 0xE4, "Soul of Baby Dodongos" },
	{ 0xE5, "Soul of Dark Link" },
	{ 0xE6, "Soul of Biris/Baris" },
	{ 0xE7, "Soul of Tailpasarans" },
	{ 0xE8, "Soul of Jabu-Jabu's Parasites" },
	{ 0xE9, "Unknown" },
	{ 0xEA, "Unknown" },
	{ 0xEB, "Soul of Moblins" },
	{ 0xEC, "Unknown" },
	{ 0xED, "Unknown" },
	{ 0xEE, "Unknown" },
	{ 0xEF, "Unknown" },
	{ 0xF0, "Unknown" },
	{ 0xF1, "Unknown" },
	{ 0xF2, "Soul of ReDeads/Gibdos (OoT)" },
	{ 0xF3, "Soul of Skullwalltulas (OoT)" },
	{ 0xF4, "Soul of Flare Dancers" },
	{ 0xF5, "Unknown" },
	{ 0xF6, "Soul of Shell Blades (OoT)" },
	{ 0xF7, "Soul of Like Likes (OoT)" },
	{ 0xF8, "Soul of Spikes" },
	{ 0xF9, "Soul of Anubis" },
	{ 0xFA, "Soul of Iron Knuckles (OoT)" },
	{ 0xFB, "Soul of Skull Kids (OoT)" },
	{ 0xFC, "Soul of Flying Pots (OoT)" },
	{ 0xFD, "Soul of Freezards (OoT)" },
	{ 0xFE, "Soul of Stingers" },
	{ 0xFF, "Soul of Wolfoses (OoT)" },
	{ 0x100, "Soul of Stalchildren (OoT)" },
	{ 0x101, "Soul of Guays (OoT)" },
	{ 0x102, "Unknown" },
	{ 0x103, "Soul of Queen Gohma" },
	{ 0x104, "Soul of King Dodongo" },
	{ 0x105, "Soul of Barinade" },
	{ 0x106, "Soul of Phantom Ganon" },
	{ 0x107, "Soul of Volvagia" },
	{ 0x108, "Soul of Morpha" },
	{ 0x109, "Soul of Bongo-Bongo" },
	{ 0x10A, "Soul of Twinrova" },
	{ 0x10B, "Soul of Gold Skulltulas (OoT)" },
	{ 0x10C, "Soul of Business Scrubs (OoT)" },
	{ 0x10D, "Unknown" },
	{ 0x10E, "Unknown" },
	{ 0x10F, "Unknown" },
	{ 0x110, "Unknown" },
	{ 0x111, "Unknown" },
	{ 0x112, "Unknown" },
	{ 0x113, "Unknown" },
	{ 0x114, "Unknown" },
	{ 0x115, "Unknown" },
	{ 0x116, "Unknown" },
	{ 0x117, "Skeleton Key (OoT)" },
	{ 0x118, "Unknown" },
	{ 0x119, "Unknown" },
	{ 0x11A, "Unknown" },
	{ 0x11B, "Unknown" },
	{ 0x11C, "Triforce of Power" },
	{ 0x11D, "Triforce of Courage" },
	{ 0x11E, "Triforce of Wisdom" },
	{ 0x11F, "Unknown" },
	{ 0x120, "Unknown" },
	{ 0x121, "Unknown" },
	{ 0x122, "Unknown" },
	{ 0x123, "Unknown" },
	{ 0x124, "Unknown" },
	{ 0x125, "Unknown" },
	{ 0x126, "Unknown" },
	{ 0x127, "Unknown" },
	{ 0x128, "Unknown" },
	{ 0x129, "Unknown" },
	{ 0x12A, "Unknown" },
	{ 0x12B, "Unknown" },
	{ 0x12C, "Unknown" },
	{ 0x12D, "Unknown" },
	{ 0x12E, "Unknown" },
	{ 0x12F, "Unknown" },
	{ 0x130, "Unknown" },
	{ 0x131, "Unknown" },
	{ 0x132, "Unknown" },
	{ 0x133, "Unknown" },
	{ 0x134, "Unknown" },
	{ 0x135, "Unknown" },
	{ 0x136, "A Button (OoT)" },
	{ 0x137, "C-Right Button (OoT)" },
	{ 0x138, "C-Left Button (OoT)" },
	{ 0x139, "C-Up Button (OoT)" },
	{ 0x13A, "C-Down Button (OoT)" },
	{ 0x13B, "Unknown" },
	{ 0x13C, "Unknown" },
	{ 0x13D, "Unknown" },
	{ 0x13E, "Soul of Darunia" },
	{ 0x13F, "Soul of Ruto (OoT)" },
	{ 0x140, "Unknown" },
	{ 0x141, "Soul of Zelda" },
	{ 0x142, "Unknown" },
	{ 0x143, "Soul of Cucco Lady (OoT)" },
	{ 0x144, "Soul of Carpenters (OoT)" },
	{ 0x145, "Unknown" },
	{ 0x146, "Soul of Mido" },
	{ 0x147, "Soul of Kokiri" },
	{ 0x148, "Soul of Kokiri Shopkeeper" },
	{ 0x149, "Unknown" },
	{ 0x14A, "Unknown" },
	{ 0x14B, "Unknown" },
	{ 0x14C, "Unknown" },
	{ 0x14D, "Unknown" },
	{ 0x14E, "Soul of Goron (OoT)" },
	{ 0x14F, "Soul of Citizens (OoT)" },
	{ 0x150, "Unknown" },
	{ 0x151, "Unknown" },
	{ 0x152, "Soul of Goron Shopkeeper (OoT)" },
	{ 0x153, "Unknown" },
	{ 0x154, "Unknown" },
	{ 0x155, "Soul of Bazaar Shopkeeper (OoT)" },
	{ 0x156, "Soul of Bombchu Shopkeeper (OoT)" },
	{ 0x157, "Soul of Potion Shopkeeper" },
	{ 0x158, "Soul of Bombchu Bowling Lady (OoT)" },
	{ 0x159, "Soul of Chest Game Owner (OoT)" },
	{ 0x15A, "Unknown" },
	{ 0x15B, "Soul of Dampe (OoT)" },
	{ 0x15C, "Soul of Graveyard Kid (OoT)" },
	{ 0x15D, "Soul of Poe Collector (OoT)" },
	{ 0x15E, "Unknown" },
	{ 0x15F, "Soul of Honey & Darling (OoT)" },
	{ 0x160, "Unknown" },
	{ 0x161, "Soul of the Rooftop Man (OoT)" },
	{ 0x162, "Unknown" },
	{ 0x163, "Unknown" },
	{ 0x164, "Unknown" },
	{ 0x165, "Soul of the Punk Boy (OoT)" },
	{ 0x166, "Soul of the Dog Lady (OoT)" },
	{ 0x167, "Soul of the Carpet Man (OoT)" },
	{ 0x168, "Unknown" },
	{ 0x169, "Unknown" },
	{ 0x16A, "Soul of the Patrolling Gerudos" },
	{ 0x16B, "Unknown" },
	{ 0x16C, "Bottle of Green Potion (OoT)" },
	{ 0x16D, "Bottle of Blue Potion (OoT)" },
	{ 0x16E, "Unknown" },
	{ 0x16F, "Unknown" },
	{ 0x170, "Unknown" },
	{ 0x171, "Unknown" },
	{ 0x172, "Child Fish (2 pounds)" },
	{ 0x173, "Child Fish (3 pounds)" },
	{ 0x174, "Child Fish (4 pounds)" },
	{ 0x175, "Child Fish (5 pounds)" },
	{ 0x176, "Child Fish (6 pounds)" },
	{ 0x177, "Child Fish (7 pounds)" },
	{ 0x178, "Child Fish (8 pounds)" },
	{ 0x179, "Unknown" },
	{ 0x17A, "Unknown" },
	{ 0x17B, "Unknown" },
	{ 0x17C, "Unknown" },
	{ 0x17D, "Unknown" },
	{ 0x17E, "Unknown" },
	{ 0x17F, "Adult Fish (4 pounds)" },
	{ 0x180, "Adult Fish (5 pounds)" },
	{ 0x181, "Adult Fish (6 pounds)" },
	{ 0x182, "Adult Fish (7 pounds)" },
	{ 0x183, "Adult Fish (8 pounds)" },
	{ 0x184, "Adult Fish (9 pounds)" },
	{ 0x185, "Adult Fish (10 pounds)" },
	{ 0x186, "Adult Fish (11 pounds)" },
	{ 0x187, "Adult Fish (12 pounds)" },
	{ 0x188, "Adult Fish (13 pounds)" },
	{ 0x189, "Adult Fish (14 pounds)" },
	{ 0x18A, "Adult Fish (15 pounds)" },
	{ 0x18B, "Adult Fish (16 pounds)" },
	{ 0x18C, "Adult Fish (17 pounds)" },
	{ 0x18D, "Adult Fish (18 pounds)" },
	{ 0x18E, "Adult Fish (19 pounds)" },
	{ 0x18F, "Unknown" },
	{ 0x190, "Unknown" },
	{ 0x191, "Unknown" },
	{ 0x192, "Unknown" },
	{ 0x193, "Unknown" },
	{ 0x194, "Unknown" },
	{ 0x195, "Unknown" },
	{ 0x196, "Unknown" },
	{ 0x197, "Unknown" },
	{ 0x198, "Unknown" },
	{ 0x199, "Unknown" },
	{ 0x19A, "Unknown" },
	{ 0x19B, "Unknown" },
	{ 0x19C, "Unknown" },
	{ 0x19D, "Unknown" },
	{ 0x19E, "Unknown" },
	{ 0x19F, "Unknown" },
	{ 0x1A0, "Unknown" },
	{ 0x1A1, "Unknown" },
	{ 0x1A2, "Unknown" },
	{ 0x1A3, "Unknown" },
	{ 0x1A4, "Bombchu Bag (OoT)" },
	{ 0x1A5, "Unknown" },
	{ 0x1A6, "Unknown" },
	{ 0x1A7, "Unknown" },
	{ 0x1A8, "Spin Attack Upgrade (OoT)" },
	{ 0x1A9, "Unknown" },
	{ 0x1AA, "Big Fairy (OoT)" },
	{ 0x1AB, "Unknown" },
	{ 0x1AC, "Stone Mask (OoT)" },
	{ 0x1AD, "Unknown" },
	{ 0x1AE, "Elegy of Emptiness (OoT)" },
	{ 0x1AF, "Green Rupee (MM)" },
	{ 0x1B0, "Blue Rupee (MM)" },
	{ 0x1B1, "Unknown" },
	{ 0x1B2, "Red Rupee (MM)" },
	{ 0x1B3, "Purple Rupee (MM)" },
	{ 0x1B4, "Silver Rupee (MM)" },
	{ 0x1B5, "Gold Rupee (MM)" },
	{ 0x1B6, "Unknown" },
	{ 0x1B7, "Unknown" },
	{ 0x1B8, "Recovery Heart (MM)" },
	{ 0x1B9, "Piece of Heart (MM)" },
	{ 0x1BA, "Heart Container (MM)" },
	{ 0x1BB, "Small Magic Jar (MM)" },
	{ 0x1BC, "Large Magic Jar (MM)" },
	{ 0x1BD, "Unknown" },
	{ 0x1BE, "1 Bomb (MM)" },
	{ 0x1BF, "5 Bombs (MM)" },
	{ 0x1C0, "10 Bombs (MM)" },
	{ 0x1C1, "20 Bombs (MM)" },
	{ 0x1C2, "30 Bombs (MM)" },
	{ 0x1C3, "Deku Stick (MM)" },
	{ 0x1C4, "10 Bombchu (MM)" },
	{ 0x1C5, "Bomb Bag (MM)" },
	{ 0x1C6, "Big Bomb Bag (MM)" },
	{ 0x1C7, "Unknown" },
	{ 0x1C8, "10 Arrows (MM)" },
	{ 0x1C9, "30 Arrows (MM)" },
	{ 0x1CA, "Unknown" },
	{ 0x1CB, "Unknown" },
	{ 0x1CC, "Unknown" },
	{ 0x1CD, "Fairy Bow (MM)" },
	{ 0x1CE, "Unknown" },
	{ 0x1CF, "Fire Arrow (MM)" },
	{ 0x1D0, "Ice Arrow (MM)" },
	{ 0x1D1, "Light Arrow (MM)" },
	{ 0x1D2, "Unknown" },
	{ 0x1D3, "Unknown" },
	{ 0x1D4, "10 Deku Nuts (MM)" },
	{ 0x1D5, "Unknown" },
	{ 0x1D6, "Unknown" },
	{ 0x1D7, "Unknown" },
	{ 0x1D8, "Unknown" },
	{ 0x1D9, "Unknown" },
	{ 0x1DA, "Unknown" },
	{ 0x1DB, "Unknown" },
	{ 0x1DC, "Unknown" },
	{ 0x1DD, "Mirror Shield (MM)" },
	{ 0x1DE, "Unknown" },
	{ 0x1DF, "Magic Bean (MM)" },
	{ 0x1E0, "1 Bombchu (MM)" },
	{ 0x1E1, "Kokiri Sword (MM)" },
	{ 0x1E2, "Unknown" },
	{ 0x1E3, "Unknown" },
	{ 0x1E4, "5 Bombchu (MM)" },
	{ 0x1E5, "Unknown" },
	{ 0x1E6, "Unknown" },
	{ 0x1E7, "Unknown" },
	{ 0x1E8, "Unknown" },
	{ 0x1E9, "Unknown" },
	{ 0x1EA, "Hookshot (MM)" },
	{ 0x1EB, "Lens of Truth (MM)" },
	{ 0x1EC, "Unknown" },
	{ 0x1ED, "Ocarina of Time (MM)" },
	{ 0x1EE, "Bombers' Notebook" },
	{ 0x1EF, "Unknown" },
	{ 0x1F0, "Empty Bottle (MM)" },
	{ 0x1F1, "Red Potion (MM)" },
	{ 0x1F2, "Green Potion (MM)" },
	{ 0x1F3, "Blue Potion (MM)" },
	{ 0x1F4, "Fairy (MM)" },
	{ 0x1F5, "Bottle of Milk (MM)" },
	{ 0x1F6, "Unknown" },
	{ 0x1F7, "Unknown" },
	{ 0x1F8, "Bottled Big Poe (MM)" },
	{ 0x1F9, "Bottle of Gold Dust" },
	{ 0x1FA, "Unknown" },
	{ 0x1FB, "Unknown" },
	{ 0x1FC, "Deku Mask" },
	{ 0x1FD, "Goron Mask (MM)" },
	{ 0x1FE, "Zora Mask (MM)" },
	{ 0x1FF, "Fierce Deity's Mask" },
	{ 0x200, "Captain's Hat" },
	{ 0x201, "Unknown" },
	{ 0x202, "Unknown" },
	{ 0x203, "Bunny Hood (MM)" },
	{ 0x204, "Keaton Mask (MM)" },
	{ 0x205, "Unknown" },
	{ 0x206, "Romani's Mask" },
	{ 0x207, "Circus Leader's Mask" },
	{ 0x208, "Postman's Hat" },
	{ 0x209, "Couple's Mask" },
	{ 0x20A, "Great Fairy's Mask" },
	{ 0x20B, "Gibdo Mask" },
	{ 0x20C, "Don Gero's Mask" },
	{ 0x20D, "Kamaro's Mask" },
	{ 0x20E, "Unknown" },
	{ 0x20F, "Stone Mask (MM)" },
	{ 0x210, "Unknown" },
	{ 0x211, "Blast Mask (MM)" },
	{ 0x212, "Mask of Scents" },
	{ 0x213, "Unknown" },
	{ 0x214, "Chateau Romani Refill (MM)" },
	{ 0x215, "Romani Milk" },
	{ 0x216, "Unknown" },
	{ 0x217, "Unknown" },
	{ 0x218, "Moon's Tear" },
	{ 0x219, "Land Title Deed" },
	{ 0x21A, "Swamp Title Deed" },
	{ 0x21B, "Unknown" },
	{ 0x21C, "Ocean Title Deed" },
	{ 0x21D, "Unknown" },
	{ 0x21E, "Unknown" },
	{ 0x21F, "Letter to Kafei" },
	{ 0x220, "Pendant of Memories" },
	{ 0x221, "World Map of Clock Town" },
	{ 0x222, "World Map of Woodfall" },
	{ 0x223, "World Map of Snowhead" },
	{ 0x224, "Unknown" },
	{ 0x225, "World Map of Great Bay" },
	{ 0x226, "World Map of Stone Tower" },
	{ 0x227, "Magic Upgrade" },
	{ 0x228, "Larger Magic Upgrade" },
	{ 0x229, "Defense Upgrade" },
	{ 0x22A, "Spin Attack Upgrade (MM)" },
	{ 0x22B, "Sonata of Awakening" },
	{ 0x22C, "Goron Lullaby" },
	{ 0x22D, "New Wave Bossa Nova" },
	{ 0x22E, "Unknown" },
	{ 0x22F, "Unknown" },
	{ 0x230, "Unknown" },
	{ 0x231, "Song of Healing" },
	{ 0x232, "Unknown" },
	{ 0x233, "Song of Soaring" },
	{ 0x234, "Song of Storms" },
	{ 0x235, "Goron Lullaby Intro" },
	{ 0x236, "Unknown" },
	{ 0x237, "Unknown" },
	{ 0x238, "Unknown" },
	{ 0x239, "Twinmold's Remains" },
	{ 0x23A, "Hero's Shield (MM)" },
	{ 0x23B, "Swamp Skulltula Token" },
	{ 0x23C, "Ocean Skulltula Token" },
	{ 0x23D, "Unknown" },
	{ 0x23E, "Small Key (Snowhead Temple)" },
	{ 0x23F, "Unknown" },
	{ 0x240, "Small Key (Stone Tower Temple)" },
	{ 0x241, "Boss Key (Woodfall Temple)" },
	{ 0x242, "Boss Key (Snowhead Temple)" },
	{ 0x243, "Boss Key (Great Bay Temple)" },
	{ 0x244, "Boss Key (Stone Tower Temple)" },
	{ 0x245, "Stray Fairy (Woodfall Temple)" },
	{ 0x246, "Stray Fairy (Snowhead Temple)" },
	{ 0x247, "Stray Fairy (Great Bay Temple)" },
	{ 0x248, "Stray Fairy (Stone Tower Temple)" },
	{ 0x249, "Unknown" },
	{ 0x24A, "Map (Woodfall Temple)" },
	{ 0x24B, "Unknown" },
	{ 0x24C, "Map (Great Bay Temple)" },
	{ 0x24D, "Map (Stone Tower Temple)" },
	{ 0x24E, "Compass (Woodfall Temple)" },
	{ 0x24F, "Unknown" },
	{ 0x250, "Compass (Great Bay Temple)" },
	{ 0x251, "Unknown" },
	{ 0x252, "Unknown" },
	{ 0x253, "Unknown" },
	{ 0x254, "Unknown" },
	{ 0x255, "Unknown" },
	{ 0x256, "Unknown" },
	{ 0x257, "Owl Statue (Great Bay)" },
	{ 0x258, "Owl Statue (Zora Cape)" },
	{ 0x259, "Owl Statue (Snowhead)" },
	{ 0x25A, "Unknown" },
	{ 0x25B, "Owl Statue (Clock Town)" },
	{ 0x25C, "Unknown" },
	{ 0x25D, "Unknown" },
	{ 0x25E, "Unknown" },
	{ 0x25F, "Owl Statue (Ikana Canyon)" },
	{ 0x260, "Unknown" },
	{ 0x261, "Unknown" },
	{ 0x262, "Unknown" },
	{ 0x263, "Soul of Octoroks (MM)" },
	{ 0x264, "Unknown" },
	{ 0x265, "Unknown" },
	{ 0x266, "Unknown" },
	{ 0x267, "Soul of Tektites (MM)" },
	{ 0x268, "Soul of Peahats (MM)" },
	{ 0x269, "Unknown" },
	{ 0x26A, "Soul of Skulltulas (MM)" },
	{ 0x26B, "Soul of Armos (MM)" },
	{ 0x26C, "Soul of Deku Babas (MM)" },
	{ 0x26D, "Unknown" },
	{ 0x26E, "Soul of Bubbles (MM)" },
	{ 0x26F, "Soul of Beamos (MM)" },
	{ 0x270, "Unknown" },
	{ 0x271, "Soul of Skullwalltulas (MM)" },
	{ 0x272, "Unknown" },
	{ 0x273, "Unknown" },
	{ 0x274, "Soul of Iron Knuckles (MM)" },
	{ 0x275, "Soul of Freezards (MM)" },
	{ 0x276, "Soul of Wolfos (MM)" },
	{ 0x277, "Soul of Guays (MM)" },
	{ 0x278, "Unknown" },
	{ 0x279, "Soul of Floormasters (MM)" },
	{ 0x27A, "Unknown" },
	{ 0x27B, "Unknown" },
	{ 0x27C, "Soul of Stalchildren (MM)" },
	{ 0x27D, "Unknown" },
	{ 0x27E, "Soul of Skullfish (MM)" },
	{ 0x27F, "Unknown" },
	{ 0x280, "Unknown" },
	{ 0x281, "Soul of Eenoes" },
	{ 0x282, "Soul of Eyegores" },
	{ 0x283, "Soul of Hiploops" },
	{ 0x284, "Soul of Real Bombchu" },
	{ 0x285, "Soul of Takkuri" },
	{ 0x286, "Unknown" },
	{ 0x287, "Unknown" },
	{ 0x288, "Soul of Bio Babas" },
	{ 0x289, "Soul of Garo" },
	{ 0x28A, "Unknown" },
	{ 0x28B, "Unknown" },
	{ 0x28C, "Soul of Gekkos" },
	{ 0x28D, "Soul of Bad Bats" },
	{ 0x28E, "Soul of Snappers" },
	{ 0x28F, "Soul of Warts" },
	{ 0x290, "Soul of Captain Keeta" },
	{ 0x291, "Soul of the Fighting Pirates" },
	{ 0x292, "Soul of Odolwa" },
	{ 0x293, "Unknown" },
	{ 0x294, "Soul of Gyorg" },
	{ 0x295, "Soul of Twinmold" },
	{ 0x296, "Unknown" },
	{ 0x297, "Unknown" },
	{ 0x298, "Soul of Town Archery Owner (MM)" },
	{ 0x299, "Soul of Swamp Archery Owner (MM)" },
	{ 0x29A, "Soul of Gorons (MM)" },
	{ 0x29B, "Soul of the Goron Baby (MM)" },
	{ 0x29C, "Soul of the Bomb Shop Owner (MM)" },
	{ 0x29D, "Unknown" },
	{ 0x29E, "Soul of the Deku Butler" },
	{ 0x29F, "Soul of Citizens (MM)" },
	{ 0x2A0, "Unknown" },
	{ 0x2A1, "Soul of Dampe (MM)" },
	{ 0x2A2, "Unknown" },
	{ 0x2A3, "Soul of the Deku Princess" },
	{ 0x2A4, "Soul of Playground Scrubs" },
	{ 0x2A5, "Soul of the Goron Elder" },
	{ 0x2A6, "Unknown" },
	{ 0x2A7, "Unknown" },
	{ 0x2A8, "Soul of Honey & Darling (MM)" },
	{ 0x2A9, "Soul of Toto (MM)" },
	{ 0x2AA, "Unknown" },
	{ 0x2AB, "Unknown" },
	{ 0x2AC, "Soul of Kafei" },
	{ 0x2AD, "Unknown" },
	{ 0x2AE, "Soul of Koume and Kotake" },
	{ 0x2AF, "Unknown" },
	{ 0x2B0, "Soul of Keg Trial Goron (MM)" },
	{ 0x2B1, "Soul of Biggoron (MM)" },
	{ 0x2B2, "Soul of Mr. Barten (MM)" },
	{ 0x2B3, "Unknown" },
	{ 0x2B4, "Unknown" },
	{ 0x2B5, "Soul of Blacksmiths" },
	{ 0x2B6, "Soul of Chest Game Lady (MM)" },
	{ 0x2B7, "Unknown" },
	{ 0x2B8, "Soul of Toilet Hand" },
	{ 0x2B9, "Soul of Trading Post Owner (MM)" },
	{ 0x2BA, "Unknown" },
	{ 0x2BB, "Unknown" },
	{ 0x2BC, "Soul of the Zora Shopkeeper (MM)" },
	{ 0x2BD, "Unknown" },
	{ 0x2BE, "Unknown" },
	{ 0x2BF, "Soul of Carpenters (MM)" },
	{ 0x2C0, "Soul of Anju (MM)" },
	{ 0x2C1, "Soul of Guru-Guru (MM)" },
	{ 0x2C2, "Unknown" },
	{ 0x2C3, "Soul of Gorman & Bros. (MM)" },
	{ 0x2C4, "Soul of Grog (MM)" },
	{ 0x2C5, "Unknown" },
	{ 0x2C6, "Soul of Swordsman (MM)" },
	{ 0x2C7, "Soul of Anju's Grandmother (MM)" },
	{ 0x2C8, "Soul of Tourist Center Owner" },
	{ 0x2C9, "Soul of the Banker (MM)" },
	{ 0x2CA, "Unknown" },
	{ 0x2CB, "Soul of Patrolling Pirates and Their Chief" },
	{ 0x2CC, "Soul of Gold Skulltulas (MM)" },
	{ 0x2CD, "Unknown" },
	{ 0x2CE, "Unknown" },
	{ 0x2CF, "Unknown" },
	{ 0x2D0, "Unknown" },
	{ 0x2D1, "Unknown" },
	{ 0x2D2, "Unknown" },
	{ 0x2D3, "Skeleton Key (MM)" },
	{ 0x2D4, "Unknown" },
	{ 0x2D5, "Unknown" },
	{ 0x2D6, "Unknown" },
	{ 0x2D7, "Unknown" },
	{ 0x2D8, "C-Down Button (MM)" },
	{ 0x2D9, "Unknown" },
	{ 0x2DA, "Unknown" },
	{ 0x2DB, "Unknown" },
	{ 0x2DC, "Unknown" },
	{ 0x2DD, "Unknown" },
	{ 0x2DE, "Bottled Big Poe (MM)" },
	{ 0x2DF, "Unknown" },
	{ 0x2E0, "Unknown" },
	{ 0x2E1, "Bombchu Bag (MM)" },
	{ 0x2E2, "Unknown" },
	{ 0x2E3, "Big Fairy (MM)" },
	{ 0x2E4, "Din's Fire (MM)" },
	{ 0x2E5, "Farore's Wind (MM)" },
	{ 0x2E6, "Nayru's Love (MM)" },
	{ 0x2E7, "Unknown" },
	{ 0x2E8, "Hover Boots (MM)" },
	{ 0x2E9, "Unknown" },
	{ 0x2EA, "Unknown" },
	{ 0x2EB, "Unknown" },
	{ 0x2EC, "Unknown" },
	{ 0x2ED, "Unknown" },
	{ 0x2EE, "Unknown" },
	{ 0x2EF, "Unknown" },
	{ 0x2F0, "Clock (Day 1)" },
	{ 0x2F1, "Clock (Night 1)" },
	{ 0x2F2, "Clock (Day 2)" },
	{ 0x2F3, "Clock (Night 2)" },
	{ 0x2F4, "Clock (Day 3)" },
	{ 0x2F5, "Clock (Night 3)" },
	{ 0x2F6, "Unknown" },
	{ 0x2F7, "Megaton Hammer (MM)" },
	{ 0x2F8, "Deku Stick Upgrade (MM)" },
	{ 0x2F9, "Unknown" },
	{ 0x2FA, "Deku Nut Upgrade (MM)" },
	{ 0x2FB, "Unknown" },
	{ 0x2FC, "Unknown" },
	{ 0x2FD, "Unknown" },
	{ 0x2FE, "Unknown" },
	{ 0x2FF, "Nothing" }
};

#pragma endregion 


void ParseKey(uint8_t Key[5], ComboItem* Item);
ItemInfo FindItem(uint32_t gi);