#pragma once

#include "Entrances.h"
#include "Scenes.h"

#pragma region Defines

#define MM_BOSS_TEMPLE_WOODFALL_ENTR  0x3800
#define MM_BOSS_TEMPLE_SNOWHEAD_ENTR  0x8200
#define MM_BOSS_TEMPLE_GREAT_BAY_ENTR  0xb800
#define MM_BOSS_TEMPLE_STONE_TOWER_ENTR  0x6600
#define MM_TEMPLE_WOODFALL_ENTR  0x3000
#define MM_TEMPLE_SNOWHEAD_ENTR  0x3c00
#define MM_TEMPLE_GREAT_BAY_ENTR  0x8c00
#define MM_TEMPLE_STONE_TOWER_INVERTED_ENTR  0x2a00
#define MM_TEMPLE_STONE_TOWER_ENTR  0x2600
#define MM_SPIDER_HOUSE_SWAMP_ENTR  0x4800
#define MM_SPIDER_HOUSE_OCEAN_ENTR  0x4a00
#define MM_BENEATH_THE_WELL_ENTR  0x9000
#define MM_BENEATH_THE_WELL_BACK_ENTR  0x9010
#define MM_IKANA_CASTLE_ENTR  0x3430
#define MM_SECRET_SHRINE_ENTR  0xba00
#define MM_PIRATE_FORTRESS_ENTR  0x7000
#define MM_CLOCK_TOWER_ROOF_ENTR  0x2c00
#define MM_WOODFALL_FROM_TEMPLE_ENTR  0x8610
#define MM_SNOWHEAD_FROM_TEMPLE_ENTR  0xb210
#define MM_GREAT_BAY_FROM_TEMPLE_ENTR  0x6a70
#define MM_STONE_TOWER_INVERTED_FROM_TEMPLE_ENTR  0xac10
#define MM_STONE_TOWER_FROM_TEMPLE_ENTR  0xaa20
#define MM_SWAMP_FROM_SPIDER_HOUSE_ENTR  0x8480
#define MM_GREAT_BAY_FROM_SPIDER_HOUSE_ENTR  0x6880
#define MM_IKANA_CANYON_FROM_WELL_ENTR  0x2050
#define MM_IKANA_CASTLE_EXTERIOR_FROM_WELL_ENTR  0x3400
#define MM_IKANA_CASTLE_EXTERIOR_FROM_CASTLE_ENTR  0x3420
#define MM_IKANA_VALLEY_FROM_SHRINE_ENTR  0x20c0
#define MM_GREAT_BAY_FROM_PIRATE_FORTRESS_ENTR  0x6850
#define MM_CLOCK_TOWN_FROM_CLOCK_TOWER_ROOF_ENTR  0xd880
#define MM_SWAMP_FROM_ROAD_ENTR  0x8400
#define MM_MOUNTAIN_VILLAGE_FROM_PATH_ENTR  0x9a60
#define MM_GREAT_BAY_COAST_FROM_FIELD_ENTR  0x6800
#define MM_IKANA_VALLEY_FROM_ROAD_ENTR  0x2000
#define MM_ROMANI_RANCH_FROM_MILK_ROAD_ENTR  0x6400
#define MM_SWAMP_ROAD_FROM_SWAMP_ENTR  0x7a10
#define MM_PATH_FROM_MOUNTAIN_VILLAGE_ENTR  0x3210
#define MM_TERMINA_FIELD_FROM_GREAT_BAY_COAST_ENTR  0x5420
#define MM_IKANA_ROAD_FROM_VALLEY_ENTR  0xa010
#define MM_MILK_ROAD_FROM_ROMANI_RANCH_ENTR  0x3e10
#define MM_CLOCK_TOWN_WEST_FROM_SOUTH_BOTTOM_ENTR  0xd410
#define MM_CLOCK_TOWN_SOUTH_BOTTOM_FROM_WEST_ENTR  0xd850
#define MM_CLOCK_TOWN_EAST_FROM_SOUTH_BOTTOM_ENTR  0xd210
#define MM_CLOCK_TOWN_SOUTH_BOTTOM_FROM_EAST_ENTR  0xd870
#define MM_CLOCK_TOWN_NORTH_FROM_EAST_ENTR  0xd610
#define MM_CLOCK_TOWN_EAST_FROM_NORTH_ENTR  0xd250
#define MM_CLOCK_TOWN_NORTH_FROM_SOUTH_ENTR  0xd620
#define MM_CLOCK_TOWN_SOUTH_FROM_NORTH_ENTR  0xd840
#define MM_CLOCK_TOWN_EAST_FROM_SOUTH_TOP_ENTR  0xd230
#define MM_CLOCK_TOWN_SOUTH_TOP_FROM_EAST_ENTR  0xd820
#define MM_CLOCK_TOWN_WEST_FROM_SOUTH_TOP_ENTR  0xd420
#define MM_CLOCK_TOWN_SOUTH_TOP_FROM_WEST_ENTR  0xd830
#define MM_CLOCK_TOWN_WEST_FROM_FIELD_ENTR  0xd400
#define MM_CLOCK_TOWN_SOUTH_FROM_FIELD_ENTR  0xd810
#define MM_CLOCK_TOWN_EAST_FROM_FIELD_ENTR  0xd200
#define MM_CLOCK_TOWN_NORTH_FROM_FIELD_ENTR  0xd600
#define MM_CLOCK_TOWN_SOUTH_FROM_LAUNDRY_POOL_ENTR  0xd860
#define MM_LAUNDRY_POOL_ENTR  0xda00
#define MM_TERMINA_FIELD_FROM_CLOCK_TOWN_WEST_ENTR  0x5400
#define MM_TERMINA_FIELD_FROM_CLOCK_TOWN_SOUTH_ENTR  0x5460
#define MM_TERMINA_FIELD_FROM_CLOCK_TOWN_EAST_ENTR  0x5470
#define MM_TERMINA_FIELD_FROM_CLOCK_TOWN_NORTH_ENTR  0x5480
#define MM_IKANA_ROAD_FROM_FIELD_ENTR  0xa000
#define MM_TERMINA_FIELD_FROM_ROAD_TO_IKANA_ENTR  0x5440
#define MM_MOUNTAIN_VILLAGE_PATH_FROM_TERMINA_FIELD_ENTR  0x3200
#define MM_TERMINA_FIELD_FROM_PATH_TO_MOUNTAIN_VILLAGE_ENTR  0x5430
#define MM_SWAMP_ROAD_FROM_FIELD_ENTR  0x7a00
#define MM_TERMINA_FIELD_FROM_ROAD_TO_SWAMP_ENTR  0x5410
#define MM_MILK_ROAD_FROM_FIELD_ENTR  0x3e00
#define MM_TERMINA_FIELD_FROM_MILK_ROAD_ENTR  0x5450
#define MM_GORMAN_TRACK_FROM_MILK_ROAD_ENTR  0xce00
#define MM_MILK_ROAD_FROM_GORMAN_TRACK_ENTR  0x3e30
#define MM_GORMAN_BACK_FROM_MILK_ROAD_ENTR  0xce30
#define MM_MILK_ROAD_FROM_GORMAN_BACK_ENTR  0x3e20
#define MM_SNOWHEAD_PATH_FROM_MOUNTAIN_VILLAGE_ENTR  0xb000
#define MM_MOUNTAIN_VILLAGE_FROM_SNOWHEAD_PATH_ENTR  0x9a40
#define MM_SNOWHEAD_FROM_SNOWHEAD_PATH_ENTR  0xb200
#define MM_PATH_SNOWHEAD_FROM_SNOWHEAD_ENTR  0xb010
#define MM_IKANA_GRAVEYARD_ENTR  0x8000
#define MM_IKANA_ROAD_FROM_IKANA_GRAVEYARD_ENTR  0xa020
#define MM_ZORA_CAPE_FROM_GREAT_BAY_COAST_ENTR  0x6a00
#define MM_GREAT_BAY_COAST_FROM_ZORA_CAPE_ENTR  0x6810
#define MM_PINNACLE_ROCK_ENTR  0x4400
#define MM_GREAT_BAY_FROM_PINNACLE_ROCK_ENTR  0x6830
#define MM_ZORA_CAPE_FROM_HALL_WATER_ENTR  0x6a10
#define MM_ZORA_HALL_UNDERWATER_ENTR  0x6000
#define MM_ZORA_CAPE_PENINSULA_ENTR  0x6a20
#define MM_ZORA_HALL_LEDGE_ENTR  0x6010
#define MM_DEKU_PALACE_MAIN_ENTRANCE_ENTR  0x5000
#define MM_SWAMP_FROM_PALACE_MAIN_ENTRANCE_ENTR  0x8430
#define MM_DEKU_PALACE_LEDGE_ENTR  0x5050
#define MM_SWAMP_FROM_PALACE_LEDGE_ENTR  0x8440
#define MM_WOODFALL_ENTR  0x8600
#define MM_SWAMP_FROM_WOODFALL_ENTR  0x8420
#define MM_MYSTERY_WOODS_ENTR  0xc200
#define MM_SWAMP_FROM_MYSTERY_WOODS_ENTR  0x8470
#define MM_SEWERS_FROM_EXTERIOR_GATE_ENTR  0x4090
#define MM_EXTERIOR_GATE_FROM_SEWERS_ENTR  0x7020
#define MM_PIRATE_FORTRESS_INTERIOR_ENTR  0x2200
#define MM_PIRATE_FORTRESS_EXTERIOR_FROM_INTERIOR_ENTR  0x7010
#define MM_PIRATE_FORTRESS_INTERIOR_FROM_LOOKOUT_ENTR  0x22c0
#define MM_PIRATE_FORTRESS_EXTERIOR_LOOKOUT_ENTR  0x7050
#define MM_IKANA_CASTLE_GARDENS_ENTR  0x3410
#define MM_IKANA_CANYON_FROM_CASTLE_GARDENS_ENTR  0x2080
#define MM_STONE_TOWER_ENTR  0xaa00
#define MM_IKANA_CANYON_FROM_STONE_TOWER_ENTR  0x2030
#define MM_TWIN_ISLANDS_FROM_MOUNTAIN_VILLAGE_ENTR  0xb400
#define MM_MOUNTAIN_VILLAGE_FROM_TWIN_ISLANDS_ENTR  0x9a20
#define MM_TWIN_ISLANDS_FROM_GORON_VILLAGE_ENTR  0xb410
#define MM_GORON_VILLAGE_FROM_TWIN_ISLANDS_ENTR  0x9400
#define MM_SWAMP_FROM_IKANA_CANYON_ENTR  0x8490
#define MM_IKANA_CASTLE_INTERIOR_KEG_ENTR  0x3440
#define MM_IKANA_CASTLE_INTERIOR_BLOCK_ENTR  0x3450
#define MM_CHEST_GAME_ENTR  0x2800
#define MM_HONEY_AND_DARLING_GAME_ENTR  0x0800
#define MM_MAYORS_OFFICE_ENTR  0x0000
#define MM_TOWN_ARCHERY_ENTR  0x3a00
#define MM_MILK_BAR_ENTR  0x2400
#define MM_FAIRY_FOUNTAIN_TOWN_ENTR  0x4600
#define MM_SWORDSMAN_SCHOOL_ENTR  0xa200
#define MM_CURIOSITY_SHOP_ENTR  0x0e00
#define MM_TRADING_POST_ENTR  0x6200
#define MM_BOMB_SHOP_ENTR  0xca00
#define MM_POST_OFFICE_ENTR  0x5600
#define MM_LOTTERY_ENTR  0x6c00
#define MM_KAFEI_HIDEOUT_ENTR  0x0e10
#define MM_POTION_SHOP_ENTR  0x0400
#define MM_DEKU_SHRINE_ENTR  0x9e00
#define MM_GORON_SHOP_ENTR  0x7400
#define MM_FISHER_HUT_ENTR  0x7200
#define MM_LABORATORY_ENTR  0x5800
#define MM_ROOM_EVANS_ENTR  0x9230
#define MM_ROOM_JAPAS_ENTR  0x9210
#define MM_ROOM_TIJO_ENTR  0x9200
#define MM_ROOM_LULU_ENTR  0x9220
#define MM_ZORA_SHOP_ENTR  0x9250
#define MM_GHOST_HUT_ENTR  0x9c00
#define MM_MUSIC_BOX_HOUSE_ENTR  0xa400
#define MM_FAIRY_FOUNTAIN_IKANA_ENTR  0x4640
#define MM_IKANA_CAVERN_ENTR  0x20e0
#define MM_FAIRY_FOUNTAIN_GREAT_BAY_ENTR  0x4630
#define MM_FAIRY_FOUNTAIN_SNOWHEAD_ENTR  0x4620
#define MM_FAIRY_FOUNTAIN_WOODFALL_ENTR  0x4610
#define MM_GORON_GRAVEYARD_ENTR  0x9600
#define MM_BLACKSMITH_ENTR  0x5200
#define MM_SWAMP_ARCHERY_ENTR  0x4200
#define MM_GORON_RACETRACK_ENTR  0xd000
#define MM_BEAVERS_ENTR  0x8e00
#define MM_CUCCO_SHACK_ENTR  0x7e00
#define MM_DOGGY_RACETRACK_ENTR  0x7c00
#define MM_STABLES_ENTR  0x0600
#define MM_RANCH_HOUSE_ENTR  0x0610
#define MM_GORON_SHRINE_ENTR  0x5e00
#define MM_DEKU_PALACE_THRONE_ENTR  0x7600
#define MM_DEKU_PALACE_THRONE_CAGE_ENTR  0x7610
#define MM_LONE_PEAK_SHRINE_ENTR  0x1500
#define MM_STOCK_POT_INN_ENTR  0xbc00
#define MM_STOCK_POT_INN_ROOF_ENTR  0xbc10
#define MM_SEWERS_FROM_EXTERIOR_DOOR_ENTR  0x40a0
#define MM_TOURIST_INFORMATION_ENTR  0xa800
#define MM_ASTRAL_OBSERVATORY_FROM_CLOCK_TOWN_EAST_ENTR  0x4c00
#define MM_ASTRAL_OBSERVATORY_FROM_FIELD_ENTR  0x4c10
#define MM_CLOCK_TOWN_EAST_FROM_CHEST_GAME_ENTR  0xd240
#define MM_CLOCK_TOWN_EAST_FROM_HONEY_AND_DARLING_ENTR  0xd260
#define MM_CLOCK_TOWN_EAST_FROM_MAYORS_OFFICE_ENTR  0xd270
#define MM_CLOCK_TOWN_EAST_FROM_TOWN_ARCHERY_ENTR  0xd280
#define MM_CLOCK_TOWN_EAST_FROM_STOCK_POT_INN_ENTR  0xd290
#define MM_CLOCK_TOWN_EAST_FROM_STOCK_POT_INN_ROOF_ENTR  0xd2a0
#define MM_CLOCK_TOWN_EAST_FROM_MILK_BAR_ENTR  0xd2b0
#define MM_CLOCK_TOWN_NORTH_FROM_FAIRY_FOUNTAIN_ENTR  0xd630
#define MM_CLOCK_TOWN_WEST_FROM_SWORDSMAN_SCHOOL_ENTR  0xd430
#define MM_CLOCK_TOWN_WEST_FROM_CURIOSITY_SHOP_ENTR  0xd440
#define MM_CLOCK_TOWN_WEST_FROM_TRADING_POST_ENTR  0xd450
#define MM_CLOCK_TOWN_WEST_FROM_BOMB_SHOP_ENTR  0xd460
#define MM_CLOCK_TOWN_WEST_FROM_POST_OFFICE_ENTR  0xd470
#define MM_CLOCK_TOWN_WEST_FROM_LOTTERY_ENTR  0xd480
#define MM_LAUNDRY_POOL_FROM_KAFEI_HIDEOUT_ENTR  0xda10
#define MM_SWAMP_FROM_POTION_SHOP_ENTR  0x8450
#define MM_DEKU_PALACE_EXTERIOR_FROM_SHRINE_ENTR  0x5040
#define MM_GORON_SHRINE_FROM_SHOP_ENTR  0x5e10
#define MM_GREAT_BAY_COAST_FROM_FISHER_HUT_ENTR  0x6840
#define MM_GREAT_BAY_COAST_FROM_LABORATORY_ENTR  0x6870
#define MM_ZORA_HALL_FROM_EVANS_ENTR  0x6040
#define MM_ZORA_HALL_FROM_JAPAS_ENTR  0x6050
#define MM_ZORA_HALL_FROM_TIJO_ENTR  0x6060
#define MM_ZORA_HALL_FROM_LULU_ENTR  0x6030
#define MM_ZORA_HALL_FROM_SHOP_ENTR  0x6020
#define MM_IKANA_CANYON_FROM_GHOST_HUT_ENTR  0x2010
#define MM_IKANA_CANYON_FROM_MUSIC_BOX_HOUSE_ENTR  0x2020
#define MM_IKANA_CANYON_FROM_FAIRY_FOUNTAIN_ENTR  0x20b0
#define MM_IKANA_CANYON_FROM_CAVERN_ENTR  0x20d0
#define MM_EXTERIOR_DOOR_FROM_SEWERS_ENTR  0x7060
#define MM_GREAT_BAY_FROM_FAIRY_FOUNTAIN_ENTR  0x6a50
#define MM_SNOWHEAD_FROM_FAIRY_FOUNTAIN_ENTR  0xb220
#define MM_SWAMP_FROM_TOURIST_INFORMATION_ENTR  0x8410
#define MM_WOODFALL_FROM_FAIRY_FOUNTAIN_ENTR  0x8620
#define MM_MOUNTAIN_VILLAGE_FROM_GORON_GRAVEYARD_ENTR  0x9a30
#define MM_MOUNTAIN_VILLAGE_FROM_BLACKSMITH_ENTR  0x9a10
#define MM_ROMANI_RANCH_FROM_CUCCO_SHACK_ENTR  0x6440
#define MM_ROMANI_RANCH_FROM_DOGGY_RACETRACK_ENTR  0x6450
#define MM_ROMANI_RANCH_FROM_STABLES_ENTR  0x6420
#define MM_ROMANI_RANCH_FROM_RANCH_HOUSE_ENTR  0x6430
#define MM_CLOCK_TOWN_EAST_FROM_ASTRAL_OBSERVATORY_ENTR  0xd220
#define MM_FIELD_FROM_ASTRAL_OBSERVATORY_ENTR  0x5490
#define MM_SWAMP_ROAD_FROM_ARCHERY_ENTR  0x7a20
#define MM_TWIN_ISLANDS_FROM_GORON_RACETRACK_ENTR  0xb420
#define MM_ZORA_CAPE_FROM_BEAVERS_ENTR  0x6a40
#define MM_GORON_VILLAGE_FROM_GORON_SHRINE_ENTR  0x9420
#define MM_GORON_VILLAGE_FROM_LONE_PEAK_SHRINE_ENTR  0x9430
#define MM_DEKU_PALACE_EXTERIOR_FROM_THRONE_ENTR  0x5020
#define MM_DEKU_PALACE_EXTERIOR_FROM_THRONE_CAGE_ENTR  0x5030
#define MM_SAKON_HIDEOUT_ENTR  0x9800
#define MM_IKANA_CANYON_FROM_SAKON_HIDEOUT_ENTR  0x2060
#define MM_WARP_OWL_GREAT_BAY_ENTR  0x68b0
#define MM_WARP_OWL_ZORA_CAPE_ENTR  0x6a60
#define MM_WARP_OWL_SNOWHEAD_ENTR  0xb230
#define MM_WARP_OWL_MOUNTAIN_VILLAGE_ENTR  0x9a80
#define MM_WARP_OWL_CLOCK_TOWN_ENTR  0xd890
#define MM_WARP_OWL_MILK_ROAD_ENTR  0x3e40
#define MM_WARP_OWL_WOODFALL_ENTR  0x8640
#define MM_WARP_OWL_SOUTHERN_SWAMP_ENTR  0x84a0
#define MM_WARP_OWL_IKANA_CANYON_ENTR  0x2040
#define MM_WARP_OWL_STONE_TOWER_ENTR  0xaa30
#define MM_WALLMASTER_DAMPE_ENTR  0xff00
#define MM_WALLMASTER_BTW_ENTRANCE_ENTR  0xff01
#define MM_WALLMASTER_BTW_FOUNTAIN_ENTR  0xff02
#define MM_WALLMASTER_BTW_EXIT_ENTR  0xff03
#define MM_GROTTO_GENERIC_FIELD_PILLAR_ENTR  0x10000
#define MM_GROTTO_GENERIC_GRASS_ENTR  0x10001
#define MM_GROTTO_GENERIC_PATH_SWAMP_ENTR  0x10002
#define MM_GROTTO_GENERIC_WOODS_ENTR  0x10003
#define MM_GROTTO_GENERIC_SWAMP_ENTR  0x10004
#define MM_GROTTO_GENERIC_MOUNTAIN_VILLAGE_ENTR  0x10005
#define MM_GROTTO_GENERIC_TWIN_ISLANDS_ENTR  0x10006
#define MM_GROTTO_GENERIC_PATH_SNOWHEAD_ENTR  0x10007
#define MM_GROTTO_GENERIC_GREAT_BAY_COAST_ENTR  0x10008
#define MM_GROTTO_GENERIC_ZORA_CAPE_ENTR  0x10009
#define MM_GROTTO_GENERIC_PATH_IKANA_ENTR  0x1000a
#define MM_GROTTO_GENERIC_GRAVEYARD_ENTR  0x1000b
#define MM_GROTTO_GENERIC_VALLEY_ENTR  0x1000c
#define MM_GROTTO_COW_FIELD_ENTR  0x1000d
#define MM_GROTTO_COW_COAST_ENTR  0x1000e
#define MM_GROTTO_GOSSIPS_MOUNTAIN_ENTR  0x1430
#define MM_GROTTO_GOSSIPS_CANYON_ENTR  0x1420
#define MM_GROTTO_GOSSIPS_OCEAN_ENTR  0x1400
#define MM_GROTTO_GOSSIPS_SWAMP_ENTR  0x1410
#define MM_GROTTO_DODONGO_ENTR  0x1470
#define MM_GROTTO_SCRUB_ENTR  0x1490
#define MM_GROTTO_PEAHAT_ENTR  0x14d0
#define MM_GROTTO_BIO_BABA_ENTR  0x14b0
#define MM_GROTTO_HOT_WATER_ENTR  0x1450
#define MM_GROTTO_BEAN_ENTR  0x14c0
#define MM_GROTTO_DEKU_PLAYGROUND_ENTR  0x3600
#define MM_GROTTO_JP_CLIMB_LEFT_ENTR  0x14f0
#define MM_GROTTO_JP_CLIMB_RIGHT_ENTR  0x1480
#define MM_GROTTO_JP_LINE_START_ENTR  0x14e0
#define MM_GROTTO_JP_LINE_END_ENTR  0x1460
#define MM_GRAVE_NIGHT1_ENTR  0x0a10
#define MM_GRAVE_NIGHT2_ENTR  0x0a00
#define MM_GRAVE_NIGHT3_ENTR  0x5a00
#define MM_GROTTO_EXIT_GENERIC_FIELD_PILLAR  0x10100
#define MM_GROTTO_EXIT_GENERIC_GRASS  0x10101
#define MM_GROTTO_EXIT_GENERIC_PATH_SWAMP  0x10102
#define MM_GROTTO_EXIT_GENERIC_WOODS  0x10103
#define MM_GROTTO_EXIT_GENERIC_SWAMP  0x10104
#define MM_GROTTO_EXIT_GENERIC_MOUNTAIN_VILLAGE  0x10105
#define MM_GROTTO_EXIT_GENERIC_TWIN_ISLANDS  0x10106
#define MM_GROTTO_EXIT_GENERIC_PATH_SNOWHEAD  0x10107
#define MM_GROTTO_EXIT_GENERIC_GREAT_BAY_COAST  0x10108
#define MM_GROTTO_EXIT_GENERIC_ZORA_CAPE  0x10109
#define MM_GROTTO_EXIT_GENERIC_PATH_IKANA  0x1010a
#define MM_GROTTO_EXIT_GENERIC_GRAVEYARD  0x1010b
#define MM_GROTTO_EXIT_GENERIC_VALLEY  0x1010c
#define MM_GROTTO_EXIT_COW_FIELD  0x1010d
#define MM_GROTTO_EXIT_COW_COAST  0x1010e
#define MM_GROTTO_EXIT_GOSSIPS_MOUNTAIN  0x1010f
#define MM_GROTTO_EXIT_GOSSIPS_CANYON  0x10110
#define MM_GROTTO_EXIT_GOSSIPS_OCEAN  0x10111
#define MM_GROTTO_EXIT_GOSSIPS_SWAMP  0x10112
#define MM_GROTTO_EXIT_DODONGO  0x10113
#define MM_GROTTO_EXIT_SCRUB  0x10114
#define MM_GROTTO_EXIT_PEAHAT  0x10115
#define MM_GROTTO_EXIT_BIO_BABA  0x10116
#define MM_GROTTO_EXIT_HOT_WATER  0x10117
#define MM_GROTTO_EXIT_BEAN  0x5090
#define MM_GROTTO_EXIT_DEKU_PLAYGROUND  0xd640
#define MM_GROTTO_EXIT_JP_CLIMB_LEFT  0x5060
#define MM_GROTTO_EXIT_JP_CLIMB_RIGHT  0x50a0
#define MM_GROTTO_EXIT_JP_LINE_START  0x5070
#define MM_GROTTO_EXIT_JP_LINE_END  0x5080
#define MM_GRAVE_EXIT_NIGHT1  0x8030
#define MM_GRAVE_EXIT_NIGHT2  0x8020
#define MM_GRAVE_EXIT_NIGHT3  0x8010
#define MM_VOID_GREAT_BAY_ENTR  0x6820
#define MM_VOID_GREAT_BAY_BY_PINNACLE_ROCK_ENTR  0x6860
#define MM_VOID_ZORA_CAPE_ENTR  0x6a30
#define MM_VOID_PINNACLE_ROCK_ENTR  0x4410
#define MM_MOON_ENTR  0xc800
#define MM_CLOCK_TOWN_FROM_SONG_OF_TIME_ENTR  0x1c00
#define MM_CLOCK_TOWER_MOON_CRASH_ENTR  0xc030
#define MM_CLOCK_TOWN_FROM_CLOCK_TOWER_ENTR  0xd800
#define MM_CLOCK_TOWER_FROM_CLOCK_TOWN_ENTR  0xc010
#define MM_COAST_FROM_MIKAU_CS_ENTR  0x68a0
#define MM_GROTTO_TYPE_GENERIC_ENTR  0x1440
#define MM_GROTTO_TYPE_COW_ENTR  0x14a0
#define MM_IKANA_GRAVEYARD_FROM_DAMPE_ENTR  0x8040
#define MM_MILK_ROAD_FROM_RANCH2_ENTR  0x3e50
#define MM_MILK_ROAD_FROM_GORMAN_TRACK2_ENTR  0x3e60
#define MM_GORMAN_TRACK_UNK2_ENTR  0xce10
#define MM_GORMAN_TRACK_UNK3_ENTR  0xce20
#define MM_GORMAN_TRACK_UNK5_ENTR  0xce40
#define MM_GORMAN_TRACK_UNK6_ENTR  0xce50
#define MM_GORON_RACETRACK_ALT_ENTR  0xd010
#define MM_INTERNAL_EXIT_GROTTO_ENTR  0xffff
#define MM_LOST_WOODS_ENTR  0xc400

#pragma endregion

const std::map<int, EntranceMetaInfo> MMEntrances =
{
		{ MM_BOSS_TEMPLE_WOODFALL_ENTR, { MM_BOSS_TEMPLE_WOODFALL_ENTR, MM_TEMPLE_WOODFALL, "globa", "", "", GameLayout::all } },
	{ MM_BOSS_TEMPLE_SNOWHEAD_ENTR, { MM_BOSS_TEMPLE_SNOWHEAD_ENTR, MM_TEMPLE_SNOWHEAD, "globa", "", "", GameLayout::all } },
	{ MM_BOSS_TEMPLE_GREAT_BAY_ENTR, { MM_BOSS_TEMPLE_GREAT_BAY_ENTR, MM_TEMPLE_GREAT_BAY, "globa", "", "", GameLayout::all } },
	{ MM_BOSS_TEMPLE_STONE_TOWER_ENTR, { MM_BOSS_TEMPLE_STONE_TOWER_ENTR, MM_TEMPLE_STONE_TOWER_INVERTED, "globa", "", "", GameLayout::all } },
	{ MM_TEMPLE_WOODFALL_ENTR, { MM_TEMPLE_WOODFALL_ENTR, MM_TEMPLE_WOODFALL, "globa", "", "", GameLayout::all } },
	{ MM_TEMPLE_SNOWHEAD_ENTR, { MM_TEMPLE_SNOWHEAD_ENTR, MM_TEMPLE_SNOWHEAD, "globa", "", "", GameLayout::all } },
	{ MM_TEMPLE_GREAT_BAY_ENTR, { MM_TEMPLE_GREAT_BAY_ENTR, MM_TEMPLE_GREAT_BAY, "globa", "", "", GameLayout::all } },
	{ MM_TEMPLE_STONE_TOWER_INVERTED_ENTR, { MM_TEMPLE_STONE_TOWER_INVERTED_ENTR, MM_TEMPLE_STONE_TOWER_INVERTED, "globa", "", "", GameLayout::all } },
	{ MM_TEMPLE_STONE_TOWER_ENTR, { MM_TEMPLE_STONE_TOWER_ENTR, MM_TEMPLE_STONE_TOWER, "globa", "", "", GameLayout::all } },
	{ MM_SPIDER_HOUSE_SWAMP_ENTR, { MM_SPIDER_HOUSE_SWAMP_ENTR, MM_SPIDER_HOUSE_SWAMP, "globa", "", "", GameLayout::all } },
	{ MM_SPIDER_HOUSE_OCEAN_ENTR, { MM_SPIDER_HOUSE_OCEAN_ENTR, MM_SPIDER_HOUSE_OCEAN, "globa", "", "", GameLayout::all } },
	{ MM_BENEATH_THE_WELL_ENTR, { MM_BENEATH_THE_WELL_ENTR, MM_BENEATH_THE_WELL, "globa", "", "", GameLayout::all } },
	{ MM_BENEATH_THE_WELL_BACK_ENTR, { MM_BENEATH_THE_WELL_BACK_ENTR, MM_BENEATH_THE_WELL, "globa", "", "", GameLayout::all } },
	{ MM_IKANA_CASTLE_ENTR, { MM_IKANA_CASTLE_ENTR, MM_CASTLE_IKANA, "globa", "", "", GameLayout::all } },
	{ MM_SECRET_SHRINE_ENTR, { MM_SECRET_SHRINE_ENTR, MM_SECRET_SHRINE, "globa", "", "", GameLayout::all } },
	{ MM_PIRATE_FORTRESS_ENTR, { MM_PIRATE_FORTRESS_ENTR, MM_PIRATE_FORTRESS_EXTERIOR, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWER_ROOF_ENTR, { MM_CLOCK_TOWER_ROOF_ENTR, MM_CLOCK_TOWER_ROOFTOP, "globa", "", "", GameLayout::all } },
	{ MM_WOODFALL_FROM_TEMPLE_ENTR, { MM_WOODFALL_FROM_TEMPLE_ENTR, MM_WOODFALL, "globa", "", "", GameLayout::all } },
	{ MM_SNOWHEAD_FROM_TEMPLE_ENTR, { MM_SNOWHEAD_FROM_TEMPLE_ENTR, MM_SNOWHEAD, "globa", "", "", GameLayout::all } },
	{ MM_GREAT_BAY_FROM_TEMPLE_ENTR, { MM_GREAT_BAY_FROM_TEMPLE_ENTR, MM_GREAT_BAY_COAST, "globa", "", "", GameLayout::all } },
	{ MM_STONE_TOWER_INVERTED_FROM_TEMPLE_ENTR, { MM_STONE_TOWER_INVERTED_FROM_TEMPLE_ENTR, MM_STONE_TOWER_INVERTED, "globa", "", "", GameLayout::all } },
	{ MM_STONE_TOWER_FROM_TEMPLE_ENTR, { MM_STONE_TOWER_FROM_TEMPLE_ENTR, MM_STONE_TOWER, "globa", "", "", GameLayout::all } },
	{ MM_SWAMP_FROM_SPIDER_HOUSE_ENTR, { MM_SWAMP_FROM_SPIDER_HOUSE_ENTR, MM_SOUTHERN_SWAMP, "globa", "", "", GameLayout::all } },
	{ MM_GREAT_BAY_FROM_SPIDER_HOUSE_ENTR, { MM_GREAT_BAY_FROM_SPIDER_HOUSE_ENTR, MM_GREAT_BAY_COAST, "globa", "", "", GameLayout::all } },
	{ MM_IKANA_CANYON_FROM_WELL_ENTR, { MM_IKANA_CANYON_FROM_WELL_ENTR, MM_IKANA_CANYON, "globa", "", "", GameLayout::all } },
	{ MM_IKANA_CASTLE_EXTERIOR_FROM_WELL_ENTR, { MM_IKANA_CASTLE_EXTERIOR_FROM_WELL_ENTR, MM_CASTLE_IKANA, "globa", "", "", GameLayout::all } },
	{ MM_IKANA_CASTLE_EXTERIOR_FROM_CASTLE_ENTR, { MM_IKANA_CASTLE_EXTERIOR_FROM_CASTLE_ENTR, MM_CASTLE_IKANA, "globa", "", "", GameLayout::all } },
	{ MM_IKANA_VALLEY_FROM_SHRINE_ENTR, { MM_IKANA_VALLEY_FROM_SHRINE_ENTR, MM_IKANA_CANYON, "globa", "", "", GameLayout::all } },
	{ MM_GREAT_BAY_FROM_PIRATE_FORTRESS_ENTR, { MM_GREAT_BAY_FROM_PIRATE_FORTRESS_ENTR, MM_GREAT_BAY_COAST, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_FROM_CLOCK_TOWER_ROOF_ENTR, { MM_CLOCK_TOWN_FROM_CLOCK_TOWER_ROOF_ENTR, MM_CLOCK_TOWN_SOUTH, "globa", "", "", GameLayout::all } },
	{ MM_SWAMP_FROM_ROAD_ENTR, { MM_SWAMP_FROM_ROAD_ENTR, MM_SOUTHERN_SWAMP, "globa", "", "", GameLayout::all } },
	{ MM_MOUNTAIN_VILLAGE_FROM_PATH_ENTR, { MM_MOUNTAIN_VILLAGE_FROM_PATH_ENTR, MM_MOUNTAIN_VILLAGE, "globa", "", "", GameLayout::all } },
	{ MM_GREAT_BAY_COAST_FROM_FIELD_ENTR, { MM_GREAT_BAY_COAST_FROM_FIELD_ENTR, MM_GREAT_BAY_COAST, "globa", "", "", GameLayout::all } },
	{ MM_IKANA_VALLEY_FROM_ROAD_ENTR, { MM_IKANA_VALLEY_FROM_ROAD_ENTR, MM_IKANA_CANYON, "globa", "", "", GameLayout::all } },
	{ MM_ROMANI_RANCH_FROM_MILK_ROAD_ENTR, { MM_ROMANI_RANCH_FROM_MILK_ROAD_ENTR, MM_ROMANI_RANCH, "globa", "", "", GameLayout::all } },
	{ MM_SWAMP_ROAD_FROM_SWAMP_ENTR, { MM_SWAMP_ROAD_FROM_SWAMP_ENTR, MM_SOUTHERN_SWAMP, "globa", "", "", GameLayout::all } },
	{ MM_PATH_FROM_MOUNTAIN_VILLAGE_ENTR, { MM_PATH_FROM_MOUNTAIN_VILLAGE_ENTR, MM_PATH_MOUNTAIN_VILLAGE, "globa", "", "", GameLayout::all } },
	{ MM_TERMINA_FIELD_FROM_GREAT_BAY_COAST_ENTR, { MM_TERMINA_FIELD_FROM_GREAT_BAY_COAST_ENTR, MM_TERMINA_FIELD, "globa", "", "", GameLayout::all } },
	{ MM_IKANA_ROAD_FROM_VALLEY_ENTR, { MM_IKANA_ROAD_FROM_VALLEY_ENTR, MM_ROAD_IKANA, "globa", "", "", GameLayout::all } },
	{ MM_MILK_ROAD_FROM_ROMANI_RANCH_ENTR, { MM_MILK_ROAD_FROM_ROMANI_RANCH_ENTR, MM_MILK_ROAD, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_WEST_FROM_SOUTH_BOTTOM_ENTR, { MM_CLOCK_TOWN_WEST_FROM_SOUTH_BOTTOM_ENTR, MM_CLOCK_TOWN_WEST, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_SOUTH_BOTTOM_FROM_WEST_ENTR, { MM_CLOCK_TOWN_SOUTH_BOTTOM_FROM_WEST_ENTR, MM_CLOCK_TOWN_SOUTH, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_EAST_FROM_SOUTH_BOTTOM_ENTR, { MM_CLOCK_TOWN_EAST_FROM_SOUTH_BOTTOM_ENTR, MM_CLOCK_TOWN_EAST, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_SOUTH_BOTTOM_FROM_EAST_ENTR, { MM_CLOCK_TOWN_SOUTH_BOTTOM_FROM_EAST_ENTR, MM_CLOCK_TOWN_SOUTH, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_NORTH_FROM_EAST_ENTR, { MM_CLOCK_TOWN_NORTH_FROM_EAST_ENTR, MM_CLOCK_TOWN_NORTH, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_EAST_FROM_NORTH_ENTR, { MM_CLOCK_TOWN_EAST_FROM_NORTH_ENTR, MM_CLOCK_TOWN_EAST, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_NORTH_FROM_SOUTH_ENTR, { MM_CLOCK_TOWN_NORTH_FROM_SOUTH_ENTR, MM_CLOCK_TOWN_NORTH, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_SOUTH_FROM_NORTH_ENTR, { MM_CLOCK_TOWN_SOUTH_FROM_NORTH_ENTR, MM_CLOCK_TOWN_SOUTH, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_EAST_FROM_SOUTH_TOP_ENTR, { MM_CLOCK_TOWN_EAST_FROM_SOUTH_TOP_ENTR, MM_CLOCK_TOWN_EAST, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_SOUTH_TOP_FROM_EAST_ENTR, { MM_CLOCK_TOWN_SOUTH_TOP_FROM_EAST_ENTR, MM_CLOCK_TOWN_SOUTH, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_WEST_FROM_SOUTH_TOP_ENTR, { MM_CLOCK_TOWN_WEST_FROM_SOUTH_TOP_ENTR, MM_CLOCK_TOWN_WEST, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_SOUTH_TOP_FROM_WEST_ENTR, { MM_CLOCK_TOWN_SOUTH_TOP_FROM_WEST_ENTR, MM_CLOCK_TOWN_SOUTH, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_WEST_FROM_FIELD_ENTR, { MM_CLOCK_TOWN_WEST_FROM_FIELD_ENTR, MM_CLOCK_TOWN_WEST, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_SOUTH_FROM_FIELD_ENTR, { MM_CLOCK_TOWN_SOUTH_FROM_FIELD_ENTR, MM_CLOCK_TOWN_SOUTH, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_EAST_FROM_FIELD_ENTR, { MM_CLOCK_TOWN_EAST_FROM_FIELD_ENTR, MM_CLOCK_TOWN_EAST, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_NORTH_FROM_FIELD_ENTR, { MM_CLOCK_TOWN_NORTH_FROM_FIELD_ENTR, MM_CLOCK_TOWN_NORTH, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_SOUTH_FROM_LAUNDRY_POOL_ENTR, { MM_CLOCK_TOWN_SOUTH_FROM_LAUNDRY_POOL_ENTR, MM_CLOCK_TOWN_SOUTH, "globa", "", "", GameLayout::all } },
	{ MM_LAUNDRY_POOL_ENTR, { MM_LAUNDRY_POOL_ENTR, MM_LAUNDRY_POOL, "globa", "", "", GameLayout::all } },
	{ MM_TERMINA_FIELD_FROM_CLOCK_TOWN_WEST_ENTR, { MM_TERMINA_FIELD_FROM_CLOCK_TOWN_WEST_ENTR, MM_TERMINA_FIELD, "globa", "", "", GameLayout::all } },
	{ MM_TERMINA_FIELD_FROM_CLOCK_TOWN_SOUTH_ENTR, { MM_TERMINA_FIELD_FROM_CLOCK_TOWN_SOUTH_ENTR, MM_TERMINA_FIELD, "globa", "", "", GameLayout::all } },
	{ MM_TERMINA_FIELD_FROM_CLOCK_TOWN_EAST_ENTR, { MM_TERMINA_FIELD_FROM_CLOCK_TOWN_EAST_ENTR, MM_TERMINA_FIELD, "globa", "", "", GameLayout::all } },
	{ MM_TERMINA_FIELD_FROM_CLOCK_TOWN_NORTH_ENTR, { MM_TERMINA_FIELD_FROM_CLOCK_TOWN_NORTH_ENTR, MM_TERMINA_FIELD, "globa", "", "", GameLayout::all } },
	{ MM_IKANA_ROAD_FROM_FIELD_ENTR, { MM_IKANA_ROAD_FROM_FIELD_ENTR, MM_ROAD_IKANA, "globa", "", "", GameLayout::all } },
	{ MM_TERMINA_FIELD_FROM_ROAD_TO_IKANA_ENTR, { MM_TERMINA_FIELD_FROM_ROAD_TO_IKANA_ENTR, MM_TERMINA_FIELD, "globa", "", "", GameLayout::all } },
	{ MM_MOUNTAIN_VILLAGE_PATH_FROM_TERMINA_FIELD_ENTR, { MM_MOUNTAIN_VILLAGE_PATH_FROM_TERMINA_FIELD_ENTR, MM_PATH_MOUNTAIN_VILLAGE, "globa", "", "", GameLayout::all } },
	{ MM_TERMINA_FIELD_FROM_PATH_TO_MOUNTAIN_VILLAGE_ENTR, { MM_TERMINA_FIELD_FROM_PATH_TO_MOUNTAIN_VILLAGE_ENTR, MM_TERMINA_FIELD, "globa", "", "", GameLayout::all } },
	{ MM_SWAMP_ROAD_FROM_FIELD_ENTR, { MM_SWAMP_ROAD_FROM_FIELD_ENTR, MM_ROAD_SOUTHERN_SWAMP, "globa", "", "", GameLayout::all } },
	{ MM_TERMINA_FIELD_FROM_ROAD_TO_SWAMP_ENTR, { MM_TERMINA_FIELD_FROM_ROAD_TO_SWAMP_ENTR, MM_TERMINA_FIELD, "globa", "", "", GameLayout::all } },
	{ MM_MILK_ROAD_FROM_FIELD_ENTR, { MM_MILK_ROAD_FROM_FIELD_ENTR, MM_MILK_ROAD, "globa", "", "", GameLayout::all } },
	{ MM_TERMINA_FIELD_FROM_MILK_ROAD_ENTR, { MM_TERMINA_FIELD_FROM_MILK_ROAD_ENTR, MM_TERMINA_FIELD, "globa", "", "", GameLayout::all } },
	{ MM_GORMAN_TRACK_FROM_MILK_ROAD_ENTR, { MM_GORMAN_TRACK_FROM_MILK_ROAD_ENTR, MM_GORMAN_TRACK, "globa", "", "", GameLayout::all } },
	{ MM_MILK_ROAD_FROM_GORMAN_TRACK_ENTR, { MM_MILK_ROAD_FROM_GORMAN_TRACK_ENTR, MM_MILK_ROAD, "globa", "", "", GameLayout::all } },
	{ MM_GORMAN_BACK_FROM_MILK_ROAD_ENTR, { MM_GORMAN_BACK_FROM_MILK_ROAD_ENTR, MM_GORMAN_TRACK, "globa", "", "", GameLayout::all } },
	{ MM_MILK_ROAD_FROM_GORMAN_BACK_ENTR, { MM_MILK_ROAD_FROM_GORMAN_BACK_ENTR, MM_MILK_ROAD, "globa", "", "", GameLayout::all } },
	{ MM_SNOWHEAD_PATH_FROM_MOUNTAIN_VILLAGE_ENTR, { MM_SNOWHEAD_PATH_FROM_MOUNTAIN_VILLAGE_ENTR, MM_PATH_SNOWHEAD, "globa", "", "", GameLayout::all } },
	{ MM_MOUNTAIN_VILLAGE_FROM_SNOWHEAD_PATH_ENTR, { MM_MOUNTAIN_VILLAGE_FROM_SNOWHEAD_PATH_ENTR, MM_MOUNTAIN_VILLAGE, "globa", "", "", GameLayout::all } },
	{ MM_SNOWHEAD_FROM_SNOWHEAD_PATH_ENTR, { MM_SNOWHEAD_FROM_SNOWHEAD_PATH_ENTR, MM_SNOWHEAD, "globa", "", "", GameLayout::all } },
	{ MM_PATH_SNOWHEAD_FROM_SNOWHEAD_ENTR, { MM_PATH_SNOWHEAD_FROM_SNOWHEAD_ENTR, MM_PATH_SNOWHEAD, "globa", "", "", GameLayout::all } },
	{ MM_IKANA_GRAVEYARD_ENTR, { MM_IKANA_GRAVEYARD_ENTR, MM_IKANA_GRAVEYARD, "globa", "", "", GameLayout::all } },
	{ MM_IKANA_ROAD_FROM_IKANA_GRAVEYARD_ENTR, { MM_IKANA_ROAD_FROM_IKANA_GRAVEYARD_ENTR, MM_ROAD_IKANA, "globa", "", "", GameLayout::all } },
	{ MM_ZORA_CAPE_FROM_GREAT_BAY_COAST_ENTR, { MM_ZORA_CAPE_FROM_GREAT_BAY_COAST_ENTR, MM_ZORA_CAPE, "globa", "", "", GameLayout::all } },
	{ MM_GREAT_BAY_COAST_FROM_ZORA_CAPE_ENTR, { MM_GREAT_BAY_COAST_FROM_ZORA_CAPE_ENTR, MM_GREAT_BAY_COAST, "globa", "", "", GameLayout::all } },
	{ MM_PINNACLE_ROCK_ENTR, { MM_PINNACLE_ROCK_ENTR, MM_PINNACLE_ROCK, "globa", "", "", GameLayout::all } },
	{ MM_GREAT_BAY_FROM_PINNACLE_ROCK_ENTR, { MM_GREAT_BAY_FROM_PINNACLE_ROCK_ENTR, MM_GREAT_BAY_COAST, "globa", "", "", GameLayout::all } },
	{ MM_ZORA_CAPE_FROM_HALL_WATER_ENTR, { MM_ZORA_CAPE_FROM_HALL_WATER_ENTR, MM_ZORA_CAPE, "globa", "", "", GameLayout::all } },
	{ MM_ZORA_HALL_UNDERWATER_ENTR, { MM_ZORA_HALL_UNDERWATER_ENTR, MM_ZORA_HALL, "globa", "", "", GameLayout::all } },
	{ MM_ZORA_CAPE_PENINSULA_ENTR, { MM_ZORA_CAPE_PENINSULA_ENTR, MM_ZORA_CAPE, "globa", "", "", GameLayout::all } },
	{ MM_ZORA_HALL_LEDGE_ENTR, { MM_ZORA_HALL_LEDGE_ENTR, MM_ZORA_HALL, "globa", "", "", GameLayout::all } },
	{ MM_DEKU_PALACE_MAIN_ENTRANCE_ENTR, { MM_DEKU_PALACE_MAIN_ENTRANCE_ENTR, MM_DEKU_PALACE, "globa", "", "", GameLayout::all } },
	{ MM_SWAMP_FROM_PALACE_MAIN_ENTRANCE_ENTR, { MM_SWAMP_FROM_PALACE_MAIN_ENTRANCE_ENTR, MM_SOUTHERN_SWAMP, "globa", "", "", GameLayout::all } },
	{ MM_DEKU_PALACE_LEDGE_ENTR, { MM_DEKU_PALACE_LEDGE_ENTR, MM_DEKU_PALACE, "globa", "", "", GameLayout::all } },
	{ MM_SWAMP_FROM_PALACE_LEDGE_ENTR, { MM_SWAMP_FROM_PALACE_LEDGE_ENTR, MM_SOUTHERN_SWAMP, "globa", "", "", GameLayout::all } },
	{ MM_WOODFALL_ENTR, { MM_WOODFALL_ENTR, MM_WOODFALL, "globa", "", "", GameLayout::all } },
	{ MM_SWAMP_FROM_WOODFALL_ENTR, { MM_SWAMP_FROM_WOODFALL_ENTR, MM_SOUTHERN_SWAMP, "globa", "", "", GameLayout::all } },
	{ MM_MYSTERY_WOODS_ENTR, { MM_MYSTERY_WOODS_ENTR, MM_LOST_WOODS, "globa", "", "", GameLayout::all } },
	{ MM_SWAMP_FROM_MYSTERY_WOODS_ENTR, { MM_SWAMP_FROM_MYSTERY_WOODS_ENTR, MM_SOUTHERN_SWAMP, "globa", "", "", GameLayout::all } },
	{ MM_SEWERS_FROM_EXTERIOR_GATE_ENTR, { MM_SEWERS_FROM_EXTERIOR_GATE_ENTR, MM_PIRATE_SEWERS, "globa", "", "", GameLayout::all } },
	{ MM_EXTERIOR_GATE_FROM_SEWERS_ENTR, { MM_EXTERIOR_GATE_FROM_SEWERS_ENTR, MM_PIRATE_FORTRESS_EXTERIOR, "globa", "", "", GameLayout::all } },
	{ MM_PIRATE_FORTRESS_INTERIOR_ENTR, { MM_PIRATE_FORTRESS_INTERIOR_ENTR, MM_PIRATE_FORTRESS_INTERIOR, "globa", "", "", GameLayout::all } },
	{ MM_PIRATE_FORTRESS_EXTERIOR_FROM_INTERIOR_ENTR, { MM_PIRATE_FORTRESS_EXTERIOR_FROM_INTERIOR_ENTR, MM_PIRATE_FORTRESS_EXTERIOR, "globa", "", "", GameLayout::all } },
	{ MM_PIRATE_FORTRESS_INTERIOR_FROM_LOOKOUT_ENTR, { MM_PIRATE_FORTRESS_INTERIOR_FROM_LOOKOUT_ENTR, MM_PIRATE_FORTRESS_INTERIOR, "globa", "", "", GameLayout::all } },
	{ MM_PIRATE_FORTRESS_EXTERIOR_LOOKOUT_ENTR, { MM_PIRATE_FORTRESS_EXTERIOR_LOOKOUT_ENTR, MM_PIRATE_FORTRESS_EXTERIOR, "globa", "", "", GameLayout::all } },
	{ MM_IKANA_CASTLE_GARDENS_ENTR, { MM_IKANA_CASTLE_GARDENS_ENTR, MM_CASTLE_IKANA, "globa", "", "", GameLayout::all } },
	{ MM_IKANA_CANYON_FROM_CASTLE_GARDENS_ENTR, { MM_IKANA_CANYON_FROM_CASTLE_GARDENS_ENTR, MM_IKANA_CANYON, "globa", "", "", GameLayout::all } },
	{ MM_STONE_TOWER_ENTR, { MM_STONE_TOWER_ENTR, MM_STONE_TOWER, "globa", "", "", GameLayout::all } },
	{ MM_IKANA_CANYON_FROM_STONE_TOWER_ENTR, { MM_IKANA_CANYON_FROM_STONE_TOWER_ENTR, MM_IKANA_CANYON, "globa", "", "", GameLayout::all } },
	{ MM_TWIN_ISLANDS_FROM_MOUNTAIN_VILLAGE_ENTR, { MM_TWIN_ISLANDS_FROM_MOUNTAIN_VILLAGE_ENTR, MM_TWIN_ISLANDS, "globa", "", "", GameLayout::all } },
	{ MM_MOUNTAIN_VILLAGE_FROM_TWIN_ISLANDS_ENTR, { MM_MOUNTAIN_VILLAGE_FROM_TWIN_ISLANDS_ENTR, MM_MOUNTAIN_VILLAGE, "globa", "", "", GameLayout::all } },
	{ MM_TWIN_ISLANDS_FROM_GORON_VILLAGE_ENTR, { MM_TWIN_ISLANDS_FROM_GORON_VILLAGE_ENTR, MM_TWIN_ISLANDS, "globa", "", "", GameLayout::all } },
	{ MM_GORON_VILLAGE_FROM_TWIN_ISLANDS_ENTR, { MM_GORON_VILLAGE_FROM_TWIN_ISLANDS_ENTR, MM_GORON_VILLAGE_WINTER, "globa", "", "", GameLayout::all } },
	{ MM_SWAMP_FROM_IKANA_CANYON_ENTR, { MM_SWAMP_FROM_IKANA_CANYON_ENTR, MM_IKANA_CANYON, "globa", "", "", GameLayout::all } },
	{ MM_IKANA_CASTLE_INTERIOR_KEG_ENTR, { MM_IKANA_CASTLE_INTERIOR_KEG_ENTR, MM_CASTLE_IKANA, "globa", "", "", GameLayout::all } },
	{ MM_IKANA_CASTLE_INTERIOR_BLOCK_ENTR, { MM_IKANA_CASTLE_INTERIOR_BLOCK_ENTR, MM_CASTLE_IKANA, "globa", "", "", GameLayout::all } },
	{ MM_CHEST_GAME_ENTR, { MM_CHEST_GAME_ENTR, MM_TREASURE_SHOP, "globa", "", "", GameLayout::all } },
	{ MM_HONEY_AND_DARLING_GAME_ENTR, { MM_HONEY_AND_DARLING_GAME_ENTR, MM_HONEY_DARLING, "globa", "", "", GameLayout::all } },
	{ MM_MAYORS_OFFICE_ENTR, { MM_MAYORS_OFFICE_ENTR, MM_MAYOR_HOUSE, "globa", "", "", GameLayout::all } },
	{ MM_TOWN_ARCHERY_ENTR, { MM_TOWN_ARCHERY_ENTR, MM_SHOOTING_GALLERY, "globa", "", "", GameLayout::all } },
	{ MM_MILK_BAR_ENTR, { MM_MILK_BAR_ENTR, MM_MILK_BAR, "globa", "", "", GameLayout::all } },
	{ MM_FAIRY_FOUNTAIN_TOWN_ENTR, { MM_FAIRY_FOUNTAIN_TOWN_ENTR, MM_FAIRY_CLOCK_TOWN, "globa", "", "", GameLayout::all } },
	{ MM_SWORDSMAN_SCHOOL_ENTR, { MM_SWORDSMAN_SCHOOL_ENTR, MM_SWORDSMAN_SCHOOL, "globa", "", "", GameLayout::all } },
	{ MM_CURIOSITY_SHOP_ENTR, { MM_CURIOSITY_SHOP_ENTR, MM_CURIOSITY_SHOP, "globa", "", "", GameLayout::all } },
	{ MM_TRADING_POST_ENTR, { MM_TRADING_POST_ENTR, MM_TRADING_POST, "globa", "", "", GameLayout::all } },
	{ MM_BOMB_SHOP_ENTR, { MM_BOMB_SHOP_ENTR, MM_BOMB_SHOP, "globa", "", "", GameLayout::all } },
	{ MM_POST_OFFICE_ENTR, { MM_POST_OFFICE_ENTR, MM_POST_OFFICE, "globa", "", "", GameLayout::all } },
	{ MM_LOTTERY_ENTR, { MM_LOTTERY_ENTR, MM_LOTTERY, "globa", "", "", GameLayout::all } },
	{ MM_KAFEI_HIDEOUT_ENTR, { MM_KAFEI_HIDEOUT_ENTR, MM_CURIOSITY_SHOP, "globa", "", "", GameLayout::all } },
	{ MM_POTION_SHOP_ENTR, { MM_POTION_SHOP_ENTR, MM_POTION_SHOP, "globa", "", "", GameLayout::all } },
	{ MM_DEKU_SHRINE_ENTR, { MM_DEKU_SHRINE_ENTR, MM_DEKU_SHRINE, "globa", "", "", GameLayout::all } },
	{ MM_GORON_SHOP_ENTR, { MM_GORON_SHOP_ENTR, MM_GORON_SHOP, "globa", "", "", GameLayout::all } },
	{ MM_FISHER_HUT_ENTR, { MM_FISHER_HUT_ENTR, MM_FISHERMAN_HUT, "globa", "", "", GameLayout::all } },
	{ MM_LABORATORY_ENTR, { MM_LABORATORY_ENTR, MM_LABORATORY, "globa", "", "", GameLayout::all } },
	{ MM_ROOM_EVANS_ENTR, { MM_ROOM_EVANS_ENTR, MM_ZORA_EVANS_ROOM, "globa", "", "", GameLayout::all } },
	{ MM_ROOM_JAPAS_ENTR, { MM_ROOM_JAPAS_ENTR, MM_ZORA_JAPAS_ROOM, "globa", "", "", GameLayout::all } },
	{ MM_ROOM_TIJO_ENTR, { MM_ROOM_TIJO_ENTR, MM_ZORA_TIJO_ROOM, "globa", "", "", GameLayout::all } },
	{ MM_ROOM_LULU_ENTR, { MM_ROOM_LULU_ENTR, MM_ZORA_LULU_ROOM, "globa", "", "", GameLayout::all } },
	{ MM_ZORA_SHOP_ENTR, { MM_ZORA_SHOP_ENTR, MM_ZORA_SHOP, "globa", "", "", GameLayout::all } },
	{ MM_GHOST_HUT_ENTR, { MM_GHOST_HUT_ENTR, MM_GHOST_HUT, "globa", "", "", GameLayout::all } },
	{ MM_MUSIC_BOX_HOUSE_ENTR, { MM_MUSIC_BOX_HOUSE_ENTR, MM_MUSIC_BOX_HOUSE, "globa", "", "", GameLayout::all } },
	{ MM_FAIRY_FOUNTAIN_IKANA_ENTR, { MM_FAIRY_FOUNTAIN_IKANA_ENTR, MM_FAIRY_IKANA, "globa", "", "", GameLayout::all } },
	{ MM_IKANA_CAVERN_ENTR, { MM_IKANA_CAVERN_ENTR, MM_SECRET_SHRINE, "globa", "", "", GameLayout::all } },
	{ MM_FAIRY_FOUNTAIN_GREAT_BAY_ENTR, { MM_FAIRY_FOUNTAIN_GREAT_BAY_ENTR, MM_FAIRY_GREAT_BAY_COAST, "globa", "", "", GameLayout::all } },
	{ MM_FAIRY_FOUNTAIN_SNOWHEAD_ENTR, { MM_FAIRY_FOUNTAIN_SNOWHEAD_ENTR, MM_FAIRY_SNOWHEAD, "globa", "", "", GameLayout::all } },
	{ MM_FAIRY_FOUNTAIN_WOODFALL_ENTR, { MM_FAIRY_FOUNTAIN_WOODFALL_ENTR, MM_FAIRY_WOODFALL, "globa", "", "", GameLayout::all } },
	{ MM_GORON_GRAVEYARD_ENTR, { MM_GORON_GRAVEYARD_ENTR, MM_GORON_GRAVEYARD, "globa", "", "", GameLayout::all } },
	{ MM_BLACKSMITH_ENTR, { MM_BLACKSMITH_ENTR, MM_BLACKSMITH, "globa", "", "", GameLayout::all } },
	{ MM_SWAMP_ARCHERY_ENTR, { MM_SWAMP_ARCHERY_ENTR, MM_SHOOTING_GALLERY_SWAMP, "globa", "", "", GameLayout::all } },
	{ MM_GORON_RACETRACK_ENTR, { MM_GORON_RACETRACK_ENTR, MM_GORON_RACETRACK, "globa", "", "", GameLayout::all } },
	{ MM_BEAVERS_ENTR, { MM_BEAVERS_ENTR, MM_WATERFALL_RAPIDS, "globa", "", "", GameLayout::all } },
	{ MM_CUCCO_SHACK_ENTR, { MM_CUCCO_SHACK_ENTR, MM_CUCCO_SHACK, "globa", "", "", GameLayout::all } },
	{ MM_DOGGY_RACETRACK_ENTR, { MM_DOGGY_RACETRACK_ENTR, MM_DOG_RACETRACK, "globa", "", "", GameLayout::all } },
	{ MM_STABLES_ENTR, { MM_STABLES_ENTR, MM_RANCH_HOUSE_BARN, "globa", "", "", GameLayout::all } },
	{ MM_RANCH_HOUSE_ENTR, { MM_RANCH_HOUSE_ENTR, MM_ROMANI_RANCH_BARN, "globa", "", "", GameLayout::all } },
	{ MM_GORON_SHRINE_ENTR, { MM_GORON_SHRINE_ENTR, MM_GORON_SHRINE, "globa", "", "", GameLayout::all } },
	{ MM_DEKU_PALACE_THRONE_ENTR, { MM_DEKU_PALACE_THRONE_ENTR, MM_DEKU_KING_CHAMBER, "globa", "", "", GameLayout::all } },
	{ MM_DEKU_PALACE_THRONE_CAGE_ENTR, { MM_DEKU_PALACE_THRONE_CAGE_ENTR, MM_DEKU_KING_CHAMBER, "globa", "", "", GameLayout::all } },
	{ MM_LONE_PEAK_SHRINE_ENTR, { MM_LONE_PEAK_SHRINE_ENTR, MM_LONE_PEAK, "globa", "", "", GameLayout::all } },
	{ MM_STOCK_POT_INN_ENTR, { MM_STOCK_POT_INN_ENTR, MM_STOCK_POT_INN, "globa", "", "", GameLayout::all } },
	{ MM_STOCK_POT_INN_ROOF_ENTR, { MM_STOCK_POT_INN_ROOF_ENTR, MM_STOCK_POT_INN, "globa", "", "", GameLayout::all } },
	{ MM_SEWERS_FROM_EXTERIOR_DOOR_ENTR, { MM_SEWERS_FROM_EXTERIOR_DOOR_ENTR, MM_PIRATE_SEWERS, "globa", "", "", GameLayout::all } },
	{ MM_TOURIST_INFORMATION_ENTR, { MM_TOURIST_INFORMATION_ENTR, MM_TOURIST_INFORMATION, "globa", "", "", GameLayout::all } },
	{ MM_ASTRAL_OBSERVATORY_FROM_CLOCK_TOWN_EAST_ENTR, { MM_ASTRAL_OBSERVATORY_FROM_CLOCK_TOWN_EAST_ENTR,  MM_OBSERVATORY, "globa", "", "", GameLayout::all } },
	{ MM_ASTRAL_OBSERVATORY_FROM_FIELD_ENTR, { MM_ASTRAL_OBSERVATORY_FROM_FIELD_ENTR,  MM_OBSERVATORY, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_EAST_FROM_CHEST_GAME_ENTR, { MM_CLOCK_TOWN_EAST_FROM_CHEST_GAME_ENTR, MM_CLOCK_TOWN_EAST, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_EAST_FROM_HONEY_AND_DARLING_ENTR, { MM_CLOCK_TOWN_EAST_FROM_HONEY_AND_DARLING_ENTR, MM_CLOCK_TOWN_EAST, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_EAST_FROM_MAYORS_OFFICE_ENTR, { MM_CLOCK_TOWN_EAST_FROM_MAYORS_OFFICE_ENTR, MM_CLOCK_TOWN_EAST, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_EAST_FROM_TOWN_ARCHERY_ENTR, { MM_CLOCK_TOWN_EAST_FROM_TOWN_ARCHERY_ENTR, MM_CLOCK_TOWN_EAST, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_EAST_FROM_STOCK_POT_INN_ENTR, { MM_CLOCK_TOWN_EAST_FROM_STOCK_POT_INN_ENTR, MM_CLOCK_TOWN_EAST, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_EAST_FROM_STOCK_POT_INN_ROOF_ENTR, { MM_CLOCK_TOWN_EAST_FROM_STOCK_POT_INN_ROOF_ENTR, MM_CLOCK_TOWN_EAST, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_EAST_FROM_MILK_BAR_ENTR, { MM_CLOCK_TOWN_EAST_FROM_MILK_BAR_ENTR, MM_CLOCK_TOWN_EAST, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_NORTH_FROM_FAIRY_FOUNTAIN_ENTR, { MM_CLOCK_TOWN_NORTH_FROM_FAIRY_FOUNTAIN_ENTR, MM_CLOCK_TOWN_NORTH, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_WEST_FROM_SWORDSMAN_SCHOOL_ENTR, { MM_CLOCK_TOWN_WEST_FROM_SWORDSMAN_SCHOOL_ENTR, MM_CLOCK_TOWN_WEST, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_WEST_FROM_CURIOSITY_SHOP_ENTR, { MM_CLOCK_TOWN_WEST_FROM_CURIOSITY_SHOP_ENTR, MM_CLOCK_TOWN_WEST, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_WEST_FROM_TRADING_POST_ENTR, { MM_CLOCK_TOWN_WEST_FROM_TRADING_POST_ENTR, MM_CLOCK_TOWN_WEST, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_WEST_FROM_BOMB_SHOP_ENTR, { MM_CLOCK_TOWN_WEST_FROM_BOMB_SHOP_ENTR, MM_CLOCK_TOWN_WEST, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_WEST_FROM_POST_OFFICE_ENTR, { MM_CLOCK_TOWN_WEST_FROM_POST_OFFICE_ENTR, MM_CLOCK_TOWN_WEST, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_WEST_FROM_LOTTERY_ENTR, { MM_CLOCK_TOWN_WEST_FROM_LOTTERY_ENTR, MM_CLOCK_TOWN_WEST, "globa", "", "", GameLayout::all } },
	{ MM_LAUNDRY_POOL_FROM_KAFEI_HIDEOUT_ENTR, { MM_LAUNDRY_POOL_FROM_KAFEI_HIDEOUT_ENTR, MM_LAUNDRY_POOL, "globa", "", "", GameLayout::all } },
	{ MM_SWAMP_FROM_POTION_SHOP_ENTR, { MM_SWAMP_FROM_POTION_SHOP_ENTR, MM_SOUTHERN_SWAMP, "globa", "", "", GameLayout::all } },
	{ MM_DEKU_PALACE_EXTERIOR_FROM_SHRINE_ENTR, { MM_DEKU_PALACE_EXTERIOR_FROM_SHRINE_ENTR, MM_DEKU_PALACE, "globa", "", "", GameLayout::all } },
	{ MM_GORON_SHRINE_FROM_SHOP_ENTR, { MM_GORON_SHRINE_FROM_SHOP_ENTR, MM_GORON_SHRINE, "globa", "", "", GameLayout::all } },
	{ MM_GREAT_BAY_COAST_FROM_FISHER_HUT_ENTR, { MM_GREAT_BAY_COAST_FROM_FISHER_HUT_ENTR, MM_GREAT_BAY_COAST, "globa", "", "", GameLayout::all } },
	{ MM_GREAT_BAY_COAST_FROM_LABORATORY_ENTR, { MM_GREAT_BAY_COAST_FROM_LABORATORY_ENTR, MM_GREAT_BAY_COAST, "globa", "", "", GameLayout::all } },
	{ MM_ZORA_HALL_FROM_EVANS_ENTR, { MM_ZORA_HALL_FROM_EVANS_ENTR, MM_ZORA_HALL, "globa", "", "", GameLayout::all } },
	{ MM_ZORA_HALL_FROM_JAPAS_ENTR, { MM_ZORA_HALL_FROM_JAPAS_ENTR, MM_ZORA_HALL, "globa", "", "", GameLayout::all } },
	{ MM_ZORA_HALL_FROM_TIJO_ENTR, { MM_ZORA_HALL_FROM_TIJO_ENTR, MM_ZORA_HALL, "globa", "", "", GameLayout::all } },
	{ MM_ZORA_HALL_FROM_LULU_ENTR, { MM_ZORA_HALL_FROM_LULU_ENTR, MM_ZORA_HALL, "globa", "", "", GameLayout::all } },
	{ MM_ZORA_HALL_FROM_SHOP_ENTR, { MM_ZORA_HALL_FROM_SHOP_ENTR, MM_ZORA_HALL, "globa", "", "", GameLayout::all } },
	{ MM_IKANA_CANYON_FROM_GHOST_HUT_ENTR, { MM_IKANA_CANYON_FROM_GHOST_HUT_ENTR, MM_IKANA_CANYON, "globa", "", "", GameLayout::all } },
	{ MM_IKANA_CANYON_FROM_MUSIC_BOX_HOUSE_ENTR, { MM_IKANA_CANYON_FROM_MUSIC_BOX_HOUSE_ENTR, MM_IKANA_CANYON, "globa", "", "", GameLayout::all } },
	{ MM_IKANA_CANYON_FROM_FAIRY_FOUNTAIN_ENTR, { MM_IKANA_CANYON_FROM_FAIRY_FOUNTAIN_ENTR, MM_IKANA_CANYON, "globa", "", "", GameLayout::all } },
	{ MM_IKANA_CANYON_FROM_CAVERN_ENTR, { MM_IKANA_CANYON_FROM_CAVERN_ENTR, MM_IKANA_CANYON, "globa", "", "", GameLayout::all } },
	{ MM_EXTERIOR_DOOR_FROM_SEWERS_ENTR, { MM_EXTERIOR_DOOR_FROM_SEWERS_ENTR, MM_PIRATE_FORTRESS_EXTERIOR, "globa", "", "", GameLayout::all } },
	{ MM_GREAT_BAY_FROM_FAIRY_FOUNTAIN_ENTR, { MM_GREAT_BAY_FROM_FAIRY_FOUNTAIN_ENTR, MM_GREAT_BAY_COAST, "globa", "", "", GameLayout::all } },
	{ MM_SNOWHEAD_FROM_FAIRY_FOUNTAIN_ENTR, { MM_SNOWHEAD_FROM_FAIRY_FOUNTAIN_ENTR, MM_SNOWHEAD, "globa", "", "", GameLayout::all } },
	{ MM_SWAMP_FROM_TOURIST_INFORMATION_ENTR, { MM_SWAMP_FROM_TOURIST_INFORMATION_ENTR, MM_SOUTHERN_SWAMP, "globa", "", "", GameLayout::all } },
	{ MM_WOODFALL_FROM_FAIRY_FOUNTAIN_ENTR, { MM_WOODFALL_FROM_FAIRY_FOUNTAIN_ENTR, MM_WOODFALL, "globa", "", "", GameLayout::all } },
	{ MM_MOUNTAIN_VILLAGE_FROM_GORON_GRAVEYARD_ENTR, { MM_MOUNTAIN_VILLAGE_FROM_GORON_GRAVEYARD_ENTR, MM_MOUNTAIN_VILLAGE, "globa", "", "", GameLayout::all } },
	{ MM_MOUNTAIN_VILLAGE_FROM_BLACKSMITH_ENTR, { MM_MOUNTAIN_VILLAGE_FROM_BLACKSMITH_ENTR, MM_MOUNTAIN_VILLAGE, "globa", "", "", GameLayout::all } },
	{ MM_ROMANI_RANCH_FROM_CUCCO_SHACK_ENTR, { MM_ROMANI_RANCH_FROM_CUCCO_SHACK_ENTR, MM_ROMANI_RANCH, "globa", "", "", GameLayout::all } },
	{ MM_ROMANI_RANCH_FROM_DOGGY_RACETRACK_ENTR, { MM_ROMANI_RANCH_FROM_DOGGY_RACETRACK_ENTR, MM_ROMANI_RANCH, "globa", "", "", GameLayout::all } },
	{ MM_ROMANI_RANCH_FROM_STABLES_ENTR, { MM_ROMANI_RANCH_FROM_STABLES_ENTR, MM_ROMANI_RANCH, "globa", "", "", GameLayout::all } },
	{ MM_ROMANI_RANCH_FROM_RANCH_HOUSE_ENTR, { MM_ROMANI_RANCH_FROM_RANCH_HOUSE_ENTR, MM_ROMANI_RANCH, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_EAST_FROM_ASTRAL_OBSERVATORY_ENTR, { MM_CLOCK_TOWN_EAST_FROM_ASTRAL_OBSERVATORY_ENTR, MM_CLOCK_TOWN_EAST, "globa", "", "", GameLayout::all } },
	{ MM_FIELD_FROM_ASTRAL_OBSERVATORY_ENTR, { MM_FIELD_FROM_ASTRAL_OBSERVATORY_ENTR, MM_TERMINA_FIELD, "globa", "", "", GameLayout::all } },
	{ MM_SWAMP_ROAD_FROM_ARCHERY_ENTR, { MM_SWAMP_ROAD_FROM_ARCHERY_ENTR, MM_ROAD_SOUTHERN_SWAMP, "globa", "", "", GameLayout::all } },
	{ MM_TWIN_ISLANDS_FROM_GORON_RACETRACK_ENTR, { MM_TWIN_ISLANDS_FROM_GORON_RACETRACK_ENTR, MM_TWIN_ISLANDS, "globa", "", "", GameLayout::all } },
	{ MM_ZORA_CAPE_FROM_BEAVERS_ENTR, { MM_ZORA_CAPE_FROM_BEAVERS_ENTR, MM_ZORA_CAPE, "globa", "", "", GameLayout::all } },
	{ MM_GORON_VILLAGE_FROM_GORON_SHRINE_ENTR, { MM_GORON_VILLAGE_FROM_GORON_SHRINE_ENTR, MM_GORON_VILLAGE_WINTER, "globa", "", "", GameLayout::all } },
	{ MM_GORON_VILLAGE_FROM_LONE_PEAK_SHRINE_ENTR, { MM_GORON_VILLAGE_FROM_LONE_PEAK_SHRINE_ENTR, MM_GORON_VILLAGE_WINTER, "globa", "", "", GameLayout::all } },
	{ MM_DEKU_PALACE_EXTERIOR_FROM_THRONE_ENTR, { MM_DEKU_PALACE_EXTERIOR_FROM_THRONE_ENTR, MM_DEKU_PALACE, "globa", "", "", GameLayout::all } },
	{ MM_DEKU_PALACE_EXTERIOR_FROM_THRONE_CAGE_ENTR, { MM_DEKU_PALACE_EXTERIOR_FROM_THRONE_CAGE_ENTR, MM_DEKU_PALACE, "globa", "", "", GameLayout::all } },
	{ MM_SAKON_HIDEOUT_ENTR, { MM_SAKON_HIDEOUT_ENTR, MM_SAKON_HIDEOUT, "globa", "", "", GameLayout::all } },
	{ MM_IKANA_CANYON_FROM_SAKON_HIDEOUT_ENTR, { MM_IKANA_CANYON_FROM_SAKON_HIDEOUT_ENTR, MM_IKANA_CANYON, "globa", "", "", GameLayout::all } },
	{ MM_WARP_OWL_GREAT_BAY_ENTR, { MM_WARP_OWL_GREAT_BAY_ENTR, MM_GREAT_BAY_COAST, "globa", "", "", GameLayout::all } },
	{ MM_WARP_OWL_ZORA_CAPE_ENTR, { MM_WARP_OWL_ZORA_CAPE_ENTR, MM_ZORA_CAPE, "globa", "", "", GameLayout::all } },
	{ MM_WARP_OWL_SNOWHEAD_ENTR, { MM_WARP_OWL_SNOWHEAD_ENTR, MM_SNOWHEAD, "globa", "", "", GameLayout::all } },
	{ MM_WARP_OWL_MOUNTAIN_VILLAGE_ENTR, { MM_WARP_OWL_MOUNTAIN_VILLAGE_ENTR, MM_MOUNTAIN_VILLAGE, "globa", "", "", GameLayout::all } },
	{ MM_WARP_OWL_CLOCK_TOWN_ENTR, { MM_WARP_OWL_CLOCK_TOWN_ENTR, MM_CLOCK_TOWN_SOUTH, "globa", "", "", GameLayout::all } },
	{ MM_WARP_OWL_MILK_ROAD_ENTR, { MM_WARP_OWL_MILK_ROAD_ENTR, MM_MILK_ROAD, "globa", "", "", GameLayout::all } },
	{ MM_WARP_OWL_WOODFALL_ENTR, { MM_WARP_OWL_WOODFALL_ENTR, MM_WOODFALL, "globa", "", "", GameLayout::all } },
	{ MM_WARP_OWL_SOUTHERN_SWAMP_ENTR, { MM_WARP_OWL_SOUTHERN_SWAMP_ENTR, MM_SOUTHERN_SWAMP, "globa", "", "", GameLayout::all } },
	{ MM_WARP_OWL_IKANA_CANYON_ENTR, { MM_WARP_OWL_IKANA_CANYON_ENTR, MM_IKANA_CANYON, "globa", "", "", GameLayout::all } },
	{ MM_WARP_OWL_STONE_TOWER_ENTR, { MM_WARP_OWL_STONE_TOWER_ENTR, MM_STONE_TOWER, "globa", "", "", GameLayout::all } },
	{ MM_WALLMASTER_DAMPE_ENTR, { MM_WALLMASTER_DAMPE_ENTR, MM_DAMPE_HOUSE, "globa", "", "", GameLayout::all } },
	{ MM_WALLMASTER_BTW_ENTRANCE_ENTR, { MM_WALLMASTER_BTW_ENTRANCE_ENTR, MM_BENEATH_THE_WELL, "globa", "", "", GameLayout::all } },
	{ MM_WALLMASTER_BTW_FOUNTAIN_ENTR, { MM_WALLMASTER_BTW_FOUNTAIN_ENTR, MM_BENEATH_THE_WELL, "globa", "", "", GameLayout::all } },
	{ MM_WALLMASTER_BTW_EXIT_ENTR, { MM_WALLMASTER_BTW_EXIT_ENTR, MM_BENEATH_THE_WELL, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_GENERIC_FIELD_PILLAR_ENTR, { MM_GROTTO_GENERIC_FIELD_PILLAR_ENTR, MM_GROTTO_TERMINA_PILLAR, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_GENERIC_GRASS_ENTR, { MM_GROTTO_GENERIC_GRASS_ENTR, MM_GROTTO_TERMINA_TALL_GRASS, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_GENERIC_PATH_SWAMP_ENTR, { MM_GROTTO_GENERIC_PATH_SWAMP_ENTR, MM_GROTTO_SOUTHERN_SWAMP_ROAD_OPEN, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_GENERIC_WOODS_ENTR, { MM_GROTTO_GENERIC_WOODS_ENTR, MM_GROTTO_WOODS_OF_MYSTERY_OPEN, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_GENERIC_SWAMP_ENTR, { MM_GROTTO_GENERIC_SWAMP_ENTR, MM_GROTTO_SOUTHERN_SWAMP_OPEN, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_GENERIC_MOUNTAIN_VILLAGE_ENTR, { MM_GROTTO_GENERIC_MOUNTAIN_VILLAGE_ENTR, MM_GROTTO_MOUNTAIN_VILLAGE_GENERIC, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_GENERIC_TWIN_ISLANDS_ENTR, { MM_GROTTO_GENERIC_TWIN_ISLANDS_ENTR, MM_GROTTO_TWIN_ISLANDS_RAMP, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_GENERIC_PATH_SNOWHEAD_ENTR, { MM_GROTTO_GENERIC_PATH_SNOWHEAD_ENTR, MM_GROTTO_PATH_TO_SNOWHEAD_GENERIC, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_GENERIC_GREAT_BAY_COAST_ENTR, { MM_GROTTO_GENERIC_GREAT_BAY_COAST_ENTR, MM_GROTTO_GREAT_BAY_COAST_FISHERMAN, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_GENERIC_ZORA_CAPE_ENTR, { MM_GROTTO_GENERIC_ZORA_CAPE_ENTR, MM_GROTTO_ZORA_CAPE_GENERIC, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_GENERIC_PATH_IKANA_ENTR, { MM_GROTTO_GENERIC_PATH_IKANA_ENTR, MM_GROTTO_IKANA_ROAD_GENERIC, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_GENERIC_GRAVEYARD_ENTR, { MM_GROTTO_GENERIC_GRAVEYARD_ENTR, MM_GROTTO_IKANA_GRAVEYARD_GENERIC, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_GENERIC_VALLEY_ENTR, { MM_GROTTO_GENERIC_VALLEY_ENTR, MM_GROTTO_IKANA_VALLEY_OPEN, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_COW_FIELD_ENTR, { MM_GROTTO_COW_FIELD_ENTR, MM_GROTTO_TERMINA_COW, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_COW_COAST_ENTR, { MM_GROTTO_COW_COAST_ENTR, MM_GROTTO_GREAT_BAY_COAST_COW, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_GOSSIPS_MOUNTAIN_ENTR, { MM_GROTTO_GOSSIPS_MOUNTAIN_ENTR, MM_GROTTO_TERMINA_MOUNTAIN_GOSSIP, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_GOSSIPS_CANYON_ENTR, { MM_GROTTO_GOSSIPS_CANYON_ENTR, MM_GROTTO_TERMINA_CANYON_GOSSIP, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_GOSSIPS_OCEAN_ENTR, { MM_GROTTO_GOSSIPS_OCEAN_ENTR, MM_GROTTO_TERMINA_OCEAN_GOSSIP, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_GOSSIPS_SWAMP_ENTR, { MM_GROTTO_GOSSIPS_SWAMP_ENTR, MM_GROTTO_TERMINA_SWAMP_GOSSIP, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_DODONGO_ENTR, { MM_GROTTO_DODONGO_ENTR, MM_GROTTO_TERMINA_DODONGO, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_SCRUB_ENTR, { MM_GROTTO_SCRUB_ENTR, MM_GROTTO_TERMINA_SCRUB, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_PEAHAT_ENTR, { MM_GROTTO_PEAHAT_ENTR, MM_GROTTO_TERMINA_PEAHAT, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_BIO_BABA_ENTR, { MM_GROTTO_BIO_BABA_ENTR, MM_GROTTO_TERMINA_BIO_BABA, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_HOT_WATER_ENTR, { MM_GROTTO_HOT_WATER_ENTR, MM_GROTTO_TWIN_ISLANDS_FROZEN, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_BEAN_ENTR, { MM_GROTTO_BEAN_ENTR, MM_GROTTO_DEKU_PALACE_BEANS, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_DEKU_PLAYGROUND_ENTR, { MM_GROTTO_DEKU_PLAYGROUND_ENTR, MM_DEKU_PLAYGROUND, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_JP_CLIMB_LEFT_ENTR, { MM_GROTTO_JP_CLIMB_LEFT_ENTR, MM_GROTTO_DEKU_PALACE_CLIMB, "globa", "", "", GameLayout::mm_jp } },
	{ MM_GROTTO_JP_CLIMB_RIGHT_ENTR, { MM_GROTTO_JP_CLIMB_RIGHT_ENTR, MM_GROTTO_DEKU_PALACE_CLIMB, "globa", "", "", GameLayout::mm_jp } },
	{ MM_GROTTO_JP_LINE_START_ENTR, { MM_GROTTO_JP_LINE_START_ENTR, MM_GROTTO_DEKU_PALACE_GENERIC, "globa", "", "", GameLayout::mm_jp } },
	{ MM_GROTTO_JP_LINE_END_ENTR, { MM_GROTTO_JP_LINE_END_ENTR, MM_GROTTO_DEKU_PALACE_GENERIC, "globa", "", "", GameLayout::mm_jp } },
	{ MM_GRAVE_NIGHT1_ENTR, { MM_GRAVE_NIGHT1_ENTR, MM_BENEATH_THE_GRAVEYARD_NIGHT1, "globa", "", "", GameLayout::all } },
	{ MM_GRAVE_NIGHT2_ENTR, { MM_GRAVE_NIGHT2_ENTR, MM_BENEATH_THE_GRAVEYARD_NIGHT2, "globa", "", "", GameLayout::all } },
	{ MM_GRAVE_NIGHT3_ENTR, { MM_GRAVE_NIGHT3_ENTR, MM_DAMPE_HOUSE, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GENERIC_FIELD_PILLAR, { MM_GROTTO_EXIT_GENERIC_FIELD_PILLAR, MM_TERMINA_FIELD, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GENERIC_GRASS, { MM_GROTTO_EXIT_GENERIC_GRASS, MM_TERMINA_FIELD, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GENERIC_PATH_SWAMP, { MM_GROTTO_EXIT_GENERIC_PATH_SWAMP, MM_ROAD_SOUTHERN_SWAMP, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GENERIC_WOODS, { MM_GROTTO_EXIT_GENERIC_WOODS, MM_LOST_WOODS, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GENERIC_SWAMP, { MM_GROTTO_EXIT_GENERIC_SWAMP, MM_SOUTHERN_SWAMP, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GENERIC_MOUNTAIN_VILLAGE, { MM_GROTTO_EXIT_GENERIC_MOUNTAIN_VILLAGE, MM_MOUNTAIN_VILLAGE, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GENERIC_TWIN_ISLANDS, { MM_GROTTO_EXIT_GENERIC_TWIN_ISLANDS, MM_TWIN_ISLANDS, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GENERIC_PATH_SNOWHEAD, { MM_GROTTO_EXIT_GENERIC_PATH_SNOWHEAD, MM_PATH_SNOWHEAD, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GENERIC_GREAT_BAY_COAST, { MM_GROTTO_EXIT_GENERIC_GREAT_BAY_COAST, MM_GREAT_BAY_COAST, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GENERIC_ZORA_CAPE, { MM_GROTTO_EXIT_GENERIC_ZORA_CAPE, MM_ZORA_CAPE, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GENERIC_PATH_IKANA, { MM_GROTTO_EXIT_GENERIC_PATH_IKANA, MM_ROAD_IKANA, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GENERIC_GRAVEYARD, { MM_GROTTO_EXIT_GENERIC_GRAVEYARD, MM_IKANA_GRAVEYARD, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GENERIC_VALLEY, { MM_GROTTO_EXIT_GENERIC_VALLEY, MM_IKANA_CANYON, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_COW_FIELD, { MM_GROTTO_EXIT_COW_FIELD, MM_TERMINA_FIELD, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_COW_COAST, { MM_GROTTO_EXIT_COW_COAST, MM_GREAT_BAY_COAST, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GOSSIPS_MOUNTAIN, { MM_GROTTO_EXIT_GOSSIPS_MOUNTAIN, MM_TERMINA_FIELD, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GOSSIPS_CANYON, { MM_GROTTO_EXIT_GOSSIPS_CANYON, MM_TERMINA_FIELD, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GOSSIPS_OCEAN, { MM_GROTTO_EXIT_GOSSIPS_OCEAN, MM_TERMINA_FIELD, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GOSSIPS_SWAMP, { MM_GROTTO_EXIT_GOSSIPS_SWAMP, MM_TERMINA_FIELD, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_DODONGO, { MM_GROTTO_EXIT_DODONGO, MM_TERMINA_FIELD, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_SCRUB, { MM_GROTTO_EXIT_SCRUB, MM_TERMINA_FIELD, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_PEAHAT, { MM_GROTTO_EXIT_PEAHAT, MM_TERMINA_FIELD, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_BIO_BABA, { MM_GROTTO_EXIT_BIO_BABA, MM_TERMINA_FIELD, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_HOT_WATER, { MM_GROTTO_EXIT_HOT_WATER, MM_TWIN_ISLANDS, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_BEAN, { MM_GROTTO_EXIT_BEAN, MM_DEKU_PALACE, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_DEKU_PLAYGROUND, { MM_GROTTO_EXIT_DEKU_PLAYGROUND, MM_CLOCK_TOWN_NORTH, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_JP_CLIMB_LEFT, { MM_GROTTO_EXIT_JP_CLIMB_LEFT, MM_DEKU_PALACE, "globa", "", "", GameLayout::mm_jp } },
	{ MM_GROTTO_EXIT_JP_CLIMB_RIGHT, { MM_GROTTO_EXIT_JP_CLIMB_RIGHT, MM_DEKU_PALACE, "globa", "", "", GameLayout::mm_jp } },
	{ MM_GROTTO_EXIT_JP_LINE_START, { MM_GROTTO_EXIT_JP_LINE_START, MM_DEKU_PALACE, "globa", "", "", GameLayout::mm_jp } },
	{ MM_GROTTO_EXIT_JP_LINE_END, { MM_GROTTO_EXIT_JP_LINE_END, MM_DEKU_PALACE, "globa", "", "", GameLayout::mm_jp } },
	{ MM_GRAVE_EXIT_NIGHT1, { MM_GRAVE_EXIT_NIGHT1, MM_IKANA_GRAVEYARD, "globa", "", "", GameLayout::all } },
	{ MM_GRAVE_EXIT_NIGHT2, { MM_GRAVE_EXIT_NIGHT2, MM_IKANA_GRAVEYARD, "globa", "", "", GameLayout::all } },
	{ MM_GRAVE_EXIT_NIGHT3, { MM_GRAVE_EXIT_NIGHT3, MM_IKANA_GRAVEYARD, "globa", "", "", GameLayout::all } },
	{ MM_VOID_GREAT_BAY_ENTR, { MM_VOID_GREAT_BAY_ENTR, MM_GREAT_BAY_COAST, "globa", "", "", GameLayout::all } },
	{ MM_VOID_GREAT_BAY_BY_PINNACLE_ROCK_ENTR, { MM_VOID_GREAT_BAY_BY_PINNACLE_ROCK_ENTR, MM_GREAT_BAY_COAST, "globa", "", "", GameLayout::all } },
	{ MM_VOID_ZORA_CAPE_ENTR, { MM_VOID_ZORA_CAPE_ENTR, MM_ZORA_CAPE, "globa", "", "", GameLayout::all } },
	{ MM_VOID_PINNACLE_ROCK_ENTR, { MM_VOID_PINNACLE_ROCK_ENTR, MM_PINNACLE_ROCK, "globa", "", "", GameLayout::all } },
	{ MM_MOON_ENTR, { MM_MOON_ENTR, MM_MOON, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_FROM_SONG_OF_TIME_ENTR, { MM_CLOCK_TOWN_FROM_SONG_OF_TIME_ENTR, MM_CLOCK_TOWN_SOUTH, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWER_MOON_CRASH_ENTR, { MM_CLOCK_TOWER_MOON_CRASH_ENTR, MM_CLOCK_TOWER_ROOFTOP, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_FROM_CLOCK_TOWER_ENTR, { MM_CLOCK_TOWN_FROM_CLOCK_TOWER_ENTR, MM_CLOCK_TOWN_SOUTH, "globa", "", "", GameLayout::all } },
	{ MM_CLOCK_TOWER_FROM_CLOCK_TOWN_ENTR, { MM_CLOCK_TOWER_FROM_CLOCK_TOWN_ENTR, MM_CLOCK_TOWER_ROOFTOP, "globa", "", "", GameLayout::all } },
	{ MM_COAST_FROM_MIKAU_CS_ENTR, { MM_COAST_FROM_MIKAU_CS_ENTR, MM_GREAT_BAY_COAST, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_TYPE_GENERIC_ENTR, { MM_GROTTO_TYPE_GENERIC_ENTR, MM_GROTTOS, "globa", "", "", GameLayout::all } },
	{ MM_GROTTO_TYPE_COW_ENTR, { MM_GROTTO_TYPE_COW_ENTR, MM_GROTTOS, "globa", "", "", GameLayout::all } },
	{ MM_IKANA_GRAVEYARD_FROM_DAMPE_ENTR, { MM_IKANA_GRAVEYARD_FROM_DAMPE_ENTR, MM_IKANA_GRAVEYARD, "globa", "", "", GameLayout::all } },
	{ MM_MILK_ROAD_FROM_RANCH2_ENTR, { MM_MILK_ROAD_FROM_RANCH2_ENTR, MM_MILK_ROAD, "globa", "", "", GameLayout::all } },
	{ MM_MILK_ROAD_FROM_GORMAN_TRACK2_ENTR, { MM_MILK_ROAD_FROM_GORMAN_TRACK2_ENTR, MM_MILK_ROAD, "globa", "", "", GameLayout::all } },
	{ MM_GORMAN_TRACK_UNK2_ENTR, { MM_GORMAN_TRACK_UNK2_ENTR, MM_GORMAN_TRACK, "globa", "", "", GameLayout::all } },
	{ MM_GORMAN_TRACK_UNK3_ENTR, { MM_GORMAN_TRACK_UNK3_ENTR, MM_GORMAN_TRACK, "globa", "", "", GameLayout::all } },
	{ MM_GORMAN_TRACK_UNK5_ENTR, { MM_GORMAN_TRACK_UNK5_ENTR, MM_GORMAN_TRACK, "globa", "", "", GameLayout::all } },
	{ MM_GORMAN_TRACK_UNK6_ENTR, { MM_GORMAN_TRACK_UNK6_ENTR, MM_GORMAN_TRACK, "globa", "", "", GameLayout::all } },
	{ MM_GORON_RACETRACK_ALT_ENTR, { MM_GORON_RACETRACK_ALT_ENTR, MM_GORON_RACETRACK, "globa", "", "", GameLayout::all } },
	{ MM_INTERNAL_EXIT_GROTTO_ENTR, { MM_INTERNAL_EXIT_GROTTO_ENTR, MM_GROTTOS, "globa", "", "", GameLayout::all } },
	{ MM_LOST_WOODS_ENTR, { MM_LOST_WOODS_ENTR, MM_LOST_WOODS, "globa", "", "", GameLayout::all } },
	{ SPAWN_LOADING, { SPAWN_LOADING, 0, "Spawn Loading", "", "", GameLayout::all } }
};