#pragma once

#include "Entrances.h"
#include "Scenes.h"

#pragma region Defines

#define MM_BOSS_TEMPLE_WOODFALL  0x3800
#define MM_BOSS_TEMPLE_SNOWHEAD  0x8200
#define MM_BOSS_TEMPLE_GREAT_BAY  0xb800
#define MM_BOSS_TEMPLE_STONE_TOWER  0x6600
#define MM_TEMPLE_WOODFALL  0x3000
#define MM_TEMPLE_SNOWHEAD  0x3c00
#define MM_TEMPLE_GREAT_BAY  0x8c00
#define MM_TEMPLE_STONE_TOWER_INVERTED  0x2a00
#define MM_TEMPLE_STONE_TOWER  0x2600
#define MM_SPIDER_HOUSE_SWAMP  0x4800
#define MM_SPIDER_HOUSE_OCEAN  0x4a00
#define MM_BENEATH_THE_WELL  0x9000
#define MM_BENEATH_THE_WELL_BACK  0x9010
#define MM_IKANA_CASTLE  0x3430
#define MM_SECRET_SHRINE  0xba00
#define MM_PIRATE_FORTRESS  0x7000
#define MM_CLOCK_TOWER_ROOF  0x2c00
#define MM_WOODFALL_FROM_TEMPLE  0x8610
#define MM_SNOWHEAD_FROM_TEMPLE  0xb210
#define MM_GREAT_BAY_FROM_TEMPLE  0x6a70
#define MM_STONE_TOWER_INVERTED_FROM_TEMPLE  0xac10
#define MM_STONE_TOWER_FROM_TEMPLE  0xaa20
#define MM_SWAMP_FROM_SPIDER_HOUSE  0x8480
#define MM_GREAT_BAY_FROM_SPIDER_HOUSE  0x6880
#define MM_IKANA_CANYON_FROM_WELL  0x2050
#define MM_IKANA_CASTLE_EXTERIOR_FROM_WELL  0x3400
#define MM_IKANA_CASTLE_EXTERIOR_FROM_CASTLE  0x3420
#define MM_IKANA_VALLEY_FROM_SHRINE  0x20c0
#define MM_GREAT_BAY_FROM_PIRATE_FORTRESS  0x6850
#define MM_CLOCK_TOWN_FROM_CLOCK_TOWER_ROOF  0xd880
#define MM_SWAMP_FROM_ROAD  0x8400
#define MM_MOUNTAIN_VILLAGE_FROM_PATH  0x9a60
#define MM_GREAT_BAY_COAST_FROM_FIELD  0x6800
#define MM_IKANA_VALLEY_FROM_ROAD  0x2000
#define MM_ROMANI_RANCH_FROM_MILK_ROAD  0x6400
#define MM_SWAMP_ROAD_FROM_SWAMP  0x7a10
#define MM_PATH_FROM_MOUNTAIN_VILLAGE  0x3210
#define MM_TERMINA_FIELD_FROM_GREAT_BAY_COAST  0x5420
#define MM_IKANA_ROAD_FROM_VALLEY  0xa010
#define MM_MILK_ROAD_FROM_ROMANI_RANCH  0x3e10
#define MM_CLOCK_TOWN_WEST_FROM_SOUTH_BOTTOM  0xd410
#define MM_CLOCK_TOWN_SOUTH_BOTTOM_FROM_WEST  0xd850
#define MM_CLOCK_TOWN_EAST_FROM_SOUTH_BOTTOM  0xd210
#define MM_CLOCK_TOWN_SOUTH_BOTTOM_FROM_EAST  0xd870
#define MM_CLOCK_TOWN_NORTH_FROM_EAST  0xd610
#define MM_CLOCK_TOWN_EAST_FROM_NORTH  0xd250
#define MM_CLOCK_TOWN_NORTH_FROM_SOUTH  0xd620
#define MM_CLOCK_TOWN_SOUTH_FROM_NORTH  0xd840
#define MM_CLOCK_TOWN_EAST_FROM_SOUTH_TOP  0xd230
#define MM_CLOCK_TOWN_SOUTH_TOP_FROM_EAST  0xd820
#define MM_CLOCK_TOWN_WEST_FROM_SOUTH_TOP  0xd420
#define MM_CLOCK_TOWN_SOUTH_TOP_FROM_WEST  0xd830
#define MM_CLOCK_TOWN_WEST_FROM_FIELD  0xd400
#define MM_CLOCK_TOWN_SOUTH_FROM_FIELD  0xd810
#define MM_CLOCK_TOWN_EAST_FROM_FIELD  0xd200
#define MM_CLOCK_TOWN_NORTH_FROM_FIELD  0xd600
#define MM_CLOCK_TOWN_SOUTH_FROM_LAUNDRY_POOL  0xd860
#define MM_LAUNDRY_POOL  0xda00
#define MM_TERMINA_FIELD_FROM_CLOCK_TOWN_WEST  0x5400
#define MM_TERMINA_FIELD_FROM_CLOCK_TOWN_SOUTH  0x5460
#define MM_TERMINA_FIELD_FROM_CLOCK_TOWN_EAST  0x5470
#define MM_TERMINA_FIELD_FROM_CLOCK_TOWN_NORTH  0x5480
#define MM_IKANA_ROAD_FROM_FIELD  0xa000
#define MM_TERMINA_FIELD_FROM_ROAD_TO_IKANA  0x5440
#define MM_MOUNTAIN_VILLAGE_PATH_FROM_TERMINA_FIELD  0x3200
#define MM_TERMINA_FIELD_FROM_PATH_TO_MOUNTAIN_VILLAGE  0x5430
#define MM_SWAMP_ROAD_FROM_FIELD  0x7a00
#define MM_TERMINA_FIELD_FROM_ROAD_TO_SWAMP  0x5410
#define MM_MILK_ROAD_FROM_FIELD  0x3e00
#define MM_TERMINA_FIELD_FROM_MILK_ROAD  0x5450
#define MM_GORMAN_TRACK_FROM_MILK_ROAD  0xce00
#define MM_MILK_ROAD_FROM_GORMAN_TRACK  0x3e30
#define MM_GORMAN_BACK_FROM_MILK_ROAD  0xce30
#define MM_MILK_ROAD_FROM_GORMAN_BACK  0x3e20
#define MM_SNOWHEAD_PATH_FROM_MOUNTAIN_VILLAGE  0xb000
#define MM_MOUNTAIN_VILLAGE_FROM_SNOWHEAD_PATH  0x9a40
#define MM_SNOWHEAD_FROM_SNOWHEAD_PATH  0xb200
#define MM_PATH_SNOWHEAD_FROM_SNOWHEAD  0xb010
#define MM_IKANA_GRAVEYARD  0x8000
#define MM_IKANA_ROAD_FROM_IKANA_GRAVEYARD  0xa020
#define MM_ZORA_CAPE_FROM_GREAT_BAY_COAST  0x6a00
#define MM_GREAT_BAY_COAST_FROM_ZORA_CAPE  0x6810
#define MM_PINNACLE_ROCK  0x4400
#define MM_GREAT_BAY_FROM_PINNACLE_ROCK  0x6830
#define MM_ZORA_CAPE_FROM_HALL_WATER  0x6a10
#define MM_ZORA_HALL_UNDERWATER  0x6000
#define MM_ZORA_CAPE_PENINSULA  0x6a20
#define MM_ZORA_HALL_LEDGE  0x6010
#define MM_DEKU_PALACE_MAIN_ENTRANCE  0x5000
#define MM_SWAMP_FROM_PALACE_MAIN_ENTRANCE  0x8430
#define MM_DEKU_PALACE_LEDGE  0x5050
#define MM_SWAMP_FROM_PALACE_LEDGE  0x8440
#define MM_WOODFALL  0x8600
#define MM_SWAMP_FROM_WOODFALL  0x8420
#define MM_MYSTERY_WOODS  0xc200
#define MM_SWAMP_FROM_MYSTERY_WOODS  0x8470
#define MM_SEWERS_FROM_EXTERIOR_GATE  0x4090
#define MM_EXTERIOR_GATE_FROM_SEWERS  0x7020
#define MM_PIRATE_FORTRESS_INTERIOR  0x2200
#define MM_PIRATE_FORTRESS_EXTERIOR_FROM_INTERIOR  0x7010
#define MM_PIRATE_FORTRESS_INTERIOR_FROM_LOOKOUT  0x22c0
#define MM_PIRATE_FORTRESS_EXTERIOR_LOOKOUT  0x7050
#define MM_IKANA_CASTLE_GARDENS  0x3410
#define MM_IKANA_CANYON_FROM_CASTLE_GARDENS  0x2080
#define MM_STONE_TOWER  0xaa00
#define MM_IKANA_CANYON_FROM_STONE_TOWER  0x2030
#define MM_TWIN_ISLANDS_FROM_MOUNTAIN_VILLAGE  0xb400
#define MM_MOUNTAIN_VILLAGE_FROM_TWIN_ISLANDS  0x9a20
#define MM_TWIN_ISLANDS_FROM_GORON_VILLAGE  0xb410
#define MM_GORON_VILLAGE_FROM_TWIN_ISLANDS  0x9400
#define MM_SWAMP_FROM_IKANA_CANYON  0x8490
#define MM_IKANA_CASTLE_INTERIOR_KEG  0x3440
#define MM_IKANA_CASTLE_INTERIOR_BLOCK  0x3450
#define MM_CHEST_GAME  0x2800
#define MM_HONEY_AND_DARLING_GAME  0x0800
#define MM_MAYORS_OFFICE  0x0000
#define MM_TOWN_ARCHERY  0x3a00
#define MM_MILK_BAR  0x2400
#define MM_FAIRY_FOUNTAIN_TOWN  0x4600
#define MM_SWORDSMAN_SCHOOL  0xa200
#define MM_CURIOSITY_SHOP  0x0e00
#define MM_TRADING_POST  0x6200
#define MM_BOMB_SHOP  0xca00
#define MM_POST_OFFICE  0x5600
#define MM_LOTTERY  0x6c00
#define MM_KAFEI_HIDEOUT  0x0e10
#define MM_POTION_SHOP  0x0400
#define MM_DEKU_SHRINE  0x9e00
#define MM_GORON_SHOP  0x7400
#define MM_FISHER_HUT  0x7200
#define MM_LABORATORY  0x5800
#define MM_ROOM_EVANS  0x9230
#define MM_ROOM_JAPAS  0x9210
#define MM_ROOM_TIJO  0x9200
#define MM_ROOM_LULU  0x9220
#define MM_ZORA_SHOP  0x9250
#define MM_GHOST_HUT  0x9c00
#define MM_MUSIC_BOX_HOUSE  0xa400
#define MM_FAIRY_FOUNTAIN_IKANA  0x4640
#define MM_IKANA_CAVERN  0x20e0
#define MM_FAIRY_FOUNTAIN_GREAT_BAY  0x4630
#define MM_FAIRY_FOUNTAIN_SNOWHEAD  0x4620
#define MM_FAIRY_FOUNTAIN_WOODFALL  0x4610
#define MM_GORON_GRAVEYARD  0x9600
#define MM_BLACKSMITH  0x5200
#define MM_SWAMP_ARCHERY  0x4200
#define MM_GORON_RACETRACK  0xd000
#define MM_BEAVERS  0x8e00
#define MM_CUCCO_SHACK  0x7e00
#define MM_DOGGY_RACETRACK  0x7c00
#define MM_STABLES  0x0600
#define MM_RANCH_HOUSE  0x0610
#define MM_GORON_SHRINE  0x5e00
#define MM_DEKU_PALACE_THRONE  0x7600
#define MM_DEKU_PALACE_THRONE_CAGE  0x7610
#define MM_LONE_PEAK_SHRINE  0x1500
#define MM_STOCK_POT_INN  0xbc00
#define MM_STOCK_POT_INN_ROOF  0xbc10
#define MM_SEWERS_FROM_EXTERIOR_DOOR  0x40a0
#define MM_TOURIST_INFORMATION  0xa800
#define MM_ASTRAL_OBSERVATORY_FROM_CLOCK_TOWN_EAST  0x4c00
#define MM_ASTRAL_OBSERVATORY_FROM_FIELD  0x4c10
#define MM_CLOCK_TOWN_EAST_FROM_CHEST_GAME  0xd240
#define MM_CLOCK_TOWN_EAST_FROM_HONEY_AND_DARLING  0xd260
#define MM_CLOCK_TOWN_EAST_FROM_MAYORS_OFFICE  0xd270
#define MM_CLOCK_TOWN_EAST_FROM_TOWN_ARCHERY  0xd280
#define MM_CLOCK_TOWN_EAST_FROM_STOCK_POT_INN  0xd290
#define MM_CLOCK_TOWN_EAST_FROM_STOCK_POT_INN_ROOF  0xd2a0
#define MM_CLOCK_TOWN_EAST_FROM_MILK_BAR  0xd2b0
#define MM_CLOCK_TOWN_NORTH_FROM_FAIRY_FOUNTAIN  0xd630
#define MM_CLOCK_TOWN_WEST_FROM_SWORDSMAN_SCHOOL  0xd430
#define MM_CLOCK_TOWN_WEST_FROM_CURIOSITY_SHOP  0xd440
#define MM_CLOCK_TOWN_WEST_FROM_TRADING_POST  0xd450
#define MM_CLOCK_TOWN_WEST_FROM_BOMB_SHOP  0xd460
#define MM_CLOCK_TOWN_WEST_FROM_POST_OFFICE  0xd470
#define MM_CLOCK_TOWN_WEST_FROM_LOTTERY  0xd480
#define MM_LAUNDRY_POOL_FROM_KAFEI_HIDEOUT  0xda10
#define MM_SWAMP_FROM_POTION_SHOP  0x8450
#define MM_DEKU_PALACE_EXTERIOR_FROM_SHRINE  0x5040
#define MM_GORON_SHRINE_FROM_SHOP  0x5e10
#define MM_GREAT_BAY_COAST_FROM_FISHER_HUT  0x6840
#define MM_GREAT_BAY_COAST_FROM_LABORATORY  0x6870
#define MM_ZORA_HALL_FROM_EVANS  0x6040
#define MM_ZORA_HALL_FROM_JAPAS  0x6050
#define MM_ZORA_HALL_FROM_TIJO  0x6060
#define MM_ZORA_HALL_FROM_LULU  0x6030
#define MM_ZORA_HALL_FROM_SHOP  0x6020
#define MM_IKANA_CANYON_FROM_GHOST_HUT  0x2010
#define MM_IKANA_CANYON_FROM_MUSIC_BOX_HOUSE  0x2020
#define MM_IKANA_CANYON_FROM_FAIRY_FOUNTAIN  0x20b0
#define MM_IKANA_CANYON_FROM_CAVERN  0x20d0
#define MM_EXTERIOR_DOOR_FROM_SEWERS  0x7060
#define MM_GREAT_BAY_FROM_FAIRY_FOUNTAIN  0x6a50
#define MM_SNOWHEAD_FROM_FAIRY_FOUNTAIN  0xb220
#define MM_SWAMP_FROM_TOURIST_INFORMATION  0x8410
#define MM_WOODFALL_FROM_FAIRY_FOUNTAIN  0x8620
#define MM_MOUNTAIN_VILLAGE_FROM_GORON_GRAVEYARD  0x9a30
#define MM_MOUNTAIN_VILLAGE_FROM_BLACKSMITH  0x9a10
#define MM_ROMANI_RANCH_FROM_CUCCO_SHACK  0x6440
#define MM_ROMANI_RANCH_FROM_DOGGY_RACETRACK  0x6450
#define MM_ROMANI_RANCH_FROM_STABLES  0x6420
#define MM_ROMANI_RANCH_FROM_RANCH_HOUSE  0x6430
#define MM_CLOCK_TOWN_EAST_FROM_ASTRAL_OBSERVATORY  0xd220
#define MM_FIELD_FROM_ASTRAL_OBSERVATORY  0x5490
#define MM_SWAMP_ROAD_FROM_ARCHERY  0x7a20
#define MM_TWIN_ISLANDS_FROM_GORON_RACETRACK  0xb420
#define MM_ZORA_CAPE_FROM_BEAVERS  0x6a40
#define MM_GORON_VILLAGE_FROM_GORON_SHRINE  0x9420
#define MM_GORON_VILLAGE_FROM_LONE_PEAK_SHRINE  0x9430
#define MM_DEKU_PALACE_EXTERIOR_FROM_THRONE  0x5020
#define MM_DEKU_PALACE_EXTERIOR_FROM_THRONE_CAGE  0x5030
#define MM_SAKON_HIDEOUT  0x9800
#define MM_IKANA_CANYON_FROM_SAKON_HIDEOUT  0x2060
#define MM_WARP_OWL_GREAT_BAY  0x68b0
#define MM_WARP_OWL_ZORA_CAPE  0x6a60
#define MM_WARP_OWL_SNOWHEAD  0xb230
#define MM_WARP_OWL_MOUNTAIN_VILLAGE  0x9a80
#define MM_WARP_OWL_CLOCK_TOWN  0xd890
#define MM_WARP_OWL_MILK_ROAD  0x3e40
#define MM_WARP_OWL_WOODFALL  0x8640
#define MM_WARP_OWL_SOUTHERN_SWAMP  0x84a0
#define MM_WARP_OWL_IKANA_CANYON  0x2040
#define MM_WARP_OWL_STONE_TOWER  0xaa30
#define MM_WALLMASTER_DAMPE  0xff00
#define MM_WALLMASTER_BTW_ENTRANCE  0xff01
#define MM_WALLMASTER_BTW_FOUNTAIN  0xff02
#define MM_WALLMASTER_BTW_EXIT  0xff03
#define MM_GROTTO_GENERIC_FIELD_PILLAR  0x10000
#define MM_GROTTO_GENERIC_GRASS  0x10001
#define MM_GROTTO_GENERIC_PATH_SWAMP  0x10002
#define MM_GROTTO_GENERIC_WOODS  0x10003
#define MM_GROTTO_GENERIC_SWAMP  0x10004
#define MM_GROTTO_GENERIC_MOUNTAIN_VILLAGE  0x10005
#define MM_GROTTO_GENERIC_TWIN_ISLANDS  0x10006
#define MM_GROTTO_GENERIC_PATH_SNOWHEAD  0x10007
#define MM_GROTTO_GENERIC_GREAT_BAY_COAST  0x10008
#define MM_GROTTO_GENERIC_ZORA_CAPE  0x10009
#define MM_GROTTO_GENERIC_PATH_IKANA  0x1000a
#define MM_GROTTO_GENERIC_GRAVEYARD  0x1000b
#define MM_GROTTO_GENERIC_VALLEY  0x1000c
#define MM_GROTTO_COW_FIELD  0x1000d
#define MM_GROTTO_COW_COAST  0x1000e
#define MM_GROTTO_GOSSIPS_MOUNTAIN  0x1430
#define MM_GROTTO_GOSSIPS_CANYON  0x1420
#define MM_GROTTO_GOSSIPS_OCEAN  0x1400
#define MM_GROTTO_GOSSIPS_SWAMP  0x1410
#define MM_GROTTO_DODONGO  0x1470
#define MM_GROTTO_SCRUB  0x1490
#define MM_GROTTO_PEAHAT  0x14d0
#define MM_GROTTO_BIO_BABA  0x14b0
#define MM_GROTTO_HOT_WATER  0x1450
#define MM_GROTTO_BEAN  0x14c0
#define MM_GROTTO_DEKU_PLAYGROUND  0x3600
#define MM_GROTTO_JP_CLIMB_LEFT  0x14f0
#define MM_GROTTO_JP_CLIMB_RIGHT  0x1480
#define MM_GROTTO_JP_LINE_START  0x14e0
#define MM_GROTTO_JP_LINE_END  0x1460
#define MM_GRAVE_NIGHT1  0x0a10
#define MM_GRAVE_NIGHT2  0x0a00
#define MM_GRAVE_NIGHT3  0x5a00
#define MM_GROTTO_EXIT_GENERIC_FIELD_PILLAR  0x10100
#define MM_GROTTO_EXIT_GENERIC_GRASS  0x10101
#define MM_GROTTO_EXIT_GENERIC_PATH_SWAMP  0x10102
#define MM_GROTTO_EXIT_GENERIC_WOODS  0x10103
#define MM_GROTTO_EXIT_GENERIC_SWAMP  0x10104
#define MM_GROTTO_EXIT_GENERIC_MOUNTAIN_VILLAGE  0x10105
#define MM_GROTTO_EXIT_GENERIC_TWIN_ISLANDS  0x10106
#define MM_GROTTO_EXIT_GENERIC_PATH_SNOWHEAD  0x10107
#define MM_GROTTO_EXIT_GENERIC_GREAT_BAY_COAST  0x10108
#define MM_GROTTO_EXIT_GENERIC_ZORA_CAPE  0x10109
#define MM_GROTTO_EXIT_GENERIC_PATH_IKANA  0x1010a
#define MM_GROTTO_EXIT_GENERIC_GRAVEYARD  0x1010b
#define MM_GROTTO_EXIT_GENERIC_VALLEY  0x1010c
#define MM_GROTTO_EXIT_COW_FIELD  0x1010d
#define MM_GROTTO_EXIT_COW_COAST  0x1010e
#define MM_GROTTO_EXIT_GOSSIPS_MOUNTAIN  0x1010f
#define MM_GROTTO_EXIT_GOSSIPS_CANYON  0x10110
#define MM_GROTTO_EXIT_GOSSIPS_OCEAN  0x10111
#define MM_GROTTO_EXIT_GOSSIPS_SWAMP  0x10112
#define MM_GROTTO_EXIT_DODONGO  0x10113
#define MM_GROTTO_EXIT_SCRUB  0x10114
#define MM_GROTTO_EXIT_PEAHAT  0x10115
#define MM_GROTTO_EXIT_BIO_BABA  0x10116
#define MM_GROTTO_EXIT_HOT_WATER  0x10117
#define MM_GROTTO_EXIT_BEAN  0x5090
#define MM_GROTTO_EXIT_DEKU_PLAYGROUND  0xd640
#define MM_GROTTO_EXIT_JP_CLIMB_LEFT  0x5060
#define MM_GROTTO_EXIT_JP_CLIMB_RIGHT  0x50a0
#define MM_GROTTO_EXIT_JP_LINE_START  0x5070
#define MM_GROTTO_EXIT_JP_LINE_END  0x5080
#define MM_GRAVE_EXIT_NIGHT1  0x8030
#define MM_GRAVE_EXIT_NIGHT2  0x8020
#define MM_GRAVE_EXIT_NIGHT3  0x8010
#define MM_VOID_GREAT_BAY  0x6820
#define MM_VOID_GREAT_BAY_BY_PINNACLE_ROCK  0x6860
#define MM_VOID_ZORA_CAPE  0x6a30
#define MM_VOID_PINNACLE_ROCK  0x4410
#define MM_MOON  0xc800
#define MM_CLOCK_TOWN_FROM_SONG_OF_TIME  0x1c00
#define MM_CLOCK_TOWER_MOON_CRASH  0xc030
#define MM_CLOCK_TOWN_FROM_CLOCK_TOWER  0xd800
#define MM_CLOCK_TOWER_FROM_CLOCK_TOWN  0xc010
#define MM_COAST_FROM_MIKAU_CS  0x68a0
#define MM_GROTTO_TYPE_GENERIC  0x1440
#define MM_GROTTO_TYPE_COW  0x14a0
#define MM_IKANA_GRAVEYARD_FROM_DAMPE  0x8040
#define MM_MILK_ROAD_FROM_RANCH2  0x3e50
#define MM_MILK_ROAD_FROM_GORMAN_TRACK2  0x3e60
#define MM_GORMAN_TRACK_UNK2  0xce10
#define MM_GORMAN_TRACK_UNK3  0xce20
#define MM_GORMAN_TRACK_UNK5  0xce40
#define MM_GORMAN_TRACK_UNK6  0xce50
#define MM_GORON_RACETRACK_ALT  0xd010
#define MM_INTERNAL_EXIT_GROTTO  0xffff
#define MM_LOST_WOODS  0xc400

#pragma endregion

const std::map<int, EntranceMetaInfo> MMEntrances =
{
	{ MM_BOSS_TEMPLE_WOODFALL, { MM_BOSS_TEMPLE_WOODFALL, MM_TEMPLE_WOODFALL, "globa", "", GameLayout::all } },
	{ MM_BOSS_TEMPLE_SNOWHEAD, { MM_BOSS_TEMPLE_SNOWHEAD, MM_TEMPLE_SNOWHEAD, "globa", "", GameLayout::all } },
	{ MM_BOSS_TEMPLE_GREAT_BAY, { MM_BOSS_TEMPLE_GREAT_BAY, MM_TEMPLE_GREAT_BAY, "globa", "", GameLayout::all } },
	{ MM_BOSS_TEMPLE_STONE_TOWER, { MM_BOSS_TEMPLE_STONE_TOWER, MM_TEMPLE_STONE_TOWER_INVERTED, "globa", "", GameLayout::all } },
	{ MM_TEMPLE_WOODFALL, { MM_TEMPLE_WOODFALL, MM_TEMPLE_WOODFALL, "globa", "", GameLayout::all } },
	{ MM_TEMPLE_SNOWHEAD, { MM_TEMPLE_SNOWHEAD, MM_TEMPLE_SNOWHEAD, "globa", "", GameLayout::all } },
	{ MM_TEMPLE_GREAT_BAY, { MM_TEMPLE_GREAT_BAY, MM_TEMPLE_GREAT_BAY, "globa", "", GameLayout::all } },
	{ MM_TEMPLE_STONE_TOWER_INVERTED, { MM_TEMPLE_STONE_TOWER_INVERTED, MM_TEMPLE_STONE_TOWER_INVERTED, "globa", "", GameLayout::all } },
	{ MM_TEMPLE_STONE_TOWER, { MM_TEMPLE_STONE_TOWER, MM_TEMPLE_STONE_TOWER, "globa", "", GameLayout::all } },
	{ MM_SPIDER_HOUSE_SWAMP, { MM_SPIDER_HOUSE_SWAMP, MM_SPIDER_HOUSE_SWAMP, "globa", "", GameLayout::all } },
	{ MM_SPIDER_HOUSE_OCEAN, { MM_SPIDER_HOUSE_OCEAN, MM_SPIDER_HOUSE_OCEAN, "globa", "", GameLayout::all } },
	{ MM_BENEATH_THE_WELL, { MM_BENEATH_THE_WELL, MM_BENEATH_THE_WELL, "globa", "", GameLayout::all } },
	{ MM_BENEATH_THE_WELL_BACK, { MM_BENEATH_THE_WELL_BACK, MM_BENEATH_THE_WELL, "globa", "", GameLayout::all } },
	{ MM_IKANA_CASTLE, { MM_IKANA_CASTLE, MM_CASTLE_IKANA, "globa", "", GameLayout::all } },
	{ MM_SECRET_SHRINE, { MM_SECRET_SHRINE, MM_SECRET_SHRINE, "globa", "", GameLayout::all } },
	{ MM_PIRATE_FORTRESS, { MM_PIRATE_FORTRESS, MM_PIRATE_FORTRESS_EXTERIOR, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWER_ROOF, { MM_CLOCK_TOWER_ROOF, MM_CLOCK_TOWER_ROOFTOP, "globa", "", GameLayout::all } },
	{ MM_WOODFALL_FROM_TEMPLE, { MM_WOODFALL_FROM_TEMPLE, MM_WOODFALL, "globa", "", GameLayout::all } },
	{ MM_SNOWHEAD_FROM_TEMPLE, { MM_SNOWHEAD_FROM_TEMPLE, MM_SNOWHEAD, "globa", "", GameLayout::all } },
	{ MM_GREAT_BAY_FROM_TEMPLE, { MM_GREAT_BAY_FROM_TEMPLE, MM_GREAT_BAY_COAST, "globa", "", GameLayout::all } },
	{ MM_STONE_TOWER_INVERTED_FROM_TEMPLE, { MM_STONE_TOWER_INVERTED_FROM_TEMPLE, MM_STONE_TOWER_INVERTED, "globa", "", GameLayout::all } },
	{ MM_STONE_TOWER_FROM_TEMPLE, { MM_STONE_TOWER_FROM_TEMPLE, MM_STONE_TOWER, "globa", "", GameLayout::all } },
	{ MM_SWAMP_FROM_SPIDER_HOUSE, { MM_SWAMP_FROM_SPIDER_HOUSE, MM_SOUTHERN_SWAMP, "globa", "", GameLayout::all } },
	{ MM_GREAT_BAY_FROM_SPIDER_HOUSE, { MM_GREAT_BAY_FROM_SPIDER_HOUSE, MM_GREAT_BAY_COAST, "globa", "", GameLayout::all } },
	{ MM_IKANA_CANYON_FROM_WELL, { MM_IKANA_CANYON_FROM_WELL, MM_IKANA_CANYON, "globa", "", GameLayout::all } },
	{ MM_IKANA_CASTLE_EXTERIOR_FROM_WELL, { MM_IKANA_CASTLE_EXTERIOR_FROM_WELL, MM_CASTLE_IKANA, "globa", "", GameLayout::all } },
	{ MM_IKANA_CASTLE_EXTERIOR_FROM_CASTLE, { MM_IKANA_CASTLE_EXTERIOR_FROM_CASTLE, MM_CASTLE_IKANA, "globa", "", GameLayout::all } },
	{ MM_IKANA_VALLEY_FROM_SHRINE, { MM_IKANA_VALLEY_FROM_SHRINE, MM_IKANA_CANYON, "globa", "", GameLayout::all } },
	{ MM_GREAT_BAY_FROM_PIRATE_FORTRESS, { MM_GREAT_BAY_FROM_PIRATE_FORTRESS, MM_GREAT_BAY_COAST, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_FROM_CLOCK_TOWER_ROOF, { MM_CLOCK_TOWN_FROM_CLOCK_TOWER_ROOF, MM_CLOCK_TOWN_SOUTH, "globa", "", GameLayout::all } },
	{ MM_SWAMP_FROM_ROAD, { MM_SWAMP_FROM_ROAD, MM_SOUTHERN_SWAMP, "globa", "", GameLayout::all } },
	{ MM_MOUNTAIN_VILLAGE_FROM_PATH, { MM_MOUNTAIN_VILLAGE_FROM_PATH, MM_MOUNTAIN_VILLAGE, "globa", "", GameLayout::all } },
	{ MM_GREAT_BAY_COAST_FROM_FIELD, { MM_GREAT_BAY_COAST_FROM_FIELD, MM_GREAT_BAY_COAST, "globa", "", GameLayout::all } },
	{ MM_IKANA_VALLEY_FROM_ROAD, { MM_IKANA_VALLEY_FROM_ROAD, MM_IKANA_CANYON, "globa", "", GameLayout::all } },
	{ MM_ROMANI_RANCH_FROM_MILK_ROAD, { MM_ROMANI_RANCH_FROM_MILK_ROAD, MM_ROMANI_RANCH, "globa", "", GameLayout::all } },
	{ MM_SWAMP_ROAD_FROM_SWAMP, { MM_SWAMP_ROAD_FROM_SWAMP, MM_SOUTHERN_SWAMP, "globa", "", GameLayout::all } },
	{ MM_PATH_FROM_MOUNTAIN_VILLAGE, { MM_PATH_FROM_MOUNTAIN_VILLAGE, MM_PATH_MOUNTAIN_VILLAGE, "globa", "", GameLayout::all } },
	{ MM_TERMINA_FIELD_FROM_GREAT_BAY_COAST, { MM_TERMINA_FIELD_FROM_GREAT_BAY_COAST, MM_TERMINA_FIELD, "globa", "", GameLayout::all } },
	{ MM_IKANA_ROAD_FROM_VALLEY, { MM_IKANA_ROAD_FROM_VALLEY, MM_ROAD_IKANA, "globa", "", GameLayout::all } },
	{ MM_MILK_ROAD_FROM_ROMANI_RANCH, { MM_MILK_ROAD_FROM_ROMANI_RANCH, MM_MILK_ROAD, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_WEST_FROM_SOUTH_BOTTOM, { MM_CLOCK_TOWN_WEST_FROM_SOUTH_BOTTOM, MM_CLOCK_TOWN_WEST, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_SOUTH_BOTTOM_FROM_WEST, { MM_CLOCK_TOWN_SOUTH_BOTTOM_FROM_WEST, MM_CLOCK_TOWN_SOUTH, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_EAST_FROM_SOUTH_BOTTOM, { MM_CLOCK_TOWN_EAST_FROM_SOUTH_BOTTOM, MM_CLOCK_TOWN_EAST, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_SOUTH_BOTTOM_FROM_EAST, { MM_CLOCK_TOWN_SOUTH_BOTTOM_FROM_EAST, MM_CLOCK_TOWN_SOUTH, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_NORTH_FROM_EAST, { MM_CLOCK_TOWN_NORTH_FROM_EAST, MM_CLOCK_TOWN_NORTH, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_EAST_FROM_NORTH, { MM_CLOCK_TOWN_EAST_FROM_NORTH, MM_CLOCK_TOWN_EAST, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_NORTH_FROM_SOUTH, { MM_CLOCK_TOWN_NORTH_FROM_SOUTH, MM_CLOCK_TOWN_NORTH, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_SOUTH_FROM_NORTH, { MM_CLOCK_TOWN_SOUTH_FROM_NORTH, MM_CLOCK_TOWN_SOUTH, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_EAST_FROM_SOUTH_TOP, { MM_CLOCK_TOWN_EAST_FROM_SOUTH_TOP, MM_CLOCK_TOWN_EAST, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_SOUTH_TOP_FROM_EAST, { MM_CLOCK_TOWN_SOUTH_TOP_FROM_EAST, MM_CLOCK_TOWN_SOUTH, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_WEST_FROM_SOUTH_TOP, { MM_CLOCK_TOWN_WEST_FROM_SOUTH_TOP, MM_CLOCK_TOWN_WEST, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_SOUTH_TOP_FROM_WEST, { MM_CLOCK_TOWN_SOUTH_TOP_FROM_WEST, MM_CLOCK_TOWN_SOUTH, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_WEST_FROM_FIELD, { MM_CLOCK_TOWN_WEST_FROM_FIELD, MM_CLOCK_TOWN_WEST, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_SOUTH_FROM_FIELD, { MM_CLOCK_TOWN_SOUTH_FROM_FIELD, MM_CLOCK_TOWN_SOUTH, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_EAST_FROM_FIELD, { MM_CLOCK_TOWN_EAST_FROM_FIELD, MM_CLOCK_TOWN_EAST, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_NORTH_FROM_FIELD, { MM_CLOCK_TOWN_NORTH_FROM_FIELD, MM_CLOCK_TOWN_NORTH, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_SOUTH_FROM_LAUNDRY_POOL, { MM_CLOCK_TOWN_SOUTH_FROM_LAUNDRY_POOL, MM_CLOCK_TOWN_SOUTH, "globa", "", GameLayout::all } },
	{ MM_LAUNDRY_POOL, { MM_LAUNDRY_POOL, MM_LAUNDRY_POOL, "globa", "", GameLayout::all } },
	{ MM_TERMINA_FIELD_FROM_CLOCK_TOWN_WEST, { MM_TERMINA_FIELD_FROM_CLOCK_TOWN_WEST, MM_TERMINA_FIELD, "globa", "", GameLayout::all } },
	{ MM_TERMINA_FIELD_FROM_CLOCK_TOWN_SOUTH, { MM_TERMINA_FIELD_FROM_CLOCK_TOWN_SOUTH, MM_TERMINA_FIELD, "globa", "", GameLayout::all } },
	{ MM_TERMINA_FIELD_FROM_CLOCK_TOWN_EAST, { MM_TERMINA_FIELD_FROM_CLOCK_TOWN_EAST, MM_TERMINA_FIELD, "globa", "", GameLayout::all } },
	{ MM_TERMINA_FIELD_FROM_CLOCK_TOWN_NORTH, { MM_TERMINA_FIELD_FROM_CLOCK_TOWN_NORTH, MM_TERMINA_FIELD, "globa", "", GameLayout::all } },
	{ MM_IKANA_ROAD_FROM_FIELD, { MM_IKANA_ROAD_FROM_FIELD, MM_ROAD_IKANA, "globa", "", GameLayout::all } },
	{ MM_TERMINA_FIELD_FROM_ROAD_TO_IKANA, { MM_TERMINA_FIELD_FROM_ROAD_TO_IKANA, MM_TERMINA_FIELD, "globa", "", GameLayout::all } },
	{ MM_MOUNTAIN_VILLAGE_PATH_FROM_TERMINA_FIELD, { MM_MOUNTAIN_VILLAGE_PATH_FROM_TERMINA_FIELD, MM_PATH_MOUNTAIN_VILLAGE, "globa", "", GameLayout::all } },
	{ MM_TERMINA_FIELD_FROM_PATH_TO_MOUNTAIN_VILLAGE, { MM_TERMINA_FIELD_FROM_PATH_TO_MOUNTAIN_VILLAGE, MM_TERMINA_FIELD, "globa", "", GameLayout::all } },
	{ MM_SWAMP_ROAD_FROM_FIELD, { MM_SWAMP_ROAD_FROM_FIELD, MM_ROAD_SOUTHERN_SWAMP, "globa", "", GameLayout::all } },
	{ MM_TERMINA_FIELD_FROM_ROAD_TO_SWAMP, { MM_TERMINA_FIELD_FROM_ROAD_TO_SWAMP, MM_TERMINA_FIELD, "globa", "", GameLayout::all } },
	{ MM_MILK_ROAD_FROM_FIELD, { MM_MILK_ROAD_FROM_FIELD, MM_MILK_ROAD, "globa", "", GameLayout::all } },
	{ MM_TERMINA_FIELD_FROM_MILK_ROAD, { MM_TERMINA_FIELD_FROM_MILK_ROAD, MM_TERMINA_FIELD, "globa", "", GameLayout::all } },
	{ MM_GORMAN_TRACK_FROM_MILK_ROAD, { MM_GORMAN_TRACK_FROM_MILK_ROAD, MM_GORMAN_TRACK, "globa", "", GameLayout::all } },
	{ MM_MILK_ROAD_FROM_GORMAN_TRACK, { MM_MILK_ROAD_FROM_GORMAN_TRACK, MM_MILK_ROAD, "globa", "", GameLayout::all } },
	{ MM_GORMAN_BACK_FROM_MILK_ROAD, { MM_GORMAN_BACK_FROM_MILK_ROAD, MM_GORMAN_TRACK, "globa", "", GameLayout::all } },
	{ MM_MILK_ROAD_FROM_GORMAN_BACK, { MM_MILK_ROAD_FROM_GORMAN_BACK, MM_MILK_ROAD, "globa", "", GameLayout::all } },
	{ MM_SNOWHEAD_PATH_FROM_MOUNTAIN_VILLAGE, { MM_SNOWHEAD_PATH_FROM_MOUNTAIN_VILLAGE, MM_PATH_SNOWHEAD, "globa", "", GameLayout::all } },
	{ MM_MOUNTAIN_VILLAGE_FROM_SNOWHEAD_PATH, { MM_MOUNTAIN_VILLAGE_FROM_SNOWHEAD_PATH, MM_MOUNTAIN_VILLAGE, "globa", "", GameLayout::all } },
	{ MM_SNOWHEAD_FROM_SNOWHEAD_PATH, { MM_SNOWHEAD_FROM_SNOWHEAD_PATH, MM_SNOWHEAD, "globa", "", GameLayout::all } },
	{ MM_PATH_SNOWHEAD_FROM_SNOWHEAD, { MM_PATH_SNOWHEAD_FROM_SNOWHEAD, MM_PATH_SNOWHEAD, "globa", "", GameLayout::all } },
	{ MM_IKANA_GRAVEYARD, { MM_IKANA_GRAVEYARD, MM_IKANA_GRAVEYARD, "globa", "", GameLayout::all } },
	{ MM_IKANA_ROAD_FROM_IKANA_GRAVEYARD, { MM_IKANA_ROAD_FROM_IKANA_GRAVEYARD, MM_ROAD_IKANA, "globa", "", GameLayout::all } },
	{ MM_ZORA_CAPE_FROM_GREAT_BAY_COAST, { MM_ZORA_CAPE_FROM_GREAT_BAY_COAST, MM_ZORA_CAPE, "globa", "", GameLayout::all } },
	{ MM_GREAT_BAY_COAST_FROM_ZORA_CAPE, { MM_GREAT_BAY_COAST_FROM_ZORA_CAPE, MM_GREAT_BAY_COAST, "globa", "", GameLayout::all } },
	{ MM_PINNACLE_ROCK, { MM_PINNACLE_ROCK, MM_PINNACLE_ROCK, "globa", "", GameLayout::all } },
	{ MM_GREAT_BAY_FROM_PINNACLE_ROCK, { MM_GREAT_BAY_FROM_PINNACLE_ROCK, MM_GREAT_BAY_COAST, "globa", "", GameLayout::all } },
	{ MM_ZORA_CAPE_FROM_HALL_WATER, { MM_ZORA_CAPE_FROM_HALL_WATER, MM_ZORA_CAPE, "globa", "", GameLayout::all } },
	{ MM_ZORA_HALL_UNDERWATER, { MM_ZORA_HALL_UNDERWATER, MM_ZORA_HALL, "globa", "", GameLayout::all } },
	{ MM_ZORA_CAPE_PENINSULA, { MM_ZORA_CAPE_PENINSULA, MM_ZORA_CAPE, "globa", "", GameLayout::all } },
	{ MM_ZORA_HALL_LEDGE, { MM_ZORA_HALL_LEDGE, MM_ZORA_HALL, "globa", "", GameLayout::all } },
	{ MM_DEKU_PALACE_MAIN_ENTRANCE, { MM_DEKU_PALACE_MAIN_ENTRANCE, MM_DEKU_PALACE, "globa", "", GameLayout::all } },
	{ MM_SWAMP_FROM_PALACE_MAIN_ENTRANCE, { MM_SWAMP_FROM_PALACE_MAIN_ENTRANCE, MM_SOUTHERN_SWAMP, "globa", "", GameLayout::all } },
	{ MM_DEKU_PALACE_LEDGE, { MM_DEKU_PALACE_LEDGE, MM_DEKU_PALACE, "globa", "", GameLayout::all } },
	{ MM_SWAMP_FROM_PALACE_LEDGE, { MM_SWAMP_FROM_PALACE_LEDGE, MM_SOUTHERN_SWAMP, "globa", "", GameLayout::all } },
	{ MM_WOODFALL, { MM_WOODFALL, MM_WOODFALL, "globa", "", GameLayout::all } },
	{ MM_SWAMP_FROM_WOODFALL, { MM_SWAMP_FROM_WOODFALL, MM_SOUTHERN_SWAMP, "globa", "", GameLayout::all } },
	{ MM_MYSTERY_WOODS, { MM_MYSTERY_WOODS, MM_LOST_WOODS, "globa", "", GameLayout::all } },
	{ MM_SWAMP_FROM_MYSTERY_WOODS, { MM_SWAMP_FROM_MYSTERY_WOODS, MM_SOUTHERN_SWAMP, "globa", "", GameLayout::all } },
	{ MM_SEWERS_FROM_EXTERIOR_GATE, { MM_SEWERS_FROM_EXTERIOR_GATE, MM_PIRATE_SEWERS, "globa", "", GameLayout::all } },
	{ MM_EXTERIOR_GATE_FROM_SEWERS, { MM_EXTERIOR_GATE_FROM_SEWERS, MM_PIRATE_FORTRESS_EXTERIOR, "globa", "", GameLayout::all } },
	{ MM_PIRATE_FORTRESS_INTERIOR, { MM_PIRATE_FORTRESS_INTERIOR, MM_PIRATE_FORTRESS_INTERIOR, "globa", "", GameLayout::all } },
	{ MM_PIRATE_FORTRESS_EXTERIOR_FROM_INTERIOR, { MM_PIRATE_FORTRESS_EXTERIOR_FROM_INTERIOR, MM_PIRATE_FORTRESS_EXTERIOR, "globa", "", GameLayout::all } },
	{ MM_PIRATE_FORTRESS_INTERIOR_FROM_LOOKOUT, { MM_PIRATE_FORTRESS_INTERIOR_FROM_LOOKOUT, MM_PIRATE_FORTRESS_INTERIOR, "globa", "", GameLayout::all } },
	{ MM_PIRATE_FORTRESS_EXTERIOR_LOOKOUT, { MM_PIRATE_FORTRESS_EXTERIOR_LOOKOUT, MM_PIRATE_FORTRESS_EXTERIOR, "globa", "", GameLayout::all } },
	{ MM_IKANA_CASTLE_GARDENS, { MM_IKANA_CASTLE_GARDENS, MM_CASTLE_IKANA, "globa", "", GameLayout::all } },
	{ MM_IKANA_CANYON_FROM_CASTLE_GARDENS, { MM_IKANA_CANYON_FROM_CASTLE_GARDENS, MM_IKANA_CANYON, "globa", "", GameLayout::all } },
	{ MM_STONE_TOWER, { MM_STONE_TOWER, MM_STONE_TOWER, "globa", "", GameLayout::all } },
	{ MM_IKANA_CANYON_FROM_STONE_TOWER, { MM_IKANA_CANYON_FROM_STONE_TOWER, MM_IKANA_CANYON, "globa", "", GameLayout::all } },
	{ MM_TWIN_ISLANDS_FROM_MOUNTAIN_VILLAGE, { MM_TWIN_ISLANDS_FROM_MOUNTAIN_VILLAGE, MM_TWIN_ISLANDS, "globa", "", GameLayout::all } },
	{ MM_MOUNTAIN_VILLAGE_FROM_TWIN_ISLANDS, { MM_MOUNTAIN_VILLAGE_FROM_TWIN_ISLANDS, MM_MOUNTAIN_VILLAGE, "globa", "", GameLayout::all } },
	{ MM_TWIN_ISLANDS_FROM_GORON_VILLAGE, { MM_TWIN_ISLANDS_FROM_GORON_VILLAGE, MM_TWIN_ISLANDS, "globa", "", GameLayout::all } },
	{ MM_GORON_VILLAGE_FROM_TWIN_ISLANDS, { MM_GORON_VILLAGE_FROM_TWIN_ISLANDS, MM_GORON_VILLAGE_WINTER, "globa", "", GameLayout::all } },
	{ MM_SWAMP_FROM_IKANA_CANYON, { MM_SWAMP_FROM_IKANA_CANYON, MM_IKANA_CANYON, "globa", "", GameLayout::all } },
	{ MM_IKANA_CASTLE_INTERIOR_KEG, { MM_IKANA_CASTLE_INTERIOR_KEG, MM_CASTLE_IKANA, "globa", "", GameLayout::all } },
	{ MM_IKANA_CASTLE_INTERIOR_BLOCK, { MM_IKANA_CASTLE_INTERIOR_BLOCK, MM_CASTLE_IKANA, "globa", "", GameLayout::all } },
	{ MM_CHEST_GAME, { MM_CHEST_GAME, MM_TREASURE_SHOP, "globa", "", GameLayout::all } },
	{ MM_HONEY_AND_DARLING_GAME, { MM_HONEY_AND_DARLING_GAME, MM_HONEY_DARLING, "globa", "", GameLayout::all } },
	{ MM_MAYORS_OFFICE, { MM_MAYORS_OFFICE, MM_MAYOR_HOUSE, "globa", "", GameLayout::all } },
	{ MM_TOWN_ARCHERY, { MM_TOWN_ARCHERY, MM_SHOOTING_GALLERY, "globa", "", GameLayout::all } },
	{ MM_MILK_BAR, { MM_MILK_BAR, MM_MILK_BAR, "globa", "", GameLayout::all } },
	{ MM_FAIRY_FOUNTAIN_TOWN, { MM_FAIRY_FOUNTAIN_TOWN, MM_FAIRY_CLOCK_TOWN, "globa", "", GameLayout::all } },
	{ MM_SWORDSMAN_SCHOOL, { MM_SWORDSMAN_SCHOOL, MM_SWORDSMAN_SCHOOL, "globa", "", GameLayout::all } },
	{ MM_CURIOSITY_SHOP, { MM_CURIOSITY_SHOP, MM_CURIOSITY_SHOP, "globa", "", GameLayout::all } },
	{ MM_TRADING_POST, { MM_TRADING_POST, MM_TRADING_POST, "globa", "", GameLayout::all } },
	{ MM_BOMB_SHOP, { MM_BOMB_SHOP, MM_BOMB_SHOP, "globa", "", GameLayout::all } },
	{ MM_POST_OFFICE, { MM_POST_OFFICE, MM_POST_OFFICE, "globa", "", GameLayout::all } },
	{ MM_LOTTERY, { MM_LOTTERY, MM_LOTTERY, "globa", "", GameLayout::all } },
	{ MM_KAFEI_HIDEOUT, { MM_KAFEI_HIDEOUT, MM_CURIOSITY_SHOP, "globa", "", GameLayout::all } },
	{ MM_POTION_SHOP, { MM_POTION_SHOP, MM_POTION_SHOP, "globa", "", GameLayout::all } },
	{ MM_DEKU_SHRINE, { MM_DEKU_SHRINE, MM_DEKU_SHRINE, "globa", "", GameLayout::all } },
	{ MM_GORON_SHOP, { MM_GORON_SHOP, MM_GORON_SHOP, "globa", "", GameLayout::all } },
	{ MM_FISHER_HUT, { MM_FISHER_HUT, MM_FISHERMAN_HUT, "globa", "", GameLayout::all } },
	{ MM_LABORATORY, { MM_LABORATORY, MM_LABORATORY, "globa", "", GameLayout::all } },
	{ MM_ROOM_EVANS, { MM_ROOM_EVANS, MM_ZORA_EVANS_ROOM, "globa", "", GameLayout::all } },
	{ MM_ROOM_JAPAS, { MM_ROOM_JAPAS, MM_ZORA_JAPAS_ROOM, "globa", "", GameLayout::all } },
	{ MM_ROOM_TIJO, { MM_ROOM_TIJO, MM_ZORA_TIJO_ROOM, "globa", "", GameLayout::all } },
	{ MM_ROOM_LULU, { MM_ROOM_LULU, MM_ZORA_LULU_ROOM, "globa", "", GameLayout::all } },
	{ MM_ZORA_SHOP, { MM_ZORA_SHOP, MM_ZORA_SHOP, "globa", "", GameLayout::all } },
	{ MM_GHOST_HUT, { MM_GHOST_HUT, MM_GHOST_HUT, "globa", "", GameLayout::all } },
	{ MM_MUSIC_BOX_HOUSE, { MM_MUSIC_BOX_HOUSE, MM_MUSIC_BOX_HOUSE, "globa", "", GameLayout::all } },
	{ MM_FAIRY_FOUNTAIN_IKANA, { MM_FAIRY_FOUNTAIN_IKANA, MM_FAIRY_IKANA, "globa", "", GameLayout::all } },
	{ MM_IKANA_CAVERN, { MM_IKANA_CAVERN, MM_SECRET_SHRINE, "globa", "", GameLayout::all } },
	{ MM_FAIRY_FOUNTAIN_GREAT_BAY, { MM_FAIRY_FOUNTAIN_GREAT_BAY, MM_FAIRY_GREAT_BAY_COAST, "globa", "", GameLayout::all } },
	{ MM_FAIRY_FOUNTAIN_SNOWHEAD, { MM_FAIRY_FOUNTAIN_SNOWHEAD, MM_FAIRY_SNOWHEAD, "globa", "", GameLayout::all } },
	{ MM_FAIRY_FOUNTAIN_WOODFALL, { MM_FAIRY_FOUNTAIN_WOODFALL, MM_FAIRY_WOODFALL, "globa", "", GameLayout::all } },
	{ MM_GORON_GRAVEYARD, { MM_GORON_GRAVEYARD, MM_GORON_GRAVEYARD, "globa", "", GameLayout::all } },
	{ MM_BLACKSMITH, { MM_BLACKSMITH, MM_BLACKSMITH, "globa", "", GameLayout::all } },
	{ MM_SWAMP_ARCHERY, { MM_SWAMP_ARCHERY, MM_SHOOTING_GALLERY_SWAMP, "globa", "", GameLayout::all } },
	{ MM_GORON_RACETRACK, { MM_GORON_RACETRACK, MM_GORON_RACETRACK, "globa", "", GameLayout::all } },
	{ MM_BEAVERS, { MM_BEAVERS, MM_WATERFALL_RAPIDS, "globa", "", GameLayout::all } },
	{ MM_CUCCO_SHACK, { MM_CUCCO_SHACK, MM_CUCCO_SHACK, "globa", "", GameLayout::all } },
	{ MM_DOGGY_RACETRACK, { MM_DOGGY_RACETRACK, MM_DOG_RACETRACK, "globa", "", GameLayout::all } },
	{ MM_STABLES, { MM_STABLES, MM_RANCH_HOUSE_BARN, "globa", "", GameLayout::all } },
	{ MM_RANCH_HOUSE, { MM_RANCH_HOUSE, MM_ROMANI_RANCH_BARN, "globa", "", GameLayout::all } },
	{ MM_GORON_SHRINE, { MM_GORON_SHRINE, MM_GORON_SHRINE, "globa", "", GameLayout::all } },
	{ MM_DEKU_PALACE_THRONE, { MM_DEKU_PALACE_THRONE, MM_DEKU_KING_CHAMBER, "globa", "", GameLayout::all } },
	{ MM_DEKU_PALACE_THRONE_CAGE, { MM_DEKU_PALACE_THRONE_CAGE, MM_DEKU_KING_CHAMBER, "globa", "", GameLayout::all } },
	{ MM_LONE_PEAK_SHRINE, { MM_LONE_PEAK_SHRINE, MM_LONE_PEAK, "globa", "", GameLayout::all } },
	{ MM_STOCK_POT_INN, { MM_STOCK_POT_INN, MM_STOCK_POT_INN, "globa", "", GameLayout::all } },
	{ MM_STOCK_POT_INN_ROOF, { MM_STOCK_POT_INN_ROOF, MM_STOCK_POT_INN, "globa", "", GameLayout::all } },
	{ MM_SEWERS_FROM_EXTERIOR_DOOR, { MM_SEWERS_FROM_EXTERIOR_DOOR, MM_PIRATE_SEWERS, "globa", "", GameLayout::all } },
	{ MM_TOURIST_INFORMATION, { MM_TOURIST_INFORMATION, MM_TOURIST_INFORMATION, "globa", "", GameLayout::all } },
	{ MM_ASTRAL_OBSERVATORY_FROM_CLOCK_TOWN_EAST, { MM_ASTRAL_OBSERVATORY_FROM_CLOCK_TOWN_EAST,  MM_OBSERVATORY, "globa", "", GameLayout::all } },
	{ MM_ASTRAL_OBSERVATORY_FROM_FIELD, { MM_ASTRAL_OBSERVATORY_FROM_FIELD,  MM_OBSERVATORY, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_EAST_FROM_CHEST_GAME, { MM_CLOCK_TOWN_EAST_FROM_CHEST_GAME, MM_CLOCK_TOWN_EAST, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_EAST_FROM_HONEY_AND_DARLING, { MM_CLOCK_TOWN_EAST_FROM_HONEY_AND_DARLING, MM_CLOCK_TOWN_EAST, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_EAST_FROM_MAYORS_OFFICE, { MM_CLOCK_TOWN_EAST_FROM_MAYORS_OFFICE, MM_CLOCK_TOWN_EAST, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_EAST_FROM_TOWN_ARCHERY, { MM_CLOCK_TOWN_EAST_FROM_TOWN_ARCHERY, MM_CLOCK_TOWN_EAST, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_EAST_FROM_STOCK_POT_INN, { MM_CLOCK_TOWN_EAST_FROM_STOCK_POT_INN, MM_CLOCK_TOWN_EAST, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_EAST_FROM_STOCK_POT_INN_ROOF, { MM_CLOCK_TOWN_EAST_FROM_STOCK_POT_INN_ROOF, MM_CLOCK_TOWN_EAST, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_EAST_FROM_MILK_BAR, { MM_CLOCK_TOWN_EAST_FROM_MILK_BAR, MM_CLOCK_TOWN_EAST, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_NORTH_FROM_FAIRY_FOUNTAIN, { MM_CLOCK_TOWN_NORTH_FROM_FAIRY_FOUNTAIN, MM_CLOCK_TOWN_NORTH, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_WEST_FROM_SWORDSMAN_SCHOOL, { MM_CLOCK_TOWN_WEST_FROM_SWORDSMAN_SCHOOL, MM_CLOCK_TOWN_WEST, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_WEST_FROM_CURIOSITY_SHOP, { MM_CLOCK_TOWN_WEST_FROM_CURIOSITY_SHOP, MM_CLOCK_TOWN_WEST, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_WEST_FROM_TRADING_POST, { MM_CLOCK_TOWN_WEST_FROM_TRADING_POST, MM_CLOCK_TOWN_WEST, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_WEST_FROM_BOMB_SHOP, { MM_CLOCK_TOWN_WEST_FROM_BOMB_SHOP, MM_CLOCK_TOWN_WEST, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_WEST_FROM_POST_OFFICE, { MM_CLOCK_TOWN_WEST_FROM_POST_OFFICE, MM_CLOCK_TOWN_WEST, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_WEST_FROM_LOTTERY, { MM_CLOCK_TOWN_WEST_FROM_LOTTERY, MM_CLOCK_TOWN_WEST, "globa", "", GameLayout::all } },
	{ MM_LAUNDRY_POOL_FROM_KAFEI_HIDEOUT, { MM_LAUNDRY_POOL_FROM_KAFEI_HIDEOUT, MM_LAUNDRY_POOL, "globa", "", GameLayout::all } },
	{ MM_SWAMP_FROM_POTION_SHOP, { MM_SWAMP_FROM_POTION_SHOP, MM_SOUTHERN_SWAMP, "globa", "", GameLayout::all } },
	{ MM_DEKU_PALACE_EXTERIOR_FROM_SHRINE, { MM_DEKU_PALACE_EXTERIOR_FROM_SHRINE, MM_DEKU_PALACE, "globa", "", GameLayout::all } },
	{ MM_GORON_SHRINE_FROM_SHOP, { MM_GORON_SHRINE_FROM_SHOP, MM_GORON_SHRINE, "globa", "", GameLayout::all } },
	{ MM_GREAT_BAY_COAST_FROM_FISHER_HUT, { MM_GREAT_BAY_COAST_FROM_FISHER_HUT, MM_GREAT_BAY_COAST, "globa", "", GameLayout::all } },
	{ MM_GREAT_BAY_COAST_FROM_LABORATORY, { MM_GREAT_BAY_COAST_FROM_LABORATORY, MM_GREAT_BAY_COAST, "globa", "", GameLayout::all } },
	{ MM_ZORA_HALL_FROM_EVANS, { MM_ZORA_HALL_FROM_EVANS, MM_ZORA_HALL, "globa", "", GameLayout::all } },
	{ MM_ZORA_HALL_FROM_JAPAS, { MM_ZORA_HALL_FROM_JAPAS, MM_ZORA_HALL, "globa", "", GameLayout::all } },
	{ MM_ZORA_HALL_FROM_TIJO, { MM_ZORA_HALL_FROM_TIJO, MM_ZORA_HALL, "globa", "", GameLayout::all } },
	{ MM_ZORA_HALL_FROM_LULU, { MM_ZORA_HALL_FROM_LULU, MM_ZORA_HALL, "globa", "", GameLayout::all } },
	{ MM_ZORA_HALL_FROM_SHOP, { MM_ZORA_HALL_FROM_SHOP, MM_ZORA_HALL, "globa", "", GameLayout::all } },
	{ MM_IKANA_CANYON_FROM_GHOST_HUT, { MM_IKANA_CANYON_FROM_GHOST_HUT, MM_IKANA_CANYON, "globa", "", GameLayout::all } },
	{ MM_IKANA_CANYON_FROM_MUSIC_BOX_HOUSE, { MM_IKANA_CANYON_FROM_MUSIC_BOX_HOUSE, MM_IKANA_CANYON, "globa", "", GameLayout::all } },
	{ MM_IKANA_CANYON_FROM_FAIRY_FOUNTAIN, { MM_IKANA_CANYON_FROM_FAIRY_FOUNTAIN, MM_IKANA_CANYON, "globa", "", GameLayout::all } },
	{ MM_IKANA_CANYON_FROM_CAVERN, { MM_IKANA_CANYON_FROM_CAVERN, MM_IKANA_CANYON, "globa", "", GameLayout::all } },
	{ MM_EXTERIOR_DOOR_FROM_SEWERS, { MM_EXTERIOR_DOOR_FROM_SEWERS, MM_PIRATE_FORTRESS_EXTERIOR, "globa", "", GameLayout::all } },
	{ MM_GREAT_BAY_FROM_FAIRY_FOUNTAIN, { MM_GREAT_BAY_FROM_FAIRY_FOUNTAIN, MM_GREAT_BAY_COAST, "globa", "", GameLayout::all } },
	{ MM_SNOWHEAD_FROM_FAIRY_FOUNTAIN, { MM_SNOWHEAD_FROM_FAIRY_FOUNTAIN, MM_SNOWHEAD, "globa", "", GameLayout::all } },
	{ MM_SWAMP_FROM_TOURIST_INFORMATION, { MM_SWAMP_FROM_TOURIST_INFORMATION, MM_SOUTHERN_SWAMP, "globa", "", GameLayout::all } },
	{ MM_WOODFALL_FROM_FAIRY_FOUNTAIN, { MM_WOODFALL_FROM_FAIRY_FOUNTAIN, MM_WOODFALL, "globa", "", GameLayout::all } },
	{ MM_MOUNTAIN_VILLAGE_FROM_GORON_GRAVEYARD, { MM_MOUNTAIN_VILLAGE_FROM_GORON_GRAVEYARD, MM_MOUNTAIN_VILLAGE, "globa", "", GameLayout::all } },
	{ MM_MOUNTAIN_VILLAGE_FROM_BLACKSMITH, { MM_MOUNTAIN_VILLAGE_FROM_BLACKSMITH, MM_MOUNTAIN_VILLAGE, "globa", "", GameLayout::all } },
	{ MM_ROMANI_RANCH_FROM_CUCCO_SHACK, { MM_ROMANI_RANCH_FROM_CUCCO_SHACK, MM_ROMANI_RANCH, "globa", "", GameLayout::all } },
	{ MM_ROMANI_RANCH_FROM_DOGGY_RACETRACK, { MM_ROMANI_RANCH_FROM_DOGGY_RACETRACK, MM_ROMANI_RANCH, "globa", "", GameLayout::all } },
	{ MM_ROMANI_RANCH_FROM_STABLES, { MM_ROMANI_RANCH_FROM_STABLES, MM_ROMANI_RANCH, "globa", "", GameLayout::all } },
	{ MM_ROMANI_RANCH_FROM_RANCH_HOUSE, { MM_ROMANI_RANCH_FROM_RANCH_HOUSE, MM_ROMANI_RANCH, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_EAST_FROM_ASTRAL_OBSERVATORY, { MM_CLOCK_TOWN_EAST_FROM_ASTRAL_OBSERVATORY, MM_CLOCK_TOWN_EAST, "globa", "", GameLayout::all } },
	{ MM_FIELD_FROM_ASTRAL_OBSERVATORY, { MM_FIELD_FROM_ASTRAL_OBSERVATORY, MM_TERMINA_FIELD, "globa", "", GameLayout::all } },
	{ MM_SWAMP_ROAD_FROM_ARCHERY, { MM_SWAMP_ROAD_FROM_ARCHERY, MM_ROAD_SOUTHERN_SWAMP, "globa", "", GameLayout::all } },
	{ MM_TWIN_ISLANDS_FROM_GORON_RACETRACK, { MM_TWIN_ISLANDS_FROM_GORON_RACETRACK, MM_TWIN_ISLANDS, "globa", "", GameLayout::all } },
	{ MM_ZORA_CAPE_FROM_BEAVERS, { MM_ZORA_CAPE_FROM_BEAVERS, MM_ZORA_CAPE, "globa", "", GameLayout::all } },
	{ MM_GORON_VILLAGE_FROM_GORON_SHRINE, { MM_GORON_VILLAGE_FROM_GORON_SHRINE, MM_GORON_VILLAGE_WINTER, "globa", "", GameLayout::all } },
	{ MM_GORON_VILLAGE_FROM_LONE_PEAK_SHRINE, { MM_GORON_VILLAGE_FROM_LONE_PEAK_SHRINE, MM_GORON_VILLAGE_WINTER, "globa", "", GameLayout::all } },
	{ MM_DEKU_PALACE_EXTERIOR_FROM_THRONE, { MM_DEKU_PALACE_EXTERIOR_FROM_THRONE, MM_DEKU_PALACE, "globa", "", GameLayout::all } },
	{ MM_DEKU_PALACE_EXTERIOR_FROM_THRONE_CAGE, { MM_DEKU_PALACE_EXTERIOR_FROM_THRONE_CAGE, MM_DEKU_PALACE, "globa", "", GameLayout::all } },
	{ MM_SAKON_HIDEOUT, { MM_SAKON_HIDEOUT, MM_SAKON_HIDEOUT, "globa", "", GameLayout::all } },
	{ MM_IKANA_CANYON_FROM_SAKON_HIDEOUT, { MM_IKANA_CANYON_FROM_SAKON_HIDEOUT, MM_IKANA_CANYON, "globa", "", GameLayout::all } },
	{ MM_WARP_OWL_GREAT_BAY, { MM_WARP_OWL_GREAT_BAY, MM_GREAT_BAY_COAST, "globa", "", GameLayout::all } },
	{ MM_WARP_OWL_ZORA_CAPE, { MM_WARP_OWL_ZORA_CAPE, MM_ZORA_CAPE, "globa", "", GameLayout::all } },
	{ MM_WARP_OWL_SNOWHEAD, { MM_WARP_OWL_SNOWHEAD, MM_SNOWHEAD, "globa", "", GameLayout::all } },
	{ MM_WARP_OWL_MOUNTAIN_VILLAGE, { MM_WARP_OWL_MOUNTAIN_VILLAGE, MM_MOUNTAIN_VILLAGE, "globa", "", GameLayout::all } },
	{ MM_WARP_OWL_CLOCK_TOWN, { MM_WARP_OWL_CLOCK_TOWN, MM_CLOCK_TOWN_SOUTH, "globa", "", GameLayout::all } },
	{ MM_WARP_OWL_MILK_ROAD, { MM_WARP_OWL_MILK_ROAD, MM_MILK_ROAD, "globa", "", GameLayout::all } },
	{ MM_WARP_OWL_WOODFALL, { MM_WARP_OWL_WOODFALL, MM_WOODFALL, "globa", "", GameLayout::all } },
	{ MM_WARP_OWL_SOUTHERN_SWAMP, { MM_WARP_OWL_SOUTHERN_SWAMP, MM_SOUTHERN_SWAMP, "globa", "", GameLayout::all } },
	{ MM_WARP_OWL_IKANA_CANYON, { MM_WARP_OWL_IKANA_CANYON, MM_IKANA_CANYON, "globa", "", GameLayout::all } },
	{ MM_WARP_OWL_STONE_TOWER, { MM_WARP_OWL_STONE_TOWER, MM_STONE_TOWER, "globa", "", GameLayout::all } },
	{ MM_WALLMASTER_DAMPE, { MM_WALLMASTER_DAMPE, MM_DAMPE_HOUSE, "globa", "", GameLayout::all } },
	{ MM_WALLMASTER_BTW_ENTRANCE, { MM_WALLMASTER_BTW_ENTRANCE, MM_BENEATH_THE_WELL, "globa", "", GameLayout::all } },
	{ MM_WALLMASTER_BTW_FOUNTAIN, { MM_WALLMASTER_BTW_FOUNTAIN, MM_BENEATH_THE_WELL, "globa", "", GameLayout::all } },
	{ MM_WALLMASTER_BTW_EXIT, { MM_WALLMASTER_BTW_EXIT, MM_BENEATH_THE_WELL, "globa", "", GameLayout::all } },
	{ MM_GROTTO_GENERIC_FIELD_PILLAR, { MM_GROTTO_GENERIC_FIELD_PILLAR, MM_GROTTO_TERMINA_PILLAR, "globa", "", GameLayout::all } },
	{ MM_GROTTO_GENERIC_GRASS, { MM_GROTTO_GENERIC_GRASS, MM_GROTTO_TERMINA_TALL_GRASS, "globa", "", GameLayout::all } },
	{ MM_GROTTO_GENERIC_PATH_SWAMP, { MM_GROTTO_GENERIC_PATH_SWAMP, MM_GROTTO_SOUTHERN_SWAMP_ROAD_OPEN, "globa", "", GameLayout::all } },
	{ MM_GROTTO_GENERIC_WOODS, { MM_GROTTO_GENERIC_WOODS, MM_GROTTO_WOODS_OF_MYSTERY_OPEN, "globa", "", GameLayout::all } },
	{ MM_GROTTO_GENERIC_SWAMP, { MM_GROTTO_GENERIC_SWAMP, MM_GROTTO_SOUTHERN_SWAMP_OPEN, "globa", "", GameLayout::all } },
	{ MM_GROTTO_GENERIC_MOUNTAIN_VILLAGE, { MM_GROTTO_GENERIC_MOUNTAIN_VILLAGE, MM_GROTTO_MOUNTAIN_VILLAGE_GENERIC, "globa", "", GameLayout::all } },
	{ MM_GROTTO_GENERIC_TWIN_ISLANDS, { MM_GROTTO_GENERIC_TWIN_ISLANDS, MM_GROTTO_TWIN_ISLANDS_RAMP, "globa", "", GameLayout::all } },
	{ MM_GROTTO_GENERIC_PATH_SNOWHEAD, { MM_GROTTO_GENERIC_PATH_SNOWHEAD, MM_GROTTO_PATH_TO_SNOWHEAD_GENERIC, "globa", "", GameLayout::all } },
	{ MM_GROTTO_GENERIC_GREAT_BAY_COAST, { MM_GROTTO_GENERIC_GREAT_BAY_COAST, MM_GROTTO_GREAT_BAY_COAST_FISHERMAN, "globa", "", GameLayout::all } },
	{ MM_GROTTO_GENERIC_ZORA_CAPE, { MM_GROTTO_GENERIC_ZORA_CAPE, MM_GROTTO_ZORA_CAPE_GENERIC, "globa", "", GameLayout::all } },
	{ MM_GROTTO_GENERIC_PATH_IKANA, { MM_GROTTO_GENERIC_PATH_IKANA, MM_GROTTO_IKANA_ROAD_GENERIC, "globa", "", GameLayout::all } },
	{ MM_GROTTO_GENERIC_GRAVEYARD, { MM_GROTTO_GENERIC_GRAVEYARD, MM_GROTTO_IKANA_GRAVEYARD_GENERIC, "globa", "", GameLayout::all } },
	{ MM_GROTTO_GENERIC_VALLEY, { MM_GROTTO_GENERIC_VALLEY, MM_GROTTO_IKANA_VALLEY_OPEN, "globa", "", GameLayout::all } },
	{ MM_GROTTO_COW_FIELD, { MM_GROTTO_COW_FIELD, MM_GROTTO_TERMINA_COW, "globa", "", GameLayout::all } },
	{ MM_GROTTO_COW_COAST, { MM_GROTTO_COW_COAST, MM_GROTTO_GREAT_BAY_COAST_COW, "globa", "", GameLayout::all } },
	{ MM_GROTTO_GOSSIPS_MOUNTAIN, { MM_GROTTO_GOSSIPS_MOUNTAIN, MM_GROTTO_TERMINA_MOUNTAIN_GOSSIP, "globa", "", GameLayout::all } },
	{ MM_GROTTO_GOSSIPS_CANYON, { MM_GROTTO_GOSSIPS_CANYON, MM_GROTTO_TERMINA_CANYON_GOSSIP, "globa", "", GameLayout::all } },
	{ MM_GROTTO_GOSSIPS_OCEAN, { MM_GROTTO_GOSSIPS_OCEAN, MM_GROTTO_TERMINA_OCEAN_GOSSIP, "globa", "", GameLayout::all } },
	{ MM_GROTTO_GOSSIPS_SWAMP, { MM_GROTTO_GOSSIPS_SWAMP, MM_GROTTO_TERMINA_SWAMP_GOSSIP, "globa", "", GameLayout::all } },
	{ MM_GROTTO_DODONGO, { MM_GROTTO_DODONGO, MM_GROTTO_TERMINA_DODONGO, "globa", "", GameLayout::all } },
	{ MM_GROTTO_SCRUB, { MM_GROTTO_SCRUB, MM_GROTTO_TERMINA_SCRUB, "globa", "", GameLayout::all } },
	{ MM_GROTTO_PEAHAT, { MM_GROTTO_PEAHAT, MM_GROTTO_TERMINA_PEAHAT, "globa", "", GameLayout::all } },
	{ MM_GROTTO_BIO_BABA, { MM_GROTTO_BIO_BABA, MM_GROTTO_TERMINA_BIO_BABA, "globa", "", GameLayout::all } },
	{ MM_GROTTO_HOT_WATER, { MM_GROTTO_HOT_WATER, MM_GROTTO_TWIN_ISLANDS_FROZEN, "globa", "", GameLayout::all } },
	{ MM_GROTTO_BEAN, { MM_GROTTO_BEAN, MM_GROTTO_DEKU_PALACE_BEANS, "globa", "", GameLayout::all } },
	{ MM_GROTTO_DEKU_PLAYGROUND, { MM_GROTTO_DEKU_PLAYGROUND, MM_DEKU_PLAYGROUND, "globa", "", GameLayout::all } },
	{ MM_GROTTO_JP_CLIMB_LEFT, { MM_GROTTO_JP_CLIMB_LEFT, MM_GROTTO_DEKU_PALACE_CLIMB, "globa", "", GameLayout::mm_jp } },
	{ MM_GROTTO_JP_CLIMB_RIGHT, { MM_GROTTO_JP_CLIMB_RIGHT, MM_GROTTO_DEKU_PALACE_CLIMB, "globa", "", GameLayout::mm_jp } },
	{ MM_GROTTO_JP_LINE_START, { MM_GROTTO_JP_LINE_START, MM_GROTTO_DEKU_PALACE_GENERIC, "globa", "", GameLayout::mm_jp } },
	{ MM_GROTTO_JP_LINE_END, { MM_GROTTO_JP_LINE_END, MM_GROTTO_DEKU_PALACE_GENERIC, "globa", "", GameLayout::mm_jp } },
	{ MM_GRAVE_NIGHT1, { MM_GRAVE_NIGHT1, MM_BENEATH_THE_GRAVEYARD_NIGHT1, "globa", "", GameLayout::all } },
	{ MM_GRAVE_NIGHT2, { MM_GRAVE_NIGHT2, MM_BENEATH_THE_GRAVEYARD_NIGHT2, "globa", "", GameLayout::all } },
	{ MM_GRAVE_NIGHT3, { MM_GRAVE_NIGHT3, MM_DAMPE_HOUSE, "globa", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GENERIC_FIELD_PILLAR, { MM_GROTTO_EXIT_GENERIC_FIELD_PILLAR, MM_TERMINA_FIELD, "globa", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GENERIC_GRASS, { MM_GROTTO_EXIT_GENERIC_GRASS, MM_TERMINA_FIELD, "globa", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GENERIC_PATH_SWAMP, { MM_GROTTO_EXIT_GENERIC_PATH_SWAMP, MM_ROAD_SOUTHERN_SWAMP, "globa", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GENERIC_WOODS, { MM_GROTTO_EXIT_GENERIC_WOODS, MM_LOST_WOODS, "globa", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GENERIC_SWAMP, { MM_GROTTO_EXIT_GENERIC_SWAMP, MM_SOUTHERN_SWAMP, "globa", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GENERIC_MOUNTAIN_VILLAGE, { MM_GROTTO_EXIT_GENERIC_MOUNTAIN_VILLAGE, MM_MOUNTAIN_VILLAGE, "globa", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GENERIC_TWIN_ISLANDS, { MM_GROTTO_EXIT_GENERIC_TWIN_ISLANDS, MM_TWIN_ISLANDS, "globa", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GENERIC_PATH_SNOWHEAD, { MM_GROTTO_EXIT_GENERIC_PATH_SNOWHEAD, MM_PATH_SNOWHEAD, "globa", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GENERIC_GREAT_BAY_COAST, { MM_GROTTO_EXIT_GENERIC_GREAT_BAY_COAST, MM_GREAT_BAY_COAST, "globa", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GENERIC_ZORA_CAPE, { MM_GROTTO_EXIT_GENERIC_ZORA_CAPE, MM_ZORA_CAPE, "globa", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GENERIC_PATH_IKANA, { MM_GROTTO_EXIT_GENERIC_PATH_IKANA, MM_ROAD_IKANA, "globa", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GENERIC_GRAVEYARD, { MM_GROTTO_EXIT_GENERIC_GRAVEYARD, MM_IKANA_GRAVEYARD, "globa", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GENERIC_VALLEY, { MM_GROTTO_EXIT_GENERIC_VALLEY, MM_IKANA_CANYON, "globa", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_COW_FIELD, { MM_GROTTO_EXIT_COW_FIELD, MM_TERMINA_FIELD, "globa", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_COW_COAST, { MM_GROTTO_EXIT_COW_COAST, MM_GREAT_BAY_COAST, "globa", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GOSSIPS_MOUNTAIN, { MM_GROTTO_EXIT_GOSSIPS_MOUNTAIN, MM_TERMINA_FIELD, "globa", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GOSSIPS_CANYON, { MM_GROTTO_EXIT_GOSSIPS_CANYON, MM_TERMINA_FIELD, "globa", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GOSSIPS_OCEAN, { MM_GROTTO_EXIT_GOSSIPS_OCEAN, MM_TERMINA_FIELD, "globa", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_GOSSIPS_SWAMP, { MM_GROTTO_EXIT_GOSSIPS_SWAMP, MM_TERMINA_FIELD, "globa", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_DODONGO, { MM_GROTTO_EXIT_DODONGO, MM_TERMINA_FIELD, "globa", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_SCRUB, { MM_GROTTO_EXIT_SCRUB, MM_TERMINA_FIELD, "globa", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_PEAHAT, { MM_GROTTO_EXIT_PEAHAT, MM_TERMINA_FIELD, "globa", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_BIO_BABA, { MM_GROTTO_EXIT_BIO_BABA, MM_TERMINA_FIELD, "globa", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_HOT_WATER, { MM_GROTTO_EXIT_HOT_WATER, MM_TWIN_ISLANDS, "globa", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_BEAN, { MM_GROTTO_EXIT_BEAN, MM_DEKU_PALACE, "globa", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_DEKU_PLAYGROUND, { MM_GROTTO_EXIT_DEKU_PLAYGROUND, MM_CLOCK_TOWN_NORTH, "globa", "", GameLayout::all } },
	{ MM_GROTTO_EXIT_JP_CLIMB_LEFT, { MM_GROTTO_EXIT_JP_CLIMB_LEFT, MM_DEKU_PALACE, "globa", "", GameLayout::mm_jp } },
	{ MM_GROTTO_EXIT_JP_CLIMB_RIGHT, { MM_GROTTO_EXIT_JP_CLIMB_RIGHT, MM_DEKU_PALACE, "globa", "", GameLayout::mm_jp } },
	{ MM_GROTTO_EXIT_JP_LINE_START, { MM_GROTTO_EXIT_JP_LINE_START, MM_DEKU_PALACE, "globa", "", GameLayout::mm_jp } },
	{ MM_GROTTO_EXIT_JP_LINE_END, { MM_GROTTO_EXIT_JP_LINE_END, MM_DEKU_PALACE, "globa", "", GameLayout::mm_jp } },
	{ MM_GRAVE_EXIT_NIGHT1, { MM_GRAVE_EXIT_NIGHT1, MM_IKANA_GRAVEYARD, "globa", "", GameLayout::all } },
	{ MM_GRAVE_EXIT_NIGHT2, { MM_GRAVE_EXIT_NIGHT2, MM_IKANA_GRAVEYARD, "globa", "", GameLayout::all } },
	{ MM_GRAVE_EXIT_NIGHT3, { MM_GRAVE_EXIT_NIGHT3, MM_IKANA_GRAVEYARD, "globa", "", GameLayout::all } },
	{ MM_VOID_GREAT_BAY, { MM_VOID_GREAT_BAY, MM_GREAT_BAY_COAST, "globa", "", GameLayout::all } },
	{ MM_VOID_GREAT_BAY_BY_PINNACLE_ROCK, { MM_VOID_GREAT_BAY_BY_PINNACLE_ROCK, MM_GREAT_BAY_COAST, "globa", "", GameLayout::all } },
	{ MM_VOID_ZORA_CAPE, { MM_VOID_ZORA_CAPE, MM_ZORA_CAPE, "globa", "", GameLayout::all } },
	{ MM_VOID_PINNACLE_ROCK, { MM_VOID_PINNACLE_ROCK, MM_PINNACLE_ROCK, "globa", "", GameLayout::all } },
	{ MM_MOON, { MM_MOON, MM_MOON, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_FROM_SONG_OF_TIME, { MM_CLOCK_TOWN_FROM_SONG_OF_TIME, MM_CLOCK_TOWN_SOUTH, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWER_MOON_CRASH, { MM_CLOCK_TOWER_MOON_CRASH, MM_CLOCK_TOWER_ROOFTOP, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWN_FROM_CLOCK_TOWER, { MM_CLOCK_TOWN_FROM_CLOCK_TOWER, MM_CLOCK_TOWN_SOUTH, "globa", "", GameLayout::all } },
	{ MM_CLOCK_TOWER_FROM_CLOCK_TOWN, { MM_CLOCK_TOWER_FROM_CLOCK_TOWN, MM_CLOCK_TOWER_ROOFTOP, "globa", "", GameLayout::all } },
	{ MM_COAST_FROM_MIKAU_CS, { MM_COAST_FROM_MIKAU_CS, MM_GREAT_BAY_COAST, "globa", "", GameLayout::all } },
	{ MM_GROTTO_TYPE_GENERIC, { MM_GROTTO_TYPE_GENERIC, MM_GROTTOS, "globa", "", GameLayout::all } },
	{ MM_GROTTO_TYPE_COW, { MM_GROTTO_TYPE_COW, MM_GROTTOS, "globa", "", GameLayout::all } },
	{ MM_IKANA_GRAVEYARD_FROM_DAMPE, { MM_IKANA_GRAVEYARD_FROM_DAMPE, MM_IKANA_GRAVEYARD, "globa", "", GameLayout::all } },
	{ MM_MILK_ROAD_FROM_RANCH2, { MM_MILK_ROAD_FROM_RANCH2, MM_MILK_ROAD, "globa", "", GameLayout::all } },
	{ MM_MILK_ROAD_FROM_GORMAN_TRACK2, { MM_MILK_ROAD_FROM_GORMAN_TRACK2, MM_MILK_ROAD, "globa", "", GameLayout::all } },
	{ MM_GORMAN_TRACK_UNK2, { MM_GORMAN_TRACK_UNK2, MM_GORMAN_TRACK, "globa", "", GameLayout::all } },
	{ MM_GORMAN_TRACK_UNK3, { MM_GORMAN_TRACK_UNK3, MM_GORMAN_TRACK, "globa", "", GameLayout::all } },
	{ MM_GORMAN_TRACK_UNK5, { MM_GORMAN_TRACK_UNK5, MM_GORMAN_TRACK, "globa", "", GameLayout::all } },
	{ MM_GORMAN_TRACK_UNK6, { MM_GORMAN_TRACK_UNK6, MM_GORMAN_TRACK, "globa", "", GameLayout::all } },
	{ MM_GORON_RACETRACK_ALT, { MM_GORON_RACETRACK_ALT, MM_GORON_RACETRACK, "globa", "", GameLayout::all } },
	{ MM_INTERNAL_EXIT_GROTTO, { MM_INTERNAL_EXIT_GROTTO, MM_GROTTOS, "globa", "", GameLayout::all } },
	{ MM_LOST_WOODS, { MM_LOST_WOODS, MM_LOST_WOODS, "globa", "", GameLayout::all } }
};