#pragma once

#include "Entrances.h"
#include "Scenes.h"

#pragma region Defines

#define OOT_SPAWN_CHILD  0x0bb
#define OOT_SPAWN_ADULT  0xf20
#define OOT_BOSS_DEKU_TREE_ENTR  0x40f
#define OOT_BOSS_DODONGO_CAVERN_ENTR  0x40b
#define OOT_BOSS_JABU_JABU_ENTR  0x301
#define OOT_BOSS_TEMPLE_FOREST_ENTR  0x00c
#define OOT_BOSS_TEMPLE_FIRE_ENTR  0x305
#define OOT_BOSS_TEMPLE_WATER_ENTR  0x417
#define OOT_BOSS_TEMPLE_SHADOW_ENTR  0x413
#define OOT_BOSS_TEMPLE_SPIRIT_ENTR  0x08d
#define OOT_DEKU_TREE_ENTR  0x000
#define OOT_DODONGO_CAVERN_ENTR  0x004
#define OOT_JABU_JABU_ENTR  0x028
#define OOT_TEMPLE_FOREST_ENTR  0x169
#define OOT_TEMPLE_FIRE_ENTR  0x165
#define OOT_TEMPLE_WATER_ENTR  0x010
#define OOT_TEMPLE_SHADOW_ENTR  0x037
#define OOT_TEMPLE_SPIRIT_ENTR  0x082
#define OOT_BOTTOM_OF_THE_WELL_ENTR  0x098
#define OOT_ICE_CAVERN_ENTR  0x088
#define OOT_GERUDO_TRAINING_GROUNDS_ENTR  0x008
#define OOT_GANON_CASTLE_ENTR  0x467
#define OOT_GANON_TOWER_ENTR  0x41b
#define OOT_KOKIRI_FOREST_FROM_DEKU_TREE_ENTR  0x209
#define OOT_MOUNTAIN_TRAIL_FROM_DODONGO_CAVERN_ENTR  0x242
#define OOT_ZORA_FOUNTAIN_FROM_JABU_JABU_ENTR  0x221
#define OOT_SACRED_MEADOW_FROM_TEMPLE_FOREST_ENTR  0x215
#define OOT_DEATH_CRATER_FROM_TEMPLE_FIRE_ENTR  0x24a
#define OOT_LAKE_HYLIA_FROM_TEMPLE_WATER_ENTR  0x21d
#define OOT_GRAVEYARD_FROM_TEMPLE_SHADOW_ENTR  0x205
#define OOT_DESERT_COLOSSUS_FROM_TEMPLE_SPIRIT_ENTR  0x1e1
#define OOT_KAKARIKO_FROM_BOTTOM_OF_THE_WELL_ENTR  0x2a6
#define OOT_ZORA_FOUNTAIN_FROM_ICE_CAVERN_ENTR  0x3d4
#define OOT_GERUDO_FORTRESS_FROM_GERUDO_TRAINING_ENTR  0x3a8
#define OOT_GANON_CASTLE_EXTERIOR_FROM_CASTLE_ENTR  0x23d
#define OOT_GANON_CASTLE_FROM_TOWER_ENTR  0x534
#define OOT_LOST_WOODS_BRIDGE_FROM_FIELD_ENTR  0x4de
#define OOT_ZORA_RIVER_FROM_FIELD_ENTR  0x0ea
#define OOT_KAKARIKO_FROM_FIELD_ENTR  0x0db
#define OOT_LON_LON_RANCH_FROM_FIELD_ENTR  0x157
#define OOT_LAKE_HYLIA_FROM_FIELD_ENTR  0x102
#define OOT_GERUDO_FORTRESS_FROM_VALLEY_ENTR  0x129
#define OOT_DEATH_MOUNTAIN_FROM_KAKARIKO_ENTR  0x13d
#define OOT_GERUDO_VALLEY_FROM_FIELD_ENTR  0x117
#define OOT_MARKET_ENTRANCE_FROM_FIELD_ENTR  0x276
#define OOT_ZORA_RIVER_FROM_LOST_WOODS_ENTR  0x1dd
#define OOT_GORON_CITY_FROM_LOST_WOODS_ENTR  0x4e2
#define OOT_LAKE_HYLIA_FROM_ZORA_DOMAIN_ENTR  0x560
#define OOT_FIELD_FROM_LOST_WOODS_BRIDGE_ENTR  0x185
#define OOT_FIELD_FROM_ZORA_RIVER_ENTR  0x181
#define OOT_FIELD_FROM_KAKARIKO_ENTR  0x17d
#define OOT_FIELD_FROM_LON_LON_RANCH_ENTR  0x1f9
#define OOT_FIELD_FROM_LAKE_HYLIA_ENTR  0x189
#define OOT_FIELD_FROM_GERUDO_VALLEY_ENTR  0x18d
#define OOT_VALLEY_FROM_GERUDO_FORTRESS_ENTR  0x22d
#define OOT_KAKARIKO_FROM_DEATH_MOUNTAIN_ENTR  0x191
#define OOT_FIELD_FROM_MARKET_ENTRANCE_ENTR  0x1fd
#define OOT_LOST_WOODS_FROM_ZORA_RIVER_ENTR  0x4da
#define OOT_LOST_WOODS_FROM_GORON_CITY_ENTR  0x4d6
#define OOT_ZORA_DOMAIN_FROM_LAKE_HYLIA_ENTR  0x328
#define OOT_SACRED_FOREST_MEADOW_ENTR  0x0fc
#define OOT_LOST_WOODS_FROM_MEADOW_ENTR  0x1a9
#define OOT_GORON_CITY_ENTR  0x14d
#define OOT_DEATH_MOUNTAIN_FROM_GORON_CITY_ENTR  0x1b9
#define OOT_ZORA_DOMAIN_ENTR  0x108
#define OOT_RIVER_FROM_DOMAIN_ENTR  0x19d
#define OOT_FOUNTAIN_ZORA_ENTR  0x225
#define OOT_DOMAIN_FROM_FOUNTAIN_ENTR  0x1a1
#define OOT_CRATER_FROM_GORON_CITY_ENTR  0x246
#define OOT_GORON_CITY_FROM_CRATER_ENTR  0x1c1
#define OOT_DEATH_MOUNTAIN_CRATER_ENTR  0x147
#define OOT_TRAIL_SUMMIT_FROM_CRATER_ENTR  0x1bd
#define OOT_LOST_WOODS_FROM_KOKIRI_FOREST_ENTR  0x11e
#define OOT_KOKIRI_FOREST_FROM_LOST_WOODS_ENTR  0x286
#define OOT_FOREST_FROM_LOST_WOODS_BRIDGE_ENTR  0x20d
#define OOT_LOST_WOODS_BRIDGE_FROM_FOREST_ENTR  0x5e0
#define OOT_GRAVEYARD_ENTR  0x0e4
#define OOT_KAKARIKO_FROM_GRAVEYARD_ENTR  0x195
#define OOT_WASTELAND_ENTR  0x130
#define OOT_FORTRESS_FROM_WASTELAND_ENTR  0x3ac
#define OOT_COLOSSUS_ENTR  0x123
#define OOT_WASTELAND_FROM_COLOSSUS_ENTR  0x365
#define OOT_MARKET_FROM_MARKET_ENTRANCE_ENTR  0x0b1
#define OOT_MARKET_ENTRANCE_FROM_MARKET_ENTR  0x033
#define OOT_HYRULE_CASTLE_ENTR  0x138
#define OOT_MARKET_FROM_CASTLE_ENTR  0x25a
#define OOT_MARKET_FROM_TEMPLE_OF_TIME_ENTRYWAY_ENTR  0x25e
#define OOT_TEMPLE_OF_TIME_ENTRYWAY_FROM_MARKET_ENTR  0x171
#define OOT_LAKE_HYLIA_FROM_VALLEY_ENTR  0x219
#define OOT_LOST_WOODS_FROM_LOST_WOODS_NORTH_ENTR  0xf01
#define OOT_LOST_WOODS_FROM_LOST_WOODS_EAST_ENTR  0x1ad
#define OOT_LOST_WOODS_FROM_LOST_WOODS_SOUTH_ENTR  0x1b1
#define OOT_LOST_WOODS_FROM_LOST_WOODS_WEST_ENTR  0x4c6
#define OOT_HOUSE_MIDO_ENTR  0x433
#define OOT_HOUSE_SARIA_ENTR  0x437
#define OOT_HOUSE_TWINS_ENTR  0x09c
#define OOT_HOUSE_KNOW_IT_ALL_ENTR  0x0c9
#define OOT_KOKIRI_SHOP_ENTR  0x0c1
#define OOT_HOUSE_POTS_ENTR  0x07e
#define OOT_LABORATORY_ENTR  0x043
#define OOT_FISHING_POND_ENTR  0x45f
#define OOT_VALLEY_TENT_ENTR  0x3a0
#define OOT_HOUSE_CARPENTER_ENTR  0x2fd
#define OOT_HOUSE_SKULLTULA_ENTR  0x550
#define OOT_HOUSE_IMPA_ENTR  0x39c
#define OOT_HOUSE_IMPA_BACK_ENTR  0x5c8
#define OOT_SHOP_GRANNY_ENTR  0x072
#define OOT_HOUSE_DAMPE_ENTR  0x30d
#define OOT_SHOP_GORON_ENTR  0x37c
#define OOT_SHOP_ZORA_ENTR  0x380
#define OOT_HOUSE_LON_LON_ENTR  0x04f
#define OOT_SILO_ENTR  0x5d0
#define OOT_STABLES_ENTR  0x2f9
#define OOT_FAIRY_MAGIC_ENTR  0x315
#define OOT_FAIRY_MAGIC2_ENTR  0x4be
#define OOT_FAIRY_DIN_ENTR  0x578
#define OOT_FAIRY_FARORE_ENTR  0x371
#define OOT_FAIRY_NAYRU_ENTR  0x588
#define OOT_FAIRY_DEFENSE_ENTR  0x4c2
#define OOT_BOMBCHU_BOWLING_ENTR  0x507
#define OOT_TREASURE_GAME_ENTR  0x063
#define OOT_BOMBCHU_SHOP_ENTR  0x528
#define OOT_ALLEY_HOUSE_ENTR  0x43b
#define OOT_MARKET_BAZAAR_ENTR  0x52c
#define OOT_MARKET_POTION_ENTR  0x388
#define OOT_CHILD_ARCHERY_ENTR  0x16d
#define OOT_KAKARIKO_BAZAAR_ENTR  0x0b7
#define OOT_ADULT_ARCHERY_ENTR  0x03b
#define OOT_HOUSE_LINK_ENTR  0x272
#define OOT_TEMPLE_OF_TIME_ENTR  0x053
#define OOT_WINDMILL_ENTR  0x453
#define OOT_SHOP_POTION_KAKARIKO_ENTR  0x384
#define OOT_SHOP_POTION_KAKARIKO_BACK_ENTR  0x3ec
#define OOT_KOKIRI_FOREST_FROM_MIDO_ENTR  0x443
#define OOT_KOKIRI_FOREST_FROM_SARIA_ENTR  0x447
#define OOT_KOKIRI_FOREST_FROM_TWINS_ENTR  0x33c
#define OOT_KOKIRI_FOREST_FROM_KNOW_IT_ALL_ENTR  0x26a
#define OOT_KOKIRI_FOREST_FROM_SHOP_ENTR  0x266
#define OOT_MARKET_ENTRANCE_FROM_POTS_ENTR  0x26e
#define OOT_LAKE_HYLIA_FROM_LABORATORY_ENTR  0x3cc
#define OOT_LAKE_HYLIA_FROM_FISHING_POND_ENTR  0x309
#define OOT_GERUDO_VALLEY_FROM_TENT_ENTR  0x3d0
#define OOT_KAKARIKO_FROM_CARPENTER_ENTR  0x349
#define OOT_KAKARIKO_FROM_SKULLTULA_ENTR  0x4ee
#define OOT_KAKARIKO_FROM_IMPA_ENTR  0x345
#define OOT_KAKARIKO_FROM_IMPA_BACK_ENTR  0x5dc
#define OOT_KAKARIKO_FROM_GRANNY_ENTR  0x34d
#define OOT_GRAVEYARD_FROM_DAMPE_ENTR  0x355
#define OOT_GORON_CITY_FROM_SHOP_ENTR  0x3fc
#define OOT_ZORA_DOMAIN_FROM_SHOP_ENTR  0x3c4
#define OOT_LON_LON_RANCH_FROM_HOUSE_ENTR  0x378
#define OOT_LON_LON_RANCH_FROM_STABLES_ENTR  0x42f
#define OOT_LON_LON_RANCH_FROM_SILO_ENTR  0x5d4
#define OOT_KOKIRI_FOREST_FROM_LINK_ENTR  0x211
#define OOT_TEMPLE_OF_TIME_ENTRYWAY_FROM_TEMPLE_ENTR  0x472
#define OOT_KAKARIKO_FROM_WINDMILL_ENTR  0x351
#define OOT_KAKARIKO_FROM_SHOP_POTION_ENTR  0x44b
#define OOT_KAKARIKO_FROM_SHOP_POTION_BACK_ENTR  0x4ff
#define OOT_DEATH_MOUNTAIN_FROM_FAIRY_ENTR  0x45b
#define OOT_DEATH_CRATER_FROM_FAIRY_ENTR  0x482
#define OOT_HYRULE_CASTLE_FROM_FAIRY_ENTR  0x340
#define OOT_ZORA_FOUNTAIN_FROM_FAIRY_ENTR  0x394
#define OOT_DESERT_COLOSSUS_FROM_FAIRY_ENTR  0x57c
#define OOT_MARKET_FROM_BOWLING_ENTR  0x3bc
#define OOT_MARKET_FROM_TREASURE_GAME_ENTR  0x1d5
#define OOT_MARKET_FROM_BOMBCHU_SHOP_ENTR  0x3c0
#define OOT_MARKET_FROM_ALLEY_HOUSE_ENTR  0x067
#define OOT_MARKET_FROM_BAZAAR_ENTR  0x3b8
#define OOT_MARKET_FROM_POTION_ENTR  0x2a2
#define OOT_MARKET_FROM_ARCHERY_ENTR  0x1cd
#define OOT_KAKARIKO_FROM_BAZAAR_ENTR  0x201
#define OOT_KAKARIKO_FROM_ARCHERY_ENTR  0x463
#define OOT_OUTSIDE_GANON_FROM_FAIRY_ENTR  0xf00
#define OOT_WARP_SONG_MEADOW_ENTR  0x600
#define OOT_WARP_SONG_CRATER_ENTR  0x4f6
#define OOT_WARP_SONG_LAKE_ENTR  0x604
#define OOT_WARP_SONG_GRAVE_ENTR  0x568
#define OOT_WARP_SONG_DESERT_ENTR  0x1f1
#define OOT_WARP_SONG_TEMPLE_ENTR  0x5f4
#define OOT_VILLAGE_OWL_ENTR  0x554
#define OOT_FIELD_OWL_ENTR  0x27e
#define OOT_WALLMASTER_FOREST_CORRIDOR_WEST_ENTR  0xf10
#define OOT_WALLMASTER_FOREST_CORRIDOR_EAST_ENTR  0xf11
#define OOT_WALLMASTER_SHADOW_ENTR  0xf12
#define OOT_WALLMASTER_SPIRIT_CHILD_RUPEES_ENTR  0xf13
#define OOT_WALLMASTER_SPIRIT_ADULT_CLIMB_ENTR  0xf14
#define OOT_WALLMASTER_SPIRIT_CHILD_SUN_ENTR  0xf15
#define OOT_WALLMASTER_SPIRIT_STATUE_ENTR  0xf16
#define OOT_WALLMASTER_BOTW_MAIN_ENTR  0xf17
#define OOT_WALLMASTER_BOTW_BASEMENT_ENTR  0xf18
#define OOT_WALLMASTER_BOTW_PIT_ENTR  0xf19
#define OOT_WALLMASTER_GTG_ENTR  0xf1a
#define OOT_WALLMASTER_GANON_SPIRIT_ENTR  0xf1b
#define OOT_WALLMASTER_GANON_LIGHT_ENTR  0xf1c
#define OOT_GROTTO_GENERIC_KOKIRI_FOREST_ENTR  0x1000
#define OOT_GROTTO_GENERIC_LOST_WOODS_ENTR  0x1001
#define OOT_GROTTO_GENERIC_KAKARIKO_ENTR  0x1002
#define OOT_GROTTO_GENERIC_DMT_ENTR  0x1003
#define OOT_GROTTO_GENERIC_DMC_ENTR  0x1004
#define OOT_GROTTO_GENERIC_RIVER_ENTR  0x1005
#define OOT_GROTTO_GENERIC_HF_SOUTHEAST_ENTR  0x1006
#define OOT_GROTTO_GENERIC_HF_OPEN_ENTR  0x1007
#define OOT_GROTTO_GENERIC_HF_MARKET_ENTR  0x1008
#define OOT_GROTTO_FAIRY_SFM_ENTR  0x1009
#define OOT_GROTTO_FAIRY_HF_ENTR  0x100a
#define OOT_GROTTO_FAIRY_RIVER_ENTR  0x100b
#define OOT_GROTTO_FAIRY_DOMAIN_ENTR  0x100c
#define OOT_GROTTO_FAIRY_FORTRESS_ENTR  0x100d
#define OOT_GROTTO_SCRUBS2_SFM_ENTR  0x100e
#define OOT_GROTTO_SCRUBS2_RIVER_ENTR  0x100f
#define OOT_GROTTO_SCRUBS2_VALLEY_ENTR  0x1010
#define OOT_GROTTO_SCRUBS2_COLOSSUS_ENTR  0x1011
#define OOT_GROTTO_SCRUBS3_RANCH_ENTR  0x1012
#define OOT_GROTTO_SCRUBS3_GORON_CITY_ENTR  0x1013
#define OOT_GROTTO_SCRUBS3_DMC_ENTR  0x1014
#define OOT_GROTTO_SCRUBS3_LAKE_ENTR  0x1015
#define OOT_GROTTO_SCRUB_UPGRADE_ENTR  0x5b0
#define OOT_GROTTO_SCRUB_HEART_PIECE_ENTR  0x59c
#define OOT_GROTTO_DEKU_THEATER_ENTR  0x5c4
#define OOT_GROTTO_WOLFOS_ENTR  0x5b4
#define OOT_GROTTO_TEKTITE_ENTR  0x5c0
#define OOT_GROTTO_FIELD_COW_ENTR  0x5a8
#define OOT_GROTTO_FIELD_TREE_ENTR  0x598
#define OOT_GROTTO_TRAIL_COW_ENTR  0x5fc
#define OOT_GROTTO_CASTLE_ENTR  0x5b8
#define OOT_GROTTO_REDEAD_ENTR  0x5a0
#define OOT_GROTTO_OCTOROK_ENTR  0x5ac
#define OOT_GRAVE_SHIELD_ENTR  0x04b
#define OOT_GRAVE_REDEAD_ENTR  0x31c
#define OOT_GRAVE_ROYAL_ENTR  0x02d
#define OOT_GRAVE_DAMPE_ENTR  0x44f
#define OOT_GROTTO_EXIT_GENERIC_KOKIRI_FOREST  0x1100
#define OOT_GROTTO_EXIT_GENERIC_LOST_WOODS  0x1101
#define OOT_GROTTO_EXIT_GENERIC_KAKARIKO  0x1102
#define OOT_GROTTO_EXIT_GENERIC_DMT  0x1103
#define OOT_GROTTO_EXIT_GENERIC_DMC  0x1104
#define OOT_GROTTO_EXIT_GENERIC_RIVER  0x1105
#define OOT_GROTTO_EXIT_GENERIC_HF_SOUTHEAST  0x1106
#define OOT_GROTTO_EXIT_GENERIC_HF_OPEN  0x1107
#define OOT_GROTTO_EXIT_GENERIC_HF_MARKET  0x1108
#define OOT_GROTTO_EXIT_FAIRY_SFM  0x1109
#define OOT_GROTTO_EXIT_FAIRY_HF  0x110a
#define OOT_GROTTO_EXIT_FAIRY_RIVER  0x110b
#define OOT_GROTTO_EXIT_FAIRY_DOMAIN  0x110c
#define OOT_GROTTO_EXIT_FAIRY_FORTRESS  0x110d
#define OOT_GROTTO_EXIT_SCRUBS2_SFM  0x110e
#define OOT_GROTTO_EXIT_SCRUBS2_RIVER  0x110f
#define OOT_GROTTO_EXIT_SCRUBS2_VALLEY  0x1110
#define OOT_GROTTO_EXIT_SCRUBS2_COLOSSUS  0x1111
#define OOT_GROTTO_EXIT_SCRUBS3_RANCH  0x1112
#define OOT_GROTTO_EXIT_SCRUBS3_GORON_CITY  0x1113
#define OOT_GROTTO_EXIT_SCRUBS3_DMC  0x1114
#define OOT_GROTTO_EXIT_SCRUBS3_LAKE  0x1115
#define OOT_GROTTO_EXIT_SCRUB_UPGRADE  0x1116
#define OOT_GROTTO_EXIT_SCRUB_HEART_PIECE  0x1117
#define OOT_GROTTO_EXIT_DEKU_THEATER  0x1118
#define OOT_GROTTO_EXIT_WOLFOS  0x1119
#define OOT_GROTTO_EXIT_TEKTITE  0x111a
#define OOT_GROTTO_EXIT_FIELD_COW  0x111b
#define OOT_GROTTO_EXIT_FIELD_TREE  0x111c
#define OOT_GROTTO_EXIT_TRAIL_COW  0x111d
#define OOT_GROTTO_EXIT_CASTLE  0x111e
#define OOT_GROTTO_EXIT_REDEAD  0x111f
#define OOT_GROTTO_EXIT_OCTOROK  0x1120
#define OOT_GRAVE_EXIT_SHIELD  0x35d
#define OOT_GRAVE_EXIT_REDEAD  0x361
#define OOT_GRAVE_EXIT_ROYAL  0x50b
#define OOT_GRAVE_EXIT_DAMPE  0x359
#define OOT_BOSS_GANON2_ENTR  0x517
#define OOT_GERUDO_FORTRESS_CAUGHT_NO_HOOK_ENTR  0x1a5
#define OOT_GERUDO_FORTRESS_CAUGHT_ENTR  0x5f8
#define OOT_CASTLE_STEALTH_ENTR  0x07a
#define OOT_CASTLE_STEALTH_FROM_COURTYARD_ENTR  0x296
#define OOT_CASTLE_COURTYARD_ENTR  0x400
#define OOT_CASTLE_CAUGHT_ENTR  0x47e
#define OOT_MARKET_FROM_MASK_SHOP_ENTR  0x1d1
#define OOT_SHOP_MASKS_ENTR  0x530
#define OOT_SAGES_CHAMBER_END_ENTR  0x06b
#define OOT_TEMPLE_OF_TIME_MASTER_SWORD_CS_ENTR  0x2ca
#define OOT_ZORA_RIVER_FROM_FIELD_WATER_ENTR  0x1d9
#define OOT_FIELD_FROM_ZORA_RIVER_WATER_ENTR  0x311
#define OOT_GROTTO_TYPE_GENERIC_ENTR  0x03f
#define OOT_GROTTO_TYPE_FAIRY_ENTR  0x36d
#define OOT_GROTTO_TYPE_SCRUB2_ENTR  0x5bc
#define OOT_GROTTO_TYPE_SCRUB3_ENTR  0x5a4
#define OOT_SHADOW_TEMPLE_FROM_LAIR_ENTR  0x2b2
#define OOT_INTERNAL_EXIT_GROTTO_ENTR  0x7fff
#define OOT_MARKET_FROM_BACK_ALLEY_TREASURE_ENTR 0x029e
#define OOT_MARKET_FROM_BACK_ALLEY_SHOOTING_ENTR 0x0262
#define OOT_BACK_ALLEY_TREASURE_FROM_MARKET_ENTR 0x029a
#define OOT_BACK_ALLEY_SHOOTING_FROM_MARKET_ENTR 0x0ad
#define OOT_DOG_LADY_FROM_BACK_ALLEY_ENTR 0x0398
#define OOT_BACK_ALLEY_FROM_DOG_LADY_ENTR 0x038c

#pragma endregion

const std::map<int, EntranceMetaInfo> OoTEntrances =
{
	{ OOT_SPAWN_CHILD, { OOT_SPAWN_CHILD, OOT_LINK_HOUSE, "Spawn Child", "Spawn Child", "", GameLayout::all } },
	{ OOT_SPAWN_ADULT, { OOT_SPAWN_ADULT, OOT_TEMPLE_OF_TIME, "Spawn Adult", "Spawn Adult", "", GameLayout::all } },
	{ OOT_BOSS_DEKU_TREE_ENTR, { OOT_BOSS_DEKU_TREE_ENTR, OOT_DEKU_TREE, "Deku Tree", "Gohma's Lair", "", GameLayout::all } },
	{ OOT_BOSS_DODONGO_CAVERN_ENTR, { OOT_BOSS_DODONGO_CAVERN_ENTR, OOT_DODONGO_CAVERN, "Dodongo Cavern", "King Dodongo's Lair", "", GameLayout::all } },
	{ OOT_BOSS_JABU_JABU_ENTR, { OOT_BOSS_JABU_JABU_ENTR, OOT_INSIDE_JABU_JABU, "Inside Jabu-Jabu", "Barinade's Lair", "", GameLayout::all } },
	{ OOT_BOSS_TEMPLE_FOREST_ENTR, { OOT_BOSS_TEMPLE_FOREST_ENTR, OOT_TEMPLE_FOREST, "Forest Temple", "Phantom Ganon's Lair", "", GameLayout::all } },
	{ OOT_BOSS_TEMPLE_FIRE_ENTR, { OOT_BOSS_TEMPLE_FIRE_ENTR, OOT_TEMPLE_FIRE, "Fire Temple", "Volvagia's Lair", "", GameLayout::all } },
	{ OOT_BOSS_TEMPLE_WATER_ENTR, { OOT_BOSS_TEMPLE_WATER_ENTR, OOT_TEMPLE_WATER, "Water Temple", "Morpha's Lair", "", GameLayout::all } },
	{ OOT_BOSS_TEMPLE_SHADOW_ENTR, { OOT_BOSS_TEMPLE_SHADOW_ENTR, OOT_TEMPLE_SHADOW, "Shadow Temple", "Bongo-Bongo's Lair", "", GameLayout::all } },
	{ OOT_BOSS_TEMPLE_SPIRIT_ENTR, { OOT_BOSS_TEMPLE_SPIRIT_ENTR, OOT_TEMPLE_SPIRIT, "Spirit Temple", "Twinrova's Lair", "", GameLayout::all } },
	{ OOT_DEKU_TREE_ENTR, { OOT_DEKU_TREE_ENTR, OOT_DEKU_TREE, "Kokiri Forest", "Deku Tree", "", GameLayout::all } },
	{ OOT_DODONGO_CAVERN_ENTR, { OOT_DODONGO_CAVERN_ENTR, OOT_DODONGO_CAVERN, "Death Mountain Trail", "Dodongo Cavern", "", GameLayout::all } },
	{ OOT_JABU_JABU_ENTR, { OOT_JABU_JABU_ENTR, OOT_INSIDE_JABU_JABU, "Zora Fountain", "Inside Jabu-Jabu", "", GameLayout::all } },
	{ OOT_TEMPLE_FOREST_ENTR, { OOT_TEMPLE_FOREST_ENTR, OOT_TEMPLE_FOREST, "Sacred Forest Meadow", "Forest Temple", "", GameLayout::all } },
	{ OOT_TEMPLE_FIRE_ENTR, { OOT_TEMPLE_FIRE_ENTR, OOT_TEMPLE_FIRE, "Death Mountain Crater", "Fire Temple", "", GameLayout::all } },
	{ OOT_TEMPLE_WATER_ENTR, { OOT_TEMPLE_WATER_ENTR, OOT_TEMPLE_WATER, "Lake Hylia", "Water Temple", "", GameLayout::all } },
	{ OOT_TEMPLE_SHADOW_ENTR, { OOT_TEMPLE_SHADOW_ENTR, OOT_TEMPLE_SHADOW, "Graveyard", "Shadow Temple", "", GameLayout::all } },
	{ OOT_TEMPLE_SPIRIT_ENTR, { OOT_TEMPLE_SPIRIT_ENTR, OOT_TEMPLE_SPIRIT, "Desert Colossus", "Spirit Temple", "", GameLayout::all } },
	{ OOT_BOTTOM_OF_THE_WELL_ENTR, { OOT_BOTTOM_OF_THE_WELL_ENTR, OOT_BOTTOM_OF_THE_WELL, "Kakariko", "Bottom of the Well", "", GameLayout::all } },
	{ OOT_ICE_CAVERN_ENTR, { OOT_ICE_CAVERN_ENTR, OOT_ICE_CAVERN, "Zora Fountain", "Ice Cavern", "", GameLayout::all } },
	{ OOT_GERUDO_TRAINING_GROUNDS_ENTR, { OOT_GERUDO_TRAINING_GROUNDS_ENTR, OOT_GERUDO_TRAINING_GROUND, "Gerudo Fortress", "Gerudo Training Ground", "", GameLayout::all } },
	{ OOT_GANON_CASTLE_ENTR, { OOT_GANON_CASTLE_ENTR, OOT_INSIDE_GANON_CASTLE, "Ganon Castle Exterior", "Inside Ganon Castle", "", GameLayout::all } },
	{ OOT_GANON_TOWER_ENTR, { OOT_GANON_TOWER_ENTR, OOT_GANON_TOWER, "Inside Ganon Castle", "Ganon Tower", "", GameLayout::all } },
	{ OOT_KOKIRI_FOREST_FROM_DEKU_TREE_ENTR, { OOT_KOKIRI_FOREST_FROM_DEKU_TREE_ENTR, OOT_KOKIRI_FOREST, "Deku Tree", "Kokiri Forest", "", GameLayout::all } },
	{ OOT_MOUNTAIN_TRAIL_FROM_DODONGO_CAVERN_ENTR, { OOT_MOUNTAIN_TRAIL_FROM_DODONGO_CAVERN_ENTR, OOT_DEATH_MOUNTAIN_TRAIL, "Dodongo Cavern", "Death Mountain Trail", "", GameLayout::all } },
	{ OOT_ZORA_FOUNTAIN_FROM_JABU_JABU_ENTR, { OOT_ZORA_FOUNTAIN_FROM_JABU_JABU_ENTR, OOT_ZORA_FOUNTAIN, "Jabu-Jabu", "Zora Fountain", "", GameLayout::all } },
	{ OOT_SACRED_MEADOW_FROM_TEMPLE_FOREST_ENTR, { OOT_SACRED_MEADOW_FROM_TEMPLE_FOREST_ENTR, OOT_SACRED_FOREST_MEADOW, "Forest Temple", "Sacred Forest Meadow", "", GameLayout::all } },
	{ OOT_DEATH_CRATER_FROM_TEMPLE_FIRE_ENTR, { OOT_DEATH_CRATER_FROM_TEMPLE_FIRE_ENTR, OOT_DEATH_MOUNTAIN_CRATER, "Fire Temple", "Death Mountain Crater", "", GameLayout::all } },
	{ OOT_LAKE_HYLIA_FROM_TEMPLE_WATER_ENTR, { OOT_LAKE_HYLIA_FROM_TEMPLE_WATER_ENTR, OOT_LAKE_HYLIA, "Water Temple", "Lake Hylia", "", GameLayout::all } },
	{ OOT_GRAVEYARD_FROM_TEMPLE_SHADOW_ENTR, { OOT_GRAVEYARD_FROM_TEMPLE_SHADOW_ENTR, OOT_GRAVEYARD, "Shadow Temple", "Graveyard", "", GameLayout::all } },
	{ OOT_DESERT_COLOSSUS_FROM_TEMPLE_SPIRIT_ENTR, { OOT_DESERT_COLOSSUS_FROM_TEMPLE_SPIRIT_ENTR, OOT_DESERT_COLOSSUS, "Spirit Temple", "Desert Colossus", "", GameLayout::all } },
	{ OOT_KAKARIKO_FROM_BOTTOM_OF_THE_WELL_ENTR, { OOT_KAKARIKO_FROM_BOTTOM_OF_THE_WELL_ENTR, OOT_KAKARIKO_VILLAGE, "Bottom of the Well", "Kakariko", "", GameLayout::all } },
	{ OOT_ZORA_FOUNTAIN_FROM_ICE_CAVERN_ENTR, { OOT_ZORA_FOUNTAIN_FROM_ICE_CAVERN_ENTR, OOT_ZORA_FOUNTAIN, "Ice Cavern", "Zora Fountain", "", GameLayout::all } },
	{ OOT_GERUDO_FORTRESS_FROM_GERUDO_TRAINING_ENTR, { OOT_GERUDO_FORTRESS_FROM_GERUDO_TRAINING_ENTR, OOT_GERUDO_FORTRESS, "Gerudo Training Ground", "Gerudo Fortress", "", GameLayout::all } },
	{ OOT_GANON_CASTLE_EXTERIOR_FROM_CASTLE_ENTR, { OOT_GANON_CASTLE_EXTERIOR_FROM_CASTLE_ENTR, OOT_GANON_CASTLE_EXTERIOR, "Ganon Castle", "Ganon Castle Exterior", "", GameLayout::all } },
	{ OOT_GANON_CASTLE_FROM_TOWER_ENTR, { OOT_GANON_CASTLE_FROM_TOWER_ENTR, OOT_INSIDE_GANON_CASTLE, "Ganon Tower", "Inside Ganon Castle", "", GameLayout::all } },
	{ OOT_LOST_WOODS_BRIDGE_FROM_FIELD_ENTR, { OOT_LOST_WOODS_BRIDGE_FROM_FIELD_ENTR, OOT_LOST_WOODS, "Hyrule Field", "Lost Woods Bridge", "", GameLayout::all } },
	{ OOT_ZORA_RIVER_FROM_FIELD_ENTR, { OOT_ZORA_RIVER_FROM_FIELD_ENTR, OOT_ZORA_RIVER, "Hyrule Field", "Zora River", "", GameLayout::all } },
	{ OOT_KAKARIKO_FROM_FIELD_ENTR, { OOT_KAKARIKO_FROM_FIELD_ENTR, OOT_KAKARIKO_VILLAGE, "Hyrule Field", "Kakariko", "", GameLayout::all } },
	{ OOT_LON_LON_RANCH_FROM_FIELD_ENTR, { OOT_LON_LON_RANCH_FROM_FIELD_ENTR, OOT_LON_LON_RANCH, "Hyrule Field", "Lon Lon's Ranch", "", GameLayout::all } },
	{ OOT_LAKE_HYLIA_FROM_FIELD_ENTR, { OOT_LAKE_HYLIA_FROM_FIELD_ENTR, OOT_LAKE_HYLIA, "Hyrule Field", "Lake Hylia", "", GameLayout::all } },
	{ OOT_GERUDO_FORTRESS_FROM_VALLEY_ENTR, { OOT_GERUDO_FORTRESS_FROM_VALLEY_ENTR, OOT_GERUDO_FORTRESS, "Gerudo Valley", "Gerudo Fortress", "", GameLayout::all } },
	{ OOT_DEATH_MOUNTAIN_FROM_KAKARIKO_ENTR, { OOT_DEATH_MOUNTAIN_FROM_KAKARIKO_ENTR, OOT_DEATH_MOUNTAIN_TRAIL, "Kakariko", "Death Mountain Trail", "", GameLayout::all } },
	{ OOT_GERUDO_VALLEY_FROM_FIELD_ENTR, { OOT_GERUDO_VALLEY_FROM_FIELD_ENTR, OOT_GERUDO_VALLEY, "Hyrule Field", "Gerudo Valley", "", GameLayout::all } },
	{ OOT_MARKET_ENTRANCE_FROM_FIELD_ENTR, { OOT_MARKET_ENTRANCE_FROM_FIELD_ENTR, OOT_MARKET, "Hyrule Field", "Market Entrance", "", GameLayout::all } },
	{ OOT_ZORA_RIVER_FROM_LOST_WOODS_ENTR, { OOT_ZORA_RIVER_FROM_LOST_WOODS_ENTR, OOT_ZORA_RIVER, "Lost Woods", "Zora River", "", GameLayout::all } },
	{ OOT_GORON_CITY_FROM_LOST_WOODS_ENTR, { OOT_GORON_CITY_FROM_LOST_WOODS_ENTR, OOT_GORON_CITY, "Lost Woods", "Goron City", "", GameLayout::all } },
	{ OOT_LAKE_HYLIA_FROM_ZORA_DOMAIN_ENTR, { OOT_LAKE_HYLIA_FROM_ZORA_DOMAIN_ENTR, OOT_LAKE_HYLIA, "Zora Domain's Shortcut", "Lake Hylia", "", GameLayout::all } },
	{ OOT_FIELD_FROM_LOST_WOODS_BRIDGE_ENTR, { OOT_FIELD_FROM_LOST_WOODS_BRIDGE_ENTR, OOT_HYRULE_FIELD, "Lost Woods Bridge", "Hyrule Field", "", GameLayout::all } },
	{ OOT_FIELD_FROM_ZORA_RIVER_ENTR, { OOT_FIELD_FROM_ZORA_RIVER_ENTR, OOT_HYRULE_FIELD, "Zora River", "Hyrule Field", "", GameLayout::all } },
	{ OOT_FIELD_FROM_KAKARIKO_ENTR, { OOT_FIELD_FROM_KAKARIKO_ENTR, OOT_HYRULE_FIELD, "Kakariko", "Hyrule Field", "", GameLayout::all } },
	{ OOT_FIELD_FROM_LON_LON_RANCH_ENTR, { OOT_FIELD_FROM_LON_LON_RANCH_ENTR, OOT_HYRULE_FIELD, "Lon Lon's Ranch", "Hyrule Field", "", GameLayout::all } },
	{ OOT_FIELD_FROM_LAKE_HYLIA_ENTR, { OOT_FIELD_FROM_LAKE_HYLIA_ENTR, OOT_HYRULE_FIELD, "Lake Hylia", "Hyrule Field", "", GameLayout::all } },
	{ OOT_FIELD_FROM_GERUDO_VALLEY_ENTR, { OOT_FIELD_FROM_GERUDO_VALLEY_ENTR, OOT_HYRULE_FIELD, "Gerudo Valley", "Hyrule Field", "", GameLayout::all } },
	{ OOT_VALLEY_FROM_GERUDO_FORTRESS_ENTR, { OOT_VALLEY_FROM_GERUDO_FORTRESS_ENTR, OOT_GERUDO_VALLEY, "Gerudo Fortress", "Gerudo Valley", "", GameLayout::all } },
	{ OOT_KAKARIKO_FROM_DEATH_MOUNTAIN_ENTR, { OOT_KAKARIKO_FROM_DEATH_MOUNTAIN_ENTR, OOT_KAKARIKO_VILLAGE, "Death Mountain Trail", "Kakariko", "", GameLayout::all } },
	{ OOT_FIELD_FROM_MARKET_ENTRANCE_ENTR, { OOT_FIELD_FROM_MARKET_ENTRANCE_ENTR, OOT_HYRULE_FIELD, "Market Entrance", "Hyrule Field", "", GameLayout::all } },
	{ OOT_LOST_WOODS_FROM_ZORA_RIVER_ENTR, { OOT_LOST_WOODS_FROM_ZORA_RIVER_ENTR, OOT_LOST_WOODS, "Zora River", "Lost Woods", "", GameLayout::all } },
	{ OOT_LOST_WOODS_FROM_GORON_CITY_ENTR, { OOT_LOST_WOODS_FROM_GORON_CITY_ENTR, OOT_LOST_WOODS, "Goron City", "Lost Woods", "", GameLayout::all } },
	{ OOT_ZORA_DOMAIN_FROM_LAKE_HYLIA_ENTR, { OOT_ZORA_DOMAIN_FROM_LAKE_HYLIA_ENTR, OOT_ZORA_DOMAIN, "Lake Hylia's Shortcut", "Zora Domain", "", GameLayout::all } },
	{ OOT_SACRED_FOREST_MEADOW_ENTR, { OOT_SACRED_FOREST_MEADOW_ENTR, OOT_SACRED_FOREST_MEADOW, "Lost Woods", "Sacred Meadow", "", GameLayout::all } },
	{ OOT_LOST_WOODS_FROM_MEADOW_ENTR, { OOT_LOST_WOODS_FROM_MEADOW_ENTR, OOT_LOST_WOODS, "Sacred Forest Meadow", "Lost Woods Woods", "", GameLayout::all } },
	{ OOT_GORON_CITY_ENTR, { OOT_GORON_CITY_ENTR, OOT_GORON_CITY, "Death Mountain Trail", "Goron City", "", GameLayout::all } },
	{ OOT_DEATH_MOUNTAIN_FROM_GORON_CITY_ENTR, { OOT_DEATH_MOUNTAIN_FROM_GORON_CITY_ENTR, OOT_DEATH_MOUNTAIN_TRAIL, "Goron City", "Death Mountain Trail", "", GameLayout::all } },
	{ OOT_ZORA_DOMAIN_ENTR, { OOT_ZORA_DOMAIN_ENTR, OOT_ZORA_DOMAIN, "Zora River", "Zora Domain", "", GameLayout::all } },
	{ OOT_RIVER_FROM_DOMAIN_ENTR, { OOT_RIVER_FROM_DOMAIN_ENTR, OOT_ZORA_RIVER, "Zora Domain", "Zora River", "", GameLayout::all } },
	{ OOT_FOUNTAIN_ZORA_ENTR, { OOT_FOUNTAIN_ZORA_ENTR, OOT_ZORA_FOUNTAIN, "Zora Domain", "Zora Fountain", "", GameLayout::all } },
	{ OOT_DOMAIN_FROM_FOUNTAIN_ENTR, { OOT_DOMAIN_FROM_FOUNTAIN_ENTR, OOT_ZORA_DOMAIN, "Zora Fountain", "Zora Domain", "", GameLayout::all } },
	{ OOT_CRATER_FROM_GORON_CITY_ENTR, { OOT_CRATER_FROM_GORON_CITY_ENTR, OOT_DEATH_MOUNTAIN_CRATER, "Goron City", "Death Mountain Crater", "", GameLayout::all } },
	{ OOT_GORON_CITY_FROM_CRATER_ENTR, { OOT_GORON_CITY_FROM_CRATER_ENTR, OOT_GORON_CITY, "Death Mountain Crater", "Goron City", "", GameLayout::all } },
	{ OOT_DEATH_MOUNTAIN_CRATER_ENTR, { OOT_DEATH_MOUNTAIN_CRATER_ENTR, OOT_DEATH_MOUNTAIN_CRATER, "Death Mountain Trail", "Death Mountain Crater", "", GameLayout::all } },
	{ OOT_TRAIL_SUMMIT_FROM_CRATER_ENTR, { OOT_TRAIL_SUMMIT_FROM_CRATER_ENTR, OOT_DEATH_MOUNTAIN_TRAIL, "Death Mountain Crater", "Death Mountain Trail", "", GameLayout::all } },
	{ OOT_LOST_WOODS_FROM_KOKIRI_FOREST_ENTR, { OOT_LOST_WOODS_FROM_KOKIRI_FOREST_ENTR, OOT_LOST_WOODS, "Kokiri Forest", "Lost Woods", "", GameLayout::all } },
	{ OOT_KOKIRI_FOREST_FROM_LOST_WOODS_ENTR, { OOT_KOKIRI_FOREST_FROM_LOST_WOODS_ENTR, OOT_KOKIRI_FOREST, "Lost Woods", "Kokiri Forest", "", GameLayout::all } },
	{ OOT_FOREST_FROM_LOST_WOODS_BRIDGE_ENTR, { OOT_FOREST_FROM_LOST_WOODS_BRIDGE_ENTR, OOT_LOST_WOODS, "Lost Woods Bridge", "Kokiri Forest", "", GameLayout::all } },
	{ OOT_LOST_WOODS_BRIDGE_FROM_FOREST_ENTR, { OOT_LOST_WOODS_BRIDGE_FROM_FOREST_ENTR, OOT_LOST_WOODS, "Kokiri Forest", "Lost Woods Bridge", "", GameLayout::all } },
	{ OOT_GRAVEYARD_ENTR, { OOT_GRAVEYARD_ENTR, OOT_GRAVEYARD, "Kakariko", "Graveyard", "", GameLayout::all } },
	{ OOT_KAKARIKO_FROM_GRAVEYARD_ENTR, { OOT_KAKARIKO_FROM_GRAVEYARD_ENTR, OOT_KAKARIKO_VILLAGE, "Graveyard", "Kakariko", "", GameLayout::all } },
	{ OOT_WASTELAND_ENTR, { OOT_WASTELAND_ENTR, OOT_HAUNTED_WASTELAND, "Gerudo Fortress", "Haunted Wasteland", "", GameLayout::all } },
	{ OOT_FORTRESS_FROM_WASTELAND_ENTR, { OOT_FORTRESS_FROM_WASTELAND_ENTR, OOT_GERUDO_FORTRESS, "Haunted Wasteland", "Gerudo Fortress", "", GameLayout::all } },
	{ OOT_COLOSSUS_ENTR, { OOT_COLOSSUS_ENTR, OOT_DESERT_COLOSSUS, "Haunted Wasteland", "Desert Colossus", "", GameLayout::all } },
	{ OOT_WASTELAND_FROM_COLOSSUS_ENTR, { OOT_WASTELAND_FROM_COLOSSUS_ENTR, OOT_HAUNTED_WASTELAND, "Desert Colossus", "Haunted Wasteland", "", GameLayout::all } },
	{ OOT_MARKET_FROM_MARKET_ENTRANCE_ENTR, { OOT_MARKET_FROM_MARKET_ENTRANCE_ENTR, OOT_MARKET, "Market Entrance", "Market", "", GameLayout::all } },
	{ OOT_MARKET_ENTRANCE_FROM_MARKET_ENTR, { OOT_MARKET_ENTRANCE_FROM_MARKET_ENTR, OOT_MARKET_ENTRANCE, "Market", "Market Entrance", "", GameLayout::all } },
	{ OOT_HYRULE_CASTLE_ENTR, { OOT_HYRULE_CASTLE_ENTR, OOT_HYRULE_CASTLE, "Market Entrance", "Hyrule Castle", "", GameLayout::all } },
	{ OOT_MARKET_FROM_CASTLE_ENTR, { OOT_MARKET_FROM_CASTLE_ENTR, OOT_MARKET, "Hyrule Castle", "Market", "", GameLayout::all } },
	{ OOT_MARKET_FROM_TEMPLE_OF_TIME_ENTRYWAY_ENTR, { OOT_MARKET_FROM_TEMPLE_OF_TIME_ENTRYWAY_ENTR, OOT_MARKET, "Temple of Time Entryway Entrance", "Market", "", GameLayout::all } },
	{ OOT_TEMPLE_OF_TIME_ENTRYWAY_FROM_MARKET_ENTR, { OOT_TEMPLE_OF_TIME_ENTRYWAY_FROM_MARKET_ENTR, OOT_TEMPLE_OF_TIME_ENTRYWAY, "Market", "Temple of Time Entryway", "", GameLayout::all } },
	{ OOT_LAKE_HYLIA_FROM_VALLEY_ENTR, { OOT_LAKE_HYLIA_FROM_VALLEY_ENTR, OOT_LAKE_HYLIA, "Gerudo Valley Waterfalls", "Lake Hylia", "", GameLayout::all } },
	{ OOT_LOST_WOODS_FROM_LOST_WOODS_NORTH_ENTR, { OOT_LOST_WOODS_FROM_LOST_WOODS_NORTH_ENTR, OOT_LOST_WOODS, "North Wrong Exit", "Lost Woods", "", GameLayout::all } },
	{ OOT_LOST_WOODS_FROM_LOST_WOODS_EAST_ENTR, { OOT_LOST_WOODS_FROM_LOST_WOODS_EAST_ENTR, OOT_LOST_WOODS, "East Wrong Exit ", "Lost Woods", "", GameLayout::all } },
	{ OOT_LOST_WOODS_FROM_LOST_WOODS_SOUTH_ENTR, { OOT_LOST_WOODS_FROM_LOST_WOODS_SOUTH_ENTR, OOT_LOST_WOODS, "South Wrong Exit", "Lost Woods", "", GameLayout::all } },
	{ OOT_LOST_WOODS_FROM_LOST_WOODS_WEST_ENTR, { OOT_LOST_WOODS_FROM_LOST_WOODS_WEST_ENTR, OOT_LOST_WOODS, "West Wrong Exit", "Lost Woods", "", GameLayout::all } },
	{ OOT_HOUSE_MIDO_ENTR, { OOT_HOUSE_MIDO_ENTR, OOT_KOKIRI_MIDO, "Kokiri Forest", "Mido's House", "", GameLayout::all } },
	{ OOT_HOUSE_SARIA_ENTR, { OOT_HOUSE_SARIA_ENTR, OOT_KOKIRI_SARIA, "Kokiri Forest", "Saria's House", "", GameLayout::all } },
	{ OOT_HOUSE_TWINS_ENTR, { OOT_HOUSE_TWINS_ENTR, OOT_KOKIRI_TWINS, "Kokiri Forest", "Twin's House", "", GameLayout::all } },
	{ OOT_HOUSE_KNOW_IT_ALL_ENTR, { OOT_HOUSE_KNOW_IT_ALL_ENTR, OOT_KOKIRI_KNOW_IT_ALL, "Kokiri Forest", "Know-It-All Brothers", "", GameLayout::all } },
	{ OOT_KOKIRI_SHOP_ENTR, { OOT_KOKIRI_SHOP_ENTR, OOT_KOKIRI_SHOP, "Kokiri Forest", "Kokiri Shop", "", GameLayout::all } },
	{ OOT_HOUSE_POTS_ENTR, { OOT_HOUSE_POTS_ENTR, OOT_GUARD_HOUSE, "Market Entrance", "Pot House", "", GameLayout::all } },
	{ OOT_LABORATORY_ENTR, { OOT_LABORATORY_ENTR, OOT_LABORATORY, "Lake Hylia", "Laboratory (OoT)", "", GameLayout::all } },
	{ OOT_FISHING_POND_ENTR, { OOT_FISHING_POND_ENTR, OOT_FISHING_POND, "Lake Hylia", "Fishing Pond", "", GameLayout::all } },
	{ OOT_VALLEY_TENT_ENTR, { OOT_VALLEY_TENT_ENTR, OOT_CARPENTER_TENT, "Gerudo Valley", "Carpenter's Tent", "", GameLayout::all } },
	{ OOT_HOUSE_CARPENTER_ENTR, { OOT_HOUSE_CARPENTER_ENTR, OOT_CARPENTER_BOSS_HOUSE, "Kakariko", "Carpenter's Boss House", "", GameLayout::all } },
	{ OOT_HOUSE_SKULLTULA_ENTR, { OOT_HOUSE_SKULLTULA_ENTR, OOT_HOUSE_OF_SKULLTULA, "Kakariko", "House of Skulltula", "", GameLayout::all } },
	{ OOT_HOUSE_IMPA_ENTR, { OOT_HOUSE_IMPA_ENTR, OOT_IMPA_HOUSE, "Kakariko", "Impa's House", "", GameLayout::all } },
	{ OOT_HOUSE_IMPA_BACK_ENTR, { OOT_HOUSE_IMPA_BACK_ENTR, OOT_IMPA_HOUSE, "Kakariko", "Impa's House Back", "", GameLayout::all } },
	{ OOT_SHOP_GRANNY_ENTR, { OOT_SHOP_GRANNY_ENTR, OOT_GRANNY_POTION_SHOP, "Kakariko", "Granny Potion Shop", "", GameLayout::all } },
	{ OOT_HOUSE_DAMPE_ENTR, { OOT_HOUSE_DAMPE_ENTR, OOT_DAMPE_HOUSE, "Graveyard", "Dampe's House", "", GameLayout::all } },
	{ OOT_SHOP_GORON_ENTR, { OOT_SHOP_GORON_ENTR, OOT_GORON_SHOP, "Goron City", "Goron Shop (OoT)", "", GameLayout::all } },
	{ OOT_SHOP_ZORA_ENTR, { OOT_SHOP_ZORA_ENTR, OOT_ZORA_SHOP, "Zora Domain", "Zora Shop (OoT)", "", GameLayout::all } },
	{ OOT_HOUSE_LON_LON_ENTR, { OOT_HOUSE_LON_LON_ENTR, OOT_RANCH_HOUSE_SILO, "Lon Lon Ranch", "Lon Lon Ranch House", "", GameLayout::all } },
	{ OOT_SILO_ENTR, { OOT_SILO_ENTR, OOT_SILO, "Lon Lon Ranch", "Silo", "", GameLayout::all } },
	{ OOT_STABLES_ENTR, { OOT_STABLES_ENTR, OOT_STABLE, "Lon Lon Ranch", "Stables (OoT)", "", GameLayout::all } },
	{ OOT_FAIRY_MAGIC_ENTR, { OOT_FAIRY_MAGIC_ENTR, OOT_GREAT_FAIRY_MAGIC, "Death Mountain Trail", "Magic Upgrade Fountain (OoT)", "", GameLayout::all } },
	{ OOT_FAIRY_MAGIC2_ENTR, { OOT_FAIRY_MAGIC2_ENTR, OOT_GREAT_FAIRY_MAGIC2, "Death Mountain Crater", "Large Magic Upgrade Fountain (OoT)", "", GameLayout::all } },
	{ OOT_FAIRY_DIN_ENTR, { OOT_FAIRY_DIN_ENTR, OOT_GREAT_FAIRY_CASTLE, "Hyrule Castle", "Din's Fire Fountain", "", GameLayout::all } },
	{ OOT_FAIRY_FARORE_ENTR, { OOT_FAIRY_FARORE_ENTR, OOT_GREAT_FAIRY_FARORE, "Zora Fountain", "Farore's Wind Fountain", "", GameLayout::all } },
	{ OOT_FAIRY_NAYRU_ENTR, { OOT_FAIRY_NAYRU_ENTR, OOT_GREAT_FAIRY_NAYRU, "Desert Colossus", "Nayru's Love Fountain", "", GameLayout::all } },
	{ OOT_FAIRY_DEFENSE_ENTR, { OOT_FAIRY_DEFENSE_ENTR, OOT_GREAT_FAIRY_CASTLE, "Ganon Castle Exterior", "Defense Upgrade Fountain (OoT)", "", GameLayout::all } },
	{ OOT_BOMBCHU_BOWLING_ENTR, { OOT_BOMBCHU_BOWLING_ENTR, OOT_BOMBCHU_BOWLING_ALLEY, "Market", "Bombchu Bowling", "", GameLayout::all } },
	{ OOT_TREASURE_GAME_ENTR, { OOT_TREASURE_GAME_ENTR, OOT_TREASURE_SHOP, "Market", "Treasure Game (OoT)", "", GameLayout::all } },
	{ OOT_BOMBCHU_SHOP_ENTR, { OOT_BOMBCHU_SHOP_ENTR, OOT_BOMBCHU_SHOP, "Back Alley", "Bombchu Shop", "", GameLayout::all } },
	{ OOT_ALLEY_HOUSE_ENTR, { OOT_ALLEY_HOUSE_ENTR, OOT_BACK_ALLEY_HOUSE2, "Back Alley", "Alley House", "", GameLayout::all } },
	{ OOT_MARKET_BAZAAR_ENTR, { OOT_MARKET_BAZAAR_ENTR, OOT_MARKET_BAZAAR, "Market", "Market Bazaar", "", GameLayout::all } },
	{ OOT_MARKET_POTION_ENTR, { OOT_MARKET_POTION_ENTR, OOT_MARKET_POTION_SHOP, "Market", "Market Potion Shop", "", GameLayout::all } },
	{ OOT_CHILD_ARCHERY_ENTR, { OOT_CHILD_ARCHERY_ENTR, OOT_MARKET_SHOOTING, "Market", "Market Shooting", "", GameLayout::all } },
	{ OOT_KAKARIKO_BAZAAR_ENTR, { OOT_KAKARIKO_BAZAAR_ENTR, OOT_KAKARIKO_BAZAAR, "Kakariko", "Kakariko Bazaar", "", GameLayout::all } },
	{ OOT_ADULT_ARCHERY_ENTR, { OOT_ADULT_ARCHERY_ENTR, OOT_KAKARIKO_SHOOTING, "Kakariko", "Kakariko Shooting", "", GameLayout::all } },
	{ OOT_HOUSE_LINK_ENTR, { OOT_HOUSE_LINK_ENTR, OOT_LINK_HOUSE, "Kokiri Forest", "Link's House", "", GameLayout::all } },
	{ OOT_TEMPLE_OF_TIME_ENTR, { OOT_TEMPLE_OF_TIME_ENTR, OOT_TEMPLE_OF_TIME, "Temple of Time Entryway", "Temple of Time", "", GameLayout::all } },
	{ OOT_WINDMILL_ENTR, { OOT_WINDMILL_ENTR, OOT_KAKARIKO_VILLAGE, "Kakariko", "Windmill", "", GameLayout::all } },
	{ OOT_SHOP_POTION_KAKARIKO_ENTR, { OOT_SHOP_POTION_KAKARIKO_ENTR, OOT_KAKARIKO_VILLAGE, "Kakariko", "Kakariko Potion Shop", "", GameLayout::all } },
	{ OOT_SHOP_POTION_KAKARIKO_BACK_ENTR, { OOT_SHOP_POTION_KAKARIKO_BACK_ENTR, OOT_KAKARIKO_VILLAGE, "Kakariko", "Kakariko Potion Shop Back", "", GameLayout::all } },
	{ OOT_KOKIRI_FOREST_FROM_MIDO_ENTR, { OOT_KOKIRI_FOREST_FROM_MIDO_ENTR, OOT_KOKIRI_FOREST, "Mido's House", "Kokiri Forest", "", GameLayout::all } },
	{ OOT_KOKIRI_FOREST_FROM_SARIA_ENTR, { OOT_KOKIRI_FOREST_FROM_SARIA_ENTR, OOT_KOKIRI_FOREST, "Saria's House", "Kokiri Forest", "", GameLayout::all } },
	{ OOT_KOKIRI_FOREST_FROM_TWINS_ENTR, { OOT_KOKIRI_FOREST_FROM_TWINS_ENTR, OOT_KOKIRI_FOREST, "Twin's House", "Kokiri Forest", "", GameLayout::all } },
	{ OOT_KOKIRI_FOREST_FROM_KNOW_IT_ALL_ENTR, { OOT_KOKIRI_FOREST_FROM_KNOW_IT_ALL_ENTR, OOT_KOKIRI_FOREST, "Know-It-All Brothers", "Kokiri Forest", "", GameLayout::all } },
	{ OOT_KOKIRI_FOREST_FROM_SHOP_ENTR, { OOT_KOKIRI_FOREST_FROM_SHOP_ENTR, OOT_KOKIRI_FOREST, "Kokiri Shop", "Kokiri Forest", "", GameLayout::all } },
	{ OOT_MARKET_ENTRANCE_FROM_POTS_ENTR, { OOT_MARKET_ENTRANCE_FROM_POTS_ENTR, OOT_MARKET_ENTRANCE, "Pot House", "Market Entrance Entrance", "", GameLayout::all } },
	{ OOT_LAKE_HYLIA_FROM_LABORATORY_ENTR, { OOT_LAKE_HYLIA_FROM_LABORATORY_ENTR, OOT_LAKE_HYLIA, "Laboratory (OoT)", "Lake Hylia", "", GameLayout::all } },
	{ OOT_LAKE_HYLIA_FROM_FISHING_POND_ENTR, { OOT_LAKE_HYLIA_FROM_FISHING_POND_ENTR, OOT_LAKE_HYLIA, "Fishing Pond", "Lake Hylia", "", GameLayout::all } },
	{ OOT_GERUDO_VALLEY_FROM_TENT_ENTR, { OOT_GERUDO_VALLEY_FROM_TENT_ENTR, OOT_GERUDO_VALLEY, "Gerudo Valley", "Carpenter's Tent", "", GameLayout::all } },
	{ OOT_KAKARIKO_FROM_CARPENTER_ENTR, { OOT_KAKARIKO_FROM_CARPENTER_ENTR, OOT_KAKARIKO_VILLAGE, "Carpenter's Boss House", "Kakariko", "", GameLayout::all } },
	{ OOT_KAKARIKO_FROM_SKULLTULA_ENTR, { OOT_KAKARIKO_FROM_SKULLTULA_ENTR, OOT_KAKARIKO_VILLAGE, "House of Skulltula", "Kakariko", "", GameLayout::all } },
	{ OOT_KAKARIKO_FROM_IMPA_ENTR, { OOT_KAKARIKO_FROM_IMPA_ENTR, OOT_KAKARIKO_VILLAGE, "Impa's House", "Kakariko", "", GameLayout::all } },
	{ OOT_KAKARIKO_FROM_IMPA_BACK_ENTR, { OOT_KAKARIKO_FROM_IMPA_BACK_ENTR, OOT_KAKARIKO_VILLAGE, "Impa's House Back", "Kakariko", "", GameLayout::all } },
	{ OOT_KAKARIKO_FROM_GRANNY_ENTR, { OOT_KAKARIKO_FROM_GRANNY_ENTR, OOT_KAKARIKO_VILLAGE, "Granny Potion Shop", "Kakariko", "", GameLayout::all } },
	{ OOT_GRAVEYARD_FROM_DAMPE_ENTR, { OOT_GRAVEYARD_FROM_DAMPE_ENTR, OOT_GRAVEYARD, "Dampe's House", "Graveyard", "", GameLayout::all } },
	{ OOT_GORON_CITY_FROM_SHOP_ENTR, { OOT_GORON_CITY_FROM_SHOP_ENTR, OOT_GORON_CITY, "Goron Shop (OoT)", "Goron City", "", GameLayout::all } },
	{ OOT_ZORA_DOMAIN_FROM_SHOP_ENTR, { OOT_ZORA_DOMAIN_FROM_SHOP_ENTR, OOT_ZORA_DOMAIN, "Zora Shop (OoT)", "Zora Domain", "", GameLayout::all } },
	{ OOT_LON_LON_RANCH_FROM_HOUSE_ENTR, { OOT_LON_LON_RANCH_FROM_HOUSE_ENTR, OOT_LON_LON_RANCH, "Lon Lon Ranch House", "Lon Lon Ranch", "", GameLayout::all } },
	{ OOT_LON_LON_RANCH_FROM_STABLES_ENTR, { OOT_LON_LON_RANCH_FROM_STABLES_ENTR, OOT_LON_LON_RANCH, "Silo", "Lon Lon Ranch", "", GameLayout::all } },
	{ OOT_LON_LON_RANCH_FROM_SILO_ENTR, { OOT_LON_LON_RANCH_FROM_SILO_ENTR, OOT_LON_LON_RANCH, "Stables (OoT)", "Lon Lon Ranch", "", GameLayout::all } },
	{ OOT_KOKIRI_FOREST_FROM_LINK_ENTR, { OOT_KOKIRI_FOREST_FROM_LINK_ENTR, OOT_KOKIRI_FOREST, "Link's House", "Kokiri Forest ", "", GameLayout::all } },
	{ OOT_TEMPLE_OF_TIME_ENTRYWAY_FROM_TEMPLE_ENTR, { OOT_TEMPLE_OF_TIME_ENTRYWAY_FROM_TEMPLE_ENTR, OOT_TEMPLE_OF_TIME_ENTRYWAY, "Temple Of Time", "Temple of Time Entryway", "", GameLayout::all } },
	{ OOT_KAKARIKO_FROM_WINDMILL_ENTR, { OOT_KAKARIKO_FROM_WINDMILL_ENTR, OOT_WINDMILL, "Windmill", "Kakariko", "", GameLayout::all } },
	{ OOT_KAKARIKO_FROM_SHOP_POTION_ENTR, { OOT_KAKARIKO_FROM_SHOP_POTION_ENTR, OOT_KAKARIKO_POTION_SHOP, "Kakariko Potion Shop", "Kakariko", "", GameLayout::all } },
	{ OOT_KAKARIKO_FROM_SHOP_POTION_BACK_ENTR, { OOT_KAKARIKO_FROM_SHOP_POTION_BACK_ENTR, OOT_KAKARIKO_POTION_SHOP, "Kakariko Potion Shop Back", "Kakariko", "", GameLayout::all } },
	{ OOT_DEATH_MOUNTAIN_FROM_FAIRY_ENTR, { OOT_DEATH_MOUNTAIN_FROM_FAIRY_ENTR, OOT_DEATH_MOUNTAIN_TRAIL, "Magic Upgrade Fountain (OoT)", "Death Mountain Trail", "", GameLayout::all } },
	{ OOT_DEATH_CRATER_FROM_FAIRY_ENTR, { OOT_DEATH_CRATER_FROM_FAIRY_ENTR, OOT_DEATH_MOUNTAIN_CRATER, "Large Magic Upgrade Fountain (OoT)", "Death Mountain Crater", "", GameLayout::all } },
	{ OOT_HYRULE_CASTLE_FROM_FAIRY_ENTR, { OOT_HYRULE_CASTLE_FROM_FAIRY_ENTR, OOT_HYRULE_CASTLE, "Din's Fire Fountain", "Hyrule Castle", "", GameLayout::all } },
	{ OOT_ZORA_FOUNTAIN_FROM_FAIRY_ENTR, { OOT_ZORA_FOUNTAIN_FROM_FAIRY_ENTR, OOT_ZORA_FOUNTAIN, "Farore's Wind Fountain", "Zora Foutain", "", GameLayout::all } },
	{ OOT_DESERT_COLOSSUS_FROM_FAIRY_ENTR, { OOT_DESERT_COLOSSUS_FROM_FAIRY_ENTR, OOT_DESERT_COLOSSUS, "Nayru's Love Fountain", "Desert Colossus", "", GameLayout::all } },
	{ OOT_MARKET_FROM_BOWLING_ENTR, { OOT_MARKET_FROM_BOWLING_ENTR, OOT_MARKET, "Bombchu Bowling", "Market", "", GameLayout::all } },
	{ OOT_MARKET_FROM_TREASURE_GAME_ENTR, { OOT_MARKET_FROM_TREASURE_GAME_ENTR, OOT_MARKET, "Treasure Game (OoT)", "Market", "", GameLayout::all } },
	{ OOT_MARKET_FROM_BOMBCHU_SHOP_ENTR, { OOT_MARKET_FROM_BOMBCHU_SHOP_ENTR, OOT_MARKET, "Bombchu Shop", "Back Alley", "", GameLayout::all } },
	{ OOT_MARKET_FROM_ALLEY_HOUSE_ENTR, { OOT_MARKET_FROM_ALLEY_HOUSE_ENTR, OOT_MARKET, "Alley House", "Back Alley", "", GameLayout::all } },
	{ OOT_MARKET_FROM_BAZAAR_ENTR, { OOT_MARKET_FROM_BAZAAR_ENTR, OOT_MARKET, "Market Bazaar", "Market", "", GameLayout::all } },
	{ OOT_MARKET_FROM_POTION_ENTR, { OOT_MARKET_FROM_POTION_ENTR, OOT_MARKET, "Market Potion Shop", "Market", "", GameLayout::all } },
	{ OOT_MARKET_FROM_ARCHERY_ENTR, { OOT_MARKET_FROM_ARCHERY_ENTR, OOT_MARKET, "Market Shooting", "Market", "", GameLayout::all } },
	{ OOT_KAKARIKO_FROM_BAZAAR_ENTR, { OOT_KAKARIKO_FROM_BAZAAR_ENTR, OOT_KAKARIKO_VILLAGE, "Kakariko Bazaar", "Kakariko", "", GameLayout::all } },
	{ OOT_KAKARIKO_FROM_ARCHERY_ENTR, { OOT_KAKARIKO_FROM_ARCHERY_ENTR, OOT_KAKARIKO_VILLAGE, "Kakariko Shooting", "Kakariko", "", GameLayout::all } },
	{ OOT_OUTSIDE_GANON_FROM_FAIRY_ENTR, { OOT_OUTSIDE_GANON_FROM_FAIRY_ENTR, OOT_GANON_CASTLE_EXTERIOR, "Defense Upgrade Fountain (OoT)", "Ganon Castle Exterior", "", GameLayout::all } },
	{ OOT_WARP_SONG_MEADOW_ENTR, { OOT_WARP_SONG_MEADOW_ENTR, OOT_SACRED_FOREST_MEADOW, "Warp Song", "Sacred Forest Meadow", "", GameLayout::all } },
	{ OOT_WARP_SONG_CRATER_ENTR, { OOT_WARP_SONG_CRATER_ENTR, OOT_DEATH_MOUNTAIN_CRATER, "Warp Song", "Death Mountain Crater ", "", GameLayout::all } },
	{ OOT_WARP_SONG_LAKE_ENTR, { OOT_WARP_SONG_LAKE_ENTR, OOT_LAKE_HYLIA, "Warp Song", "Lake Hylia", "", GameLayout::all } },
	{ OOT_WARP_SONG_GRAVE_ENTR, { OOT_WARP_SONG_GRAVE_ENTR, OOT_GRAVEYARD, "Warp Song", "Graveyard", "", GameLayout::all } },
	{ OOT_WARP_SONG_DESERT_ENTR, { OOT_WARP_SONG_DESERT_ENTR, OOT_DESERT_COLOSSUS, "Warp Song", "Desert Colossus", "", GameLayout::all } },
	{ OOT_WARP_SONG_TEMPLE_ENTR, { OOT_WARP_SONG_TEMPLE_ENTR, OOT_TEMPLE_OF_TIME, "Warp Song", "Temple of Time", "", GameLayout::all } },
	{ OOT_VILLAGE_OWL_ENTR, { OOT_VILLAGE_OWL_ENTR, OOT_DEATH_MOUNTAIN_TRAIL, "Death Mountain Trail Owl", "Kakariko", "", GameLayout::all } },
	{ OOT_FIELD_OWL_ENTR, { OOT_FIELD_OWL_ENTR, OOT_LAKE_HYLIA, "Lake Hylia Owl", "Hyrule Field", "", GameLayout::all } },
	{ OOT_WALLMASTER_FOREST_CORRIDOR_WEST_ENTR, { OOT_WALLMASTER_FOREST_CORRIDOR_WEST_ENTR, OOT_TEMPLE_FOREST, "Wallmaster", "Forest Temple", "", GameLayout::all } },
	{ OOT_WALLMASTER_FOREST_CORRIDOR_EAST_ENTR, { OOT_WALLMASTER_FOREST_CORRIDOR_EAST_ENTR, OOT_TEMPLE_FOREST, "Wallmaster", "Forest Temple", "", GameLayout::all } },
	{ OOT_WALLMASTER_SHADOW_ENTR, { OOT_WALLMASTER_SHADOW_ENTR, OOT_TEMPLE_SHADOW, "Wallmaster", "Shadow Temple", "", GameLayout::all } },
	{ OOT_WALLMASTER_SPIRIT_CHILD_RUPEES_ENTR, { OOT_WALLMASTER_SPIRIT_CHILD_RUPEES_ENTR, OOT_TEMPLE_SPIRIT, "Wallmaster", "Spirit Temple", "", GameLayout::all } },
	{ OOT_WALLMASTER_SPIRIT_ADULT_CLIMB_ENTR, { OOT_WALLMASTER_SPIRIT_ADULT_CLIMB_ENTR, OOT_TEMPLE_SPIRIT, "Wallmaster", "Spirit Temple", "", GameLayout::all } },
	{ OOT_WALLMASTER_SPIRIT_CHILD_SUN_ENTR, { OOT_WALLMASTER_SPIRIT_CHILD_SUN_ENTR, OOT_TEMPLE_SPIRIT, "Wallmaster", "Spirit Temple", "", GameLayout::all } },
	{ OOT_WALLMASTER_SPIRIT_STATUE_ENTR, { OOT_WALLMASTER_SPIRIT_STATUE_ENTR, OOT_TEMPLE_SPIRIT, "Wallmaster", "Spirit Temple", "", GameLayout::all } },
	{ OOT_WALLMASTER_BOTW_MAIN_ENTR, { OOT_WALLMASTER_BOTW_MAIN_ENTR, OOT_BOTTOM_OF_THE_WELL, "Wallmaster", "Bottom of the Well", "", GameLayout::all } },
	{ OOT_WALLMASTER_BOTW_BASEMENT_ENTR, { OOT_WALLMASTER_BOTW_BASEMENT_ENTR, OOT_BOTTOM_OF_THE_WELL, "Wallmaster", "Bottom of the Well", "", GameLayout::all } },
	{ OOT_WALLMASTER_BOTW_PIT_ENTR, { OOT_WALLMASTER_BOTW_PIT_ENTR, OOT_BOTTOM_OF_THE_WELL, "Wallmaster", "Bottom of the Well", "", GameLayout::all } },
	{ OOT_WALLMASTER_GTG_ENTR, { OOT_WALLMASTER_GTG_ENTR, OOT_GERUDO_TRAINING_GROUND, "Wallmaster", "Gerudo Training Ground", "", GameLayout::all } },
	{ OOT_WALLMASTER_GANON_SPIRIT_ENTR, { OOT_WALLMASTER_GANON_SPIRIT_ENTR, OOT_INSIDE_GANON_CASTLE, "Wallmaster", "Inside Ganon Castle", "", GameLayout::all } },
	{ OOT_WALLMASTER_GANON_LIGHT_ENTR, { OOT_WALLMASTER_GANON_LIGHT_ENTR, OOT_INSIDE_GANON_CASTLE, "Wallmaster", "Inside Ganon Castle", "", GameLayout::all } },
	{ OOT_GROTTO_GENERIC_KOKIRI_FOREST_ENTR, { OOT_GROTTO_GENERIC_KOKIRI_FOREST_ENTR, OOT_KOKIRI_FOREST, "Kokiri Forest", "Kokiri Forest Storms Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_GENERIC_LOST_WOODS_ENTR, { OOT_GROTTO_GENERIC_LOST_WOODS_ENTR, OOT_LOST_WOODS, "Lost Woods", "Lost Woods Boulder Grotto Near Goron City", "", GameLayout::all } },
	{ OOT_GROTTO_GENERIC_KAKARIKO_ENTR, { OOT_GROTTO_GENERIC_KAKARIKO_ENTR, OOT_KAKARIKO_VILLAGE, "Kakariko", "Kakariko Open Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_GENERIC_DMT_ENTR, { OOT_GROTTO_GENERIC_DMT_ENTR, OOT_DEATH_MOUNTAIN_TRAIL, "Death Mountain Trail", "Death Mountain Trail Storms Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_GENERIC_DMC_ENTR, { OOT_GROTTO_GENERIC_DMC_ENTR, OOT_DEATH_MOUNTAIN_CRATER, "Death Mountain Crater", "Death Mountain Crater Boulder Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_GENERIC_RIVER_ENTR, { OOT_GROTTO_GENERIC_RIVER_ENTR, OOT_ZORA_RIVER, "Zora River", "Zora River Generic Open Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_GENERIC_HF_SOUTHEAST_ENTR, { OOT_GROTTO_GENERIC_HF_SOUTHEAST_ENTR, OOT_HYRULE_FIELD, "Hyrule Field", "Hyrule Field Southeast Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_GENERIC_HF_OPEN_ENTR, { OOT_GROTTO_GENERIC_HF_OPEN_ENTR, OOT_HYRULE_FIELD, "Hyrule Field", "Hyrule Field Open Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_GENERIC_HF_MARKET_ENTR, { OOT_GROTTO_GENERIC_HF_MARKET_ENTR, OOT_HYRULE_FIELD, "Hyrule Field", "Hyrule Field Near Market Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_FAIRY_SFM_ENTR, { OOT_GROTTO_FAIRY_SFM_ENTR, OOT_SACRED_FOREST_MEADOW, "Sacred Forest Meadow", "Sacred Forest Meadow Fairy Fountain Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_FAIRY_HF_ENTR, { OOT_GROTTO_FAIRY_HF_ENTR, OOT_HYRULE_FIELD, "Hyrule Field", "Hyrule Field Fairy Fountain Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_FAIRY_RIVER_ENTR, { OOT_GROTTO_FAIRY_RIVER_ENTR, OOT_ZORA_RIVER, "Zora River", "Zora River Fairy Fountain Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_FAIRY_DOMAIN_ENTR, { OOT_GROTTO_FAIRY_DOMAIN_ENTR, OOT_ZORA_DOMAIN, "Zora Domain", "Zora Domain Fairy Fountain Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_FAIRY_FORTRESS_ENTR, { OOT_GROTTO_FAIRY_FORTRESS_ENTR, OOT_GERUDO_FORTRESS, "Gerudo Fortress", "Gerudo Fortress Fairy Fountain Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_SCRUBS2_SFM_ENTR, { OOT_GROTTO_SCRUBS2_SFM_ENTR, OOT_SACRED_FOREST_MEADOW, "Sacred Forest Meadow", "Sacred Forest Meadow Storms Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_SCRUBS2_RIVER_ENTR, { OOT_GROTTO_SCRUBS2_RIVER_ENTR, OOT_ZORA_RIVER, "Zora River", "Zora River Storms Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_SCRUBS2_VALLEY_ENTR, { OOT_GROTTO_SCRUBS2_VALLEY_ENTR, OOT_GERUDO_VALLEY, "Gerudo Valley", "Gerudo Valley Storms Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_SCRUBS2_COLOSSUS_ENTR, { OOT_GROTTO_SCRUBS2_COLOSSUS_ENTR, OOT_DESERT_COLOSSUS, "Desert Colossus", "Desert Colossus Silver Boulder Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_SCRUBS3_RANCH_ENTR, { OOT_GROTTO_SCRUBS3_RANCH_ENTR, OOT_LON_LON_RANCH, "Lon Lon Ranch", "Lon Lon Ranch Open Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_SCRUBS3_GORON_CITY_ENTR, { OOT_GROTTO_SCRUBS3_GORON_CITY_ENTR, OOT_GORON_CITY, "Goron City", "Goron City Open Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_SCRUBS3_DMC_ENTR, { OOT_GROTTO_SCRUBS3_DMC_ENTR, OOT_DEATH_MOUNTAIN_CRATER, "Death Mountain Crater", "Death Mountain Crater Red Boulder Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_SCRUBS3_LAKE_ENTR, { OOT_GROTTO_SCRUBS3_LAKE_ENTR, OOT_LAKE_HYLIA, "Lake Hylia", "Lake Hylia Under Tomb Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_SCRUB_UPGRADE_ENTR, { OOT_GROTTO_SCRUB_UPGRADE_ENTR, OOT_LOST_WOODS, "Lost Woods", "Lost Woods Scrub Upgrade Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_SCRUB_HEART_PIECE_ENTR, { OOT_GROTTO_SCRUB_HEART_PIECE_ENTR, OOT_HYRULE_FIELD, "Hyrule Field", "Hyrule Field Scrub Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_DEKU_THEATER_ENTR, { OOT_GROTTO_DEKU_THEATER_ENTR, OOT_LOST_WOODS, "Lost Woods", "Lost Woods Deku Theater", "", GameLayout::all } },
	{ OOT_GROTTO_WOLFOS_ENTR, { OOT_GROTTO_WOLFOS_ENTR, OOT_SACRED_FOREST_MEADOW, "Sacred Forest Meadow", "Sacred Forest Meadow Wolfos Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_TEKTITE_ENTR, { OOT_GROTTO_TEKTITE_ENTR, OOT_HYRULE_FIELD, "Hyrule Field", "Hyrule Field Tektite Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_FIELD_COW_ENTR, { OOT_GROTTO_FIELD_COW_ENTR, OOT_HYRULE_FIELD, "Hyrule Field", "Hyrule Field Grotto Near Gerudo Valley", "", GameLayout::all } },
	{ OOT_GROTTO_FIELD_TREE_ENTR, { OOT_GROTTO_FIELD_TREE_ENTR, OOT_HYRULE_FIELD, "Hyrule Field", "Hyrule Field Tree Grotto Near Kakariko", "", GameLayout::all } },
	{ OOT_GROTTO_TRAIL_COW_ENTR, { OOT_GROTTO_TRAIL_COW_ENTR, OOT_DEATH_MOUNTAIN_TRAIL, "Death Mountain Trail", "Death Mountain Trail Cow Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_CASTLE_ENTR, { OOT_GROTTO_CASTLE_ENTR, OOT_HYRULE_CASTLE, "Hyrule Castle", "Hyrule Castle Storms Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_REDEAD_ENTR, { OOT_GROTTO_REDEAD_ENTR, OOT_KAKARIKO_VILLAGE, "Kakariko", "Kakariko Redead Grotto", "", GameLayout::all } },
	{ OOT_GROTTO_OCTOROK_ENTR, { OOT_GROTTO_OCTOROK_ENTR, OOT_GERUDO_VALLEY, "Gerudo Valley", "Gerudo Valley Octorok Grotto", "", GameLayout::all } },
	{ OOT_GRAVE_SHIELD_ENTR, { OOT_GRAVE_SHIELD_ENTR, OOT_GRAVEYARD, "Graveyard", "Graveyard Shield Tomb", "", GameLayout::all } },
	{ OOT_GRAVE_REDEAD_ENTR, { OOT_GRAVE_REDEAD_ENTR, OOT_GRAVEYARD, "Graveyard", "Graveyard Fairy Fountain Tomb", "", GameLayout::all } },
	{ OOT_GRAVE_ROYAL_ENTR, { OOT_GRAVE_ROYAL_ENTR, OOT_GRAVEYARD, "Graveyard", "Graveyard Royal Family Tomb", "", GameLayout::all } },
	{ OOT_GRAVE_DAMPE_ENTR, { OOT_GRAVE_DAMPE_ENTR, OOT_GRAVEYARD, "Graveyard", "Graveyard Dampe Tomb", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_GENERIC_KOKIRI_FOREST, { OOT_GROTTO_EXIT_GENERIC_KOKIRI_FOREST, OOT_GROTTO_KOKIRI_FOREST_STORMS, "Kokiri Forest Storms Grotto", "Kokiri Forest", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_GENERIC_LOST_WOODS, { OOT_GROTTO_EXIT_GENERIC_LOST_WOODS, OOT_GROTTO_LOST_WOODS_GENERIC, "Lost Woods Boulder Grotto Near Goron City", "Lost Woods", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_GENERIC_KAKARIKO, { OOT_GROTTO_EXIT_GENERIC_KAKARIKO, OOT_GROTTO_KAKARIKO_OPEN, "Kakariko Open Grotto", "Kakariko", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_GENERIC_DMT, { OOT_GROTTO_EXIT_GENERIC_DMT, OOT_GROTTO_DEATH_TRIAL_STORMS, "Death Mountain Trail Storms Grotto", "Death Mountain Trail", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_GENERIC_DMC, { OOT_GROTTO_EXIT_GENERIC_DMC, OOT_GROTTO_DEATH_CRATER_GENERIC, "Death Mountain Crater Boulder Grotto", "Death Mountain Crater", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_GENERIC_RIVER, { OOT_GROTTO_EXIT_GENERIC_RIVER, OOT_GROTTO_ZORA_RIVER_GENERIC, "Zora River Generic Open Grotto", "Zora River", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_GENERIC_HF_SOUTHEAST, { OOT_GROTTO_EXIT_GENERIC_HF_SOUTHEAST, OOT_GROTTO_HYRULE_SE, "Hyrule Field Southeast Grotto", "Hyrule Field", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_GENERIC_HF_OPEN, { OOT_GROTTO_EXIT_GENERIC_HF_OPEN, OOT_GROTTO_HYRULE_OPEN, "Hyrule Field Open Grotto", "Hyrule Field", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_GENERIC_HF_MARKET, { OOT_GROTTO_EXIT_GENERIC_HF_MARKET, OOT_GROTTO_HYRULE_MARKET, "Hyrule Field Near Market Grotto", "Hyrule Field", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_FAIRY_SFM, { OOT_GROTTO_EXIT_FAIRY_SFM, OOT_FAIRY_SACRED_MEADOW, "Sacred Forest Meadow Fairy Fountain Grotto", "Sacred Forest Meadow", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_FAIRY_HF, { OOT_GROTTO_EXIT_FAIRY_HF, OOT_FAIRY_HYRULE, "Hyrule Field Fairy Fountain Grotto", "Hyrule Field", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_FAIRY_RIVER, { OOT_GROTTO_EXIT_FAIRY_RIVER, OOT_FAIRY_ZORA_RIVER, "Zora River Fairy Fountain Grotto", "Zora River", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_FAIRY_DOMAIN, { OOT_GROTTO_EXIT_FAIRY_DOMAIN, OOT_FAIRY_ZORA_DOMAIN, "Zora Domain Fairy Fountain Grotto", "Zora Domain", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_FAIRY_FORTRESS, { OOT_GROTTO_EXIT_FAIRY_FORTRESS, OOT_FAIRY_GERUDO_FORTRESS, "Gerudo Fortress Fairy Fountain Grotto", "Gerudo Fortress", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_SCRUBS2_SFM, { OOT_GROTTO_EXIT_SCRUBS2_SFM, OOT_GROTTO_SACRED_MEADOW_STORMS, "Sacred Forest Meadow Storms Grotto", "Sacred Forest Meadow", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_SCRUBS2_RIVER, { OOT_GROTTO_EXIT_SCRUBS2_RIVER, OOT_GROTTO_ZORA_RIVER_STORMS, "Zora River Storms Grotto", "Zora River", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_SCRUBS2_VALLEY, { OOT_GROTTO_EXIT_SCRUBS2_VALLEY, OOT_GROTTO_VALLEY_STORMS, "Gerudo Valley Storms Grotto", "Gerudo Valley", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_SCRUBS2_COLOSSUS, { OOT_GROTTO_EXIT_SCRUBS2_COLOSSUS, OOT_GROTTO_DESERT_SCRUBS, "Desert Colossus Silver Boulder Grotto", "Desert Colossus", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_SCRUBS3_RANCH, { OOT_GROTTO_EXIT_SCRUBS3_RANCH, OOT_GROTTO_LON_LON_SCRUBS, "Lon Lon Ranch Open Grotto", "Lon Lon Ranch", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_SCRUBS3_GORON_CITY, { OOT_GROTTO_EXIT_SCRUBS3_GORON_CITY, OOT_GROTTO_GORON_CITY_SCRUBS, "Goron City Open Grotto", "Goron City", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_SCRUBS3_DMC, { OOT_GROTTO_EXIT_SCRUBS3_DMC, OOT_GROTTO_DEATH_CRATER_SCRUBS, "Death Mountain Crater Red Boulder Grotto", "Death Mountain Crater", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_SCRUBS3_LAKE, { OOT_GROTTO_EXIT_SCRUBS3_LAKE, OOT_GROTTO_LAKE_HYLIA_SCRUBS, "Lake Hylia Under Tomb Grotto", "Lake Hylia", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_SCRUB_UPGRADE, { OOT_GROTTO_EXIT_SCRUB_UPGRADE, OOT_GROTTO_LOST_WOODS_SCRUB_UPGRADE, "Lost Woods Scrub Upgrade Grotto", "Lost Woods", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_SCRUB_HEART_PIECE, { OOT_GROTTO_EXIT_SCRUB_HEART_PIECE, OOT_GROTTO_HYRULE_SCRUBS, "Hyrule Field Scrub Grotto", "Hyrule Field", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_DEKU_THEATER, { OOT_GROTTO_EXIT_DEKU_THEATER, OOT_GROTTO_LOST_WOODS_THEATER, "Lost Woods Deku Theater", "Lost Woods", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_WOLFOS, { OOT_GROTTO_EXIT_WOLFOS, OOT_GROTTO_SACRED_MEADOW_WOLFOS, "Sacred Forest Meadow Wolfos Grotto", "Sacred Forest Meadow", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_TEKTITE, { OOT_GROTTO_EXIT_TEKTITE, OOT_GROTTO_HYRULE_TEKTITE, "Hyrule Field Tektite Grotto", "Hyrule Field", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_FIELD_COW, { OOT_GROTTO_EXIT_FIELD_COW, OOT_GROTTO_HYRULE_GERUDO, "Hyrule Field Grotto Near Gerudo Valley", "Hyrule Field", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_FIELD_TREE, { OOT_GROTTO_EXIT_FIELD_TREE, OOT_GROTTO_HYRULE_KAKARIKO, "Hyrule Field Tree Grotto Near Kakariko", "Hyrule Field", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_TRAIL_COW, { OOT_GROTTO_EXIT_TRAIL_COW, OOT_GROTTO_DEATH_TRIAL_COW, "Death Mountain Trail Cow Grotto", "Death Mountain Trail", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_CASTLE, { OOT_GROTTO_EXIT_CASTLE, OOT_GROTTO_CASTLE_STORMS, "Hyrule Castle Storms Grotto", "Hyrule Castle", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_REDEAD, { OOT_GROTTO_EXIT_REDEAD, OOT_GROTTO_KAKARIKO_REDEAD, "Kakariko Redead Grotto", "Kakariko", "", GameLayout::all } },
	{ OOT_GROTTO_EXIT_OCTOROK, { OOT_GROTTO_EXIT_OCTOROK, OOT_GROTTO_VALLEY_OCTOROK, "Gerudo Valley Octorok Grotto", "Gerudo Valley", "", GameLayout::all } },
	{ OOT_GRAVE_EXIT_SHIELD, { OOT_GRAVE_EXIT_SHIELD, OOT_TOMB_REDEAD, "Graveyard Shield Tomb", "Graveyard", "", GameLayout::all } },
	{ OOT_GRAVE_EXIT_REDEAD, { OOT_GRAVE_EXIT_REDEAD, OOT_TOMB_FAIRY, "Graveyard Fairy Fountain Tomb", "Graveyard", "", GameLayout::all } },
	{ OOT_GRAVE_EXIT_ROYAL, { OOT_GRAVE_EXIT_ROYAL, OOT_TOMB_ROYAL, "Graveyard Royal Family Tomb", "Graveyard", "", GameLayout::all } },
	{ OOT_GRAVE_EXIT_DAMPE, { OOT_GRAVE_EXIT_DAMPE, OOT_TOMB_DAMPE_WINDMILL, "Graveyard Dampe Tomb", "Graveyard", "", GameLayout::all } },
	{ OOT_BOSS_GANON2_ENTR, { OOT_BOSS_GANON2_ENTR, OOT_GANON_BATTLE_ARENA, "", "", "", GameLayout::all } },
	{ OOT_GERUDO_FORTRESS_CAUGHT_NO_HOOK_ENTR, { OOT_GERUDO_FORTRESS_CAUGHT_NO_HOOK_ENTR, OOT_GERUDO_FORTRESS, "", "", "", GameLayout::all } },
	{ OOT_GERUDO_FORTRESS_CAUGHT_ENTR, { OOT_GERUDO_FORTRESS_CAUGHT_ENTR, OOT_GERUDO_FORTRESS, "", "", "", GameLayout::all } },
	{ OOT_CASTLE_STEALTH_ENTR, { OOT_CASTLE_STEALTH_ENTR, OOT_HYRULE_CASTLE, "", "", "", GameLayout::all } },
	{ OOT_CASTLE_STEALTH_FROM_COURTYARD_ENTR, { OOT_CASTLE_STEALTH_FROM_COURTYARD_ENTR, OOT_CASTLE_COURTYARD, "", "", "", GameLayout::all } },
	{ OOT_CASTLE_COURTYARD_ENTR, { OOT_CASTLE_COURTYARD_ENTR, OOT_CASTLE_COURTYARD, "Hyrule Castle", "Castle Courtyard", "", GameLayout::all } },
	{ OOT_CASTLE_CAUGHT_ENTR, { OOT_CASTLE_CAUGHT_ENTR, OOT_HYRULE_CASTLE, "", "", "", GameLayout::all } },
	{ OOT_MARKET_FROM_MASK_SHOP_ENTR, { OOT_MARKET_FROM_MASK_SHOP_ENTR, OOT_MARKET, "Mask Shop", "Market", "", GameLayout::all } },
	{ OOT_SHOP_MASKS_ENTR, { OOT_SHOP_MASKS_ENTR, OOT_MARKET, "Market", "Mask Shop", "", GameLayout::all } },
	{ OOT_SAGES_CHAMBER_END_ENTR, { OOT_SAGES_CHAMBER_END_ENTR, OOT_CHAMBER_OF_THE_SAGES, "Temple of Time", "Sages Chamber", "", GameLayout::all } },
	{ OOT_TEMPLE_OF_TIME_MASTER_SWORD_CS_ENTR, { OOT_TEMPLE_OF_TIME_MASTER_SWORD_CS_ENTR, OOT_TEMPLE_OF_TIME, "Master Sword", "Temple of Time", "", GameLayout::all } },
	{ OOT_ZORA_RIVER_FROM_FIELD_WATER_ENTR, { OOT_ZORA_RIVER_FROM_FIELD_WATER_ENTR, OOT_ZORA_RIVER, "Hyrule Field Water", "Zora River Water", "", GameLayout::all } },
	{ OOT_FIELD_FROM_ZORA_RIVER_WATER_ENTR, { OOT_FIELD_FROM_ZORA_RIVER_WATER_ENTR, OOT_HYRULE_FIELD, "Zora River Water", "Hyrule Field Water", "", GameLayout::all } },
	{ OOT_GROTTO_TYPE_GENERIC_ENTR, { OOT_GROTTO_TYPE_GENERIC_ENTR, OOT_GROTTOS, "", "", "", GameLayout::all } },
	{ OOT_GROTTO_TYPE_FAIRY_ENTR, { OOT_GROTTO_TYPE_FAIRY_ENTR, OOT_GROTTOS, "", "", "", GameLayout::all } },
	{ OOT_GROTTO_TYPE_SCRUB2_ENTR, { OOT_GROTTO_TYPE_SCRUB2_ENTR, OOT_GROTTOS, "", "", "", GameLayout::all } },
	{ OOT_GROTTO_TYPE_SCRUB3_ENTR, { OOT_GROTTO_TYPE_SCRUB3_ENTR, OOT_GROTTOS, "", "", "", GameLayout::all } },
	{ OOT_SHADOW_TEMPLE_FROM_LAIR_ENTR, { OOT_SHADOW_TEMPLE_FROM_LAIR_ENTR, OOT_TEMPLE_SHADOW, "Bongo-Bongo's Lair", "Shadow Temple", "", GameLayout::all } },
	{ OOT_INTERNAL_EXIT_GROTTO_ENTR, { OOT_INTERNAL_EXIT_GROTTO_ENTR, OOT_GROTTOS, "", "", "", GameLayout::all } },
	{ OOT_MARKET_FROM_BACK_ALLEY_TREASURE_ENTR, { OOT_MARKET_FROM_BACK_ALLEY_TREASURE_ENTR, OOT_BACK_ALLEY, "Back Alley Treasure Game Side", "Market Treasure Game Side", "", GameLayout::all } },
	{ OOT_MARKET_FROM_BACK_ALLEY_SHOOTING_ENTR, { OOT_MARKET_FROM_BACK_ALLEY_SHOOTING_ENTR, OOT_BACK_ALLEY, "Back Alley Shooting Side", "Market Shooting Side", "", GameLayout::all } },
	{ OOT_BACK_ALLEY_TREASURE_FROM_MARKET_ENTR, { OOT_BACK_ALLEY_TREASURE_FROM_MARKET_ENTR, OOT_MARKET, "Market Treasure Game Side", "Back Alley Treasure Game Side", "", GameLayout::all } },
	{ OOT_BACK_ALLEY_SHOOTING_FROM_MARKET_ENTR, { OOT_BACK_ALLEY_SHOOTING_FROM_MARKET_ENTR, OOT_MARKET, "Market Shooting Side", "Back Alley Shooting Side", "", GameLayout::all } },
	{ OOT_DOG_LADY_FROM_BACK_ALLEY_ENTR, { OOT_DOG_LADY_FROM_BACK_ALLEY_ENTR, OOT_BACK_ALLEY, "Back Alley", "Dog Lady's House", "", GameLayout::all } },
	{ OOT_BACK_ALLEY_FROM_DOG_LADY_ENTR, { OOT_BACK_ALLEY_FROM_DOG_LADY_ENTR, OOT_BACK_ALLEY_HOUSE, "Dog Lady's House", "Back Alley", "", GameLayout::all } },
	{ SPAWN_LOADING, { SPAWN_LOADING, 0, "Wrap Song / Save Menu", "Spawn Loading", "", GameLayout::all } }
};