#pragma once

#include "Entrances.h"
#include "Scenes.h"

#pragma region Defines

#define OOT_SPAWN_CHILD  0x0bb
#define OOT_SPAWN_ADULT  0xf20
#define OOT_BOSS_DEKU_TREE  0x40f
#define OOT_BOSS_DODONGO_CAVERN  0x40b
#define OOT_BOSS_JABU_JABU  0x301
#define OOT_BOSS_TEMPLE_FOREST  0x00c
#define OOT_BOSS_TEMPLE_FIRE  0x305
#define OOT_BOSS_TEMPLE_WATER  0x417
#define OOT_BOSS_TEMPLE_SHADOW  0x413
#define OOT_BOSS_TEMPLE_SPIRIT  0x08d
#define OOT_DEKU_TREE  0x000
#define OOT_DODONGO_CAVERN  0x004
#define OOT_JABU_JABU  0x028
#define OOT_TEMPLE_FOREST  0x169
#define OOT_TEMPLE_FIRE  0x165
#define OOT_TEMPLE_WATER  0x010
#define OOT_TEMPLE_SHADOW  0x037
#define OOT_TEMPLE_SPIRIT  0x082
#define OOT_BOTTOM_OF_THE_WELL  0x098
#define OOT_ICE_CAVERN  0x088
#define OOT_GERUDO_TRAINING_GROUNDS  0x008
#define OOT_GANON_CASTLE  0x467
#define OOT_GANON_TOWER  0x41b
#define OOT_KOKIRI_FOREST_FROM_DEKU_TREE  0x209
#define OOT_MOUNTAIN_TRAIL_FROM_DODONGO_CAVERN  0x242
#define OOT_ZORA_FOUNTAIN_FROM_JABU_JABU  0x221
#define OOT_SACRED_MEADOW_FROM_TEMPLE_FOREST  0x215
#define OOT_DEATH_CRATER_FROM_TEMPLE_FIRE  0x24a
#define OOT_LAKE_HYLIA_FROM_TEMPLE_WATER  0x21d
#define OOT_GRAVEYARD_FROM_TEMPLE_SHADOW  0x205
#define OOT_DESERT_COLOSSUS_FROM_TEMPLE_SPIRIT  0x1e1
#define OOT_KAKARIKO_FROM_BOTTOM_OF_THE_WELL  0x2a6
#define OOT_ZORA_FOUNTAIN_FROM_ICE_CAVERN  0x3d4
#define OOT_GERUDO_FORTRESS_FROM_GERUDO_TRAINING  0x3a8
#define OOT_GANON_CASTLE_EXTERIOR_FROM_CASTLE  0x23d
#define OOT_GANON_CASTLE_FROM_TOWER  0x534
#define OOT_LOST_WOODS_BRIDGE_FROM_FIELD  0x4de
#define OOT_ZORA_RIVER_FROM_FIELD  0x0ea
#define OOT_KAKARIKO_FROM_FIELD  0x0db
#define OOT_LON_LON_RANCH_FROM_FIELD  0x157
#define OOT_LAKE_HYLIA_FROM_FIELD  0x102
#define OOT_GERUDO_FORTRESS_FROM_VALLEY  0x129
#define OOT_DEATH_MOUNTAIN_FROM_KAKARIKO  0x13d
#define OOT_GERUDO_VALLEY_FROM_FIELD  0x117
#define OOT_MARKET_ENTRANCE_FROM_FIELD  0x276
#define OOT_ZORA_RIVER_FROM_LOST_WOODS  0x1dd
#define OOT_GORON_CITY_FROM_LOST_WOODS  0x4e2
#define OOT_LAKE_HYLIA_FROM_ZORA_DOMAIN  0x560
#define OOT_FIELD_FROM_LOST_WOODS_BRIDGE  0x185
#define OOT_FIELD_FROM_ZORA_RIVER  0x181
#define OOT_FIELD_FROM_KAKARIKO  0x17d
#define OOT_FIELD_FROM_LON_LON_RANCH  0x1f9
#define OOT_FIELD_FROM_LAKE_HYLIA  0x189
#define OOT_FIELD_FROM_GERUDO_VALLEY  0x18d
#define OOT_VALLEY_FROM_GERUDO_FORTRESS  0x22d
#define OOT_KAKARIKO_FROM_DEATH_MOUNTAIN  0x191
#define OOT_FIELD_FROM_MARKET_ENTRANCE  0x1fd
#define OOT_LOST_WOODS_FROM_ZORA_RIVER  0x4da
#define OOT_LOST_WOODS_FROM_GORON_CITY  0x4d6
#define OOT_ZORA_DOMAIN_FROM_LAKE_HYLIA  0x328
#define OOT_SACRED_FOREST_MEADOW  0x0fc
#define OOT_LOST_WOODS_FROM_MEADOW  0x1a9
#define OOT_GORON_CITY  0x14d
#define OOT_DEATH_MOUNTAIN_FROM_GORON_CITY  0x1b9
#define OOT_ZORA_DOMAIN  0x108
#define OOT_RIVER_FROM_DOMAIN  0x19d
#define OOT_FOUNTAIN_ZORA  0x225
#define OOT_DOMAIN_FROM_FOUNTAIN  0x1a1
#define OOT_CRATER_FROM_GORON_CITY  0x246
#define OOT_GORON_CITY_FROM_CRATER  0x1c1
#define OOT_DEATH_MOUNTAIN_CRATER  0x147
#define OOT_TRAIL_SUMMIT_FROM_CRATER  0x1bd
#define OOT_LOST_WOODS_FROM_KOKIRI_FOREST  0x11e
#define OOT_KOKIRI_FOREST_FROM_LOST_WOODS  0x286
#define OOT_FOREST_FROM_LOST_WOODS_BRIDGE  0x20d
#define OOT_LOST_WOODS_BRIDGE_FROM_FOREST  0x5e0
#define OOT_GRAVEYARD  0x0e4
#define OOT_KAKARIKO_FROM_GRAVEYARD  0x195
#define OOT_WASTELAND  0x130
#define OOT_FORTRESS_FROM_WASTELAND  0x3ac
#define OOT_COLOSSUS  0x123
#define OOT_WASTELAND_FROM_COLOSSUS  0x365
#define OOT_MARKET_FROM_MARKET_ENTRANCE  0x0b1
#define OOT_MARKET_ENTRANCE_FROM_MARKET  0x033
#define OOT_HYRULE_CASTLE  0x138
#define OOT_MARKET_FROM_CASTLE  0x25a
#define OOT_MARKET_FROM_TEMPLE_OF_TIME_ENTRYWAY  0x25e
#define OOT_TEMPLE_OF_TIME_ENTRYWAY_FROM_MARKET  0x171
#define OOT_LAKE_HYLIA_FROM_VALLEY  0x219
#define OOT_LOST_WOODS_FROM_LOST_WOODS_NORTH  0xf01
#define OOT_LOST_WOODS_FROM_LOST_WOODS_EAST  0x1ad
#define OOT_LOST_WOODS_FROM_LOST_WOODS_SOUTH  0x1b1
#define OOT_LOST_WOODS_FROM_LOST_WOODS_WEST  0x4c6
#define OOT_HOUSE_MIDO  0x433
#define OOT_HOUSE_SARIA  0x437
#define OOT_HOUSE_TWINS  0x09c
#define OOT_HOUSE_KNOW_IT_ALL  0x0c9
#define OOT_KOKIRI_SHOP  0x0c1
#define OOT_HOUSE_POTS  0x07e
#define OOT_LABORATORY  0x043
#define OOT_FISHING_POND  0x45f
#define OOT_VALLEY_TENT  0x3a0
#define OOT_HOUSE_CARPENTER  0x2fd
#define OOT_HOUSE_SKULLTULA  0x550
#define OOT_HOUSE_IMPA  0x39c
#define OOT_HOUSE_IMPA_BACK  0x5c8
#define OOT_SHOP_GRANNY  0x072
#define OOT_HOUSE_DAMPE  0x30d
#define OOT_SHOP_GORON  0x37c
#define OOT_SHOP_ZORA  0x380
#define OOT_HOUSE_LON_LON  0x04f
#define OOT_SILO  0x5d0
#define OOT_STABLES  0x2f9
#define OOT_FAIRY_MAGIC  0x315
#define OOT_FAIRY_MAGIC2  0x4be
#define OOT_FAIRY_DIN  0x578
#define OOT_FAIRY_FARORE  0x371
#define OOT_FAIRY_NAYRU  0x588
#define OOT_FAIRY_DEFENSE  0x4c2
#define OOT_BOMBCHU_BOWLING  0x507
#define OOT_TREASURE_GAME  0x063
#define OOT_BOMBCHU_SHOP  0x528
#define OOT_ALLEY_HOUSE  0x43b
#define OOT_MARKET_BAZAAR  0x52c
#define OOT_MARKET_POTION  0x388
#define OOT_CHILD_ARCHERY  0x16d
#define OOT_KAKARIKO_BAZAAR  0x0b7
#define OOT_ADULT_ARCHERY  0x03b
#define OOT_HOUSE_LINK  0x272
#define OOT_TEMPLE_OF_TIME  0x053
#define OOT_WINDMILL  0x453
#define OOT_SHOP_POTION_KAKARIKO  0x384
#define OOT_SHOP_POTION_KAKARIKO_BACK  0x3ec
#define OOT_KOKIRI_FOREST_FROM_MIDO  0x443
#define OOT_KOKIRI_FOREST_FROM_SARIA  0x447
#define OOT_KOKIRI_FOREST_FROM_TWINS  0x33c
#define OOT_KOKIRI_FOREST_FROM_KNOW_IT_ALL  0x26a
#define OOT_KOKIRI_FOREST_FROM_SHOP  0x266
#define OOT_MARKET_ENTRANCE_FROM_POTS  0x26e
#define OOT_LAKE_HYLIA_FROM_LABORATORY  0x3cc
#define OOT_LAKE_HYLIA_FROM_FISHING_POND  0x309
#define OOT_GERUDO_VALLEY_FROM_TENT  0x3d0
#define OOT_KAKARIKO_FROM_CARPENTER  0x349
#define OOT_KAKARIKO_FROM_SKULLTULA  0x4ee
#define OOT_KAKARIKO_FROM_IMPA  0x345
#define OOT_KAKARIKO_FROM_IMPA_BACK  0x5dc
#define OOT_KAKARIKO_FROM_GRANNY  0x34d
#define OOT_GRAVEYARD_FROM_DAMPE  0x355
#define OOT_GORON_CITY_FROM_SHOP  0x3fc
#define OOT_ZORA_DOMAIN_FROM_SHOP  0x3c4
#define OOT_LON_LON_RANCH_FROM_HOUSE  0x378
#define OOT_LON_LON_RANCH_FROM_STABLES  0x42f
#define OOT_LON_LON_RANCH_FROM_SILO  0x5d4
#define OOT_KOKIRI_FOREST_FROM_LINK  0x211
#define OOT_TEMPLE_OF_TIME_ENTRYWAY_FROM_TEMPLE  0x472
#define OOT_KAKARIKO_FROM_WINDMILL  0x351
#define OOT_KAKARIKO_FROM_SHOP_POTION  0x44b
#define OOT_KAKARIKO_FROM_SHOP_POTION_BACK  0x4ff
#define OOT_DEATH_MOUNTAIN_FROM_FAIRY  0x45b
#define OOT_DEATH_CRATER_FROM_FAIRY  0x482
#define OOT_HYRULE_CASTLE_FROM_FAIRY  0x340
#define OOT_ZORA_FOUNTAIN_FROM_FAIRY  0x394
#define OOT_DESERT_COLOSSUS_FROM_FAIRY  0x57c
#define OOT_MARKET_FROM_BOWLING  0x3bc
#define OOT_MARKET_FROM_TREASURE_GAME  0x1d5
#define OOT_MARKET_FROM_BOMBCHU_SHOP  0x3c0
#define OOT_MARKET_FROM_ALLEY_HOUSE  0x067
#define OOT_MARKET_FROM_BAZAAR  0x3b8
#define OOT_MARKET_FROM_POTION  0x2a2
#define OOT_MARKET_FROM_ARCHERY  0x1cd
#define OOT_KAKARIKO_FROM_BAZAAR  0x201
#define OOT_KAKARIKO_FROM_ARCHERY  0x463
#define OOT_OUTSIDE_GANON_FROM_FAIRY  0xf00
#define OOT_WARP_SONG_MEADOW  0x600
#define OOT_WARP_SONG_CRATER  0x4f6
#define OOT_WARP_SONG_LAKE  0x604
#define OOT_WARP_SONG_GRAVE  0x568
#define OOT_WARP_SONG_DESERT  0x1f1
#define OOT_WARP_SONG_TEMPLE  0x5f4
#define OOT_VILLAGE_OWL  0x554
#define OOT_FIELD_OWL  0x27e
#define OOT_WALLMASTER_FOREST_CORRIDOR_WEST  0xf10
#define OOT_WALLMASTER_FOREST_CORRIDOR_EAST  0xf11
#define OOT_WALLMASTER_SHADOW  0xf12
#define OOT_WALLMASTER_SPIRIT_CHILD_RUPEES  0xf13
#define OOT_WALLMASTER_SPIRIT_ADULT_CLIMB  0xf14
#define OOT_WALLMASTER_SPIRIT_CHILD_SUN  0xf15
#define OOT_WALLMASTER_SPIRIT_STATUE  0xf16
#define OOT_WALLMASTER_BOTW_MAIN  0xf17
#define OOT_WALLMASTER_BOTW_BASEMENT  0xf18
#define OOT_WALLMASTER_BOTW_PIT  0xf19
#define OOT_WALLMASTER_GTG  0xf1a
#define OOT_WALLMASTER_GANON_SPIRIT  0xf1b
#define OOT_WALLMASTER_GANON_LIGHT  0xf1c
#define OOT_GROTTO_GENERIC_KOKIRI_FOREST  0x1000
#define OOT_GROTTO_GENERIC_LOST_WOODS  0x1001
#define OOT_GROTTO_GENERIC_KAKARIKO  0x1002
#define OOT_GROTTO_GENERIC_DMT  0x1003
#define OOT_GROTTO_GENERIC_DMC  0x1004
#define OOT_GROTTO_GENERIC_RIVER  0x1005
#define OOT_GROTTO_GENERIC_HF_SOUTHEAST  0x1006
#define OOT_GROTTO_GENERIC_HF_OPEN  0x1007
#define OOT_GROTTO_GENERIC_HF_MARKET  0x1008
#define OOT_GROTTO_FAIRY_SFM  0x1009
#define OOT_GROTTO_FAIRY_HF  0x100a
#define OOT_GROTTO_FAIRY_RIVER  0x100b
#define OOT_GROTTO_FAIRY_DOMAIN  0x100c
#define OOT_GROTTO_FAIRY_FORTRESS  0x100d
#define OOT_GROTTO_SCRUBS2_SFM  0x100e
#define OOT_GROTTO_SCRUBS2_RIVER  0x100f
#define OOT_GROTTO_SCRUBS2_VALLEY  0x1010
#define OOT_GROTTO_SCRUBS2_COLOSSUS  0x1011
#define OOT_GROTTO_SCRUBS3_RANCH  0x1012
#define OOT_GROTTO_SCRUBS3_GORON_CITY  0x1013
#define OOT_GROTTO_SCRUBS3_DMC  0x1014
#define OOT_GROTTO_SCRUBS3_LAKE  0x1015
#define OOT_GROTTO_SCRUB_UPGRADE  0x5b0
#define OOT_GROTTO_SCRUB_HEART_PIECE  0x59c
#define OOT_GROTTO_DEKU_THEATER  0x5c4
#define OOT_GROTTO_WOLFOS  0x5b4
#define OOT_GROTTO_TEKTITE  0x5c0
#define OOT_GROTTO_FIELD_COW  0x5a8
#define OOT_GROTTO_FIELD_TREE  0x598
#define OOT_GROTTO_TRAIL_COW  0x5fc
#define OOT_GROTTO_CASTLE  0x5b8
#define OOT_GROTTO_REDEAD  0x5a0
#define OOT_GROTTO_OCTOROK  0x5ac
#define OOT_GRAVE_SHIELD  0x04b
#define OOT_GRAVE_REDEAD  0x31c
#define OOT_GRAVE_ROYAL  0x02d
#define OOT_GRAVE_DAMPE  0x44f
#define OOT_GROTTO_EXIT_GENERIC_KOKIRI_FOREST  0x1100
#define OOT_GROTTO_EXIT_GENERIC_LOST_WOODS  0x1101
#define OOT_GROTTO_EXIT_GENERIC_KAKARIKO  0x1102
#define OOT_GROTTO_EXIT_GENERIC_DMT  0x1103
#define OOT_GROTTO_EXIT_GENERIC_DMC  0x1104
#define OOT_GROTTO_EXIT_GENERIC_RIVER  0x1105
#define OOT_GROTTO_EXIT_GENERIC_HF_SOUTHEAST  0x1106
#define OOT_GROTTO_EXIT_GENERIC_HF_OPEN  0x1107
#define OOT_GROTTO_EXIT_GENERIC_HF_MARKET  0x1108
#define OOT_GROTTO_EXIT_FAIRY_SFM  0x1109
#define OOT_GROTTO_EXIT_FAIRY_HF  0x110a
#define OOT_GROTTO_EXIT_FAIRY_RIVER  0x110b
#define OOT_GROTTO_EXIT_FAIRY_DOMAIN  0x110c
#define OOT_GROTTO_EXIT_FAIRY_FORTRESS  0x110d
#define OOT_GROTTO_EXIT_SCRUBS2_SFM  0x110e
#define OOT_GROTTO_EXIT_SCRUBS2_RIVER  0x110f
#define OOT_GROTTO_EXIT_SCRUBS2_VALLEY  0x1110
#define OOT_GROTTO_EXIT_SCRUBS2_COLOSSUS  0x1111
#define OOT_GROTTO_EXIT_SCRUBS3_RANCH  0x1112
#define OOT_GROTTO_EXIT_SCRUBS3_GORON_CITY  0x1113
#define OOT_GROTTO_EXIT_SCRUBS3_DMC  0x1114
#define OOT_GROTTO_EXIT_SCRUBS3_LAKE  0x1115
#define OOT_GROTTO_EXIT_SCRUB_UPGRADE  0x1116
#define OOT_GROTTO_EXIT_SCRUB_HEART_PIECE  0x1117
#define OOT_GROTTO_EXIT_DEKU_THEATER  0x1118
#define OOT_GROTTO_EXIT_WOLFOS  0x1119
#define OOT_GROTTO_EXIT_TEKTITE  0x111a
#define OOT_GROTTO_EXIT_FIELD_COW  0x111b
#define OOT_GROTTO_EXIT_FIELD_TREE  0x111c
#define OOT_GROTTO_EXIT_TRAIL_COW  0x111d
#define OOT_GROTTO_EXIT_CASTLE  0x111e
#define OOT_GROTTO_EXIT_REDEAD  0x111f
#define OOT_GROTTO_EXIT_OCTOROK  0x1120
#define OOT_GRAVE_EXIT_SHIELD  0x35d
#define OOT_GRAVE_EXIT_REDEAD  0x361
#define OOT_GRAVE_EXIT_ROYAL  0x50b
#define OOT_GRAVE_EXIT_DAMPE  0x359
#define OOT_BOSS_GANON2  0x517
#define OOT_GERUDO_FORTRESS_CAUGHT_NO_HOOK  0x1a5
#define OOT_GERUDO_FORTRESS_CAUGHT  0x5f8
#define OOT_CASTLE_STEALTH  0x07a
#define OOT_CASTLE_STEALTH_FROM_COURTYARD  0x296
#define OOT_CASTLE_COURTYARD  0x400
#define OOT_CASTLE_CAUGHT  0x47e
#define OOT_MARKET_FROM_MASK_SHOP  0x1d1
#define OOT_SHOP_MASKS  0x530
#define OOT_SAGES_CHAMBER_END  0x06b
#define OOT_TEMPLE_OF_TIME_MASTER_SWORD_CS  0x2ca
#define OOT_ZORA_RIVER_FROM_FIELD_WATER  0x1d9
#define OOT_FIELD_FROM_ZORA_RIVER_WATER  0x311
#define OOT_GROTTO_TYPE_GENERIC  0x03f
#define OOT_GROTTO_TYPE_FAIRY  0x36d
#define OOT_GROTTO_TYPE_SCRUB2  0x5bc
#define OOT_GROTTO_TYPE_SCRUB3  0x5a4
#define OOT_SHADOW_TEMPLE_FROM_LAIR  0x2b2
#define OOT_INTERNAL_EXIT_GROTTO  0x7fff

#pragma endregion

const std::map<int, EntranceMetaInfo> OoTEntrances =
{
	{ OOT_SPAWN_CHILD, { OOT_SPAWN_CHILD, OOT_LINK_HOUSE, "Spawn Child", "", GameLayout::all} },
	{ OOT_SPAWN_ADULT, { OOT_SPAWN_ADULT, OOT_TEMPLE_OF_TIME, "Spawn Adult", "", GameLayout::all} },
	{ OOT_BOSS_DEKU_TREE, { OOT_BOSS_DEKU_TREE, OOT_DEKU_TREE, "Gohma's Lair", "", GameLayout::all} },
	{ OOT_BOSS_DODONGO_CAVERN, { OOT_BOSS_DODONGO_CAVERN, OOT_DODONGO_CAVERN, "King Dodongo's Lair", "", GameLayout::all} },
	{ OOT_BOSS_JABU_JABU, { OOT_BOSS_JABU_JABU, OOT_INSIDE_JABU_JABU, "Barinade's Lair", "", GameLayout::all} },
	{ OOT_BOSS_TEMPLE_FOREST, { OOT_BOSS_TEMPLE_FOREST, OOT_TEMPLE_FOREST, "Phantom Ganon's Lair", "", GameLayout::all} },
	{ OOT_BOSS_TEMPLE_FIRE, { OOT_BOSS_TEMPLE_FIRE, OOT_TEMPLE_FIRE, "Volvagia's Lair", "", GameLayout::all} },
	{ OOT_BOSS_TEMPLE_WATER, { OOT_BOSS_TEMPLE_WATER, OOT_TEMPLE_WATER, "Morpha's Lair", "", GameLayout::all} },
	{ OOT_BOSS_TEMPLE_SHADOW, { OOT_BOSS_TEMPLE_SHADOW, OOT_TEMPLE_SHADOW, "Bongo-Bongo's Lair", "", GameLayout::all} },
	{ OOT_BOSS_TEMPLE_SPIRIT, { OOT_BOSS_TEMPLE_SPIRIT, OOT_TEMPLE_SPIRIT, "Twinrova's Lair", "", GameLayout::all} },
	{ OOT_DEKU_TREE, { OOT_DEKU_TREE, OOT_KOKIRI_FOREST, "Deku Tree", "", GameLayout::all} },
	{ OOT_DODONGO_CAVERN, { OOT_DODONGO_CAVERN, OOT_DEATH_MOUNTAIN_TRAIL, "Dodongo Cavern", "", GameLayout::all} },
	{ OOT_JABU_JABU, { OOT_JABU_JABU, OOT_ZORA_FOUNTAIN, "Inside Jabu-Jabu", "", GameLayout::all} },
	{ OOT_TEMPLE_FOREST, { OOT_TEMPLE_FOREST, OOT_SACRED_FOREST_MEADOW, "Forest Temple", "", GameLayout::all} },
	{ OOT_TEMPLE_FIRE, { OOT_TEMPLE_FIRE, OOT_DEATH_MOUNTAIN_CRATER, "Fire Temple", "", GameLayout::all} },
	{ OOT_TEMPLE_WATER, { OOT_TEMPLE_WATER, OOT_LAKE_HYLIA, "Water Temple", "", GameLayout::all} },
	{ OOT_TEMPLE_SHADOW, { OOT_TEMPLE_SHADOW, OOT_GRAVEYARD, "Shadow Temple", "", GameLayout::all} },
	{ OOT_TEMPLE_SPIRIT, { OOT_TEMPLE_SPIRIT, OOT_DESERT_COLOSSUS, "Spirit Temple", "", GameLayout::all} },
	{ OOT_BOTTOM_OF_THE_WELL, { OOT_BOTTOM_OF_THE_WELL, OOT_KAKARIKO_VILLAGE, "Bottom of the Well", "", GameLayout::all} },
	{ OOT_ICE_CAVERN, { OOT_ICE_CAVERN, OOT_ZORA_FOUNTAIN, "Ice Cavern", "", GameLayout::all} },
	{ OOT_GERUDO_TRAINING_GROUNDS, { OOT_GERUDO_TRAINING_GROUNDS, OOT_GERUDO_FORTRESS, "Gerudo Training Ground", "", GameLayout::all} },
	{ OOT_GANON_CASTLE, { OOT_GANON_CASTLE, OOT_INSIDE_GANON_CASTLE, "Inside Ganon Castle From Outside", "", GameLayout::all} },
	{ OOT_GANON_TOWER, { OOT_GANON_TOWER, OOT_GANON_TOWER, "Ganon Tower From Inside Ganon Castle", "", GameLayout::all} },
	{ OOT_KOKIRI_FOREST_FROM_DEKU_TREE, { OOT_KOKIRI_FOREST_FROM_DEKU_TREE, OOT_KOKIRI_FOREST, "Kokiri Forest From Deku Tree", "", GameLayout::all} },
	{ OOT_MOUNTAIN_TRAIL_FROM_DODONGO_CAVERN, { OOT_MOUNTAIN_TRAIL_FROM_DODONGO_CAVERN, OOT_DEATH_MOUNTAIN_TRAIL, "Death Mountain Trail From Dodongo Cavern", "", GameLayout::all} },
	{ OOT_ZORA_FOUNTAIN_FROM_JABU_JABU, { OOT_ZORA_FOUNTAIN_FROM_JABU_JABU, OOT_ZORA_FOUNTAIN, "Zora Fountain From Jabu-Jabu", "", GameLayout::all} },
	{ OOT_SACRED_MEADOW_FROM_TEMPLE_FOREST, { OOT_SACRED_MEADOW_FROM_TEMPLE_FOREST, OOT_SACRED_FOREST_MEADOW, "Sacred Forest Meadow From Forest Temple", "", GameLayout::all} },
	{ OOT_DEATH_CRATER_FROM_TEMPLE_FIRE, { OOT_DEATH_CRATER_FROM_TEMPLE_FIRE, OOT_DEATH_MOUNTAIN_CRATER, "Death Mountain Crater From Fire Temple", "", GameLayout::all} },
	{ OOT_LAKE_HYLIA_FROM_TEMPLE_WATER, { OOT_LAKE_HYLIA_FROM_TEMPLE_WATER, OOT_LAKE_HYLIA, "Lake Hylia From Water Temple", "", GameLayout::all} },
	{ OOT_GRAVEYARD_FROM_TEMPLE_SHADOW, { OOT_GRAVEYARD_FROM_TEMPLE_SHADOW, OOT_GRAVEYARD, "Graveyard From Shadow Temple", "", GameLayout::all} },
	{ OOT_DESERT_COLOSSUS_FROM_TEMPLE_SPIRIT, { OOT_DESERT_COLOSSUS_FROM_TEMPLE_SPIRIT, OOT_DESERT_COLOSSUS, "Desert Colossus From Spirit Temple", "", GameLayout::all} },
	{ OOT_KAKARIKO_FROM_BOTTOM_OF_THE_WELL, { OOT_KAKARIKO_FROM_BOTTOM_OF_THE_WELL, OOT_KAKARIKO_VILLAGE, "Kakariko From Bottom of the Well", "", GameLayout::all} },
	{ OOT_ZORA_FOUNTAIN_FROM_ICE_CAVERN, { OOT_ZORA_FOUNTAIN_FROM_ICE_CAVERN, OOT_ZORA_FOUNTAIN, "Zora Fountain From Ice Cavern", "", GameLayout::all} },
	{ OOT_GERUDO_FORTRESS_FROM_GERUDO_TRAINING, { OOT_GERUDO_FORTRESS_FROM_GERUDO_TRAINING, OOT_GERUDO_FORTRESS, "Gerudo Fortress From Gerudo Training Ground", "", GameLayout::all} },
	{ OOT_GANON_CASTLE_EXTERIOR_FROM_CASTLE, { OOT_GANON_CASTLE_EXTERIOR_FROM_CASTLE, OOT_GANON_CASTLE_EXTERIOR, "Ganon Castle Exterior From Ganon Castle", "", GameLayout::all} },
	{ OOT_GANON_CASTLE_FROM_TOWER, { OOT_GANON_CASTLE_FROM_TOWER, OOT_INSIDE_GANON_CASTLE, "Inside Ganon Castle From Ganon Tower", "", GameLayout::all} },
	{ OOT_LOST_WOODS_BRIDGE_FROM_FIELD, { OOT_LOST_WOODS_BRIDGE_FROM_FIELD, OOT_LOST_WOODS, "Lost Woods Bridge From Hyrule Field", "", GameLayout::all} },
	{ OOT_ZORA_RIVER_FROM_FIELD, { OOT_ZORA_RIVER_FROM_FIELD, OOT_ZORA_RIVER, "Zora River From Hyrule Field", "", GameLayout::all} },
	{ OOT_KAKARIKO_FROM_FIELD, { OOT_KAKARIKO_FROM_FIELD, OOT_KAKARIKO_VILLAGE, "Kakariko From Hyrule Field", "", GameLayout::all} },
	{ OOT_LON_LON_RANCH_FROM_FIELD, { OOT_LON_LON_RANCH_FROM_FIELD, OOT_LON_LON_RANCH, "Lon Lon's Ranch From Hyrule Field", "", GameLayout::all} },
	{ OOT_LAKE_HYLIA_FROM_FIELD, { OOT_LAKE_HYLIA_FROM_FIELD, OOT_LAKE_HYLIA, "Lake Hylia From Hyrule Field", "", GameLayout::all} },
	{ OOT_GERUDO_FORTRESS_FROM_VALLEY, { OOT_GERUDO_FORTRESS_FROM_VALLEY, OOT_GERUDO_FORTRESS, "Gerudo Fortress From Gerudo Valley", "", GameLayout::all} },
	{ OOT_DEATH_MOUNTAIN_FROM_KAKARIKO, { OOT_DEATH_MOUNTAIN_FROM_KAKARIKO, OOT_DEATH_MOUNTAIN_TRAIL, "Death Mountain Trail From Kakariko", "", GameLayout::all} },
	{ OOT_GERUDO_VALLEY_FROM_FIELD, { OOT_GERUDO_VALLEY_FROM_FIELD, OOT_GERUDO_VALLEY, "Gerudo Valley From Hyrule Field", "", GameLayout::all} },
	{ OOT_MARKET_ENTRANCE_FROM_FIELD, { OOT_MARKET_ENTRANCE_FROM_FIELD, OOT_MARKET, "Market Entrance From Hyrule Field", "", GameLayout::all} },
	{ OOT_ZORA_RIVER_FROM_LOST_WOODS, { OOT_ZORA_RIVER_FROM_LOST_WOODS, OOT_ZORA_RIVER, "Zora River From Lost Woods", "", GameLayout::all} },
	{ OOT_GORON_CITY_FROM_LOST_WOODS, { OOT_GORON_CITY_FROM_LOST_WOODS, OOT_GORON_CITY, "Goron City From Lost Woods", "", GameLayout::all} },
	{ OOT_LAKE_HYLIA_FROM_ZORA_DOMAIN, { OOT_LAKE_HYLIA_FROM_ZORA_DOMAIN, OOT_LAKE_HYLIA, "Lake Hylia From Zora Domain's Shortcut", "", GameLayout::all} },
	{ OOT_FIELD_FROM_LOST_WOODS_BRIDGE, { OOT_FIELD_FROM_LOST_WOODS_BRIDGE, OOT_HYRULE_FIELD, "Hyrule Field From Lost Woods Bridge", "", GameLayout::all} },
	{ OOT_FIELD_FROM_ZORA_RIVER, { OOT_FIELD_FROM_ZORA_RIVER, OOT_HYRULE_FIELD, "Hyrule Field From Zora River", "", GameLayout::all} },
	{ OOT_FIELD_FROM_KAKARIKO, { OOT_FIELD_FROM_KAKARIKO, OOT_HYRULE_FIELD, "Hyrule Field From Kakariko", "", GameLayout::all} },
	{ OOT_FIELD_FROM_LON_LON_RANCH, { OOT_FIELD_FROM_LON_LON_RANCH, OOT_HYRULE_FIELD, "Hyrule Field From Lon Lon's Ranch", "", GameLayout::all} },
	{ OOT_FIELD_FROM_LAKE_HYLIA, { OOT_FIELD_FROM_LAKE_HYLIA, OOT_HYRULE_FIELD, "Hyrule Field From Lake Hylia", "", GameLayout::all} },
	{ OOT_FIELD_FROM_GERUDO_VALLEY, { OOT_FIELD_FROM_GERUDO_VALLEY, OOT_HYRULE_FIELD, "Hyrule Field From Gerudo Valley", "", GameLayout::all} },
	{ OOT_VALLEY_FROM_GERUDO_FORTRESS, { OOT_VALLEY_FROM_GERUDO_FORTRESS, OOT_GERUDO_VALLEY, "Gerudo Valley From Gerudo Fortress", "", GameLayout::all} },
	{ OOT_KAKARIKO_FROM_DEATH_MOUNTAIN, { OOT_KAKARIKO_FROM_DEATH_MOUNTAIN, OOT_KAKARIKO_VILLAGE, "Kakariko From Death Mountain Trail", "", GameLayout::all} },
	{ OOT_FIELD_FROM_MARKET_ENTRANCE, { OOT_FIELD_FROM_MARKET_ENTRANCE, OOT_HYRULE_FIELD, "Hyrule Field From Market Entrance", "", GameLayout::all} },
	{ OOT_LOST_WOODS_FROM_ZORA_RIVER, { OOT_LOST_WOODS_FROM_ZORA_RIVER, OOT_LOST_WOODS, "Lost Woods From Zora River", "", GameLayout::all} },
	{ OOT_LOST_WOODS_FROM_GORON_CITY, { OOT_LOST_WOODS_FROM_GORON_CITY, OOT_LOST_WOODS, "Lost Woods From Goron City", "", GameLayout::all} },
	{ OOT_ZORA_DOMAIN_FROM_LAKE_HYLIA, { OOT_ZORA_DOMAIN_FROM_LAKE_HYLIA, OOT_ZORA_DOMAIN, "Zora Domain From Lake Hylia's Shortcut", "", GameLayout::all} },
	{ OOT_SACRED_FOREST_MEADOW, { OOT_SACRED_FOREST_MEADOW, OOT_SACRED_FOREST_MEADOW, "Sacred Meadow From Lost Woods", "", GameLayout::all} },
	{ OOT_LOST_WOODS_FROM_MEADOW, { OOT_LOST_WOODS_FROM_MEADOW, OOT_LOST_WOODS, "Lost Woods Woods From Sacred Forest Meadow", "", GameLayout::all} },
	{ OOT_GORON_CITY, { OOT_GORON_CITY, OOT_GORON_CITY, "Goron City From Death Mountain Trail", "", GameLayout::all} },
	{ OOT_DEATH_MOUNTAIN_FROM_GORON_CITY, { OOT_DEATH_MOUNTAIN_FROM_GORON_CITY, OOT_DEATH_MOUNTAIN_TRAIL, "Death Mountain Trail From Goron City", "", GameLayout::all} },
	{ OOT_ZORA_DOMAIN, { OOT_ZORA_DOMAIN, OOT_ZORA_DOMAIN, "Zora Domain From Zora River", "", GameLayout::all} },
	{ OOT_RIVER_FROM_DOMAIN, { OOT_RIVER_FROM_DOMAIN, OOT_ZORA_RIVER, "Zora River From Zora Domain", "", GameLayout::all} },
	{ OOT_FOUNTAIN_ZORA, { OOT_FOUNTAIN_ZORA, OOT_ZORA_FOUNTAIN, "Zora Fountain From Zora Domain", "", GameLayout::all} },
	{ OOT_DOMAIN_FROM_FOUNTAIN, { OOT_DOMAIN_FROM_FOUNTAIN, OOT_ZORA_DOMAIN, "Zora Domain From Zora Fountain", "", GameLayout::all} },
	{ OOT_CRATER_FROM_GORON_CITY, { OOT_CRATER_FROM_GORON_CITY, OOT_DEATH_MOUNTAIN_CRATER, "Death Mountain Crater From Goron City", "", GameLayout::all} },
	{ OOT_GORON_CITY_FROM_CRATER, { OOT_GORON_CITY_FROM_CRATER, OOT_GORON_CITY, "Goron City From Death Mountain Crater", "", GameLayout::all} },
	{ OOT_DEATH_MOUNTAIN_CRATER, { OOT_DEATH_MOUNTAIN_CRATER, OOT_DEATH_MOUNTAIN_CRATER, "Death Mountain Crater From Death Mountain Trail", "", GameLayout::all} },
	{ OOT_TRAIL_SUMMIT_FROM_CRATER, { OOT_TRAIL_SUMMIT_FROM_CRATER, OOT_DEATH_MOUNTAIN_TRAIL, "Death Mountain Trail From Death Mountain Crater", "", GameLayout::all} },
	{ OOT_LOST_WOODS_FROM_KOKIRI_FOREST, { OOT_LOST_WOODS_FROM_KOKIRI_FOREST, OOT_LOST_WOODS, "Lost Woods From Kokiri Forest", "", GameLayout::all} },
	{ OOT_KOKIRI_FOREST_FROM_LOST_WOODS, { OOT_KOKIRI_FOREST_FROM_LOST_WOODS, OOT_KOKIRI_FOREST, "Kokiri Forest From Lost Woods", "", GameLayout::all} },
	{ OOT_FOREST_FROM_LOST_WOODS_BRIDGE, { OOT_FOREST_FROM_LOST_WOODS_BRIDGE, OOT_LOST_WOODS, "Kokiri Forest From Lost Woods Bridge", "", GameLayout::all} },
	{ OOT_LOST_WOODS_BRIDGE_FROM_FOREST, { OOT_LOST_WOODS_BRIDGE_FROM_FOREST, OOT_LOST_WOODS, "Lost Woods Bridge From Kokiri Forest", "", GameLayout::all} },
	{ OOT_GRAVEYARD, { OOT_GRAVEYARD, OOT_GRAVEYARD, "Graveyard From Kakariko", "", GameLayout::all} },
	{ OOT_KAKARIKO_FROM_GRAVEYARD, { OOT_KAKARIKO_FROM_GRAVEYARD, OOT_KAKARIKO_VILLAGE, "Kakariko From Graveyard", "", GameLayout::all} },
	{ OOT_WASTELAND, { OOT_WASTELAND, OOT_HAUNTED_WASTELAND, "Haunted Wasteland From Gerudo Fortress", "", GameLayout::all} },
	{ OOT_FORTRESS_FROM_WASTELAND, { OOT_FORTRESS_FROM_WASTELAND, OOT_GERUDO_FORTRESS, "Gerudo Fortress From Haunted Wasteland", "", GameLayout::all} },
	{ OOT_COLOSSUS, { OOT_COLOSSUS, OOT_DESERT_COLOSSUS, "Desert Colossus From Haunted Wasteland", "", GameLayout::all} },
	{ OOT_WASTELAND_FROM_COLOSSUS, { OOT_WASTELAND_FROM_COLOSSUS, OOT_HAUNTED_WASTELAND, "Haunted Wasteland From Desert Colossus", "", GameLayout::all} },
	{ OOT_MARKET_FROM_MARKET_ENTRANCE, { OOT_MARKET_FROM_MARKET_ENTRANCE, OOT_MARKET, "Market From Market Entrance", "", GameLayout::all} },
	{ OOT_MARKET_ENTRANCE_FROM_MARKET, { OOT_MARKET_ENTRANCE_FROM_MARKET, OOT_MARKET_ENTRANCE, "Market Entrance From Market", "", GameLayout::all} },
	{ OOT_HYRULE_CASTLE, { OOT_HYRULE_CASTLE, OOT_HYRULE_CASTLE, "Hyrule Castle - Market Entrance", "", GameLayout::all} },
	{ OOT_MARKET_FROM_CASTLE, { OOT_MARKET_FROM_CASTLE, OOT_MARKET, "Market - Hyrule Castle Entrance", "", GameLayout::all} },
	{ OOT_MARKET_FROM_TEMPLE_OF_TIME_ENTRYWAY, { OOT_MARKET_FROM_TEMPLE_OF_TIME_ENTRYWAY, OOT_MARKET, "Market - Temple of Time Entryway Entrance", "", GameLayout::all} },
	{ OOT_TEMPLE_OF_TIME_ENTRYWAY_FROM_MARKET, { OOT_TEMPLE_OF_TIME_ENTRYWAY_FROM_MARKET, OOT_TEMPLE_OF_TIME_ENTRYWAY, "Temple of Time Entryway - Market Entrance", "", GameLayout::all} },
	{ OOT_LAKE_HYLIA_FROM_VALLEY, { OOT_LAKE_HYLIA_FROM_VALLEY, OOT_LAKE_HYLIA, "Gerudo Valley Waterfalls To Lake Hylia", "", GameLayout::all} },
	{ OOT_LOST_WOODS_FROM_LOST_WOODS_NORTH, { OOT_LOST_WOODS_FROM_LOST_WOODS_NORTH, OOT_LOST_WOODS, "Lost Woods North Wrong Exit", "", GameLayout::all} },
	{ OOT_LOST_WOODS_FROM_LOST_WOODS_EAST, { OOT_LOST_WOODS_FROM_LOST_WOODS_EAST, OOT_LOST_WOODS, "Lost Woods East Wrong Exit ", "", GameLayout::all} },
	{ OOT_LOST_WOODS_FROM_LOST_WOODS_SOUTH, { OOT_LOST_WOODS_FROM_LOST_WOODS_SOUTH, OOT_LOST_WOODS, "Lost Woods South Wrong Exit", "", GameLayout::all} },
	{ OOT_LOST_WOODS_FROM_LOST_WOODS_WEST, { OOT_LOST_WOODS_FROM_LOST_WOODS_WEST, OOT_LOST_WOODS, "Lost Woods West Wrong Exit", "", GameLayout::all} },
	{ OOT_HOUSE_MIDO, { OOT_HOUSE_MIDO, OOT_KOKIRI_MIDO, "Mido's House Entrance", "", GameLayout::all} },
	{ OOT_HOUSE_SARIA, { OOT_HOUSE_SARIA, OOT_KOKIRI_SARIA, "Saria's House Entrance", "", GameLayout::all} },
	{ OOT_HOUSE_TWINS, { OOT_HOUSE_TWINS, OOT_KOKIRI_TWINS, "Twin's House Entrance", "", GameLayout::all} },
	{ OOT_HOUSE_KNOW_IT_ALL, { OOT_HOUSE_KNOW_IT_ALL, OOT_KOKIRI_KNOW_IT_ALL, "Know-It-All Brothers Entrance", "", GameLayout::all} },
	{ OOT_KOKIRI_SHOP, { OOT_KOKIRI_SHOP, OOT_KOKIRI_SHOP, "Kokiri Shop Entrance", "", GameLayout::all} },
	{ OOT_HOUSE_POTS, { OOT_HOUSE_POTS, OOT_GUARD_HOUSE, "House Pots From Market Entrance", "", GameLayout::all} },
	{ OOT_LABORATORY, { OOT_LABORATORY, OOT_LABORATORY, "Laboratory From Lake Hylia", "", GameLayout::all} },
	{ OOT_FISHING_POND, { OOT_FISHING_POND, OOT_FISHING_POND, "Fishing Pond From Lake Hylia", "", GameLayout::all} },
	{ OOT_VALLEY_TENT, { OOT_VALLEY_TENT, OOT_CARPENTER_TENT, "Carpenter's Tent Entrance", "", GameLayout::all} },
	{ OOT_HOUSE_CARPENTER, { OOT_HOUSE_CARPENTER, OOT_CARPENTER_BOSS_HOUSE, "Carpenter's Boss House Entrance", "", GameLayout::all} },
	{ OOT_HOUSE_SKULLTULA, { OOT_HOUSE_SKULLTULA, OOT_HOUSE_OF_SKULLTULA, "House of Skulltula Entrance", "", GameLayout::all} },
	{ OOT_HOUSE_IMPA, { OOT_HOUSE_IMPA, OOT_IMPA_HOUSE, "Impa House Entrance", "", GameLayout::all} },
	{ OOT_HOUSE_IMPA_BACK, { OOT_HOUSE_IMPA_BACK, OOT_IMPA_HOUSE, "Impa House Back Entrance", "", GameLayout::all} },
	{ OOT_SHOP_GRANNY, { OOT_SHOP_GRANNY, OOT_GRANNY_POTION_SHOP, "Granny Potion Shop Entrance", "", GameLayout::all} },
	{ OOT_HOUSE_DAMPE, { OOT_HOUSE_DAMPE, OOT_DAMPE_HOUSE, "", "", GameLayout::all} },
	{ OOT_SHOP_GORON, { OOT_SHOP_GORON, OOT_GORON_SHOP, "", "", GameLayout::all} },
	{ OOT_SHOP_ZORA, { OOT_SHOP_ZORA, OOT_ZORA_SHOP, "", "", GameLayout::all} },
	{ OOT_HOUSE_LON_LON, { OOT_HOUSE_LON_LON, OOT_RANCH_HOUSE_SILO, "Lon Lon Ranc", "", GameLayout::all} },
	{ OOT_SILO, { OOT_SILO, OOT_SILO, "Lon Ranch", "", GameLayout::all} },
	{ OOT_STABLES, { OOT_STABLES, OOT_STABLE, "Lon Ranch", "", GameLayout::all} },
	{ OOT_FAIRY_MAGIC, { OOT_FAIRY_MAGIC, OOT_GREAT_FAIRY_MAGIC, "", "", GameLayout::all} },
	{ OOT_FAIRY_MAGIC2, { OOT_FAIRY_MAGIC2, OOT_GREAT_FAIRY_MAGIC2, "", "", GameLayout::all} },
	{ OOT_FAIRY_DIN, { OOT_FAIRY_DIN, OOT_GREAT_FAIRY_CASTLE, "", "", GameLayout::all} },
	{ OOT_FAIRY_FARORE, { OOT_FAIRY_FARORE, OOT_GREAT_FAIRY_FARORE, "", "", GameLayout::all} },
	{ OOT_FAIRY_NAYRU, { OOT_FAIRY_NAYRU, OOT_GREAT_FAIRY_NAYRU, "", "", GameLayout::all} },
	{ OOT_FAIRY_DEFENSE, { OOT_FAIRY_DEFENSE, OOT_GREAT_FAIRY_CASTLE, "", "", GameLayout::all} },
	{ OOT_BOMBCHU_BOWLING, { OOT_BOMBCHU_BOWLING, OOT_BOMBCHU_BOWLING_ALLEY, "", "", GameLayout::all} },
	{ OOT_TREASURE_GAME, { OOT_TREASURE_GAME, OOT_TREASURE_SHOP, "", "", GameLayout::all} },
	{ OOT_BOMBCHU_SHOP, { OOT_BOMBCHU_SHOP, OOT_BOMBCHU_SHOP, "", "", GameLayout::all} },
	{ OOT_ALLEY_HOUSE, { OOT_ALLEY_HOUSE, OOT_BACK_ALLEY_HOUSE2, "", "", GameLayout::all} },
	{ OOT_MARKET_BAZAAR, { OOT_MARKET_BAZAAR, OOT_MARKET_BAZAAR, "", "", GameLayout::all} },
	{ OOT_MARKET_POTION, { OOT_MARKET_POTION, OOT_MARKET_POTION_SHOP, "", "", GameLayout::all} },
	{ OOT_CHILD_ARCHERY, { OOT_CHILD_ARCHERY, OOT_MARKET_SHOOTING, "", "", GameLayout::all} },
	{ OOT_KAKARIKO_BAZAAR, { OOT_KAKARIKO_BAZAAR, OOT_KAKARIKO_BAZAAR, "", "", GameLayout::all} },
	{ OOT_ADULT_ARCHERY, { OOT_ADULT_ARCHERY, OOT_KAKARIKO_SHOOTING, "", "", GameLayout::all} },
	{ OOT_HOUSE_LINK, { OOT_HOUSE_LINK, OOT_LINK_HOUSE, "", "", GameLayout::all} },
	{ OOT_TEMPLE_OF_TIME, { OOT_TEMPLE_OF_TIME, OOT_TEMPLE_OF_TIME, "Temple of Tim", "", GameLayout::all} },
	{ OOT_WINDMILL, { OOT_WINDMILL, OOT_WINDMILL, "OOT Windmill", "", GameLayout::all} },
	{ OOT_SHOP_POTION_KAKARIKO, { OOT_SHOP_POTION_KAKARIKO, OOT_KAKARIKO_POTION_SHOP, "Kakariko Potion Sho", "", GameLayout::all} },
	{ OOT_SHOP_POTION_KAKARIKO_BACK, { OOT_SHOP_POTION_KAKARIKO_BACK, OOT_KAKARIKO_POTION_SHOP, "", "", GameLayout::all} },
	{ OOT_KOKIRI_FOREST_FROM_MIDO, { OOT_KOKIRI_FOREST_FROM_MIDO, OOT_KOKIRI_FOREST, "Kokiri Forest Forest Mido's House", "", GameLayout::all} },
	{ OOT_KOKIRI_FOREST_FROM_SARIA, { OOT_KOKIRI_FOREST_FROM_SARIA, OOT_KOKIRI_FOREST, "Kokiri Forest Forest Saria's House", "", GameLayout::all} },
	{ OOT_KOKIRI_FOREST_FROM_TWINS, { OOT_KOKIRI_FOREST_FROM_TWINS, OOT_KOKIRI_FOREST, "Kokiri Forest Forest of Twins", "", GameLayout::all} },
	{ OOT_KOKIRI_FOREST_FROM_KNOW_IT_ALL, { OOT_KOKIRI_FOREST_FROM_KNOW_IT_ALL, OOT_KOKIRI_FOREST, "Kokiri Forest Know All House", "", GameLayout::all} },
	{ OOT_KOKIRI_FOREST_FROM_SHOP, { OOT_KOKIRI_FOREST_FROM_SHOP, OOT_KOKIRI_FOREST, "Kokiri Forest Forest Kokiri Shop", "", GameLayout::all} },
	{ OOT_MARKET_ENTRANCE_FROM_POTS, { OOT_MARKET_ENTRANCE_FROM_POTS, OOT_MARKET_ENTRANCE, "Market Entrance Entrance Pot House", "", GameLayout::all} },
	{ OOT_LAKE_HYLIA_FROM_LABORATORY, { OOT_LAKE_HYLIA_FROM_LABORATORY, OOT_LAKE_HYLIA, "Lake Hylia Hylia OOT Laboratory", "", GameLayout::all} },
	{ OOT_LAKE_HYLIA_FROM_FISHING_POND, { OOT_LAKE_HYLIA_FROM_FISHING_POND, OOT_LAKE_HYLIA, "", "", GameLayout::all} },
	{ OOT_GERUDO_VALLEY_FROM_TENT, { OOT_GERUDO_VALLEY_FROM_TENT, OOT_GERUDO_VALLEY, "", "", GameLayout::all} },
	{ OOT_KAKARIKO_FROM_CARPENTER, { OOT_KAKARIKO_FROM_CARPENTER, OOT_KAKARIKO_VILLAGE, "Kakarik", "", GameLayout::all} },
	{ OOT_KAKARIKO_FROM_SKULLTULA, { OOT_KAKARIKO_FROM_SKULLTULA, OOT_KAKARIKO_VILLAGE, "Kakarik", "", GameLayout::all} },
	{ OOT_KAKARIKO_FROM_IMPA, { OOT_KAKARIKO_FROM_IMPA, OOT_KAKARIKO_VILLAGE, "Kakarik", "", GameLayout::all} },
	{ OOT_KAKARIKO_FROM_IMPA_BACK, { OOT_KAKARIKO_FROM_IMPA_BACK, OOT_KAKARIKO_VILLAGE, "Kakariko From House Back", "", GameLayout::all} },
	{ OOT_KAKARIKO_FROM_GRANNY, { OOT_KAKARIKO_FROM_GRANNY, OOT_KAKARIKO_VILLAGE, "Kakariko Bac", "", GameLayout::all} },
	{ OOT_GRAVEYARD_FROM_DAMPE, { OOT_GRAVEYARD_FROM_DAMPE, OOT_GRAVEYARD, "Graveyar", "", GameLayout::all} },
	{ OOT_GORON_CITY_FROM_SHOP, { OOT_GORON_CITY_FROM_SHOP, OOT_GORON_CITY, "Goron City City Goron Shop", "", GameLayout::all} },
	{ OOT_ZORA_DOMAIN_FROM_SHOP, { OOT_ZORA_DOMAIN_FROM_SHOP, OOT_ZORA_DOMAIN, "Zora Domain Domain Zora Shop", "", GameLayout::all} },
	{ OOT_LON_LON_RANCH_FROM_HOUSE, { OOT_LON_LON_RANCH_FROM_HOUSE, OOT_LON_LON_RANCH, "Lon Lon Ranch Ranch Ranch House", "", GameLayout::all} },
	{ OOT_LON_LON_RANCH_FROM_STABLES, { OOT_LON_LON_RANCH_FROM_STABLES, OOT_LON_LON_RANCH, "Lon Lon Ranch Ranch Ranch Stables", "", GameLayout::all} },
	{ OOT_LON_LON_RANCH_FROM_SILO, { OOT_LON_LON_RANCH_FROM_SILO, OOT_LON_LON_RANCH, "Lon Lon Ranch Ranch Ranch Silo", "", GameLayout::all} },
	{ OOT_KOKIRI_FOREST_FROM_LINK, { OOT_KOKIRI_FOREST_FROM_LINK, OOT_KOKIRI_FOREST, "Kokiri Forest Forest Link's House", "", GameLayout::all} },
	{ OOT_TEMPLE_OF_TIME_ENTRYWAY_FROM_TEMPLE, { OOT_TEMPLE_OF_TIME_ENTRYWAY_FROM_TEMPLE, OOT_TEMPLE_OF_TIME_ENTRYWAY, "Temple Of Time Entryway Entryway of Time", "", GameLayout::all} },
	{ OOT_KAKARIKO_FROM_WINDMILL, { OOT_KAKARIKO_FROM_WINDMILL, OOT_WINDMILL, "Kakarik", "", GameLayout::all} },
	{ OOT_KAKARIKO_FROM_SHOP_POTION, { OOT_KAKARIKO_FROM_SHOP_POTION, OOT_KAKARIKO_POTION_SHOP, "Kakariko Potion Shop From Potion Shop", "", GameLayout::all} },
	{ OOT_KAKARIKO_FROM_SHOP_POTION_BACK, { OOT_KAKARIKO_FROM_SHOP_POTION_BACK, OOT_KAKARIKO_POTION_SHOP, "Kakariko Potion Shop Shop Shop Back", "", GameLayout::all} },
	{ OOT_DEATH_MOUNTAIN_FROM_FAIRY, { OOT_DEATH_MOUNTAIN_FROM_FAIRY, OOT_DEATH_MOUNTAIN_TRAIL, "Death Moutain Trail Mountain Fountain Magic", "", GameLayout::all} },
	{ OOT_DEATH_CRATER_FROM_FAIRY, { OOT_DEATH_CRATER_FROM_FAIRY, OOT_DEATH_MOUNTAIN_CRATER, "", "", GameLayout::all} },
	{ OOT_HYRULE_CASTLE_FROM_FAIRY, { OOT_HYRULE_CASTLE_FROM_FAIRY, OOT_HYRULE_CASTLE, "", "", GameLayout::all} },
	{ OOT_ZORA_FOUNTAIN_FROM_FAIRY, { OOT_ZORA_FOUNTAIN_FROM_FAIRY, OOT_ZORA_FOUNTAIN, "Zora Foutain Fountain Fountain Farore", "", GameLayout::all} },
	{ OOT_DESERT_COLOSSUS_FROM_FAIRY, { OOT_DESERT_COLOSSUS_FROM_FAIRY, OOT_DESERT_COLOSSUS, "Desert Colossus Colossus Fountain Nayru", "", GameLayout::all} },
	{ OOT_MARKET_FROM_BOWLING, { OOT_MARKET_FROM_BOWLING, OOT_MARKET, "Marke", "", GameLayout::all} },
	{ OOT_MARKET_FROM_TREASURE_GAME, { OOT_MARKET_FROM_TREASURE_GAME, OOT_MARKET, "Market From Chest Game", "", GameLayout::all} },
	{ OOT_MARKET_FROM_BOMBCHU_SHOP, { OOT_MARKET_FROM_BOMBCHU_SHOP, OOT_MARKET, "Market From Bombchu Shop", "", GameLayout::all} },
	{ OOT_MARKET_FROM_ALLEY_HOUSE, { OOT_MARKET_FROM_ALLEY_HOUSE, OOT_MARKET, "Market From East Home", "", GameLayout::all} },
	{ OOT_MARKET_FROM_BAZAAR, { OOT_MARKET_FROM_BAZAAR, OOT_MARKET, "Marke", "", GameLayout::all} },
	{ OOT_MARKET_FROM_POTION, { OOT_MARKET_FROM_POTION, OOT_MARKET, "Marke", "", GameLayout::all} },
	{ OOT_MARKET_FROM_ARCHERY, { OOT_MARKET_FROM_ARCHERY, OOT_MARKET, "Marke", "", GameLayout::all} },
	{ OOT_KAKARIKO_FROM_BAZAAR, { OOT_KAKARIKO_FROM_BAZAAR, OOT_KAKARIKO_VILLAGE, "Kakarik", "", GameLayout::all} },
	{ OOT_KAKARIKO_FROM_ARCHERY, { OOT_KAKARIKO_FROM_ARCHERY, OOT_KAKARIKO_VILLAGE, "Kakarik", "", GameLayout::all} },
	{ OOT_OUTSIDE_GANON_FROM_FAIRY, { OOT_OUTSIDE_GANON_FROM_FAIRY, OOT_GANON_CASTLE_EXTERIOR, "", "", GameLayout::all} },
	{ OOT_WARP_SONG_MEADOW, { OOT_WARP_SONG_MEADOW, OOT_SACRED_FOREST_MEADOW, "Sacred Meado", "", GameLayout::all} },
	{ OOT_WARP_SONG_CRATER, { OOT_WARP_SONG_CRATER, OOT_DEATH_MOUNTAIN_CRATER, "Death Mountain Crater ", "", GameLayout::all} },
	{ OOT_WARP_SONG_LAKE, { OOT_WARP_SONG_LAKE, OOT_LAKE_HYLIA, "Lake Hyli", "", GameLayout::all} },
	{ OOT_WARP_SONG_GRAVE, { OOT_WARP_SONG_GRAVE, OOT_GRAVEYARD, "Graveyard Uppe", "", GameLayout::all} },
	{ OOT_WARP_SONG_DESERT, { OOT_WARP_SONG_DESERT, OOT_DESERT_COLOSSUS, "Desert Colossu", "", GameLayout::all} },
	{ OOT_WARP_SONG_TEMPLE, { OOT_WARP_SONG_TEMPLE, OOT_TEMPLE_OF_TIME, "Temple of Tim", "", GameLayout::all} },
	{ OOT_VILLAGE_OWL, { OOT_VILLAGE_OWL, OOT_DEATH_MOUNTAIN_TRAIL, "Death Mountain Trail Oot Mountain Summit", "", GameLayout::all} },
	{ OOT_FIELD_OWL, { OOT_FIELD_OWL, OOT_LAKE_HYLIA, "Lake Hylia Oot Lake Hylia", "", GameLayout::all} },
	{ OOT_WALLMASTER_FOREST_CORRIDOR_WEST, { OOT_WALLMASTER_FOREST_CORRIDOR_WEST, OOT_TEMPLE_FOREST, "", "", GameLayout::all} },
	{ OOT_WALLMASTER_FOREST_CORRIDOR_EAST, { OOT_WALLMASTER_FOREST_CORRIDOR_EAST, OOT_TEMPLE_FOREST, "", "", GameLayout::all} },
	{ OOT_WALLMASTER_SHADOW, { OOT_WALLMASTER_SHADOW, OOT_TEMPLE_SHADOW, "", "", GameLayout::all} },
	{ OOT_WALLMASTER_SPIRIT_CHILD_RUPEES, { OOT_WALLMASTER_SPIRIT_CHILD_RUPEES, OOT_TEMPLE_SPIRIT, "", "", GameLayout::all} },
	{ OOT_WALLMASTER_SPIRIT_ADULT_CLIMB, { OOT_WALLMASTER_SPIRIT_ADULT_CLIMB, OOT_TEMPLE_SPIRIT, "", "", GameLayout::all} },
	{ OOT_WALLMASTER_SPIRIT_CHILD_SUN, { OOT_WALLMASTER_SPIRIT_CHILD_SUN, OOT_TEMPLE_SPIRIT, "", "", GameLayout::all} },
	{ OOT_WALLMASTER_SPIRIT_STATUE, { OOT_WALLMASTER_SPIRIT_STATUE, OOT_TEMPLE_SPIRIT, "", "", GameLayout::all} },
	{ OOT_WALLMASTER_BOTW_MAIN, { OOT_WALLMASTER_BOTW_MAIN, OOT_BOTTOM_OF_THE_WELL, "", "", GameLayout::all} },
	{ OOT_WALLMASTER_BOTW_BASEMENT, { OOT_WALLMASTER_BOTW_BASEMENT, OOT_BOTTOM_OF_THE_WELL, "", "", GameLayout::all} },
	{ OOT_WALLMASTER_BOTW_PIT, { OOT_WALLMASTER_BOTW_PIT, OOT_BOTTOM_OF_THE_WELL, "", "", GameLayout::all} },
	{ OOT_WALLMASTER_GTG, { OOT_WALLMASTER_GTG, OOT_GERUDO_TRAINING_GROUND, "", "", GameLayout::all} },
	{ OOT_WALLMASTER_GANON_SPIRIT, { OOT_WALLMASTER_GANON_SPIRIT, OOT_INSIDE_GANON_CASTLE, "", "", GameLayout::all} },
	{ OOT_WALLMASTER_GANON_LIGHT, { OOT_WALLMASTER_GANON_LIGHT, OOT_INSIDE_GANON_CASTLE, "", "", GameLayout::all} },
	{ OOT_GROTTO_GENERIC_KOKIRI_FOREST, { OOT_GROTTO_GENERIC_KOKIRI_FOREST, OOT_GROTTO_KOKIRI_FOREST_STORMS, "", "", GameLayout::all} },
	{ OOT_GROTTO_GENERIC_LOST_WOODS, { OOT_GROTTO_GENERIC_LOST_WOODS, OOT_GROTTO_LOST_WOODS_GENERIC, "", "", GameLayout::all} },
	{ OOT_GROTTO_GENERIC_KAKARIKO, { OOT_GROTTO_GENERIC_KAKARIKO, OOT_GROTTO_KAKARIKO_OPEN, "Kakariko Bac", "", GameLayout::all} },
	{ OOT_GROTTO_GENERIC_DMT, { OOT_GROTTO_GENERIC_DMT, OOT_GROTTO_DEATH_TRIAL_STORMS, "Death Mountai", "", GameLayout::all} },
	{ OOT_GROTTO_GENERIC_DMC, { OOT_GROTTO_GENERIC_DMC, OOT_GROTTO_DEATH_CRATER_GENERIC, "Death Mountain Crater ", "", GameLayout::all} },
	{ OOT_GROTTO_GENERIC_RIVER, { OOT_GROTTO_GENERIC_RIVER, OOT_GROTTO_ZORA_RIVER_GENERIC, "Zora River Uppe", "", GameLayout::all} },
	{ OOT_GROTTO_GENERIC_HF_SOUTHEAST, { OOT_GROTTO_GENERIC_HF_SOUTHEAST, OOT_GROTTO_HYRULE_SE, "", "", GameLayout::all} },
	{ OOT_GROTTO_GENERIC_HF_OPEN, { OOT_GROTTO_GENERIC_HF_OPEN, OOT_GROTTO_HYRULE_OPEN, "", "", GameLayout::all} },
	{ OOT_GROTTO_GENERIC_HF_MARKET, { OOT_GROTTO_GENERIC_HF_MARKET, OOT_GROTTO_HYRULE_MARKET, "", "", GameLayout::all} },
	{ OOT_GROTTO_FAIRY_SFM, { OOT_GROTTO_FAIRY_SFM, OOT_FAIRY_SACRED_MEADOW, "Sacred Meado", "", GameLayout::all} },
	{ OOT_GROTTO_FAIRY_HF, { OOT_GROTTO_FAIRY_HF, OOT_FAIRY_HYRULE, "Hyrule Fiel", "", GameLayout::all} },
	{ OOT_GROTTO_FAIRY_RIVER, { OOT_GROTTO_FAIRY_RIVER, OOT_FAIRY_ZORA_RIVER, "Zora River Uppe", "", GameLayout::all} },
	{ OOT_GROTTO_FAIRY_DOMAIN, { OOT_GROTTO_FAIRY_DOMAIN, OOT_FAIRY_ZORA_DOMAIN, "Zora Domai", "", GameLayout::all} },
	{ OOT_GROTTO_FAIRY_FORTRESS, { OOT_GROTTO_FAIRY_FORTRESS, OOT_FAIRY_GERUDO_FORTRESS, "Gerudo Fortress Exteri", "", GameLayout::all} },
	{ OOT_GROTTO_SCRUBS2_SFM, { OOT_GROTTO_SCRUBS2_SFM, OOT_GROTTO_SACRED_MEADOW_STORMS, "Sacred Meado", "", GameLayout::all} },
	{ OOT_GROTTO_SCRUBS2_RIVER, { OOT_GROTTO_SCRUBS2_RIVER, OOT_GROTTO_ZORA_RIVER_STORMS, "Zora Rive", "", GameLayout::all} },
	{ OOT_GROTTO_SCRUBS2_VALLEY, { OOT_GROTTO_SCRUBS2_VALLEY, OOT_GROTTO_VALLEY_STORMS, "Gerudo Valley After Br", "", GameLayout::all} },
	{ OOT_GROTTO_SCRUBS2_COLOSSUS, { OOT_GROTTO_SCRUBS2_COLOSSUS, OOT_GROTTO_DESERT_SCRUBS, "Desert Colossu", "", GameLayout::all} },
	{ OOT_GROTTO_SCRUBS3_RANCH, { OOT_GROTTO_SCRUBS3_RANCH, OOT_GROTTO_LON_LON_SCRUBS, "Lon Lon Ranc", "", GameLayout::all} },
	{ OOT_GROTTO_SCRUBS3_GORON_CITY, { OOT_GROTTO_SCRUBS3_GORON_CITY, OOT_GROTTO_GORON_CITY_SCRUBS, "", "", GameLayout::all} },
	{ OOT_GROTTO_SCRUBS3_DMC, { OOT_GROTTO_SCRUBS3_DMC, OOT_GROTTO_DEATH_CRATER_SCRUBS, "Death Mountain Crater ", "", GameLayout::all} },
	{ OOT_GROTTO_SCRUBS3_LAKE, { OOT_GROTTO_SCRUBS3_LAKE, OOT_GROTTO_LAKE_HYLIA_SCRUBS, "Lake Hyli", "", GameLayout::all} },
	{ OOT_GROTTO_SCRUB_UPGRADE, { OOT_GROTTO_SCRUB_UPGRADE, OOT_GROTTO_LOST_WOODS_SCRUB_UPGRADE, "Lost Woods Dee", "", GameLayout::all} },
	{ OOT_GROTTO_SCRUB_HEART_PIECE, { OOT_GROTTO_SCRUB_HEART_PIECE, OOT_GROTTO_HYRULE_SCRUBS, "", "", GameLayout::all} },
	{ OOT_GROTTO_DEKU_THEATER, { OOT_GROTTO_DEKU_THEATER, OOT_GROTTO_LOST_WOODS_THEATER, "Lost Woods Dee", "", GameLayout::all} },
	{ OOT_GROTTO_WOLFOS, { OOT_GROTTO_WOLFOS, OOT_GROTTO_SACRED_MEADOW_WOLFOS, "Meadow Entryway", "", GameLayout::all} },
	{ OOT_GROTTO_TEKTITE, { OOT_GROTTO_TEKTITE, OOT_GROTTO_HYRULE_TEKTITE, "Hyrule Field", "", GameLayout::all} },
	{ OOT_GROTTO_FIELD_COW, { OOT_GROTTO_FIELD_COW, OOT_GROTTO_HYRULE_GERUDO, "Hyrule Fiel", "", GameLayout::all} },
	{ OOT_GROTTO_FIELD_TREE, { OOT_GROTTO_FIELD_TREE, OOT_GROTTO_HYRULE_KAKARIKO, "Hyrule Fiel", "", GameLayout::all} },
	{ OOT_GROTTO_TRAIL_COW, { OOT_GROTTO_TRAIL_COW, OOT_GROTTO_DEATH_TRIAL_COW, "Death Mountai", "", GameLayout::all} },
	{ OOT_GROTTO_CASTLE, { OOT_GROTTO_CASTLE, OOT_GROTTO_CASTLE_STORMS, "Near Grotto", "", GameLayout::all} },
	{ OOT_GROTTO_REDEAD, { OOT_GROTTO_REDEAD, OOT_GROTTO_KAKARIKO_REDEAD, "OOT Kakariko", "", GameLayout::all} },
	{ OOT_GROTTO_OCTOROK, { OOT_GROTTO_OCTOROK, OOT_GROTTO_VALLEY_OCTOROK, "Grotto Ledge", "", GameLayout::all} },
	{ OOT_GRAVE_SHIELD, { OOT_GRAVE_SHIELD, OOT_TOMB_REDEAD, "", "", GameLayout::all} },
	{ OOT_GRAVE_REDEAD, { OOT_GRAVE_REDEAD, OOT_TOMB_FAIRY, "", "", GameLayout::all} },
	{ OOT_GRAVE_ROYAL, { OOT_GRAVE_ROYAL, OOT_TOMB_ROYAL, "", "", GameLayout::all} },
	{ OOT_GRAVE_DAMPE, { OOT_GRAVE_DAMPE, OOT_TOMB_DAMPE_WINDMILL, "Ortside Graveyard Grave", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_GENERIC_KOKIRI_FOREST, { OOT_GROTTO_EXIT_GENERIC_KOKIRI_FOREST, OOT_KOKIRI_FOREST, "Kokiri Forest Generic Storms Grotto", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_GENERIC_LOST_WOODS, { OOT_GROTTO_EXIT_GENERIC_LOST_WOODS, OOT_LOST_WOODS, "Lost Woods Generic Generic Grotto", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_GENERIC_KAKARIKO, { OOT_GROTTO_EXIT_GENERIC_KAKARIKO, OOT_KAKARIKO_VILLAGE, "Kakariko Exit Generic Grotto", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_GENERIC_DMT, { OOT_GROTTO_EXIT_GENERIC_DMT, OOT_DEATH_MOUNTAIN_TRAIL, "Death Mountain Trail Exit Storms Grotto", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_GENERIC_DMC, { OOT_GROTTO_EXIT_GENERIC_DMC, OOT_DEATH_MOUNTAIN_CRATER, "", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_GENERIC_RIVER, { OOT_GROTTO_EXIT_GENERIC_RIVER, OOT_ZORA_RIVER, "Zora River Exit Open Grotto", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_GENERIC_HF_SOUTHEAST, { OOT_GROTTO_EXIT_GENERIC_HF_SOUTHEAST, OOT_HYRULE_FIELD, "Hyrule Field Generic Southeast Grotto", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_GENERIC_HF_OPEN, { OOT_GROTTO_EXIT_GENERIC_HF_OPEN, OOT_HYRULE_FIELD, "Hyrule Field Generic Open Grotto", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_GENERIC_HF_MARKET, { OOT_GROTTO_EXIT_GENERIC_HF_MARKET, OOT_HYRULE_FIELD, "Hyrule Field Generic Near Market", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_FAIRY_SFM, { OOT_GROTTO_EXIT_FAIRY_SFM, OOT_SACRED_FOREST_MEADOW, "Sacred Forest Meadow Exit Fairy Grotto", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_FAIRY_HF, { OOT_GROTTO_EXIT_FAIRY_HF, OOT_HYRULE_FIELD, "Hyrule Field Exit Fairy Grotto", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_FAIRY_RIVER, { OOT_GROTTO_EXIT_FAIRY_RIVER, OOT_ZORA_RIVER, "Zora River Exit Boulder Grotto", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_FAIRY_DOMAIN, { OOT_GROTTO_EXIT_FAIRY_DOMAIN, OOT_ZORA_DOMAIN, "Zora Domain Exit Domain Grotto", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_FAIRY_FORTRESS, { OOT_GROTTO_EXIT_FAIRY_FORTRESS, OOT_GERUDO_FORTRESS, "Gerudo Fortress Exit Fortress Grotto", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_SCRUBS2_SFM, { OOT_GROTTO_EXIT_SCRUBS2_SFM, OOT_SACRED_FOREST_MEADOW, "Sacred Forest Meadow Exit Storms Grotto", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_SCRUBS2_RIVER, { OOT_GROTTO_EXIT_SCRUBS2_RIVER, OOT_ZORA_RIVER, "Zora River Exit Storms Grotto", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_SCRUBS2_VALLEY, { OOT_GROTTO_EXIT_SCRUBS2_VALLEY, OOT_GERUDO_VALLEY, "", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_SCRUBS2_COLOSSUS, { OOT_GROTTO_EXIT_SCRUBS2_COLOSSUS, OOT_DESERT_COLOSSUS, "Desert Colossus Exit Colossus Grotto", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_SCRUBS3_RANCH, { OOT_GROTTO_EXIT_SCRUBS3_RANCH, OOT_LON_LON_RANCH, "Lon Lon Ranch Exit Ranch Grotto", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_SCRUBS3_GORON_CITY, { OOT_GROTTO_EXIT_SCRUBS3_GORON_CITY, OOT_GORON_CITY, "Goron City Scrubs3 City Grotto", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_SCRUBS3_DMC, { OOT_GROTTO_EXIT_SCRUBS3_DMC, OOT_DEATH_MOUNTAIN_CRATER, "", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_SCRUBS3_LAKE, { OOT_GROTTO_EXIT_SCRUBS3_LAKE, OOT_LAKE_HYLIA, "Lake Hylia Exit Hylia Grotto", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_SCRUB_UPGRADE, { OOT_GROTTO_EXIT_SCRUB_UPGRADE, OOT_LOST_WOODS, "Lost Woods Exit Scrub Grotto", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_SCRUB_HEART_PIECE, { OOT_GROTTO_EXIT_SCRUB_HEART_PIECE, OOT_HYRULE_FIELD, "Hyrule Field Scrub Scrub Grotto", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_DEKU_THEATER, { OOT_GROTTO_EXIT_DEKU_THEATER, OOT_LOST_WOODS, "Lost Woods Exit Deku Theater", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_WOLFOS, { OOT_GROTTO_EXIT_WOLFOS, OOT_SACRED_FOREST_MEADOW, "Sacred Meadow Entryway", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_TEKTITE, { OOT_GROTTO_EXIT_TEKTITE, OOT_HYRULE_FIELD, "Hyrule Fiel", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_FIELD_COW, { OOT_GROTTO_EXIT_FIELD_COW, OOT_HYRULE_FIELD, "Hyrule Field Exit Near GV", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_FIELD_TREE, { OOT_GROTTO_EXIT_FIELD_TREE, OOT_HYRULE_FIELD, "Hyrule Field Exit Near Kak", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_TRAIL_COW, { OOT_GROTTO_EXIT_TRAIL_COW, OOT_DEATH_MOUNTAIN_TRAIL, "Death Mountain Trail Exit Cow Grotto", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_CASTLE, { OOT_GROTTO_EXIT_CASTLE, OOT_HYRULE_CASTLE, "Hyrule Castle Near Gro", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_REDEAD, { OOT_GROTTO_EXIT_REDEAD, OOT_KAKARIKO_VILLAGE, "Kakarik", "", GameLayout::all} },
	{ OOT_GROTTO_EXIT_OCTOROK, { OOT_GROTTO_EXIT_OCTOROK, OOT_GERUDO_VALLEY, "Octorok Grotto Ledg", "", GameLayout::all} },
	{ OOT_GRAVE_EXIT_SHIELD, { OOT_GRAVE_EXIT_SHIELD, OOT_GRAVEYARD, "Graveyar", "", GameLayout::all} },
	{ OOT_GRAVE_EXIT_REDEAD, { OOT_GRAVE_EXIT_REDEAD, OOT_GRAVEYARD, "Graveyar", "", GameLayout::all} },
	{ OOT_GRAVE_EXIT_ROYAL, { OOT_GRAVE_EXIT_ROYAL, OOT_GRAVEYARD, "Graveyar", "", GameLayout::all} },
	{ OOT_GRAVE_EXIT_DAMPE, { OOT_GRAVE_EXIT_DAMPE, OOT_GRAVEYARD, "Graveyar", "", GameLayout::all} },
	{ OOT_BOSS_GANON2, { OOT_BOSS_GANON2, OOT_GANON_BATTLE_ARENA, "", "", GameLayout::all} },
	{ OOT_GERUDO_FORTRESS_CAUGHT_NO_HOOK, { OOT_GERUDO_FORTRESS_CAUGHT_NO_HOOK, OOT_GERUDO_FORTRESS, "", "", GameLayout::all} },
	{ OOT_GERUDO_FORTRESS_CAUGHT, { OOT_GERUDO_FORTRESS_CAUGHT, OOT_GERUDO_FORTRESS, "", "", GameLayout::all} },
	{ OOT_CASTLE_STEALTH, { OOT_CASTLE_STEALTH, OOT_HYRULE_CASTLE, "", "", GameLayout::all} },
	{ OOT_CASTLE_STEALTH_FROM_COURTYARD, { OOT_CASTLE_STEALTH_FROM_COURTYARD, OOT_CASTLE_COURTYARD, "", "", GameLayout::all} },
	{ OOT_CASTLE_COURTYARD, { OOT_CASTLE_COURTYARD, OOT_CASTLE_COURTYARD, "", "", GameLayout::all} },
	{ OOT_CASTLE_CAUGHT, { OOT_CASTLE_CAUGHT, OOT_HYRULE_CASTLE, "", "", GameLayout::all} },
	{ OOT_MARKET_FROM_MASK_SHOP, { OOT_MARKET_FROM_MASK_SHOP, OOT_MARKET, "Market From Mask Shop", "", GameLayout::all} },
	{ OOT_SHOP_MASKS, { OOT_SHOP_MASKS, OOT_MARKET, "Market Oot OOT Market", "", GameLayout::all} },
	{ OOT_SAGES_CHAMBER_END, { OOT_SAGES_CHAMBER_END, OOT_CHAMBER_OF_THE_SAGES, "", "", GameLayout::all} },
	{ OOT_TEMPLE_OF_TIME_MASTER_SWORD_CS, { OOT_TEMPLE_OF_TIME_MASTER_SWORD_CS, OOT_TEMPLE_OF_TIME, "", "", GameLayout::all} },
	{ OOT_ZORA_RIVER_FROM_FIELD_WATER, { OOT_ZORA_RIVER_FROM_FIELD_WATER, OOT_ZORA_RIVER, "", "", GameLayout::all} },
	{ OOT_FIELD_FROM_ZORA_RIVER_WATER, { OOT_FIELD_FROM_ZORA_RIVER_WATER, OOT_HYRULE_FIELD, "", "", GameLayout::all} },
	{ OOT_GROTTO_TYPE_GENERIC, { OOT_GROTTO_TYPE_GENERIC, OOT_GROTTOS, "", "", GameLayout::all} },
	{ OOT_GROTTO_TYPE_FAIRY, { OOT_GROTTO_TYPE_FAIRY, OOT_GROTTOS, "", "", GameLayout::all} },
	{ OOT_GROTTO_TYPE_SCRUB2, { OOT_GROTTO_TYPE_SCRUB2, OOT_GROTTOS, "", "", GameLayout::all} },
	{ OOT_GROTTO_TYPE_SCRUB3, { OOT_GROTTO_TYPE_SCRUB3, OOT_GROTTOS, "", "", GameLayout::all} },
	{ OOT_SHADOW_TEMPLE_FROM_LAIR, { OOT_SHADOW_TEMPLE_FROM_LAIR, OOT_TEMPLE_SHADOW, "", "", GameLayout::all} },
	{ OOT_INTERNAL_EXIT_GROTTO, { OOT_INTERNAL_EXIT_GROTTO, OOT_GROTTOS, "", "", GameLayout::all} }
};