//! Reachability logic (OoTMM world graph).
//!
//! The immutable logic tables live in `crate::data` (generated by
//! `tools/gen_logic.py` from the root `Logic/` folder): a region graph whose
//! exits / events / locations each carry an access rule compiled to a small
//! stack bytecode (`data::Op`, pool `data::EXPRS`).
//!
//! The evaluator + fixed-point solver turn an inventory + settings + tricks into
//! the set of reachable locations; the app consumes `solve_world` and
//! `logic_location_set` to drive the accessibility filter (map + object tree).

use std::collections::HashSet;

use crate::data;

mod eval;
mod solve;
pub use solve::{solve, Reachability};
mod inputs;
pub use inputs::WorldInputs;

/// Compute reachability for the shown player: resolve their multiworld inventory
/// + the seed settings into solver [`Inputs`], then run the fixed point.
/// `settings` must already be `apply`-ed; `worlds` are all physical worlds and
/// `player` is the 1-based player whose map is displayed. This is the single entry
/// point the app calls when the tracked state changes.
pub fn solve_world(
    settings: &crate::settings::Settings,
    worlds: &[crate::WorldData],
    player: u8,
) -> Reachability {
    solve(&WorldInputs::build(settings, worlds, player))
}

/// Every location string that carries a logic rule (already game-prefixed, so it
/// matches `ObjectDef.location` directly). A tracker object whose location is not
/// in this set has no rule and must be treated as always reachable.
pub fn logic_location_set() -> HashSet<&'static str> {
    let mut set = HashSet::new();
    for r in data::LOGIC_REGIONS {
        for l in r.locations {
            set.insert(l.loc);
        }
    }
    set
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::data::{LogicRegion, Op};

    /// All regions hosting a given location (a check can be reachable from
    /// several). Test helper; linear scan is fine at this size.
    fn regions_for_location(location: &str) -> Vec<&'static LogicRegion> {
        data::LOGIC_REGIONS
            .iter()
            .filter(|r| r.locations.iter().any(|l| l.loc == location))
            .collect()
    }

    /// Highest operand index each name/pool table must cover, so a bad emission
    /// (dangling index) is caught rather than panicking at solve time.
    #[test]
    fn bytecode_indices_in_range() {
        let n_events = data::EVENT_NAMES.len();
        let n_tricks = data::TRICK_NAMES.len();
        let n_skeys = data::SETTING_KEYS.len();
        let n_svals = data::SETTING_VALUES.len();
        let n_oot_t = data::OOT_TIME_VALUES.len();
        let n_mm_t = data::MM_TIME_VALUES.len();
        let n_special = data::SPECIAL_NAMES.len();
        let n_flag = data::FLAG_NAMES.len();
        let n_builtin = data::BUILTIN_NAMES.len();

        for (ei, expr) in data::EXPRS.iter().enumerate() {
            for op in expr.iter() {
                match *op {
                    Op::Event(i) => assert!((i as usize) < n_events, "expr {ei}: event {i}"),
                    Op::Trick(i) => assert!((i as usize) < n_tricks, "expr {ei}: trick {i}"),
                    Op::Setting(i) => assert!((i as usize) < n_skeys, "expr {ei}: setting {i}"),
                    Op::SettingEq(k, v) => {
                        assert!((k as usize) < n_skeys, "expr {ei}: setting key {k}");
                        assert!((v as usize) < n_svals, "expr {ei}: setting val {v}");
                    }
                    Op::OotTime(i) => assert!((i as usize) < n_oot_t, "expr {ei}: oot_time {i}"),
                    Op::MmTime(i) => assert!((i as usize) < n_mm_t, "expr {ei}: mm_time {i}"),
                    Op::Special(i) => assert!((i as usize) < n_special, "expr {ei}: special {i}"),
                    Op::Flag(i, _) => assert!((i as usize) < n_flag, "expr {ei}: flag {i}"),
                    Op::Builtin(i) => assert!((i as usize) < n_builtin, "expr {ei}: builtin {i}"),
                    Op::Age(a) => assert!(a <= 1, "expr {ei}: age {a}"),
                    _ => {}
                }
            }
        }
    }

    /// Every region edge points at a real region, and every rule reference points
    /// at a real expression in the pool.
    #[test]
    fn region_graph_is_consistent() {
        let n_regions = data::LOGIC_REGIONS.len();
        let n_exprs = data::EXPRS.len();
        for r in data::LOGIC_REGIONS {
            for e in r.exits {
                assert!((e.to as usize) < n_regions, "{}: exit -> {}", r.name, e.to);
                assert!((e.expr as usize) < n_exprs, "{}: exit expr {}", r.name, e.expr);
            }
            for ev in r.events {
                assert!((ev.expr as usize) < n_exprs, "{}: event expr {}", r.name, ev.expr);
            }
            for l in r.locations {
                assert!((l.expr as usize) < n_exprs, "{}: loc expr {}", r.name, l.expr);
            }
            assert!(r.game <= 1, "{}: bad game {}", r.name, r.game);
        }
    }

    /// The join spot-check: a well-known OoT check resolves to a logic rule in the
    /// Deku Tree dungeon.
    #[test]
    fn known_location_has_a_rule() {
        let set = logic_location_set();
        assert!(set.contains("OOT Deku Tree Map Chest"), "Deku Tree Map Chest missing");
        let regions = regions_for_location("OOT Deku Tree Map Chest");
        assert!(regions.iter().any(|r| r.dungeon == "DT"), "not hosted in the Deku Tree");
    }

    /// Regression guard for the MM Secret Shrine data fix: the pot / miniboss
    /// checks were named `Pot 1..9` / `Dinalfos Chest` in the tracker while the
    /// OoTMM spoiler + logic use `Pot Entrance/Underwater N` / `Dinolfos Chest`.
    /// The mismatch left them with no logic rule, so the accessibility filter
    /// defaulted them to "always shown" (the reported bug). They must now join.
    #[test]
    fn secret_shrine_checks_join_logic() {
        let set = logic_location_set();
        for loc in [
            "MM Secret Shrine Dinolfos Chest",
            "MM Secret Shrine Pot Entrance 1",
            "MM Secret Shrine Pot Entrance 3",
            "MM Secret Shrine Pot Underwater 1",
            "MM Secret Shrine Pot Underwater 6",
        ] {
            assert!(set.contains(loc), "{loc} has no logic rule (join broke)");
            assert!(
                data::MM_OBJECTS.iter().any(|o| o.location == loc),
                "{loc} is not a rendered tracker object"
            );
        }
        // And the old (buggy) names must be gone from the object table.
        for stale in ["MM Secret Shrine Pot 1", "MM Secret Shrine Dinalfos Chest"] {
            assert!(
                !data::MM_OBJECTS.iter().any(|o| o.location == stale),
                "stale location {stale} still present"
            );
        }
    }

    /// Coverage: the overwhelming majority of the objects the tracker renders must
    /// join to a logic rule. A big drop here means an upstream rename broke the
    /// `ObjectDef.location` <-> logic-location join (the thing to fix on update).
    #[test]
    fn object_location_coverage() {
        let set = logic_location_set();
        let mut total = 0usize;
        let mut covered = 0usize;
        for objs in [data::OOT_OBJECTS, data::MM_OBJECTS] {
            for o in objs {
                if o.type_ == data::ObjectType::none {
                    continue;
                }
                total += 1;
                if set.contains(o.location) {
                    covered += 1;
                }
            }
        }
        let ratio = covered as f64 / total as f64;
        assert!(
            ratio >= 0.97,
            "logic covers only {covered}/{total} ({:.1}%) of rendered objects",
            ratio * 100.0
        );
    }
}
