#pragma once

#include "Multi/API.h"
#include "Combo/Objects.h"
#include "UI/Icons.h"
#include <QString>

// Defined in UI/Settings.h. Forward-declared here so the item-ID translation helpers below can
// take / return it without pulling the (heavy) Settings header into this widely-included file.
enum class ROMVersion;

#pragma region Defines

#pragma region OoT

#define OOT_BOMBS_5 0x1
#define OOT_NUTS_5 0x2
#define OOT_BOMBCHU_10 0x3
#define OOT_BOW 0x4
#define OOT_SLINGSHOT 0x5
#define OOT_BOOMERANG 0x6
#define OOT_STICK 0x7
#define OOT_HOOKSHOT 0x8
#define OOT_LONGSHOT 0x9
#define OOT_LENS 0xA
#define OOT_ZELDA_LETTER 0xB
#define OOT_OCARINA_TIME 0xC
#define OOT_HAMMER 0xD
#define OOT_COJIRO 0xE
#define OOT_BOTTLE_EMPTY 0xF
#define OOT_POTION_RED 0x10
#define OOT_POTION_GREEN 0x11
#define OOT_POTION_BLUE 0x12
#define OOT_FAIRY 0x13
#define OOT_BOTTLE_MILK 0x14
#define OOT_BOTTLE_RUTO_LETTER 0x15
#define OOT_MAGIC_BEAN 0x16
#define OOT_MASK_SKULL 0x17
#define OOT_MASK_SPOOKY 0x18
#define OOT_CHICKEN 0x19
#define OOT_MASK_KEATON 0x1A
#define OOT_MASK_BUNNY 0x1B
#define OOT_MASK_TRUTH 0x1C
#define OOT_POCKET_EGG 0x1D
#define OOT_POCKET_CUCCO 0x1E
#define OOT_ODD_MUSHROOM 0x1F
#define OOT_ODD_POTION 0x20
#define OOT_POACHER_SAW 0x21
#define OOT_BROKEN_GORON_SWORD 0x22
#define OOT_PRESCRIPTION 0x23
#define OOT_EYEBALL_FROG 0x24
#define OOT_EYE_DROPS 0x25
#define OOT_CLAIM_CHECK 0x26
#define OOT_SWORD_KOKIRI 0x27
#define OOT_SWORD_KNIFE 0x28
#define OOT_SHIELD_DEKU 0x29
#define OOT_SHIELD_HYLIAN 0x2A
#define OOT_SHIELD_MIRROR 0x2B
#define OOT_TUNIC_GORON 0x2C
#define OOT_TUNIC_ZORA 0x2D
#define OOT_BOOTS_IRON 0x2E
#define OOT_BOOTS_HOVER 0x2F
#define OOT_QUIVER2 0x30
#define OOT_QUIVER3 0x31
#define OOT_BOMB_BAG 0x32
#define OOT_BOMB_BAG2 0x33
#define OOT_BOMB_BAG3 0x34
#define OOT_SILVER_GAUNTLETS 0x35
#define OOT_GOLDEN_GAUNTLETS 0x36
#define OOT_SCALE_SILVER 0x37
#define OOT_SCALE_GOLDEN 0x38
#define OOT_STONE_OF_AGONY 0x39
#define OOT_GERUDO_CARD 0x3A
#define OOT_OCARINA_FAIRY 0x3B
#define OOT_DEKU_SEEDS_5 0x3C
#define OOT_HEART_CONTAINER 0x3D
#define OOT_HEART_PIECE 0x3E
#define OOT_BOSS_KEY 0x3F
#define OOT_COMPASS 0x40
#define OOT_MAP 0x41
#define OOT_SMALL_KEY 0x42
#define OOT_MAGIC_JAR_SMALL 0x43
#define OOT_MAGIC_JAR_LARGE 0x44
#define OOT_WALLET2 0x45
#define OOT_WALLET3 0x46
#define OOT_WEIRD_EGG 0x47
#define OOT_RECOVERY_HEART 0x48
#define OOT_ARROWS_5 0x49
#define OOT_ARROWS_10 0x4A
#define OOT_ARROWS_30 0x4B
#define OOT_RUPEE_GREEN 0x4C
#define OOT_RUPEE_BLUE 0x4D
#define OOT_RUPEE_RED 0x4E
#define OOT_HEART_CONTAINER2 0x4F
#define OOT_MILK 0x50
#define OOT_MASK_GORON 0x51
#define OOT_MASK_ZORA 0x52
#define OOT_MASK_GERUDO 0x53
#define OOT_GORON_BRACELET 0x54
#define OOT_RUPEE_PURPLE 0x55
#define OOT_RUPEE_HUGE 0x56
#define OOT_SWORD_BIGGORON 0x57
#define OOT_ARROW_FIRE 0x58
#define OOT_ARROW_ICE 0x59
#define OOT_ARROW_LIGHT 0x5A
#define OOT_GS_TOKEN 0x5B
#define OOT_SPELL_FIRE 0x5C
#define OOT_SPELL_WIND 0x5D
#define OOT_SPELL_LOVE 0x5E
#define OOT_BULLET_BAG 0x5F
#define OOT_BULLET_BAG2 0x60
#define OOT_STICKS_5 0x61
#define OOT_STICKS_10 0x62
#define OOT_NUTS_5_ALT 0x63
#define OOT_NUTS_10 0x64
#define OOT_BOMB 0x65
#define OOT_BOMBS_10 0x66
#define OOT_BOMBS_20 0x67
#define OOT_BOMBS_30 0x68
#define OOT_DEKU_SEEDS_30 0x69
#define OOT_BOMBCHU_5 0x6A
#define OOT_BOMBCHU_20 0x6B
#define OOT_FISH 0x6C
#define OOT_BUGS 0x6D
#define OOT_BLUE_FIRE 0x6E
#define OOT_POE 0x6F
#define OOT_BIG_POE 0x70
#define OOT_TC_SMALL_KEY 0x71
#define OOT_TC_RUPEE_GREEN 0x72
#define OOT_TC_RUPEE_BLUE 0x73
#define OOT_TC_RUPEE_RED 0x74
#define OOT_TC_RUPEE_PURPLE 0x75
#define OOT_TC_HEART_PIECE 0x76
#define OOT_STICK_UPGRADE2 0x77
#define OOT_STICK_UPGRADE3 0x78
#define OOT_NUT_UPGRADE2 0x79
#define OOT_NUT_UPGRADE3 0x7A
#define OOT_BULLET_BAG3 0x7B
#define OOT_UNUSED_ICE_TRAP 0x7C
#define OOT_UNK_7D 0x7D
#define OOT_UNK_7E 0x7E
#define OOT_UNK_7F 0x7F
#define OOT_STICK_UPGRADE 0x80
#define OOT_NUT_UPGRADE 0x81
#define OOT_RUPEE_RAINBOW 0x82
#define OOT_SONG_TP_FOREST 0x83
#define OOT_SONG_TP_FIRE 0x84
#define OOT_SONG_TP_WATER 0x85
#define OOT_SONG_TP_SPIRIT 0x86
#define OOT_SONG_TP_SHADOW 0x87
#define OOT_SONG_TP_LIGHT 0x88
#define OOT_SONG_ZELDA 0x89
#define OOT_SONG_EPONA 0x8A
#define OOT_SONG_SARIA 0x8B
#define OOT_SONG_SUN 0x8C
#define OOT_SONG_TIME 0x8D
#define OOT_SONG_STORMS 0x8E
#define OOT_SONG_EMPTINESS 0x8F
#define OOT_SONG_HEALING 0x90
#define OOT_SONG_SOARING 0x91
#define OOT_SONG_AWAKENING 0x92
#define OOT_SONG_GORON 0x93
#define OOT_SONG_GORON_HALF 0x94
#define OOT_SONG_ZORA 0x95
#define OOT_SONG_ORDER 0x96
#define OOT_SONG_NOTE_TP_FOREST 0x97
#define OOT_SONG_NOTE_TP_FIRE 0x98
#define OOT_SONG_NOTE_TP_WATER 0x99
#define OOT_SONG_NOTE_TP_SPIRIT 0x9A
#define OOT_SONG_NOTE_TP_SHADOW 0x9B
#define OOT_SONG_NOTE_TP_LIGHT 0x9C
#define OOT_SONG_NOTE_ZELDA 0x9D
#define OOT_SONG_NOTE_EPONA 0x9E
#define OOT_SONG_NOTE_SARIA 0x9F
#define OOT_SONG_NOTE_SUN 0xA0
#define OOT_SONG_NOTE_TIME 0xA1
#define OOT_SONG_NOTE_STORMS 0xA2
#define OOT_SONG_NOTE_EMPTINESS 0xA3
#define OOT_SONG_NOTE_HEALING 0xA4
#define OOT_SONG_NOTE_SOARING 0xA5
#define OOT_SONG_NOTE_AWAKENING 0xA6
#define OOT_SONG_NOTE_GORON 0xA7
#define OOT_SONG_NOTE_ZORA 0xA8
#define OOT_SONG_NOTE_ORDER 0xA9
#define OOT_SWORD_MASTER 0xAA
#define OOT_STONE_EMERALD 0xAB
#define OOT_STONE_RUBY 0xAC
#define OOT_STONE_SAPPHIRE 0xAD
#define OOT_MEDALLION_FOREST 0xAE
#define OOT_MEDALLION_FIRE 0xAF
#define OOT_MEDALLION_WATER 0xB0
#define OOT_MEDALLION_SPIRIT 0xB1
#define OOT_MEDALLION_SHADOW 0xB2
#define OOT_MEDALLION_LIGHT 0xB3
#define OOT_MAGIC_UPGRADE 0xB4
#define OOT_MAGIC_UPGRADE2 0xB5
#define OOT_DEFENSE_UPGRADE 0xB6
#define OOT_PROGRESSIVE_SHIELD_DEKU 0xB7
#define OOT_PROGRESSIVE_SHIELD_HYLIAN 0xB8
#define OOT_SMALL_KEY_FOREST 0xB9
#define OOT_SMALL_KEY_FIRE 0xBA
#define OOT_SMALL_KEY_WATER 0xBB
#define OOT_SMALL_KEY_SPIRIT 0xBC
#define OOT_SMALL_KEY_SHADOW 0xBD
#define OOT_SMALL_KEY_GANON 0xBE
#define OOT_SMALL_KEY_BOTW 0xBF
#define OOT_SMALL_KEY_GF 0xC0
#define OOT_SMALL_KEY_GTG 0xC1
#define OOT_BOSS_KEY_FOREST 0xC2
#define OOT_BOSS_KEY_FIRE 0xC3
#define OOT_BOSS_KEY_WATER 0xC4
#define OOT_BOSS_KEY_SPIRIT 0xC5
#define OOT_BOSS_KEY_SHADOW 0xC6
#define OOT_BOSS_KEY_GANON 0xC7
#define OOT_MAP_DT 0xC8
#define OOT_MAP_DC 0xC9
#define OOT_MAP_JJ 0xCA
#define OOT_MAP_FOREST 0xCB
#define OOT_MAP_FIRE 0xCC
#define OOT_MAP_WATER 0xCD
#define OOT_MAP_SPIRIT 0xCE
#define OOT_MAP_SHADOW 0xCF
#define OOT_MAP_BOTW 0xD0
#define OOT_MAP_IC 0xD1
#define OOT_COMPASS_DT 0xD2
#define OOT_COMPASS_DC 0xD3
#define OOT_COMPASS_JJ 0xD4
#define OOT_COMPASS_FOREST 0xD5
#define OOT_COMPASS_FIRE 0xD6
#define OOT_COMPASS_WATER 0xD7
#define OOT_COMPASS_SPIRIT 0xD8
#define OOT_COMPASS_SHADOW 0xD9
#define OOT_COMPASS_BOTW 0xDA
#define OOT_COMPASS_IC 0xDB
#define OOT_WALLET 0xDC
#define OOT_WALLET4 0xDD
#define OOT_TRIFORCE 0xDE
#define OOT_WALLET5 0xDF
#define OOT_RUPEE_SILVER_DC 0xE0
#define OOT_RUPEE_SILVER_BOTW 0xE1
#define OOT_RUPEE_SILVER_SPIRIT_CHILD 0xE2
#define OOT_RUPEE_SILVER_SPIRIT_SUN 0xE3
#define OOT_RUPEE_SILVER_SPIRIT_BOULDERS 0xE4
#define OOT_RUPEE_SILVER_SPIRIT_LOBBY 0xE5
#define OOT_RUPEE_SILVER_SPIRIT_ADULT 0xE6
#define OOT_RUPEE_SILVER_SHADOW_SCYTHE 0xE7
#define OOT_RUPEE_SILVER_SHADOW_PIT 0xE8
#define OOT_RUPEE_SILVER_SHADOW_SPIKES 0xE9
#define OOT_RUPEE_SILVER_SHADOW_BLADES 0xEA
#define OOT_RUPEE_SILVER_IC_SCYTHE 0xEB
#define OOT_RUPEE_SILVER_IC_BLOCK 0xEC
#define OOT_RUPEE_SILVER_GTG_SLOPES 0xED
#define OOT_RUPEE_SILVER_GTG_LAVA 0xEE
#define OOT_RUPEE_SILVER_GTG_WATER 0xEF
#define OOT_RUPEE_SILVER_GANON_SPIRIT 0xF0
#define OOT_RUPEE_SILVER_GANON_LIGHT 0xF1
#define OOT_RUPEE_SILVER_GANON_FIRE 0xF2
#define OOT_RUPEE_SILVER_GANON_FOREST 0xF3
#define OOT_RUPEE_SILVER_GANON_SHADOW 0xF4
#define OOT_RUPEE_SILVER_GANON_WATER 0xF5
#define OOT_SOUL_ENEMY_STALFOS 0xF6
#define OOT_SOUL_ENEMY_OCTOROK 0xF7
#define OOT_SOUL_ENEMY_WALLMASTER 0xF8
#define OOT_SOUL_ENEMY_DODONGO 0xF9
#define OOT_SOUL_ENEMY_KEESE 0xFA
#define OOT_SOUL_ENEMY_TEKTITE 0xFB
#define OOT_SOUL_ENEMY_LEEVER 0xFC
#define OOT_SOUL_ENEMY_PEAHAT 0xFD
#define OOT_SOUL_ENEMY_LIZALFOS_DINOLFOS 0xFE
#define OOT_SOUL_ENEMY_GOHMA_LARVA 0xFF
#define OOT_SOUL_ENEMY_SHABOM 0x100
#define OOT_SOUL_ENEMY_BABY_DODONGO 0x101
#define OOT_SOUL_ENEMY_DARK_LINK 0x102
#define OOT_SOUL_ENEMY_BIRI_BARI 0x103
#define OOT_SOUL_ENEMY_TAILPASARN 0x104
#define OOT_SOUL_ENEMY_PARASITE 0x105
#define OOT_SOUL_ENEMY_SKULLTULA 0x106
#define OOT_SOUL_ENEMY_TORCH_SLUG 0x107
#define OOT_SOUL_ENEMY_MOBLIN 0x108
#define OOT_SOUL_ENEMY_ARMOS 0x109
#define OOT_SOUL_ENEMY_DEKU_BABA 0x10A
#define OOT_SOUL_ENEMY_DEKU_SCRUB 0x10B
#define OOT_SOUL_ENEMY_BUBBLE 0x10C
#define OOT_SOUL_ENEMY_BEAMOS 0x10D
#define OOT_SOUL_ENEMY_FLOORMASTER 0x10E
#define OOT_SOUL_ENEMY_REDEAD_GIBDO 0x10F
#define OOT_SOUL_ENEMY_SKULLWALLTULA 0x110
#define OOT_SOUL_ENEMY_FLARE_DANCER 0x111
#define OOT_SOUL_ENEMY_DEAD_HAND 0x112
#define OOT_SOUL_ENEMY_SHELL_BLADE 0x113
#define OOT_SOUL_ENEMY_LIKE_LIKE 0x114
#define OOT_SOUL_ENEMY_SPIKE 0x115
#define OOT_SOUL_ENEMY_ANUBIS 0x116
#define OOT_SOUL_ENEMY_IRON_KNUCKLE 0x117
#define OOT_SOUL_ENEMY_SKULL_KID 0x118
#define OOT_SOUL_ENEMY_FLYING_POT 0x119
#define OOT_SOUL_ENEMY_FREEZARD 0x11A
#define OOT_SOUL_ENEMY_STINGER 0x11B
#define OOT_SOUL_ENEMY_WOLFOS 0x11C
#define OOT_SOUL_ENEMY_STALCHILD 0x11D
#define OOT_SOUL_ENEMY_GUAY 0x11E
#define OOT_SOUL_ENEMY_THIEVES 0x11F
#define OOT_SOUL_ENEMY_POE 0x120
#define OOT_SOUL_BOSS_QUEEN_GOHMA 0x121
#define OOT_SOUL_BOSS_KING_DODONGO 0x122
#define OOT_SOUL_BOSS_BARINADE 0x123
#define OOT_SOUL_BOSS_PHANTOM_GANON 0x124
#define OOT_SOUL_BOSS_VOLVAGIA 0x125
#define OOT_SOUL_BOSS_MORPHA 0x126
#define OOT_SOUL_BOSS_BONGO_BONGO 0x127
#define OOT_SOUL_BOSS_TWINROVA 0x128
#define OOT_SOUL_NPC_SARIA 0x129
#define OOT_SOUL_NPC_DARUNIA 0x12A
#define OOT_SOUL_NPC_RUTO 0x12B
#define OOT_SOUL_NPC_KING_ZORA 0x12C
#define OOT_SOUL_NPC_ZELDA 0x12D
#define OOT_SOUL_NPC_SHEIK 0x12E
#define OOT_SOUL_NPC_ANJU 0x12F
#define OOT_SOUL_NPC_CARPENTERS 0x130
#define OOT_SOUL_NPC_GURU_GURU 0x131
#define OOT_SOUL_NPC_MIDO 0x132
#define OOT_SOUL_NPC_KOKIRI 0x133
#define OOT_SOUL_NPC_KOKIRI_SHOPKEEPER 0x134
#define OOT_SOUL_NPC_HYLIAN_GUARD 0x135
#define OOT_SOUL_NPC_CITIZEN 0x136
#define OOT_SOUL_NPC_MALON 0x137
#define OOT_SOUL_NPC_TALON 0x138
#define OOT_SOUL_NPC_FISHING_POND_OWNER 0x139
#define OOT_SOUL_NPC_GORON 0x13A
#define OOT_SOUL_NPC_MEDIGORON 0x13B
#define OOT_SOUL_NPC_BIGGORON 0x13C
#define OOT_SOUL_NPC_GORON_CHILD 0x13D
#define OOT_SOUL_NPC_GORON_SHOPKEEPER 0x13E
#define OOT_SOUL_NPC_ZORA 0x13F
#define OOT_SOUL_NPC_ZORA_SHOPKEEPER 0x140
#define OOT_SOUL_NPC_BAZAAR_SHOPKEEPER 0x141
#define OOT_SOUL_NPC_BOMBCHU_SHOPKEEPER 0x142
#define OOT_SOUL_NPC_POTION_SHOPKEEPER 0x143
#define OOT_SOUL_NPC_BOMBCHU_BOWLING_LADY 0x144
#define OOT_SOUL_NPC_CHEST_GAME_OWNER 0x145
#define OOT_SOUL_NPC_SHOOTING_GALLERY_OWNER 0x146
#define OOT_SOUL_NPC_DAMPE 0x147
#define OOT_SOUL_NPC_BOMBERS 0x148
#define OOT_SOUL_NPC_POE_COLLECTOR 0x149
#define OOT_SOUL_NPC_COMPOSER_BROS 0x14A
#define OOT_SOUL_NPC_HONEY_DARLING 0x14B
#define OOT_SOUL_NPC_ASTRONOMER 0x14C
#define OOT_SOUL_NPC_ROOFTOP_MAN 0x14D
#define OOT_SOUL_NPC_BEAN_SALESMAN 0x14E
#define OOT_SOUL_NPC_SCIENTIST 0x14F
#define OOT_SOUL_NPC_GORMAN 0x150
#define OOT_SOUL_NPC_GROG 0x151
#define OOT_SOUL_NPC_DOG_LADY 0x152
#define OOT_SOUL_NPC_CARPET_MAN 0x153
#define OOT_SOUL_NPC_OLD_HAG 0x154
#define OOT_SOUL_NPC_BANKER 0x155
#define OOT_SOUL_NPC_THIEVES 0x156
#define OOT_SOUL_ANIMAL_CUCCO 0x157
#define OOT_SOUL_ANIMAL_COW 0x158
#define OOT_SOUL_ANIMAL_DOG 0x159
#define OOT_SOUL_ANIMAL_BUTTERFLY 0x15A
#define OOT_SOUL_MISC_GS 0x15B
#define OOT_SOUL_MISC_BUSINESS_SCRUB 0x15C
#define OOT_KEY_RING 0x15D
#define OOT_KEY_RING_FOREST 0x15E
#define OOT_KEY_RING_FIRE 0x15F
#define OOT_KEY_RING_WATER 0x160
#define OOT_KEY_RING_SPIRIT 0x161
#define OOT_KEY_RING_SHADOW 0x162
#define OOT_KEY_RING_GANON 0x163
#define OOT_KEY_RING_BOTW 0x164
#define OOT_KEY_RING_GF 0x165
#define OOT_KEY_RING_GTG 0x166
#define OOT_SKELETON_KEY 0x167
#define OOT_COIN_RED 0x168
#define OOT_COIN_GREEN 0x169
#define OOT_COIN_BLUE 0x16A
#define OOT_COIN_YELLOW 0x16B
#define OOT_TRIFORCE_POWER 0x16C
#define OOT_TRIFORCE_COURAGE 0x16D
#define OOT_TRIFORCE_WISDOM 0x16E
#define OOT_POUCH_SILVER_DC 0x16F
#define OOT_POUCH_SILVER_BOTW 0x170
#define OOT_POUCH_SILVER_SPIRIT_CHILD 0x171
#define OOT_POUCH_SILVER_SPIRIT_SUN 0x172
#define OOT_POUCH_SILVER_SPIRIT_BOULDERS 0x173
#define OOT_POUCH_SILVER_SPIRIT_LOBBY 0x174
#define OOT_POUCH_SILVER_SPIRIT_ADULT 0x175
#define OOT_POUCH_SILVER_SHADOW_SCYTHE 0x176
#define OOT_POUCH_SILVER_SHADOW_PIT 0x177
#define OOT_POUCH_SILVER_SHADOW_SPIKES 0x178
#define OOT_POUCH_SILVER_SHADOW_BLADES 0x179
#define OOT_POUCH_SILVER_IC_SCYTHE 0x17A
#define OOT_POUCH_SILVER_IC_BLOCK 0x17B
#define OOT_POUCH_SILVER_GTG_SLOPES 0x17C
#define OOT_POUCH_SILVER_GTG_LAVA 0x17D
#define OOT_POUCH_SILVER_GTG_WATER 0x17E
#define OOT_POUCH_SILVER_GANON_SPIRIT 0x17F
#define OOT_POUCH_SILVER_GANON_LIGHT 0x180
#define OOT_POUCH_SILVER_GANON_FIRE 0x181
#define OOT_POUCH_SILVER_GANON_FOREST 0x182
#define OOT_POUCH_SILVER_GANON_SHADOW 0x183
#define OOT_POUCH_SILVER_GANON_WATER 0x184
#define OOT_RUPEE_MAGICAL 0x185
#define OOT_BUTTON_A 0x186
#define OOT_BUTTON_C_RIGHT 0x187
#define OOT_BUTTON_C_LEFT 0x188
#define OOT_BUTTON_C_UP 0x189
#define OOT_BUTTON_C_DOWN 0x18A
#define OOT_SMALL_KEY_TCG 0x18B
#define OOT_KEY_RING_TCG 0x18C
#define OOT_BOTTLE_POTION_RED 0x18D
#define OOT_BOTTLE_POTION_GREEN 0x18E
#define OOT_BOTTLE_POTION_BLUE 0x18F
#define OOT_BOTTLE_FAIRY 0x190
#define OOT_BOTTLE_POE 0x191
#define OOT_BOTTLE_BIG_POE 0x192
#define OOT_BOTTLE_BLUE_FIRE 0x193
#define OOT_FISHING_POND_CHILD_FISH_2LBS 0x194
#define OOT_FISHING_POND_CHILD_FISH_3LBS 0x195
#define OOT_FISHING_POND_CHILD_FISH_4LBS 0x196
#define OOT_FISHING_POND_CHILD_FISH_5LBS 0x197
#define OOT_FISHING_POND_CHILD_FISH_6LBS 0x198
#define OOT_FISHING_POND_CHILD_FISH_7LBS 0x199
#define OOT_FISHING_POND_CHILD_FISH_8LBS 0x19A
#define OOT_FISHING_POND_CHILD_FISH_9LBS 0x19B
#define OOT_FISHING_POND_CHILD_FISH_10LBS 0x19C
#define OOT_FISHING_POND_CHILD_FISH_11LBS 0x19D
#define OOT_FISHING_POND_CHILD_FISH_12LBS 0x19E
#define OOT_FISHING_POND_CHILD_FISH_13LBS 0x19F
#define OOT_FISHING_POND_CHILD_FISH_14LBS 0x1A0
#define OOT_FISHING_POND_ADULT_FISH_4LBS 0x1A1
#define OOT_FISHING_POND_ADULT_FISH_5LBS 0x1A2
#define OOT_FISHING_POND_ADULT_FISH_6LBS 0x1A3
#define OOT_FISHING_POND_ADULT_FISH_7LBS 0x1A4
#define OOT_FISHING_POND_ADULT_FISH_8LBS 0x1A5
#define OOT_FISHING_POND_ADULT_FISH_9LBS 0x1A6
#define OOT_FISHING_POND_ADULT_FISH_10LBS 0x1A7
#define OOT_FISHING_POND_ADULT_FISH_11LBS 0x1A8
#define OOT_FISHING_POND_ADULT_FISH_12LBS 0x1A9
#define OOT_FISHING_POND_ADULT_FISH_13LBS 0x1AA
#define OOT_FISHING_POND_ADULT_FISH_14LBS 0x1AB
#define OOT_FISHING_POND_ADULT_FISH_15LBS 0x1AC
#define OOT_FISHING_POND_ADULT_FISH_16LBS 0x1AD
#define OOT_FISHING_POND_ADULT_FISH_17LBS 0x1AE
#define OOT_FISHING_POND_ADULT_FISH_18LBS 0x1AF
#define OOT_FISHING_POND_ADULT_FISH_19LBS 0x1B0
#define OOT_FISHING_POND_ADULT_FISH_20LBS 0x1B1
#define OOT_FISHING_POND_ADULT_FISH_21LBS 0x1B2
#define OOT_FISHING_POND_ADULT_FISH_22LBS 0x1B3
#define OOT_FISHING_POND_ADULT_FISH_23LBS 0x1B4
#define OOT_FISHING_POND_ADULT_FISH_24LBS 0x1B5
#define OOT_FISHING_POND_ADULT_FISH_25LBS 0x1B6
#define OOT_FISHING_POND_CHILD_LOACH_14LBS 0x1B7
#define OOT_FISHING_POND_CHILD_LOACH_15LBS 0x1B8
#define OOT_FISHING_POND_CHILD_LOACH_16LBS 0x1B9
#define OOT_FISHING_POND_CHILD_LOACH_17LBS 0x1BA
#define OOT_FISHING_POND_CHILD_LOACH_18LBS 0x1BB
#define OOT_FISHING_POND_CHILD_LOACH_19LBS 0x1BC
#define OOT_FISHING_POND_ADULT_LOACH_29LBS 0x1BD
#define OOT_FISHING_POND_ADULT_LOACH_30LBS 0x1BE
#define OOT_FISHING_POND_ADULT_LOACH_31LBS 0x1BF
#define OOT_FISHING_POND_ADULT_LOACH_32LBS 0x1C0
#define OOT_FISHING_POND_ADULT_LOACH_33LBS 0x1C1
#define OOT_FISHING_POND_ADULT_LOACH_34LBS 0x1C2
#define OOT_FISHING_POND_ADULT_LOACH_35LBS 0x1C3
#define OOT_FISHING_POND_ADULT_LOACH_36LBS 0x1C4
#define OOT_BOMBCHU_BAG 0x1C5
#define OOT_BOMBCHU_BAG2 0x1C6
#define OOT_BOMBCHU_BAG3 0x1C7
#define OOT_BOMBCHU_BAG_FIRST_5 0x1C8
#define OOT_BOMBCHU_BAG_FIRST_10 0x1C9
#define OOT_BOMBCHU_BAG_FIRST_20 0x1CA
#define OOT_SWORD_RAZOR 0x1CB
#define OOT_SWORD_GILDED 0x1CC
#define OOT_SPIN_UPGRADE 0x1CD
#define OOT_TRIFORCE_FULL 0x1CE
#define OOT_FAIRY_BIG 0x1CF
#define OOT_MASK_BLAST 0x1D0
#define OOT_MASK_STONE 0x1D1
#define OOT_MASK_KAMARO 0x1D2
#define OOT_SCALE_BRONZE 0x1D3
#define OOT_GREAT_FAIRY_SWORD 0x1D4
#define OOT_WEIRD_MUSHROOM 0x1D5
#define OOT_CHATEAU 0x1D6
#define OOT_GOLD_DUST 0x1D7
#define OOT_SEAHORSE2 0x1D8
#define OOT_BOTTLED_GOLD_DUST 0x1D9
#define OOT_BOTTLE_CHATEAU 0x1DA
#define OOT_POWDER_KEG 0x1DB
#define OOT_TRAP_ICE 0x1DC
#define OOT_TRAP_FIRE 0x1DD
#define OOT_TRAP_SHOCK 0x1DE
#define OOT_TRAP_DRAIN 0x1DF
#define OOT_TRAP_ANTI_MAGIC 0x1E0
#define OOT_TRAP_KNOCKBACK 0x1E1
#define OOT_TRAP_RUPOOR 0x1E2
#define OOT_PLATINUM_TOKEN 0x1E3
#define OOT_RUSTY_KEY_TREASURE_CHEST_GAME 0x1E4
#define OOT_RUSTY_KEY_GUARD_HOUSE 0x1E5
#define OOT_RUSTY_KEY_HYRULE_CASTLE 0x1E6
#define OOT_RUSTY_KEY_DOG_LADY_HOUSE 0x1E7
#define OOT_RUSTY_KEY_BACK_ALLEY_HOUSE 0x1E8
#define OOT_RUSTY_KEY_BOMBCHU_SHOP 0x1E9
#define OOT_RUSTY_KEY_MASK_SHOP 0x1EA
#define OOT_RUSTY_KEY_CHILD_BAZAAR 0x1EB
#define OOT_RUSTY_KEY_CHILD_POTION_SHOP 0x1EC
#define OOT_RUSTY_KEY_CHILD_SHOOTING_GALLERY 0x1ED
#define OOT_RUSTY_KEY_BOMBCHU_BOWLING 0x1EE
#define OOT_RUSTY_KEY_LABORATORY 0x1EF
#define OOT_RUSTY_KEY_FISHING_POND 0x1F0
#define OOT_RUSTY_KEY_SILO 0x1F1
#define OOT_RUSTY_KEY_RANCH_STABLE 0x1F2
#define OOT_RUSTY_KEY_RANCH_HOUSE 0x1F3
#define OOT_RUSTY_KEY_RANCH_HOUSE_ROOM 0x1F4
#define OOT_RUSTY_KEY_GRAVEYARD 0x1F5
#define OOT_RUSTY_KEY_WINDMILL 0x1F6
#define OOT_RUSTY_KEY_IMPA_HOUSE 0x1F7
#define OOT_RUSTY_KEY_CARPENTER_HOUSE 0x1F8
#define OOT_RUSTY_KEY_GRANNY_POTION_SHOP 0x1F9
#define OOT_RUSTY_KEY_ADULT_SHOOTING_GALLERY 0x1FA
#define OOT_RUSTY_KEY_SKULLTULA_HOUSE 0x1FB
#define OOT_RUSTY_KEY_ADULT_BAZAAR 0x1FC
#define OOT_RUSTY_KEY_ADULT_POTION_SHOP 0x1FD
#define OOT_RUSTY_KEY_ADULT_POTION_SHOP_BACK 0x1FE
#define OOT_CLOCK 0x1FF
#define OOT_SHOVEL 0x200

#pragma endregion OoT

#pragma region MM

#define MM_RUPEE_GREEN 0x201
#define MM_RUPEE_BLUE 0x202
#define MM_RUPEE_RED_10 0x203
#define MM_RUPEE_RED 0x204
#define MM_RUPEE_PURPLE 0x205
#define MM_RUPEE_SILVER 0x206
#define MM_RUPEE_GOLD 0x207
#define MM_WALLET2 0x208
#define MM_WALLET3 0x209
#define MM_RECOVERY_HEART 0x20A
#define MM_HEART_PIECE 0x20B
#define MM_HEART_CONTAINER 0x20C
#define MM_MAGIC_JAR_SMALL 0x20D
#define MM_MAGIC_JAR_LARGE 0x20E
#define MM_STRAY_FAIRY 0x20F
#define MM_STRAY_FAIRY_WF 0x210
#define MM_STRAY_FAIRY_SH 0x211
#define MM_STRAY_FAIRY_GB 0x212
#define MM_STRAY_FAIRY_ST 0x213
#define MM_STRAY_FAIRY_TOWN 0x214
#define MM_TRANSCENDENT_FAIRY 0x215
#define MM_BOMB 0x216
#define MM_BOMBS_5 0x217
#define MM_BOMBS_10 0x218
#define MM_BOMBS_20 0x219
#define MM_BOMBS_30 0x21A
#define MM_STICK 0x21B
#define MM_BOMBCHU_10 0x21C
#define MM_BOMB_BAG 0x21D
#define MM_BOMB_BAG2 0x21E
#define MM_BOMB_BAG3 0x21F
#define MM_ARROWS_10 0x220
#define MM_ARROWS_30 0x221
#define MM_ARROWS_40 0x222
#define MM_UNK_21 0x223
#define MM_BOW 0x224
#define MM_QUIVER2 0x225
#define MM_QUIVER3 0x226
#define MM_ARROW_FIRE 0x227
#define MM_ARROW_ICE 0x228
#define MM_ARROW_LIGHT 0x229
#define MM_NUT 0x22A
#define MM_NUTS_5 0x22B
#define MM_NUTS_10 0x22C
#define MM_UNK_2B 0x22D
#define MM_UNK_2C 0x22E
#define MM_UNK_2D 0x22F
#define MM_BOMBCHU_20 0x230
#define MM_UNK_2F 0x231
#define MM_UNK_30 0x232
#define MM_UNK_31 0x233
#define MM_SHIELD_DEKU 0x234
#define MM_SHIELD_HERO 0x235
#define MM_SHIELD_MIRROR 0x236
#define MM_PROGRESSIVE_SHIELD_DEKU 0x237
#define MM_PROGRESSIVE_SHIELD_HERO 0x238
#define MM_POWDER_KEG 0x239
#define MM_MAGIC_BEAN 0x23A
#define MM_BOMBCHU 0x23B
#define MM_SWORD_KOKIRI 0x23C
#define MM_SWORD_RAZOR 0x23D
#define MM_SWORD_GILDED 0x23E
#define MM_BOMBCHU_5 0x23F
#define MM_GREAT_FAIRY_SWORD 0x240
#define MM_SMALL_KEY 0x241
#define MM_BOSS_KEY 0x242
#define MM_MAP 0x243
#define MM_COMPASS 0x244
#define MM_HOOKSHOT 0x245
#define MM_LENS 0x246
#define MM_PICTOGRAPH_BOX 0x247
#define MM_OCARINA_OF_TIME 0x248
#define MM_BOMBER_NOTEBOOK 0x249
#define MM_BOTTLE_POTION_RED 0x24A
#define MM_BOTTLE_EMPTY 0x24B
#define MM_POTION_RED 0x24C
#define MM_POTION_GREEN 0x24D
#define MM_POTION_BLUE 0x24E
#define MM_FAIRY 0x24F
#define MM_BOTTLE_MILK 0x250
#define MM_FISH 0x251
#define MM_BUGS 0x252
#define MM_BIG_POE 0x253
#define MM_BOTTLED_GOLD_DUST 0x254
#define MM_WEIRD_MUSHROOM 0x255
#define MM_BOTTLE_CHATEAU 0x256
#define MM_MASK_DEKU 0x257
#define MM_MASK_GORON 0x258
#define MM_MASK_ZORA 0x259
#define MM_MASK_FIERCE_DEITY 0x25A
#define MM_MASK_CAPTAIN 0x25B
#define MM_MASK_GIANT 0x25C
#define MM_MASK_ALL_NIGHT 0x25D
#define MM_MASK_BUNNY 0x25E
#define MM_MASK_KEATON 0x25F
#define MM_MASK_GARO 0x260
#define MM_MASK_ROMANI 0x261
#define MM_MASK_TROUPE_LEADER 0x262
#define MM_MASK_POSTMAN 0x263
#define MM_MASK_COUPLE 0x264
#define MM_MASK_GREAT_FAIRY 0x265
#define MM_MASK_GIBDO 0x266
#define MM_MASK_DON_GERO 0x267
#define MM_MASK_KAMARO 0x268
#define MM_MASK_TRUTH 0x269
#define MM_MASK_STONE 0x26A
#define MM_MASK_BREMEN 0x26B
#define MM_MASK_BLAST 0x26C
#define MM_MASK_SCENTS 0x26D
#define MM_MASK_KAFEI 0x26E
#define MM_MASK_GERUDO 0x26F
#define MM_MASK_SKULL 0x270
#define MM_MASK_SPOOKY 0x271
#define MM_MASK_ADULT 0x272
#define MM_CHATEAU 0x273
#define MM_MILK 0x274
#define MM_GOLD_DUST 0x275
#define MM_SEAHORSE2 0x276
#define MM_MOON_TEAR 0x277
#define MM_DEED_LAND 0x278
#define MM_DEED_SWAMP 0x279
#define MM_DEED_MOUNTAIN 0x27A
#define MM_DEED_OCEAN 0x27B
#define MM_ROOM_KEY 0x27C
#define MM_LETTER_TO_MAMA 0x27D
#define MM_LETTER_TO_KAFEI 0x27E
#define MM_PENDANT_OF_MEMORIES 0x27F
#define MM_WORLD_MAP_CLOCK_TOWN 0x280
#define MM_WORLD_MAP_WOODFALL 0x281
#define MM_WORLD_MAP_SNOWHEAD 0x282
#define MM_WORLD_MAP_ROMANI_RANCH 0x283
#define MM_WORLD_MAP_GREAT_BAY 0x284
#define MM_WORLD_MAP_STONE_TOWER 0x285
#define MM_MAGIC_UPGRADE 0x286
#define MM_MAGIC_UPGRADE2 0x287
#define MM_DEFENSE_UPGRADE 0x288
#define MM_SPIN_UPGRADE 0x289
#define MM_SONG_AWAKENING 0x28A
#define MM_SONG_GORON 0x28B
#define MM_SONG_ZORA 0x28C
#define MM_SONG_EMPTINESS 0x28D
#define MM_SONG_ORDER 0x28E
#define MM_SONG_TIME 0x28F
#define MM_SONG_HEALING 0x290
#define MM_SONG_EPONA 0x291
#define MM_SONG_SOARING 0x292
#define MM_SONG_STORMS 0x293
#define MM_SONG_SUN 0x294
#define MM_SONG_TP_FOREST 0x295
#define MM_SONG_TP_FIRE 0x296
#define MM_SONG_TP_WATER 0x297
#define MM_SONG_TP_SPIRIT 0x298
#define MM_SONG_TP_SHADOW 0x299
#define MM_SONG_TP_LIGHT 0x29A
#define MM_SONG_ZELDA 0x29B
#define MM_SONG_SARIA 0x29C
#define MM_SONG_GORON_HALF 0x29D
#define MM_SONG_NOTE_AWAKENING 0x29E
#define MM_SONG_NOTE_GORON 0x29F
#define MM_SONG_NOTE_ZORA 0x2A0
#define MM_SONG_NOTE_EMPTINESS 0x2A1
#define MM_SONG_NOTE_ORDER 0x2A2
#define MM_SONG_NOTE_TIME 0x2A3
#define MM_SONG_NOTE_HEALING 0x2A4
#define MM_SONG_NOTE_EPONA 0x2A5
#define MM_SONG_NOTE_SOARING 0x2A6
#define MM_SONG_NOTE_STORMS 0x2A7
#define MM_SONG_NOTE_SUN 0x2A8
#define MM_SONG_NOTE_TP_FOREST 0x2A9
#define MM_SONG_NOTE_TP_FIRE 0x2AA
#define MM_SONG_NOTE_TP_WATER 0x2AB
#define MM_SONG_NOTE_TP_SPIRIT 0x2AC
#define MM_SONG_NOTE_TP_SHADOW 0x2AD
#define MM_SONG_NOTE_TP_LIGHT 0x2AE
#define MM_SONG_NOTE_ZELDA 0x2AF
#define MM_SONG_NOTE_SARIA 0x2B0
#define MM_REMAINS_ODOLWA 0x2B1
#define MM_REMAINS_GOHT 0x2B2
#define MM_REMAINS_GYORG 0x2B3
#define MM_REMAINS_TWINMOLD 0x2B4
#define MM_GS_TOKEN_SWAMP 0x2B5
#define MM_GS_TOKEN_OCEAN 0x2B6
#define MM_PLATINUM_TOKEN 0x2B7
#define MM_SMALL_KEY_WF 0x2B8
#define MM_SMALL_KEY_SH 0x2B9
#define MM_SMALL_KEY_GB 0x2BA
#define MM_SMALL_KEY_ST 0x2BB
#define MM_BOSS_KEY_WF 0x2BC
#define MM_BOSS_KEY_SH 0x2BD
#define MM_BOSS_KEY_GB 0x2BE
#define MM_BOSS_KEY_ST 0x2BF
#define MM_MAP_WF 0x2C0
#define MM_MAP_SH 0x2C1
#define MM_MAP_GB 0x2C2
#define MM_MAP_ST 0x2C3
#define MM_COMPASS_WF 0x2C4
#define MM_COMPASS_SH 0x2C5
#define MM_COMPASS_GB 0x2C6
#define MM_COMPASS_ST 0x2C7
#define MM_OCARINA_FAIRY 0x2C8
#define MM_HOOKSHOT_SHORT 0x2C9
#define MM_WALLET 0x2CA
#define MM_WALLET4 0x2CB
#define MM_OWL_GREAT_BAY 0x2CC
#define MM_OWL_ZORA_CAPE 0x2CD
#define MM_OWL_SNOWHEAD 0x2CE
#define MM_OWL_MOUNTAIN_VILLAGE 0x2CF
#define MM_OWL_CLOCK_TOWN 0x2D0
#define MM_OWL_MILK_ROAD 0x2D1
#define MM_OWL_WOODFALL 0x2D2
#define MM_OWL_SOUTHERN_SWAMP 0x2D3
#define MM_OWL_IKANA_CANYON 0x2D4
#define MM_OWL_STONE_TOWER 0x2D5
#define MM_OWL_HIDDEN 0x2D6
#define MM_WALLET5 0x2D7
#define MM_SLINGSHOT 0x2D8
#define MM_DEKU_SEEDS_5 0x2D9
#define MM_DEKU_SEEDS_30 0x2DA
#define MM_BULLET_BAG2 0x2DB
#define MM_BULLET_BAG3 0x2DC
#define MM_SOUL_ENEMY_OCTOROK 0x2DD
#define MM_SOUL_ENEMY_WALLMASTER 0x2DE
#define MM_SOUL_ENEMY_DODONGO 0x2DF
#define MM_SOUL_ENEMY_KEESE 0x2E0
#define MM_SOUL_ENEMY_TEKTITE 0x2E1
#define MM_SOUL_ENEMY_PEAHAT 0x2E2
#define MM_SOUL_ENEMY_LIZALFOS_DINOLFOS 0x2E3
#define MM_SOUL_ENEMY_SKULLTULA 0x2E4
#define MM_SOUL_ENEMY_ARMOS 0x2E5
#define MM_SOUL_ENEMY_DEKU_BABA 0x2E6
#define MM_SOUL_ENEMY_DEKU_SCRUB 0x2E7
#define MM_SOUL_ENEMY_BUBBLE 0x2E8
#define MM_SOUL_ENEMY_BEAMOS 0x2E9
#define MM_SOUL_ENEMY_REDEAD_GIBDO 0x2EA
#define MM_SOUL_ENEMY_SKULLWALLTULA 0x2EB
#define MM_SOUL_ENEMY_SHELL_BLADE 0x2EC
#define MM_SOUL_ENEMY_LIKE_LIKE 0x2ED
#define MM_SOUL_ENEMY_IRON_KNUCKLE 0x2EE
#define MM_SOUL_ENEMY_FREEZARD 0x2EF
#define MM_SOUL_ENEMY_WOLFOS 0x2F0
#define MM_SOUL_ENEMY_GUAY 0x2F1
#define MM_SOUL_ENEMY_FLYING_POT 0x2F2
#define MM_SOUL_ENEMY_FLOORMASTER 0x2F3
#define MM_SOUL_ENEMY_CHUCHU 0x2F4
#define MM_SOUL_ENEMY_DEEP_PYTHON 0x2F5
#define MM_SOUL_ENEMY_STALCHILD 0x2F6
#define MM_SOUL_ENEMY_LEEVER 0x2F7
#define MM_SOUL_ENEMY_SKULLFISH 0x2F8
#define MM_SOUL_ENEMY_DEXIHAND 0x2F9
#define MM_SOUL_ENEMY_DRAGONFLY 0x2FA
#define MM_SOUL_ENEMY_EENO 0x2FB
#define MM_SOUL_ENEMY_EYEGORE 0x2FC
#define MM_SOUL_ENEMY_HIPLOOP 0x2FD
#define MM_SOUL_ENEMY_REAL_BOMBCHU 0x2FE
#define MM_SOUL_ENEMY_TAKKURI 0x2FF
#define MM_SOUL_ENEMY_BOE 0x300
#define MM_SOUL_ENEMY_NEJIRON 0x301
#define MM_SOUL_ENEMY_BIO_BABA 0x302
#define MM_SOUL_ENEMY_GARO 0x303
#define MM_SOUL_ENEMY_WIZZROBE 0x304
#define MM_SOUL_ENEMY_GOMESS 0x305
#define MM_SOUL_ENEMY_GEKKO 0x306
#define MM_SOUL_ENEMY_BAD_BAT 0x307
#define MM_SOUL_ENEMY_SNAPPER 0x308
#define MM_SOUL_ENEMY_WART 0x309
#define MM_SOUL_ENEMY_CAPTAIN_KEETA 0x30A
#define MM_SOUL_ENEMY_THIEVES 0x30B
#define MM_SOUL_ENEMY_POE 0x30C
#define MM_SOUL_BOSS_ODOLWA 0x30D
#define MM_SOUL_BOSS_GOHT 0x30E
#define MM_SOUL_BOSS_GYORG 0x30F
#define MM_SOUL_BOSS_TWINMOLD 0x310
#define MM_SOUL_BOSS_IGOS 0x311
#define MM_SOUL_NPC_AROMA 0x312
#define MM_SOUL_NPC_SHOOTING_GALLERY_OWNER 0x313
#define MM_SOUL_NPC_BAZAAR_SHOPKEEPER 0x314
#define MM_SOUL_NPC_GORON 0x315
#define MM_SOUL_NPC_GORON_CHILD 0x316
#define MM_SOUL_NPC_BOMBCHU_SHOPKEEPER 0x317
#define MM_SOUL_NPC_BOMBERS 0x318
#define MM_SOUL_NPC_BUTLER_DEKU 0x319
#define MM_SOUL_NPC_CITIZEN 0x31A
#define MM_SOUL_NPC_COMPOSER_BROS 0x31B
#define MM_SOUL_NPC_DAMPE 0x31C
#define MM_SOUL_NPC_DEKU_KING 0x31D
#define MM_SOUL_NPC_DEKU_PRINCESS 0x31E
#define MM_SOUL_NPC_PLAYGROUND_SCRUBS 0x31F
#define MM_SOUL_NPC_GORON_ELDER 0x320
#define MM_SOUL_NPC_CHEST_GAME_OWNER 0x321
#define MM_SOUL_NPC_GORON_SHOPKEEPER 0x322
#define MM_SOUL_NPC_HONEY_DARLING 0x323
#define MM_SOUL_NPC_TOTO 0x324
#define MM_SOUL_NPC_RUTO 0x325
#define MM_SOUL_NPC_ZORA_MUSICIANS 0x326
#define MM_SOUL_NPC_KAFEI 0x327
#define MM_SOUL_NPC_KEATON 0x328
#define MM_SOUL_NPC_KOUME_KOTAKE 0x329
#define MM_SOUL_NPC_MAYOR_DOTOUR 0x32A
#define MM_SOUL_NPC_MEDIGORON 0x32B
#define MM_SOUL_NPC_BIGGORON 0x32C
#define MM_SOUL_NPC_TALON 0x32D
#define MM_SOUL_NPC_ASTRONOMER 0x32E
#define MM_SOUL_NPC_POE_COLLECTOR 0x32F
#define MM_SOUL_NPC_BLACKSMITHS 0x330
#define MM_SOUL_NPC_BOMBCHU_BOWLING_LADY 0x331
#define MM_SOUL_NPC_TINGLE 0x332
#define MM_SOUL_NPC_TOILET_HAND 0x333
#define MM_SOUL_NPC_FISHING_POND_OWNER 0x334
#define MM_SOUL_NPC_ROOFTOP_MAN 0x335
#define MM_SOUL_NPC_ZORA 0x336
#define MM_SOUL_NPC_ZORA_SHOPKEEPER 0x337
#define MM_SOUL_NPC_MALON 0x338
#define MM_SOUL_NPC_BEAN_SALESMAN 0x339
#define MM_SOUL_NPC_CARPENTERS 0x33A
#define MM_SOUL_NPC_ANJU 0x33B
#define MM_SOUL_NPC_GURU_GURU 0x33C
#define MM_SOUL_NPC_SCIENTIST 0x33D
#define MM_SOUL_NPC_GORMAN 0x33E
#define MM_SOUL_NPC_GROG 0x33F
#define MM_SOUL_NPC_DOG_LADY 0x340
#define MM_SOUL_NPC_CARPET_MAN 0x341
#define MM_SOUL_NPC_OLD_HAG 0x342
#define MM_SOUL_NPC_TOURIST_CENTER 0x343
#define MM_SOUL_NPC_BANKER 0x344
#define MM_SOUL_NPC_MOON_CHILDREN 0x345
#define MM_SOUL_NPC_THIEVES 0x346
#define MM_SOUL_ANIMAL_CUCCO 0x347
#define MM_SOUL_ANIMAL_COW 0x348
#define MM_SOUL_ANIMAL_DOG 0x349
#define MM_SOUL_ANIMAL_BUTTERFLY 0x34A
#define MM_SOUL_MISC_GS 0x34B
#define MM_SOUL_MISC_BUSINESS_SCRUB 0x34C
#define MM_KEY_RING 0x34D
#define MM_KEY_RING_WF 0x34E
#define MM_KEY_RING_SH 0x34F
#define MM_KEY_RING_GB 0x350
#define MM_KEY_RING_ST 0x351
#define MM_SKELETON_KEY 0x352
#define MM_BUTTON_A 0x353
#define MM_BUTTON_C_RIGHT 0x354
#define MM_BUTTON_C_LEFT 0x355
#define MM_BUTTON_C_UP 0x356
#define MM_BUTTON_C_DOWN 0x357
#define MM_BOTTLE_POTION_GREEN 0x358
#define MM_BOTTLE_POTION_BLUE 0x359
#define MM_BOTTLE_FAIRY 0x35A
#define MM_POE 0x35B
#define MM_BOTTLE_POE 0x35C
#define MM_BOTTLE_BIG_POE 0x35D
#define MM_BOMBCHU_BAG 0x35E
#define MM_BOMBCHU_BAG2 0x35F
#define MM_BOMBCHU_BAG3 0x360
#define MM_BOMBCHU_BAG_FIRST_1 0x361
#define MM_BOMBCHU_BAG_FIRST_5 0x362
#define MM_BOMBCHU_BAG_FIRST_10 0x363
#define MM_BOMBCHU_BAG_FIRST_20 0x364
#define MM_FAIRY_BIG 0x365
#define MM_SPELL_FIRE 0x366
#define MM_SPELL_WIND 0x367
#define MM_SPELL_LOVE 0x368
#define MM_BOOTS_IRON 0x369
#define MM_BOOTS_HOVER 0x36A
#define MM_TUNIC_GORON 0x36B
#define MM_TUNIC_ZORA 0x36C
#define MM_SCALE_BRONZE 0x36D
#define MM_SCALE_SILVER 0x36E
#define MM_SCALE_GOLDEN 0x36F
#define MM_GORON_BRACELET 0x370
#define MM_SILVER_GAUNTLETS 0x371
#define MM_GOLDEN_GAUNTLETS 0x372
#define MM_CLOCK1 0x373
#define MM_CLOCK2 0x374
#define MM_CLOCK3 0x375
#define MM_CLOCK4 0x376
#define MM_CLOCK5 0x377
#define MM_CLOCK6 0x378
#define MM_HAMMER 0x379
#define MM_BOOMERANG 0x37A
#define MM_STICK_UPGRADE 0x37B
#define MM_STICK_UPGRADE2 0x37C
#define MM_STICK_UPGRADE3 0x37D
#define MM_NUT_UPGRADE 0x37E
#define MM_NUT_UPGRADE2 0x37F
#define MM_NUT_UPGRADE3 0x380
#define MM_STONE_OF_AGONY 0x381
#define MM_BOTTLE_RUTO_LETTER 0x382
#define MM_BOTTLE_BLUE_FIRE 0x383
#define MM_BLUE_FIRE 0x384
#define MM_RUSTY_KEY_TOURIST_INFORMATION 0x385
#define MM_RUSTY_KEY_POTION_SHOP 0x386
#define MM_RUSTY_KEY_POST_OFFICE 0x387
#define MM_RUSTY_KEY_SWORDSMAN_SCHOOL 0x388
#define MM_RUSTY_KEY_LOTTERY 0x389
#define MM_RUSTY_KEY_BOMB_SHOP 0x38A
#define MM_RUSTY_KEY_TRADING_POST 0x38B
#define MM_RUSTY_KEY_CURIOSITY_SHOP 0x38C
#define MM_RUSTY_KEY_KAFEI_HIDEOUT 0x38D
#define MM_RUSTY_KEY_TOWN_ARCHERY 0x38E
#define MM_RUSTY_KEY_SWAMP_ARCHERY 0x38F
#define MM_RUSTY_KEY_OBSERVATORY 0x390
#define MM_RUSTY_KEY_BLACKSMITH 0x391
#define MM_RUSTY_KEY_MUSIC_HOUSE 0x392
#define MM_RUSTY_KEY_LABORATORY 0x393
#define MM_RUSTY_KEY_BENEATH_GRAVEYARD 0x394
#define MM_RUSTY_KEY_DAMPE_HOUSE 0x395
#define MM_RUSTY_KEY_MAYOR_RESIDENCE 0x396
#define MM_RUSTY_KEY_MAYOR_RESIDENCE_OFFICE 0x397
#define MM_RUSTY_KEY_MAYOR_RESIDENCE_SALON 0x398
#define MM_RUSTY_KEY_MAYOR_RESIDENCE_KAFEI 0x399
#define MM_RUSTY_KEY_TREASURE_CHEST_GAME 0x39A
#define MM_RUSTY_KEY_HONEY_DARLING 0x39B
#define MM_RUSTY_KEY_MILK_BAR 0x39C
#define MM_RUSTY_KEY_DOG_RACETRACK 0x39D
#define MM_RUSTY_KEY_CUCCO_SHACK 0x39E
#define MM_RUSTY_KEY_RANCH_HOUSE 0x39F
#define MM_RUSTY_KEY_RANCH_BARN 0x3A0
#define MM_RUSTY_KEY_RANCH_HOUSE_ROOM 0x3A1
#define MM_RUSTY_KEY_ZORA_SHOP 0x3A2
#define MM_RUSTY_KEY_ZORA_JAPAS_ROOM 0x3A3
#define MM_RUSTY_KEY_ZORA_TIJO_ROOM 0x3A4
#define MM_RUSTY_KEY_ZORA_LULU_ROOM 0x3A5
#define MM_RUSTY_KEY_ZORA_EVAN_ROOM 0x3A6
#define MM_RUSTY_KEY_STOCK_POT_INN 0x3A7
#define MM_RUSTY_KEY_STOCK_POT_INN_ROOF 0x3A8
#define MM_RUSTY_KEY_GRANDMA_ROOM 0x3A9
#define MM_RUSTY_KEY_STOCK_POT_INN_STAFF_ROOM 0x3AA
#define MM_RUSTY_KEY_STOCK_POT_INN_DORMITORY 0x3AB
#define MM_SHOVEL 0x3AC
#define MM_MASK_MAJORA 0x3AD
#define MM_SOLD_OUT 0x3AE
#define NOTHING 0x3AF
#define MM_SCOOP 0x3B0

#pragma endregion MM

#pragma region Shared

#define SHARED_ARROW_FIRE 0x3B1
#define SHARED_ARROW_ICE 0x3B2
#define SHARED_ARROW_LIGHT 0x3B3
#define SHARED_ARROWS_10 0x3B4
#define SHARED_ARROWS_30 0x3B5
#define SHARED_ARROWS_40 0x3B6
#define SHARED_ARROWS_5 0x3B7
#define SHARED_BIG_POE 0x3B8
#define SHARED_BLUE_FIRE 0x3B9
#define SHARED_BOMB 0x3BA
#define SHARED_BOMB_BAG 0x3BB
#define SHARED_BOMBCHU 0x3BC
#define SHARED_BOMBCHU_10 0x3BD
#define SHARED_BOMBCHU_20 0x3BE
#define SHARED_BOMBCHU_5 0x3BF
#define SHARED_BOMBCHU_BAG 0x3C0
#define SHARED_BOMBS_10 0x3C1
#define SHARED_BOMBS_20 0x3C2
#define SHARED_BOMBS_30 0x3C3
#define SHARED_BOMBS_5 0x3C4
#define SHARED_BOOTS_HOVER 0x3C5
#define SHARED_BOOTS_IRON 0x3C6
#define SHARED_BOTTLE_BIG_POE 0x3C7
#define SHARED_BOTTLE_BLUE_FIRE 0x3C8
#define SHARED_BOTTLE_CHATEAU 0x3C9
#define SHARED_BOTTLE_EMPTY 0x3CA
#define SHARED_BOTTLE_FAIRY 0x3CB
#define SHARED_BOTTLE_MILK 0x3CC
#define SHARED_BOTTLE_POE 0x3CD
#define SHARED_BOTTLE_POTION_BLUE 0x3CE
#define SHARED_BOTTLE_POTION_GREEN 0x3CF
#define SHARED_BOTTLE_POTION_RED 0x3D0
#define SHARED_BOTTLE_RUTO_LETTER 0x3D1
#define SHARED_BOTTLED_GOLD_DUST 0x3D2
#define SHARED_BOW 0x3D3
#define SHARED_BUGS 0x3D4
#define SHARED_BUTTON_A 0x3D5
#define SHARED_BUTTON_C_DOWN 0x3D6
#define SHARED_BUTTON_C_LEFT 0x3D7
#define SHARED_BUTTON_C_RIGHT 0x3D8
#define SHARED_BUTTON_C_UP 0x3D9
#define SHARED_CHATEAU 0x3DA
#define SHARED_DEFENSE_UPGRADE 0x3DB
#define SHARED_FAIRY 0x3DC
#define SHARED_FAIRY_BIG 0x3DD
#define SHARED_FISH 0x3DE
#define SHARED_HAMMER 0x3DF
#define SHARED_BOOMERANG 0x3E0
#define SHARED_HEART_CONTAINER 0x3E1
#define SHARED_HEART_PIECE 0x3E2
#define SHARED_HOOKSHOT 0x3E3
#define SHARED_LENS 0x3E4
#define SHARED_MAGIC_JAR_LARGE 0x3E5
#define SHARED_MAGIC_JAR_SMALL 0x3E6
#define SHARED_MAGIC_UPGRADE 0x3E7
#define SHARED_MASK_BLAST 0x3E8
#define SHARED_MASK_BUNNY 0x3E9
#define SHARED_MASK_GORON 0x3EA
#define SHARED_MASK_KEATON 0x3EB
#define SHARED_MASK_KAMARO 0x3EC
#define SHARED_MASK_STONE 0x3ED
#define SHARED_MASK_TRUTH 0x3EE
#define SHARED_MASK_ZORA 0x3EF
#define SHARED_MILK 0x3F0
#define SHARED_NUT 0x3F1
#define SHARED_NUT_UPGRADE 0x3F2
#define SHARED_NUTS_10 0x3F3
#define SHARED_NUTS_5 0x3F4
#define SHARED_OCARINA 0x3F5
#define SHARED_PLATINUM_TOKEN 0x3F6
#define SHARED_POE 0x3F7
#define SHARED_POTION_BLUE 0x3F8
#define SHARED_POTION_GREEN 0x3F9
#define SHARED_POTION_RED 0x3FA
#define SHARED_RECOVERY_HEART 0x3FB
#define SHARED_RUPEE_BLUE 0x3FC
#define SHARED_RUPEE_GOLD 0x3FD
#define SHARED_RUPEE_GREEN 0x3FE
#define SHARED_RUPEE_PURPLE 0x3FF
#define SHARED_RUPEE_RAINBOW 0x400
#define SHARED_RUPEE_RED 0x401
#define SHARED_RUPEE_SILVER 0x402
#define SHARED_SCALE 0x403
#define SHARED_SHIELD 0x404
#define SHARED_SHIELD_DEKU 0x405
#define SHARED_SHIELD_HYLIAN 0x406
#define SHARED_SHIELD_MIRROR 0x407
#define SHARED_SHOVEL 0x408
#define SHARED_SKELETON_KEY 0x409
#define SHARED_SONG_EMPTINESS 0x40A
#define SHARED_SONG_EPONA 0x40B
#define SHARED_SONG_NOTE_EMPTINESS 0x40C
#define SHARED_SONG_NOTE_EPONA 0x40D
#define SHARED_SONG_NOTE_STORMS 0x40E
#define SHARED_SONG_NOTE_SUN 0x40F
#define SHARED_SONG_NOTE_TIME 0x410
#define SHARED_SONG_STORMS 0x411
#define SHARED_SONG_SUN 0x412
#define SHARED_SONG_TIME 0x413
#define SHARED_SONG_NOTE_HEALING 0x414
#define SHARED_SONG_NOTE_SOARING 0x415
#define SHARED_SONG_NOTE_AWAKENING 0x416
#define SHARED_SONG_NOTE_GORON 0x417
#define SHARED_SONG_NOTE_ZORA 0x418
#define SHARED_SONG_NOTE_ORDER 0x419
#define SHARED_SONG_HEALING 0x41A
#define SHARED_SONG_SOARING 0x41B
#define SHARED_SONG_AWAKENING 0x41C
#define SHARED_SONG_GORON 0x41D
#define SHARED_SONG_GORON_HALF 0x41E
#define SHARED_SONG_ZORA 0x41F
#define SHARED_SONG_ORDER 0x420
#define SHARED_SONG_NOTE_SARIA 0x421
#define SHARED_SONG_NOTE_TP_FIRE 0x422
#define SHARED_SONG_NOTE_TP_FOREST 0x423
#define SHARED_SONG_NOTE_TP_LIGHT 0x424
#define SHARED_SONG_NOTE_TP_SHADOW 0x425
#define SHARED_SONG_NOTE_TP_SPIRIT 0x426
#define SHARED_SONG_NOTE_TP_WATER 0x427
#define SHARED_SONG_NOTE_ZELDA 0x428
#define SHARED_SONG_SARIA 0x429
#define SHARED_SONG_TP_FIRE 0x42A
#define SHARED_SONG_TP_FOREST 0x42B
#define SHARED_SONG_TP_LIGHT 0x42C
#define SHARED_SONG_TP_SHADOW 0x42D
#define SHARED_SONG_TP_SPIRIT 0x42E
#define SHARED_SONG_TP_WATER 0x42F
#define SHARED_SONG_ZELDA 0x430
#define SHARED_SOUL_ANIMAL_BUTTERFLY 0x431
#define SHARED_SOUL_ANIMAL_COW 0x432
#define SHARED_SOUL_ANIMAL_CUCCO 0x433
#define SHARED_SOUL_ANIMAL_DOG 0x434
#define SHARED_SOUL_ENEMY_ARMOS 0x435
#define SHARED_SOUL_ENEMY_BEAMOS 0x436
#define SHARED_SOUL_ENEMY_BUBBLE 0x437
#define SHARED_SOUL_ENEMY_DEKU_BABA 0x438
#define SHARED_SOUL_ENEMY_DEKU_SCRUB 0x439
#define SHARED_SOUL_ENEMY_DODONGO 0x43A
#define SHARED_SOUL_ENEMY_FLOORMASTER 0x43B
#define SHARED_SOUL_ENEMY_FLYING_POT 0x43C
#define SHARED_SOUL_ENEMY_FREEZARD 0x43D
#define SHARED_SOUL_ENEMY_GUAY 0x43E
#define SHARED_SOUL_ENEMY_IRON_KNUCKLE 0x43F
#define SHARED_SOUL_ENEMY_KEESE 0x440
#define SHARED_SOUL_ENEMY_LEEVER 0x441
#define SHARED_SOUL_ENEMY_LIKE_LIKE 0x442
#define SHARED_SOUL_ENEMY_LIZALFOS_DINOLFOS 0x443
#define SHARED_SOUL_ENEMY_OCTOROK 0x444
#define SHARED_SOUL_ENEMY_PEAHAT 0x445
#define SHARED_SOUL_ENEMY_POE 0x446
#define SHARED_SOUL_ENEMY_REDEAD_GIBDO 0x447
#define SHARED_SOUL_ENEMY_SHELL_BLADE 0x448
#define SHARED_SOUL_ENEMY_SKULLTULA 0x449
#define SHARED_SOUL_ENEMY_SKULLWALLTULA 0x44A
#define SHARED_SOUL_ENEMY_STALCHILD 0x44B
#define SHARED_SOUL_ENEMY_TEKTITE 0x44C
#define SHARED_SOUL_ENEMY_THIEVES 0x44D
#define SHARED_SOUL_ENEMY_WALLMASTER 0x44E
#define SHARED_SOUL_ENEMY_WOLFOS 0x44F
#define SHARED_SOUL_MISC_BUSINESS_SCRUB 0x450
#define SHARED_SOUL_MISC_GS 0x451
#define SHARED_SOUL_NPC_ANJU 0x452
#define SHARED_SOUL_NPC_ASTRONOMER 0x453
#define SHARED_SOUL_NPC_BANKER 0x454
#define SHARED_SOUL_NPC_BAZAAR_SHOPKEEPER 0x455
#define SHARED_SOUL_NPC_BEAN_SALESMAN 0x456
#define SHARED_SOUL_NPC_BIGGORON 0x457
#define SHARED_SOUL_NPC_BOMBCHU_BOWLING_LADY 0x458
#define SHARED_SOUL_NPC_BOMBCHU_SHOPKEEPER 0x459
#define SHARED_SOUL_NPC_BOMBERS 0x45A
#define SHARED_SOUL_NPC_CARPENTERS 0x45B
#define SHARED_SOUL_NPC_CARPET_MAN 0x45C
#define SHARED_SOUL_NPC_CHEST_GAME_OWNER 0x45D
#define SHARED_SOUL_NPC_CITIZEN 0x45E
#define SHARED_SOUL_NPC_COMPOSER_BROS 0x45F
#define SHARED_SOUL_NPC_DAMPE 0x460
#define SHARED_SOUL_NPC_DOG_LADY 0x461
#define SHARED_SOUL_NPC_FISHING_POND_OWNER 0x462
#define SHARED_SOUL_NPC_GORMAN 0x463
#define SHARED_SOUL_NPC_GORON 0x464
#define SHARED_SOUL_NPC_GORON_CHILD 0x465
#define SHARED_SOUL_NPC_GORON_SHOPKEEPER 0x466
#define SHARED_SOUL_NPC_GROG 0x467
#define SHARED_SOUL_NPC_GURU_GURU 0x468
#define SHARED_SOUL_NPC_HONEY_DARLING 0x469
#define SHARED_SOUL_NPC_MALON 0x46A
#define SHARED_SOUL_NPC_MEDIGORON 0x46B
#define SHARED_SOUL_NPC_OLD_HAG 0x46C
#define SHARED_SOUL_NPC_POE_COLLECTOR 0x46D
#define SHARED_SOUL_NPC_ROOFTOP_MAN 0x46E
#define SHARED_SOUL_NPC_RUTO 0x46F
#define SHARED_SOUL_NPC_SCIENTIST 0x470
#define SHARED_SOUL_NPC_SHOOTING_GALLERY_OWNER 0x471
#define SHARED_SOUL_NPC_TALON 0x472
#define SHARED_SOUL_NPC_THIEVES 0x473
#define SHARED_SOUL_NPC_ZORA 0x474
#define SHARED_SOUL_NPC_ZORA_SHOPKEEPER 0x475
#define SHARED_SPELL_FIRE 0x476
#define SHARED_SPELL_LOVE 0x477
#define SHARED_SPELL_WIND 0x478
#define SHARED_SPIN_UPGRADE 0x479
#define SHARED_STICK 0x47A
#define SHARED_STICK_UPGRADE 0x47B
#define SHARED_STICKS_10 0x47C
#define SHARED_STICKS_5 0x47D
#define SHARED_STONE_OF_AGONY 0x47E
#define SHARED_STRENGTH 0x47F
#define SHARED_SWORD 0x480
#define SHARED_TRIFORCE 0x481
#define SHARED_TRIFORCE_COURAGE 0x482
#define SHARED_TRIFORCE_POWER 0x483
#define SHARED_TRIFORCE_WISDOM 0x484
#define SHARED_TUNIC_GORON 0x485
#define SHARED_TUNIC_ZORA 0x486
#define SHARED_WALLET 0x487
#define OOT_PROG_WALLET 0x488
#define OOT_SWORD 0x489
#define OOT_OCARINA 0x48A
#define OOT_SCALE 0x48B
#define OOT_SHIELD 0x48C
#define OOT_STRENGTH 0x48D
#define OOT_SWORD_GORON 0x48E
#define MM_PROG_WALLET 0x48F
#define MM_SWORD 0x490
#define MM_CLOCK 0x491
#define MM_OCARINA 0x492
#define MM_SCALE 0x493
#define MM_SHIELD 0x494
#define MM_STRENGTH 0x495
#define SHARED_SLINGSHOT 0x496
#define SHARED_DEKU_SEEDS_5 0x497
#define SHARED_DEKU_SEEDS_30 0x498
#define SHARED_BULLET_BAG2 0x499
#define SHARED_BULLET_BAG3 0x49A
#define SHARED_QUIVER2 0x49B
#define SHARED_QUIVER3 0x49C
#define SHARED_POWDER_KEG 0x49D
#define SHARED_MASK_GERUDO 0x49E
#define SHARED_MASK_SKULL 0x49F
#define SHARED_MASK_SPOOKY 0x4A0
#define SHARED_GREAT_FAIRY_SWORD 0x4A1

#pragma endregion Shared

#pragma endregion Defines

/*
*   Identifies a single trackable location in the combo randomizer, combining
*   game, overlay type, scene, room, and object into one key.
*/
typedef struct ComboItem
{
	/* The game this item belongs to (0 = OoT, 1 = MM). */
	uint8_t GameID;
	/* The overlay type that classifies the container (chest, NPC, collectible, etc.). */
	uint8_t OvType;
	/* The scene ID in which this item is located. */
	uint32_t SceneID;
	/* The room index within the scene in which this item is located. */
	uint32_t RoomID;
	uint32_t ObjectID;
} ComboItem;


typedef struct ItemInfo
{
	uint32_t ItemID;
	const char* ItemName;
    EGameIcon RenderType;
    bool CanBeShared;
} ItemInfo;



/*
*   Decode a raw 5 byte combo key into its matching ComboItem fields.
*
*   @param Key      The raw 5 byte key (Game, OvType, Scene, Room, Object).
*   @param Item     The combo item to populate with the decoded values.
*/
void ParseKey(uint8_t Key[5], ComboItem* Item);

/*
*   Find the item information matching the given item ID.
*
*   @param gi       The item ID to search for.
*
*   @return The item information matching the given ID, or a null pointer if none matched.
*/
const ItemInfo * FindItem(uint32_t gi);

/*
*   Find the item information matching the given item name.
*
*   @param Name     The item name to search for (newlines are stripped before matching).
*
*   @return The item information matching the given name, or a null pointer if none matched.
*/
const ItemInfo* FindItemByName(QString Name);

/*
*   Progressive capacity upgrades (Bow / Big Quiver / Biggest Quiver, Fairy Slingshot / Large /
*   Largest Bullet Bag - per game and their shared variants) all carry the base item's name in the
*   spoiler log, so a single placement is indistinguishable between the base and any of its upgrades.
*   Tells whether two item IDs belong to the same such family, which the progression location tree
*   uses to list every "Bow" placement under the bow AND every quiver widget (and likewise for the
*   slingshot / bullet bags).
*
*   @param ItemA    The first item ID.
*   @param ItemB    The second item ID.
*
*   @return <b>True</b> when both IDs belong to the same progressive capacity family, <b>false</b>
*           otherwise (including when either ID is not part of any such family).
*/
bool ItemsShareProgressiveFamily(uint32_t ItemA, uint32_t ItemB);

/*
*   Progressive capacity upgrades (Big / Biggest Quiver, Large / Largest Bullet Bag) are not listed
*   individually in the spoiler's starting items: only the base (bow / slingshot) appears, with a
*   count. A count of 2 also grants the first upgrade, 3 the second. Given an upgrade item ID, report
*   its base item and the starting count required for the player to begin the run owning that upgrade.
*
*   @param ItemID           The candidate progressive upgrade item ID.
*   @param OutBaseID        Receives the base item ID of the family (bow / slingshot) when matched.
*   @param OutRequiredCount Receives the base starting count granting this upgrade (2 or 3) when matched.
*
*   @return <b>True</b> when ItemID is a progressive capacity upgrade, <b>false</b> otherwise.
*/
bool GetProgressiveUpgradeRequirement(uint32_t ItemID, uint32_t& OutBaseID, uint32_t& OutRequiredCount);

/*
*   Set the active OoTMM ROM build. Item IDs reported by a stable build are translated by
*   ResolveRawItemID so they line up with the tracker's internal (dev) numbering.
*
*   @param Version    The detected ROM build (stable or dev).
*/
void SetActiveROMVersion(ROMVersion Version, bool FromSpoiler = false);

/*
*   Get the active OoTMM ROM build last set with SetActiveROMVersion (defaults to dev).
*
*   @return The active ROM build.
*/
ROMVersion GetActiveROMVersion();

/*
*   Tell whether the active ROM build was set from a spoiler "Version:" line (authoritative) rather
*   than inferred from the DLL-reported game version.
*
*   @return true if a spoiler set the version, false otherwise.
*/
bool IsActiveROMVersionFromSpoiler();

/*
*   Translate a raw in-game item ID into the tracker's internal (dev-build) item ID space.
*
*   The dev OoTMM build inserts new items at several points, pushing every later ID upward. The
*   tracker's #define / ItemList table follows the dev numbering, so a stable build reports lower
*   IDs that must be shifted up to match. Dev builds already use the tracker numbering and are
*   returned unchanged. The active build is taken from the last SetActiveROMVersion call.
*
*   @param RawItemID    The raw item ID reported by the game.
*
*   @return The item ID expressed in the tracker's internal (dev) numbering.
*/
uint32_t ResolveRawItemID(uint32_t RawItemID);

/*
*   Translate a raw OoT NPC ID reported by the game into the tracker's internal (dev-build) NPC
*   numbering. The dev build removed the unused `SCRUB_HP` slot (0x12), so the Gold Skulltula
*   reward NPCs `GS_10`..`GS_50` are reported one ID higher on a stable build (0x13..0x17) than on
*   dev (0x12..0x16). This shifts just that range back down. Only OoT NPC IDs are affected, and only
*   on a stable build; dev builds already match the tracker numbering and are returned unchanged.
*
*   @param RawNpcID    The raw OoT NPC ID reported by the game.
*
*   @return The OoT NPC ID expressed in the tracker's internal (dev) numbering.
*/
uint32_t ResolveRawOoTNpcID(uint32_t RawNpcID);
