language = "fr"
hide_collected_map = false
hide_collected_list = false
auto_snap = false
auto_zoom = false
backup_on_save = false
auto_follow_item = false
auto_follow_entrance = false
auto_gps_start = false
auto_load_tracking = false
auto_load_spoiler = false
use_multiplayer = false
mp_host = "multi.ootmm.com"
mp_port = "13248"
